### ISSUE TITLE
Add support of customization of colorization level

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#10]
Colorization level may looks like this:
- [x] https://github.com/izhangzhihao/intellij-rainbow-brackets/pull/35 `do not colorize brackets without content`
 * do not colorize `method()` 
 * colorize `method(param)`

- [x] https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/233 `do not colorize brackets without another brackets inside`
 * do not colorize `method(param)`
 * colorize external brackets of `method(array[3])`

- [ ] `do not colorize brackets without another brackets of the same type inside`
 * do not colorize `method(array[3])`
 * colorize external brackets of `method(new Entity())`

And separately 
- [ ] `always colorize multi-line brackets` (regardless of colorization level)
 * do not colorize `['firstName', 'secondName', 'city, 'address']`
 * always colorize
```js
[
  'firstName', 'secondName',
  'city', 'address'
]
```
* * sub-option `not apply to {...}` - ex. if `always colorize multi-line brackets` is on but colorization level is not forcing to colorize
```js
function f () {
   return 1
}
```
than `{...}` should not be colorized

**Comment by Alexsey** [comment]
This proposal includes https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2

**Comment by Alexsey** [comment]
Another idea for options:
* Change color of consequent brackets of the same type
It could add expressiveness for multi-dimensional arrays
* * Colorize second pare brackets in different color `element = matrix[raw][column]`
* * Colorize brackets equally `element = users[i].phone[0]`

**Comment by mfn** [comment]
Another suggestion:
- Only colorize non-class/non-method brackets

I've been using the Plugin for a while (great idea, kudos!) but what throws me off is that even on class/method levels the brackets are colored which to me doesn't make sense. Their indentation level and organization in the source files is the most consistent thing anyway.

But everything else (conditions, literal usases in nested data-structures, younameit) benefits greatly from the coloring.

**Comment by Alexsey** [comment]
@mfn this is the case I was targeting when propose sub-option `not apply to {...}`. I thing it should fit the case without need of such deep context knowledge

**Comment by izhangzhihao** [comment]
do not colorize brackets without content: see #35

**Comment by ahait** [comment]
choose to colorize brackets, but not paranthesis.
