### ISSUE TITLE
Option to configure file types to apply rainbow to

### ISSUE THREAD

**Issue by keeganwitt** [izhangzhihao/intellij-rainbow-brackets#1046]
It'd be nice if we had an option to configure which file types (probably by file extension) get rainbow applied.  For example, maybe I want JavaScript rainbowified, but not Java.  I've seen it pop up warnings on big files saying it won't rainbowify it, but I don't need it to process that file anyway (e.g. SQL).  So in addition to being able to choose the behavior you want, it could save some processing too.

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-brackets#disable-rainbow-brackets-for-specific-languages

**Comment by keeganwitt** [comment]
Would it be possible to expose this settings rather than having to manually edit a config file?

**Comment by izhangzhihao** [comment]
PR welcome
