### ISSUE TITLE
New Option: do not colorize multi-line brackets

### ISSUE THREAD

**Issue by fatihcoskun79** [izhangzhihao/intellij-rainbow-brackets#1061]
This is a request for a new feature.

A new option "Do not colorize multi-line brackets". When checked, only those brackets will be colorized that have a matching bracket on the same line.

Rationale:
I can visually identify multi-line brackets by the indentation level already, therefore I don't need them colorized.

**Comment by izhangzhihao** [comment]
Similar to `always colorize multi-line brackets` request in #10

**Comment by izhangzhihao** [comment]
And that is easy as well, sample code to get line number(in [DefaultRainbowVisitor](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/visitor/DefaultRainbowVisitor.kt#L18) we will visit all elements)

```kotlin
document.lineNumber(element.startOffset)
```
After we know `startElement` & `endElement`, we could check the line number and decide whether rainbowify theme or not.
