### ISSUE TITLE
New keymap: enable/disable bracket colorization

### ISSUE THREAD

**Issue by fatihcoskun79** [izhangzhihao/intellij-rainbow-brackets#1062]
This is a request for a new feature. A new keymap: enable/disable bracket colorization. When used this keymap will toggle colorization of brackets on/off.

**Comment by izhangzhihao** [comment]
That would be easy, do you want to contribute to this project?  [Please refer to the `plugin.xml`](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/src/main/resources/META-INF/plugin.xml#L743-L760)
