### ISSUE TITLE
New option: colorize brackets only within highlighted scope

### ISSUE THREAD

**Issue by fatihcoskun79** [izhangzhihao/intellij-rainbow-brackets#1063]
This is a request for a new feature. A new option: colorize brackets only within highlighted scope. When checked brackets colorization is disabled except within the currently highlighted scope.

**Comment by izhangzhihao** [comment]
It seems impossible to me since the `HighlightVisitor` didn't know the highlighted scope, so I will close this issue. Or if you could contribute, it will be great!
