### ISSUE TITLE
Don't rainbowify big files notification annoying

### ISSUE THREAD

**Issue by thiakil** [izhangzhihao/intellij-rainbow-brackets#1067]
## Your programming language(s)
All

## Expected Behavior
Notification that large files won't be rainbowify should only display once and be dismissed, never to show again.

## Current Behavior
Shows every time ~~a big file is opened.~~ IDE is restarted

## Code snippet for reproduce (for bugs)
Open any large file, restart IDE, see message again

## Your Environment

* Plugin version: 6.16

```
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to Redacted
Subscription is active until Redacted
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: com.github.novotnyr.jwt-intellij-plugin, ASM Bytecode Outline 2017, String Manipulation, org.jetbrains.kotlin, io.ktor.intellij.plugin, com.jetbrains.php, com.illuminatedcloud2.intellij, izhangzhihao.rainbow.brackets, PlantUML integration
```

**Comment by izhangzhihao** [comment]
Does the notification show every time when you open a big file? I think it only shows once per IDE instance which means the notification shows only once(if you never close your IDE instance).

Or you could just disable the option:

![image](https://user-images.githubusercontent.com/12044174/109296415-3ae74180-786b-11eb-873c-a3d46fb8c4fa.png)

**Comment by thiakil** [comment]
Definitely shows every time

**Comment by izhangzhihao** [comment]
When you open two projects at the same time, does it shows twice？

**Comment by thiakil** [comment]
Apologies - it seems to be once per IDE restart (I use both IDEA and PHPStorm, so that's probably how I got confused)

**Comment by izhangzhihao** [comment]
Great then.

**Comment by thiakil** [comment]
It's still annoying to see it every day, why does it need to show every time the ide is opened?

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/109296415-3ae74180-786b-11eb-873c-a3d46fb8c4fa.png)

**Comment by thiakil** [comment]
If I wanted it to apply to big files I would do that

**Comment by izhangzhihao** [comment]
I will try to change the notification in the next release~

**Comment by izhangzhihao** [comment]
Please try the latest build snapshot: https://github.com/izhangzhihao/intellij-rainbow-brackets#install-snapshot-build
