### ISSUE TITLE
dart中, intent guide没有和Android studio自带的guide重合

### ISSUE THREAD

**Issue by AndrewTseZhou** [izhangzhihao/intellij-rainbow-brackets#1080]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://izhangzhihao.github.io/rainbow-brackets-document/) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ ] This issue/feature request is not reported before.

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, explain the difference from current behavior

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Licensed to IntelliJ Rainbow Brackets / Zhang Zhihao
Subscription is active until February 19, 2021
For non-commercial open source development only.
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.tooltip.initialDelay=900, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets
```

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by AndrewTseZhou** [comment]
> Any screenshots?

![image](https://user-images.githubusercontent.com/22510709/109785342-00a0ea00-7c47-11eb-832d-96261dcd50fb.png)

**Comment by izhangzhihao** [comment]
Your Environment please

**Comment by AndrewTseZhou** [comment]
> Your Environment please

Android Studio 4.0, 4.1
OS:  Big Sur 11.1, 11.2
Rainbow Brackets:  6.16 and before

It began to appear in November last year.

**Comment by izhangzhihao** [comment]
Works as expected for me:

![image](https://user-images.githubusercontent.com/12044174/109787878-a6edef00-7c49-11eb-9a06-0b58874da80a.png)

```
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 16
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, izhangzhihao.rainbow.brackets
```

**Comment by AndrewTseZhou** [comment]
> Works as expected for me:
> 
> ![image](https://user-images.githubusercontent.com/12044174/109787878-a6edef00-7c49-11eb-9a06-0b58874da80a.png)
> 
> ```
> Android Studio 4.1.2
> Build #AI-201.8743.12.41.7042882, built on December 20, 2020
> Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.16
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1237M
> Cores: 16
> Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
> Non-Bundled Plugins: Dart, izhangzhihao.rainbow.brackets
> ```

your macOS version is not big sur.

**Comment by izhangzhihao** [comment]
there is nothing to do with big sur ...

**Comment by izhangzhihao** [comment]
Can you show me that?

![image](https://user-images.githubusercontent.com/12044174/109788652-7a86a280-7c4a-11eb-8e4e-fa83bd67257d.png)

**Comment by AndrewTseZhou** [comment]
![image](https://user-images.githubusercontent.com/22510709/109788802-a570f680-7c4a-11eb-981a-feb76723ef4f.png)

**Comment by izhangzhihao** [comment]
Can you show me that:

```
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 16
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, izhangzhihao.rainbow.brackets
```

**Comment by AndrewTseZhou** [comment]
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 5036M
Cores: 12

**Comment by izhangzhihao** [comment]
Interesting, how do you get this plugin installed?

**Comment by izhangzhihao** [comment]
And you are using big sur as well: macOS 10.16

**Comment by izhangzhihao** [comment]
PLEASE PROVIDE THE CORRECT INFOMATION.

**Comment by AndrewTseZhou** [comment]
> Interesting, how do you get this plugin installed?

marketplace.

![image](https://user-images.githubusercontent.com/22510709/109789565-6d1de800-7c4b-11eb-87f0-ce527766b820.png)
![image](https://user-images.githubusercontent.com/22510709/109789623-79a24080-7c4b-11eb-8767-a2584fa27c90.png)

**Comment by AndrewTseZhou** [comment]
I guess that you are not open the AS's "Show indent guides"

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/109789903-c6861700-7c4b-11eb-856a-f868fb238a34.png)

I did a clean installation, with all default config.

**Comment by izhangzhihao** [comment]
Could help me verify a new installation works for you or not?

**Comment by AndrewTseZhou** [comment]
> Could help me verify a new installation works for you or not?

Ok

**Comment by AndrewTseZhou** [comment]
> And you are using big sur as well: macOS 10.16

I think, this is AS's bug. Because AS 4.1.X doesn't adapt for Big Sur. so can not get correct info

**Comment by izhangzhihao** [comment]
Any update?

**Comment by AndrewTseZhou** [comment]
> Any update?

no
