### ISSUE TITLE
Same level brackets should have same color

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#11]
Consider JS  code
```javascript
const _ = require('lodash') || false
const moment = require('moment')
``` 
**Current behavior:**
Top bracket is green and bottom is yellow
![rainbow_color_bug](https://user-images.githubusercontent.com/6392013/33320147-e70a5c28-d449-11e7-9987-4416082c5a30.png)

**Expected behavior:**
Both brackets should be yellow

**Comment by izhangzhihao** [comment]
Maybe we should create a specific implement for javascript language, If we have a specific implement we could fix this issue. please take a look [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#implement-for-some-language-you-would-like)

**Comment by izhangzhihao** [comment]
Related to all issues in javascript support.

**Comment by Alexsey** [comment]
I agree that we may need to have a specific implementation to fix some of the issues with JS. But does this one looks like JS specific?

**Comment by izhangzhihao** [comment]
So what should JS specific implementation looks like?

**Comment by izhangzhihao** [comment]
Sorry, maybe I don't understand your idea clearly.

**Comment by Alexsey** [comment]
I mean that https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/21 is probably JS specific and this https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/12 may be JS specific. But the one this issue is started about is probably general and should be the same in all languages

**Comment by izhangzhihao** [comment]
If you checkout #19 you will see, a JS specific implementation will fix most of tht issues in js support

**Comment by izhangzhihao** [comment]
If we JS specific implementation, in #21 '(' will always be a '(', and in #12 maybe we don't need to add implement about '>'

**Comment by Alexsey** [comment]
Thant make sense. https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/12 could probably be fixed by just disabling `rainbow-brackets` for `<>`. But how it could be used to fix https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/21 I mean it's about determining what is plan text and what is code and not about global enable/disable of plugin

**Comment by izhangzhihao** [comment]
I'm not mean to globally enable/disable of plugin. And about "determining what is plan text and what is code" I think that is what intellij should do, and if we have a specific implementation, we just to match like '(' in code, not plain text.

**Comment by izhangzhihao** [comment]
But now in js implementation is to match string like "(", and don't "(" is code or not.

**Comment by Alexsey** [comment]
Ok, looking at Scala example I can assume that copy past it and remove block with `<>` may fix https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/12 because JS doesn't have `<>` breaks. But I have no idea how to adopt it to fix other issues. BTW I'm not familiar with Kotlin, so if it needs an actual programming - just tell me - I woundn't even try :)

**Comment by izhangzhihao** [comment]
<img width="386" alt="screen shot 2018-01-11 at 1 16 10 pm" src="https://user-images.githubusercontent.com/12044174/34809712-a2846314-f6d1-11e7-975c-e2fab634f7e7.png">

Should been fixed in next release!

**Comment by Alexsey** [comment]
This is so cool! Thank you!
