### ISSUE TITLE
Colors nearly invisible on light UI

### ISSUE THREAD

**Issue by davew945** [izhangzhihao/intellij-rainbow-brackets#113]
I use a light UI with a pale blue background. 
Your color scheme looks to be designed for a dark scheme and
the colors are nearly invisible for me.
Is there any way I can specify my own styles for the brackets -
color, bold?

Thank you.

**Comment by izhangzhihao** [comment]
Yes! you could config your own color schema [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/IC-2017.2/README.md#config-brackets-colors)

**Comment by izhangzhihao** [comment]
And [here](https://gist.github.com/Avinash-Bhat/c4d0575dad56046d930b1af3197d8d5d) is a example.

**Comment by izhangzhihao** [comment]
It will be great if you could share your schema with others cause I'm not really good at color.
