### ISSUE TITLE
Symbol less ">" is considered as a bracket even without leading "<"

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#12]
Consider JS code
```js
console.log(a > b)
console.log(a == b)
```
**Current behavior:**
Symbol `>` is highlighted with blue
![rainbow_less_bug](https://user-images.githubusercontent.com/6392013/34355411-bb396026-ea3d-11e7-98e5-055b9350a07d.png)

**Expected behavior:**
Symbol `>` should not be highlighted. The same as `==` below

**Comment by rostopira** [comment]
Same bug in Kotlin code

**Comment by izhangzhihao** [comment]
<img width="198" alt="screen shot 2018-01-11 at 1 25 40 pm" src="https://user-images.githubusercontent.com/12044174/34809883-f119439a-f6d2-11e7-9f40-aebc71c93997.png">

Should been fixed in next release !
