### ISSUE TITLE
Rainbow brackets not shown for Dart

### ISSUE THREAD

**Issue by jimhotchkin-wf** [izhangzhihao/intellij-rainbow-brackets#13]
Hello!  Even after the application of the new "show bracket highlighting for unsupported languages" option, the rainbow bracket effects are not seen in `.dart` files. WebStorm 2017.3 Build #WS-173.3727.108

**Comment by izhangzhihao** [comment]
Have you restart webstorm after you apply the option?

**Comment by izhangzhihao** [comment]
This plugin is not tested against for Dart yet. And the option you applyed is experimental. I will check this later. Thanks for your reminder.:wink:

**Comment by izhangzhihao** [comment]
Have you installed the [dart plugin](https://plugins.jetbrains.com/plugin/6351-dart)?

**Comment by jimhotchkin-wf** [comment]
Thank you!

**Comment by moonvader** [comment]
Have same problem in Android Studio: Dart and Rainbow Brackets plugins are installed.
Rainbow Brackets are working fine for example for Java but not working for Dart. What should I do?

@jimhotchkin-wf do you have a solution?

**Comment by izhangzhihao** [comment]
It works in my env even without a dart sdk installed:
<img width="377" alt="screen shot 2018-03-24 at 11 33 59 pm" src="https://user-images.githubusercontent.com/12044174/37865735-debc6fd4-2fbb-11e8-9839-a299066ea5a2.png">

**Comment by izhangzhihao** [comment]
@moonvader Please comment your env as below:

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.519, built on March 22, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

**Comment by eturk1** [comment]
so works in Intellij but not Android Studio?

**Comment by izhangzhihao** [comment]
> so works in Intellij but not Android Studio?

It should work for all IntelliJ based IDEs, including Android Studio.

**Comment by eturk1** [comment]
> > so works in Intellij but not Android Studio?
> 
> It should work for all IntelliJ based IDEs, including Android Studio.

wow, and like magic I just went back into Android Studio to look at the project again and there's the Rainbow. :) thanks for the great work!
