### ISSUE TITLE
Brackets in unsupported languages not consistent with restart

### ISSUE THREAD

**Issue by egoisticalgoat** [izhangzhihao/intellij-rainbow-brackets#15]
When restarting PHPStorm while having a smarty template file open (not sure if other unsupported languages act the same, couldn't test it yet), after the restart the colouring of squiggly and normal brackets got lost. When i restarted while having another file open, everything worked fine. 

this was my code i tested this with
```smarty
<div class="lp-dialog">
  {if $hasTags}

  {/if}
</div>
```
When i first created this file, the curly braces got coloured in correctly as well as the html tags, but after restarting, the curly braces lost their colouring, and not even a restart of phpstorm changed that. But, when i closed the file or opened a tab with another file (not another smarty template, bug consists then) before restarting, they got coloured in correctly again.

Ps. The brackets on the closing 'if' are slightly bugged. Depending on if there's a space between the slash and the bracket, only the left or right one gets coloured, never both. But that's probably a different issue.

**Comment by izhangzhihao** [comment]
The option "Enable rainbow brackets for any languages even it's NOT supported (Restart required)" is still **experimental**, and maybe will been removed later.
