### ISSUE TITLE
Highlighting broken on v5.9 and light theme 

### ISSUE THREAD

**Issue by rohandhruva** [izhangzhihao/intellij-rainbow-brackets#155]
## Your programming language
Java / Kotlin

## Expected Behavior
On a light theme, brackets should be highlighted with a light colour

## Current Behavior
They're highlighted with dark colour, making them unreadable.

## Possible Solution
If fixing the issue is not straightforward, maybe an option to disable the block highlighting? 

## Code snippet for reproduce (for bugs)
n/a

## Your Environment

* Plugin version: 5.9
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

(also happens on Android studio 3.1 and intellij idea)

```
Android Studio 3.2 Beta 4
Build #AI-181.5281.24.32.4886486, built on July 11, 2018
JRE: 1.8.0_152-release-1136-b04 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
```

**Comment by rohandhruva** [comment]
Here's a few screenshots:

![image](https://user-images.githubusercontent.com/748533/42775204-aaa1f6f2-88e8-11e8-8ca2-5c222cf5c0e6.png)

![image](https://user-images.githubusercontent.com/748533/42775182-9c4732ac-88e8-11e8-862b-4eae9231258e.png)

**Comment by izhangzhihao** [comment]
Great catch! What about this: 
<img width="250" alt="screen shot 2018-07-17 at 10 01 03 am" src="https://user-images.githubusercontent.com/12044174/42792545-5d36706c-89a8-11e8-82bf-f2c0989b9235.png">

**Comment by izhangzhihao** [comment]
Here is a build snapshot : [intellij-rainbow-brackets-5.9.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/2199878/intellij-rainbow-brackets-5.9.zip)

**Comment by rohandhruva** [comment]
Perfect -- looks great, thank you so much @izhangzhihao for taking a look at the issue and fixing it so quickly (and for the excellent plugin!)
