### ISSUE TITLE
Error background color when cursor nears brackets

### ISSUE THREAD

**Issue by tyan-boot** [izhangzhihao/intellij-rainbow-brackets#157]
## Error Background Color
error background when cursor near to brackets etc.
![image](https://user-images.githubusercontent.com/4982027/42977142-0935d38e-8bf8-11e8-802b-5bfe2c9a5914.png)

<del>this happens when i upgrade IDEA to 181.5540.7</del>
Rollback to 5.8.3 and IDEA 2018 1.5 (5281.24) and it works well. But 5.9 stills incorrect in this IDEA version.

## Your Environment

* Plugin version: 5.9

```
IntelliJ IDEA 2018.1.6 (Ultimate Edition)
Build #IU-181.5540.7, built on July 11, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by izhangzhihao** [comment]
See #155
