### ISSUE TITLE
Support for endif;

### ISSUE THREAD

**Issue by N6REJ** [izhangzhihao/intellij-rainbow-brackets#16]
Please add support for : & endif;
I love the color matching!

**Comment by izhangzhihao** [comment]
The purpose of this plugin is to colorify **brackets**, so we won't support `endif` or something else. Maybe we could create another new plugin for what you expected.

**Comment by N6REJ** [comment]
@izhangzhihao i understand that, and thats wonderful, but ? '' : '' are the same as if/else brackets so why not include that function?  just seems a natural fit.

**Comment by izhangzhihao** [comment]
This plugin don't care `if/else` as well.
