### ISSUE TITLE
Color indent guide lines

### ISSUE THREAD

**Issue by Phoenix616** [izhangzhihao/intellij-rainbow-brackets#164]
## Expected Behavior
* There should be an option to color the indent guide lines the same as the curly brackets on that level:
![With bracket colors](https://user-images.githubusercontent.com/5768781/43349013-f3bd952a-91f4-11e8-9acb-48ffdf49f7d9.png)

* Maybe it could use a sightly opaque/darker version of the bracket color as the bright one might be a bit much:
![With darker bracket colors](https://user-images.githubusercontent.com/5768781/43349068-3a62ebb0-91f5-11e8-80dc-9c9651d1196c.png)

## Current Behavior
* Indent guide lines use one color for everything:
![Current coloring](https://user-images.githubusercontent.com/5768781/43349003-e59c2704-91f4-11e8-9a7e-92d03d403832.png)

## Your Environment

* Plugin version: 5.9.1
* IDE & Operating System version:

```
IntelliJ IDEA 2018.1.1 EAP (Ultimate Edition)
Build #IU-181.4445.4, built on March 29, 2018

JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

**Comment by izhangzhihao** [comment]
Some useful info : [Change color of code fold markers and guide lines](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206178229-Change-color-of-code-fold-markers-and-guide-lines-).

**Comment by izhangzhihao** [comment]
Some useful info : [Change color of code fold markers and guide lines](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206178229-Change-color-of-code-fold-markers-and-guide-lines-). If we are going to implement this feature we need to override the built-in color settings.

**Comment by kamronbatman** [comment]
@izhangzhihao, I think that is expected?

**Comment by izhangzhihao** [comment]
It's a nice to have feature I think.

**Comment by Polyterative** [comment]
This would be absolutely fantastic

**Comment by RacerDelux** [comment]
Agreed. Very useful feature. Helps to distinguish code blocks a bit better.

**Comment by YiiGuxing** [comment]
We need to paint our own indent guide:
1.  Create a range highlighter and add it to `MarkupModel` : `MarkupModel.addRangeHighlighter()` ;
2. Add a `CustomHighlighterRenderer` to the range highlighter: `RangeHighlighter.setCustomRenderer(CustomHighlighterRenderer)` ;
3. Paint custom indent guides in  `CustomHighlighterRenderer.paint()` .

See: `com.intellij.codeInsight.daemon.impl.IndentsPass` .

**Comment by vroudge** [comment]
I would L O V E this feature

**Comment by shoelessness** [comment]
Perhaps there could also be an option to color the indents, not just the guides, as [vscode-indent-rainbow](https://github.com/oderwat/vscode-indent-rainbow) does?

**Comment by JTBrinkmann** [comment]
this probably is beyond the scope of this plugin, but the indent guide highlighting of the Atom package [indent-guide-improved](https://atom.io/packages/indent-guide-improved) might offer some inspiration for good UX.

![screenrecording of indent-guide-improved](https://i.github-camo.com/83f38ef15d0f90120fec4fc21fab18fc3ac0effc/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f68617261692f696e64656e742d67756964652d696d70726f7665642f6d61737465722f646f632f64656d6f2e676966)

**Comment by willemjanvdun** [comment]
Love this idea! You have got my vote ;)

**Comment by lecksfrawen** [comment]
As an alternative, it could be implemented as in this VSCode plugin:
https://github.com/oderwat/vscode-indent-rainbow

![image](https://user-images.githubusercontent.com/303818/61401355-7f40ec00-a897-11e9-928f-20c45adfd7e3.png)

**Comment by TheBestPessimist** [comment]
Btw, intellij already provides this in a way: 
![intellij](https://user-images.githubusercontent.com/4482210/61442453-52044480-a950-11e9-80fa-9d5746cd70cb.gif)

**Comment by mattbishop** [comment]
I'd like to see this much more explicit. VS Code has a plugin that colorizes the indent space: https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow

**Comment by charl-nml** [comment]
The VS Code plugin @mattbishop  mentions above is super handy. 
![image](https://user-images.githubusercontent.com/55179403/64675453-83425200-d473-11e9-9061-55bde68abcc1.png)

**Comment by tomcatnach** [comment]
+1 for this issue, really makes me want to use VSCode as somebody who has to format YAML.

**Comment by YiiGuxing** [comment]
# It's Coming Soon!!!
![IndentGuide](https://user-images.githubusercontent.com/10737066/65654570-e45d4e80-e04b-11e9-9849-ed9523d60ec5.png)

**Comment by izhangzhihao** [comment]
在 2019年9月26日，上午10:55，Yii.Guxing <notifications@github.com> 写道：
Ohhhhhhhhhhhhhh

**Comment by vroudge** [comment]
Amazing ! I've been following this issue for such a long time, I'm so happy
that this is happening. It was the ONE feature I liked from VSCode and that
I wanted. Thank you!!

**Comment by YiiGuxing** [comment]
![img](https://user-images.githubusercontent.com/10737066/65765792-c41cb500-e15b-11e9-8877-2239c6afa7bf.gif)

**Comment by Phoenix616** [comment]
That looks really cool! I could imagine that the highlighting could get annoying after a while so maybe there could be an option to toggle that behaviour? (if that isn't already planed)

**Comment by YiiGuxing** [comment]
@Phoenix616 The default is disabled because it is not perfect and there are still some issues that need to be resolved.
![image](https://user-images.githubusercontent.com/10737066/65766998-288d4380-e15f-11e9-81d4-0d6c54c55b57.png)

**Comment by Phoenix616** [comment]
I was more referring to an option disabling the highlight effect when selecting the block (so that it just stays the same color without getting brighter)

**Comment by YiiGuxing** [comment]
@Phoenix616 Highlighting is not easy to trigger.

**Comment by RacerDelux** [comment]
Looks like it does not work in .vue files.

**Comment by TheBestPessimist** [comment]
There's 1 thing which could be improved for this feature: when the cursor is over a bracket (and the bracket and its pair are highlighted), the corresonding indent guide should also be highlighted.

wdyt about this?


![image](https://user-images.githubusercontent.com/4482210/67660740-2ab60e00-f968-11e9-9951-382c4e3f7881.png)

**Comment by JJCUBER** [comment]
I have this enabled, however it is not working in any of my file types (including .cs).  Rainbow Brackets also isn't working as a whole for .shader files for me.  Could someone please inform me on how to solve these issues?  I am on the latest version of Rider currently.
