### ISSUE TITLE
Copy/Paste the "selection"

### ISSUE THREAD

**Issue by naubry** [izhangzhihao/intellij-rainbow-brackets#169]
I think the ability to copy/paste the highlighted scope would be an interesting feature, no?
I assigned the plugin to the left double click, which can simulate a selection with the mouse as on Eclipse for example. But for the moment, copy/paste is not possible. #

**Comment by izhangzhihao** [comment]
But scope highting depend on where your cursor is your cursor will move when you are trying to copy/parse highlighted scope so that the highlighted scope will move...

**Comment by naubry** [comment]
When I assign the plugin to the left double click, I can move my cursor, move in the file with the scroll wheel or scrollbar, or click with my mouse to another place of the file without losing the selection by the plugin.
![2018-08-15_11-21-53](https://user-images.githubusercontent.com/141868/44141692-2a47e8ba-a07e-11e8-9d1c-18154f601ead.jpg)

**Comment by izhangzhihao** [comment]
Maybe related to #65  "Do not remove effect until clicking".

**Comment by naubry** [comment]
For me the behavior is really good. I lose the selection only if I press a key on my keyboard. But maybe this is a bug that actually suits me.

**Comment by izhangzhihao** [comment]
I think when you press another key on the keyboard will be a new keymap realized by the ide itself, it means release last keymap as well, then remove effects will be by design.

**Comment by innerfly** [comment]
It would be handy to have a possibility to copy highlighted area
