### ISSUE TITLE
Missing color in PHP annotations

### ISSUE THREAD

**Issue by garak** [izhangzhihao/intellij-rainbow-brackets#17]
See image, one of curly brackets should be yellow and is uncoloured instead
![schermata del 2018-01-02 15-43-54](https://user-images.githubusercontent.com/179866/34487224-abf4df96-efd3-11e7-8f15-89bc29c284a4.png)

**Comment by izhangzhihao** [comment]
If you have free time to add a specific implement for PHP language, If we have a specific implement we could fix this issue. please take a look [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#implement-for-some-language-you-would-like)

**Comment by izhangzhihao** [comment]
Check out here: https://www.jetbrains.org/intellij/sdk/docs/phpstorm/php_open_api.html
And all tokens should be in `com.jetbrains.php.lang.lexer.PhpTokenTypes` package, so that would be easy.

**Comment by izhangzhihao** [comment]
PS: I guess I would not do it myself cause I didn't have any knowledge about PHP.
