### ISSUE TITLE
Use high-contrast colors on adjacent brackets

### ISSUE THREAD

**Issue by roshad** [izhangzhihao/intellij-rainbow-brackets#171]

**Comment by roshad** [comment]
![20180830194141212](https://user-images.githubusercontent.com/30169506/44849442-b5c84500-ac8c-11e8-9518-e08e2c0fd20d.jpg)
difficult to distinguish

**Comment by izhangzhihao** [comment]
Will fixed in next release. For now, you can adjust your own color schema by [customize-colors](https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors).
