### ISSUE TITLE
dependencies: kotlin-compiler?

### ISSUE THREAD

**Issue by YiiGuxing** [izhangzhihao/intellij-rainbow-brackets#178]
为什么要依赖kotlin-compiler？
https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/7ca9eec37c1931ab5172dd8e6e970de6b38116ce/build.gradle#L61
https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/7ca9eec37c1931ab5172dd8e6e970de6b38116ce/build.gradle#L62

这会影响插件代码对IntelliJ Platform API的使用！

**Comment by izhangzhihao** [comment]
删掉确实是可以的，不过为什么加了kotlin compiler的依赖会影响对IntelliJ Platform API的使用呢？

**Comment by YiiGuxing** [comment]
两者API有冲突，有相同的类，但方法不同，IDE只认kotlin compiler的。我在color-settings分支删了的，其他的先不动吧。我只是怕你有什么特殊用途才在这问的。

**Comment by izhangzhihao** [comment]
没什么特别用途，可以删掉～
