### ISSUE TITLE
where to customize brackets color ?

### ISSUE THREAD

**Issue by adrianmak** [izhangzhihao/intellij-rainbow-brackets#18]
as title

**Comment by izhangzhihao** [comment]
Not able to customize color yet.

**Comment by tg44** [comment]
Would be nice to get color options as inside themes, bcs these colors are really hard to see on the light theme... Random idea: what if the RainbowColors.kt would populated from some kind of config file, and on the conf menu we can choose from multiple configs files?
(If I will have time this weekend, I will try to implement this.)

**Comment by izhangzhihao** [comment]
@tg44 That would be great! Cause I'm really unfamiliar with swing 😭 ! PR welcome!

**Comment by ironhussar** [comment]
It would be great if the colour options could be broken up by language and bracket type. To make it easy, it could just be written in a config file, where you can specify the colours you want to use (in hex). If the file doesn't exist, then the plugin would use its default colour generation.

This would mean those who want to customise can, but it's not mandatory.

Thanks for this great plugin!

**Comment by izhangzhihao** [comment]
Please try this snapshot build [intellij-rainbow-brackets-5.0.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1859249/intellij-rainbow-brackets-5.0.zip).

If you want to config the color, add this to your config file(APP_CONFIG/rainbow_brackets.xml), In my env(mac os) is /Users/izhangzhihao/Library/Preferences/IntelliJIdea2018.1/options/rainbow_brackets.xml:

```xml
<option name="lightRoundBracketsColors">
      <array>
        <option value="0xE6B422" />
        <option value="0x43A047" />
        <option value="0x2196F3" />
        <option value="0x3F51B5" />
        <option value="0x00897B" />
      </array>
 </option>
```

The default color:

``` kotlin
    var lightRoundBracketsColors = arrayOf(
            "0xE66A01",
            "0x1B5E20",
            "0x006BE7",
            "0x283593",
            "0x004D40"
    )

    var darkRoundBracketsColors = arrayOf(
            "0xE6B422",
            "0x43A047",
            "0x2196F3",
            "0x3F51B5",
            "0x00897B"
    )

    var lightSquareBracketsColors = arrayOf(
            "0x0B9087",
            "0x827717",
            "0x6444E6"
    )

    var darkSquareBracketsColors = arrayOf(
            "0x33CCFF",
            "0xD4E157",
            "0x8080FF"
    )

    var lightSquigglyBracketsColors = arrayOf(
            "0x0057D2",
            "0x558B2F",
            "0xFF6D27"
    )

    var darkSquigglyBracketsColors = arrayOf(
            "0x1976D2",
            "0x8BC34A",
            "0xFF9863"
    )

    var lightAngleBracketsColor = lightRoundBracketsColors
    var darkAngleBracketsColor = darkRoundBracketsColors
```

**Comment by izhangzhihao** [comment]
**NOTE:The lightXXX and the darkXXX should be the same size!**

**Comment by iwaduarte** [comment]
How to achieve that configuration in webstorm 2019 version?

**Comment by izhangzhihao** [comment]
@iwaduarte check it out https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors
