### ISSUE TITLE
Custom `Matched brace` color scheme

### ISSUE THREAD

**Issue by arozans** [izhangzhihao/intellij-rainbow-brackets#180]
## Expected Behavior
User should have a possibility to choose`Matched brace` color scheme ( File | Settings | Editor | Color Scheme | General | Matched brace).

## Current Behavior
At every startup those colors are being overriden by plugin with colors that look too pale for brackets for which plugin is not turned on.

## Possible Solution
An option to not override `Matched brace` color scheme.

## Environment

* Plugin version:
v5.10

* System:
```
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.3647.12, built on October 10, 2018
JRE: 1.8.0_152-release-1343-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic
```

**Comment by izhangzhihao** [comment]
If you don't want intellij-rainbow-brackets to override `Matched Brace` color schema, you can set `overrideMatchedBraceAttributes` to `false` in your config file(`APP_CONFIG/rainbow_brackets.xml`) then restart your IDE, In my env(MAC os) is `/Users/izhangzhihao/Library/Preferences/IntelliJIdea2018.3/options/rainbow_brackets.xml`:

```
<application>
  <component name="RainbowSettings">
    <option name="overrideMatchedBraceAttributes" value="false"/>
  </component>
</application>
```

**Comment by arozans** [comment]
Thanks - that works. Under Ubuntu machine the path is  ~/.IntelliJIdea<version>/config/options/rainbow_brackets.xml

**Comment by oxysoft** [comment]
This should be added to the settings page. I was about to post an issue about the plugin resetting my color scheme configuration.

edit: Even with this setting, it's still messing up my 'Matched brace' configuration and forcing bold onto it. Jetbrains Rider 2018.3.3 on W10.

**Comment by izhangzhihao** [comment]
@oxysoft Your IDE need a restart.

**Comment by mallowigi** [comment]
Resurrecting this issue, there should be a setting for that, I just reported an issue to JetBrains unbeknownst of this issue.

**Comment by ghost** [comment]
Same. This should be set to not override by default.

**Comment by ghost** [comment]
Just did this, it doesn't work in my case. I'm sure that:
* I'm using the correct config file and the cooresponding IDE.
* The color isn't what I set before restart. 

My config file.
```xml
<application>
  <component name="RainbowSettings">
    <option name="customNotifyShowed" value="true" />
    <option name="version" value="5.19" />
    <option name="overrideMatchedBraceAttributes" value="false"/>
  </component>
</application>
```
Thanks for looking into this.

**Comment by nerdy-panda** [comment]
not working for me !!! 
The color has changed, but does not colorize the settings

**Comment by izhangzhihao** [comment]
@itonedeveloper your ide version?

**Comment by nerdy-panda** [comment]
@izhangzhihao 

PhpStorm 2019.1.3

**Comment by izhangzhihao** [comment]
Seems related to #234, please try [this](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/243#issuecomment-524383270) snapshot.
