### ISSUE TITLE
Ability to increase the number of colours in the IDE

### ISSUE THREAD

**Issue by phunni** [izhangzhihao/intellij-rainbow-brackets#187]
## Your programming language
Java

## Expected Behavior
There should be an option in the settings in Idea to increase/decrease the number of colours available.

## Current Behavior
I believe, from looking around at different issues, that it may be possible to increase/decrease the number of colours by editing a config file. It seems to me that it would be good to be able to do this with the settings UI in the IDE

## Your Environment

* Plugin version: 5.10
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1380-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.71-rt44-1-rt-lts
```

**Comment by phunni** [comment]
Would it be possible for someone to confirm that, in the meantime, this is possible via a config file and, if so, give examples?

**Comment by anthonyp-cs** [comment]
This would definitely be helpful for deeply nested SASS/SCSS. Is there a way to achieve this in the config file?

**Comment by izhangzhihao** [comment]
Yep, in versions before 5.9.1, users could define infinite levels of colors in the config file.

**Comment by izhangzhihao** [comment]
@YiiGuxing Can we add this feature to the config panel?

**Comment by YiiGuxing** [comment]
@izhangzhihao Can't add colors dynamically. Maybe we can do this by configuring the number of colors.

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/73246108-c580eb80-41e8-11ea-8910-02337d254cbf.png)

![image](https://user-images.githubusercontent.com/12044174/73246227-0aa51d80-41e9-11ea-8259-b9d233a0639f.png)

**Comment by izhangzhihao** [comment]
### Want to config the number of colors?

<kbd>Settings/Preferences</kbd> > <kbd>Other Settings</kbd> > <kbd>Rainbow Brackets</kbd> > `Number of colors`: 10 or more

NOTE: There are 10 default colors for both light and dark theme, if your number is bigger than 10, you can config them in the config file.
Please fellow [the official guide](https://www.jetbrains.com/help/idea/configuring-colors-and-fonts.html#share-color-scheme): 
* `Export a color scheme as XML`
* Edit the xml file, put `ROUND_BRACKETS_RAINBOW_COLOR10` to `ROUND_BRACKETS_RAINBOW_COLOR100` to match your number just like [the default color scheme](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/IC-2017.2/src/main/resources/colorSchemes/rainbow-color-default-darcula.xml).
* `Import a color scheme`

**Comment by izhangzhihao** [comment]
By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.
