### ISSUE TITLE
Can not scroll when highlight activated

### ISSUE THREAD

**Issue by luokuning** [izhangzhihao/intellij-rainbow-brackets#188]
## Expected Behavior
When I activate rainbow bracket highlight with `⌘` + `Button3 click`, I can scroll editor with touchpad (two fingers scroll)

## Current Behavior
When rainbow bracket highlight is activated, I can not scroll editor with touchpad

I don't know whether it's a bug or it's designed to be like that.

## Your Environment

* Plugin version: 5.10

```
WebStorm 2018.2.5
Build #WS-182.4892.25, built on October 18, 2018
Subscription is active until November 5, 2019
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

**Comment by izhangzhihao** [comment]
Actually, `⌘` + `two fingers scroll` is another shortcut:

![image](https://user-images.githubusercontent.com/12044174/48200993-bfaca980-e39b-11e8-80a9-da9d6d9da52a.png)

**Comment by izhangzhihao** [comment]
And `Highlight current scope` only works when `⌘` + `Button3` pressed.

**Comment by izhangzhihao** [comment]
![screen recording 2018-11-08 at 9 12 16 pm](https://user-images.githubusercontent.com/12044174/48201815-38ad0080-e39e-11e8-972f-9adce96f4c43.gif)

**Comment by luokuning** [comment]
Got it, So is there any way that I can scroll the editor while I'm highlighting the scope?

**Comment by izhangzhihao** [comment]
I think this may be related to #65 . I mean if #65 implemented, you could scroll the editor while highlighting.
