### ISSUE TITLE
Kotlin expression inside string bug

### ISSUE THREAD

**Issue by rostopira** [izhangzhihao/intellij-rainbow-brackets#19]
I can't explain better, than with screenshot
![screen shot 2018-01-03 at 12 16 19 pm 2](https://user-images.githubusercontent.com/16724952/34514807-2509f4b4-f080-11e7-9425-e4b3cacd4c85.png)

**Comment by Alexsey** [comment]
It's strange. Is `rainbow-brackets` depends on language? In JS same combination of brackets doesn't produce such effect:
```js
function f () {
    console.log(`${console.log()}`)
}
```

![1](https://user-images.githubusercontent.com/6392013/34561824-7947420a-f154-11e7-8cbd-2245686030c1.png)

**Comment by rostopira** [comment]
@Alexsey pay attention to string format. In Kotlin it's inside "${}" instead of `${}` in Js

**Comment by Alexsey** [comment]
Yes, you are right - probably that's the reason for different behavior

**Comment by izhangzhihao** [comment]
<img width="453" alt="screen shot 2018-01-10 at 11 16 10 am" src="https://user-images.githubusercontent.com/12044174/34754296-d7a7d952-f5f7-11e7-99d9-ba1eb3e15a5b.png">

Should be fixed in kotlin, I will push to github later.
