### ISSUE TITLE
Remove red-variation colors from default configuration!!!

### ISSUE THREAD

**Issue by urosjarc** [izhangzhihao/intellij-rainbow-brackets#192]
Many times it happens that brackets turn kinda red when I'm programming and I try to figure it out if this is a syntax error or some strange intelij hints that is playing with me.

I know you can setup scheme, but red and all its variations should be banned from default plugin configuration.

I saw that many issues have been reported before me, but this issue perssist because brackets with lower font size settings looks like some error (even if color is orange).

![screenshot from 2018-11-27 11-43-53](https://user-images.githubusercontent.com/8678755/49076654-cd867980-f239-11e8-9cd5-ff25c3dbe55c.png)

**Comment by izhangzhihao** [comment]
Ok, do you have any thoughts on the new colors?

**Comment by izhangzhihao** [comment]
Especially for the light theme, cause I'm not really like the default color config for the light theme.

**Comment by urosjarc** [comment]
I would really suggest that you use colors described in this study and chose those which appeal the most people... http://www.joehallock.com/edu/COM498/preferences.html

**Comment by urosjarc** [comment]
Here is aggregated data sets: http://www.joehallock.com/edu/COM498/datasets.html
