### ISSUE TITLE
Ignore Haskell multiline comments and pragmas

### ISSUE THREAD

**Issue by develop7** [izhangzhihao/intellij-rainbow-brackets#196]
## Your programming language

Haskell

## Expected Behavior

The `{-`/`-}` brackets should not be highlighted since they cannot be nested

## Current Behavior

They are highlighted, here: 
![image](https://user-images.githubusercontent.com/89889/49326518-523c0500-f564-11e8-8773-f672a271b87e.png)

## Code snippet for reproduce (for bugs)

```haskell
{-# LANGUAGE TypeFamilies          #-}
{-# LANGUAGE TypeSynonymInstances  #-}
{-# LANGUAGE UndecidableInstances  #-}
``` 

## Your Environment

* [intellij-Haskell v1.0beta36](https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta36)
* Plugin version: 5.12
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.4-1-default (GNOME 3.30.2 on openSUSE Tumbleweed 20181129)
```

**Comment by izhangzhihao** [comment]
Oh, I bet it is a feature. This plugin not only rainbowify nested brackets but also rainbowify the brackets which cannot be nested.

**Comment by develop7** [comment]
@izhangzhihao the very point of rainbowification is to help dealing with *nested* brackets, isn't it?

**Comment by izhangzhihao** [comment]
Yes, but not only rainbowify nested brackets.


________________________________
收件人: Andrei Dziahel <notifications@github.com>
发送时间: 星期三, 十二月 5, 2018 3:11 上午
收件人: izhangzhihao/intellij-rainbow-brackets
抄送: 张志豪; Mention
主题: Re: [izhangzhihao/intellij-rainbow-brackets] Ignore Haskell multiline comments and pragmas (#196)


@izhangzhihao<https://github.com/izhangzhihao> the very point of rainbowification is to help dealing with nested brackets, isn't it?

―
