### ISSUE TITLE
在Android Studio中，Kotlin支持不是很完善

### ISSUE THREAD

**Issue by dhhAndroid** [izhangzhihao/intellij-rainbow-brackets#197]
**You should “star” this repo before creating a issue, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issue track](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) before creating one.

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, explain the difference from current behavior

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Please provide code snippet

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.519, built on March 22, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

**NOTE: If you are reporting a performance issue, please comment your hardware env like this:**

```
CPU: 2.2 GHz Intel Core i7
Total Number of Cores: 4
Memery: 16GB 1600 MHz DDR3
Storage: 256GB SSD
```
### AS最新版本，本插件也是最新版本，效果如下图
![_20181207132138](https://user-images.githubusercontent.com/22829707/49629385-46e54f80-fa24-11e8-9562-65f0d021c4e8.png)

**Comment by izhangzhihao** [comment]
I guess your code does not compile.
