### ISSUE TITLE
Inconsistent Colors  (C)

### ISSUE THREAD

**Issue by sitbon** [izhangzhihao/intellij-rainbow-brackets#198]
## C colors -- occasional mismatch

Hello, loving this plugin. Just seeing this here and there:

![screenshot_20181210_181916](https://user-images.githubusercontent.com/1381063/49774235-e87cd300-fca8-11e8-98cc-a379c82c7e11.png)

* Plugin version: v5.12
* IDE:
```
CLion 2018.3
Build #CL-183.4284.156, built on November 23, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-3-amd64
```

**Comment by izhangzhihao** [comment]
Please provide a valid sample code

**Comment by sitbon** [comment]
Sorry, I originally thought this was trivially reproducible.

Turns out not, such that I cannot copy-paste the offending code into another C file without references and see the same result. Also, I tried reproducing the issue based solely from the nesting structure of the code and that didn't work either.

I'm unable to share the rest of the code in the above snippet until it is made open source (soon), but I managed to find another simpler example (with full code [here](https://github.com/sitbon/mtou/blob/4eafce5c6097a042c3681f0fa13672df7eba569f/main.c#L338)):

![screenshot_20181212_170901_snip](https://user-images.githubusercontent.com/1381063/49908829-1ab93c80-fe31-11e8-94bd-5190aecfd6ca.png)

Hope that helps a little. Thanks again for the great plugin.

**Comment by intellij-rainbow-brackets** [comment]
Minimum sample should be:

```C
#include <iostream>

void issue198() {
    if (errno) perror("sendto");
}
```
![image](https://user-images.githubusercontent.com/39412597/49915246-7f2ad900-fecf-11e8-9a4e-859548005a1d.png)

**Comment by intellij-rainbow-brackets** [comment]
But if we simply change `errno` to `true` :
![image](https://user-images.githubusercontent.com/39412597/49930567-d8126580-feff-11e8-8de4-975808b3af71.png)

**Comment by izhangzhihao** [comment]
Similar with #41 and related to macros.

**Comment by sitbon** [comment]
Here is another example in case it is useful, although it is probably the same macro-related issue.

![screenshot_20181220_122002](https://user-images.githubusercontent.com/1381063/50308970-d42b9980-0451-11e9-8280-01dc013df15f.png)

```C
#define A       ((int)12)
#define B       13
#define C       (signed char)(-81 - 3)

struct st {
    int a, b;
};

static const struct st VALUES[] = {

        {A, (C)},
        {B, (2)},
        {A, (B)},
        {A, (A)},
        {(A), C},

        {A, A | (B << A)},
        {A, B},

        {A, B},
        {B, A | B | (B+1) | (B-1)},
        {A, B},
        {B, A + B},
        {B, A},

        {B, C},
        {B, C - A},

        {B, (char) A},
        {B, (unsigned char) (-97 - C)},

        {C, A},

};
```

**Comment by intellij-rainbow-brackets** [comment]
![image](https://user-images.githubusercontent.com/39412597/50321165-7ad37100-050a-11e9-9870-61d2e9dfeb1a.png)
Works as expected at latest version.
