### ISSUE TITLE
Change the default color schema in light theme

### ISSUE THREAD

**Issue by hallozhm** [izhangzhihao/intellij-rainbow-brackets#1993]
The default 5 colors in light themes look so close to black, so many people like me may mistake it doesn't work.

**Comment by izhangzhihao** [comment]
You are right, the light theme doesn't seem as good as we want it. But I didn't have better ideas of the color schema, if you have any, PR welcome

**Comment by izhangzhihao** [comment]
By the way, you still could [customize your color](https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors) or [use color generator](https://github.com/izhangzhihao/intellij-rainbow-brackets#use-color-generator).

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/125185334-e6ab8f80-e256-11eb-85fe-495dc53f341b.png)

We will release a new color schema for the light theme in the next release. 

Closed by https://github.com/izhangzhihao/intellij-rainbow-brackets/commit/85db7e2f664302be773b2717a9bf5788edf243cc
