### ISSUE TITLE
Don't highlight empty brackets

### ISSUE THREAD

**Issue by nvlad** [izhangzhihao/intellij-rainbow-brackets#2]
may be add option to enable it

**Comment by izhangzhihao** [comment]
What do you mean about "Don't highlight empty brackets" ? Could you please leave an example code ? And your OS version and  which product you are using and which language you want to hight ? Thansk.

**Comment by nvlad** [comment]
I'm thinking empty brackets "()" "<>" "[]" draw with default color. 
ex. 
`FunctionName()` empty "()" on function call
