### ISSUE TITLE
Feature request: mark return@closure with same color as bracket (Kotlin)

### ISSUE THREAD

**Issue by rostopira** [izhangzhihao/intellij-rainbow-brackets#20]
Consider following kotlin code
```
someClosure {
    internalClosure {
        return@someClosure
    }
}
```
`@someClosure` is colored with blue by default. Would be very handy, if it were marked with the same color as `someClosure` brackets

**Comment by rostopira** [comment]
Also, consider following case with renamed closures
```
x.getValue {
    y.getValue get2@ {
        return@get2
    }
}
```

**Comment by izhangzhihao** [comment]
Similar to #34 .

**Comment by izhangzhihao** [comment]
I'm going to close it because this new features should belong to a new plugin (not exist for now, maybe you could create one. Maybe something like [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) will also helpful), this plugin only rainbow-ify brackets.

**Comment by izhangzhihao** [comment]
Feel free to re-open it or raise a new one if you have any issue.
