### ISSUE TITLE
Settings reset every time Intellij IDEA starts up

### ISSUE THREAD

**Issue by sentoren** [izhangzhihao/intellij-rainbow-brackets#201]
## Your programming language
Java

## Expected Behavior
* Custom Settings for Rainbow Brackets are saved upon closing Intellij IDEA and become available when Intellij IDEA is started back up.
* Rainbow Brackets won't post an "updated plugin" message if update wasn't applied.

## Current Behavior
* Custom Settings revert to default upon Intellij IDEA start-up.
* Notification that Rainbow Brackets has updated occurs on start-up, despite being on the latest release for quite some time.

## Code snippet for reproduce (for bugs)
Please provide code snippet

## Your Environment

* Plugin version: 5.13
* IDE & Operating System version:

```
IntelliJ IDEA 2018.2.7 (Ultimate Edition)
Build #IU-182.5107.41, built on November 26, 2018
JRE: 1.8.0_152-release-1248-b22 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

## Additional Notes
Issue does not occur on PyCharm which also has Rainbow Brackets installed.

**Comment by izhangzhihao** [comment]
What else plugins have you installed? I think that may because of plugin conflict.

**Comment by sentoren** [comment]
Thanks for the quick response! I did a reinstall of Intellij and cleared out unnecessary custom plugins, and it is now fixed. It's possible that it was conflicting with the Night Owl Theme plugin, but could have also just been an issue that was resolved with the resinstall.

Closing this issue since it is resolved now for me.
