### ISSUE TITLE
not working with Rider c#

### ISSUE THREAD

**Issue by DotNetDevlll** [izhangzhihao/intellij-rainbow-brackets#207]
Hi,

First of all thank you for this awesome plugin!
The plugin works fine in Phpstorm, but not in Rider. Tried on serveral .cs file
(version 5.14.  Rider 2018.3.1)

There is any hope Rider will be supported in the near future?

**Comment by izhangzhihao** [comment]
You should upgrade your Rider IDE, try Rider 2018.3 or above. See https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/6#issuecomment-440285295
