### ISSUE TITLE
Add support for Java decompiled code

### ISSUE THREAD

**Issue by Thihup** [izhangzhihao/intellij-rainbow-brackets#209]
## Expected Behavior
 - Please add support for decompiled Java code

## Current Behavior
  - Java decompiled code doesn't have bracket highlighting.

## Your Environment
- Plugin version: 5.14
IntelliJ IDEA 2019.1 EAP (Ultimate Edition)
Build #IU-191.4212.41, built on January 24, 2019
JRE: 1.8.0_152-release-1402-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29deepin-generic

**Comment by izhangzhihao** [comment]
I'm going to close this ticket because it seems not possible to do.
