### ISSUE TITLE
Wrong bracket colorization based on spaces

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#21]
Consider JS code
```js
`open (${f})`
```
CB: Last round bracket is colored blue with `rainbow-brackets`
![1](https://user-images.githubusercontent.com/6392013/34617465-32bfed82-f244-11e7-8850-bc45112ce98a.png)

EB: Last round bracket should be green the same as the first one and should not be colorized with `rainbow-brackets` at all because it's a plane text

BTW:
```js
`open (${f} )`
```
Is working fine. So the issue is about wrong space-based recognition of scopes
![2](https://user-images.githubusercontent.com/6392013/34617532-6ed2e126-f244-11e7-8e46-7ce73fc115b6.png)

**Comment by izhangzhihao** [comment]
<img width="214" alt="screen shot 2018-01-11 at 1 24 26 pm" src="https://user-images.githubusercontent.com/12044174/34809848-c5933c12-f6d2-11e7-9335-be673a3e2e5c.png">

Should been fixed in next release !
