### ISSUE TITLE
Add language black list to settings page rather than config file

### ISSUE THREAD

**Issue by yunti** [izhangzhihao/intellij-rainbow-brackets#210]
## Your programming language
python, (and others)

Rainbow brackets is very useful for non languages which don't use whitspace eg js, and C style languages.   
Hopwever for languages that do use whitespace eg Python - I definitely don't have a need for this, and it just creates noise.

Can an option be added to opt out certain languages (eg based on file extension?)

**Eh whoops, I should have read the readme all the way to the bottom.  Can this be added to settings rather than just config file?**

**Comment by izhangzhihao** [comment]
Actually, we have no intention to add this feature.
