### ISSUE TITLE
Make the colors brighter

### ISSUE THREAD

**Issue by feinstein** [izhangzhihao/intellij-rainbow-brackets#213]
I am using the Dracula theme and a lot of the brackets colors are very dim and hard to see, like this one:

![image](https://user-images.githubusercontent.com/8120472/54310507-4aebb500-45b1-11e9-82cf-b91e2bdabdce.png)

It would be nice to have brighter colors, or some sort of adjustment of the brightness of the colors.

**Comment by izhangzhihao** [comment]
checkout https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors

**Comment by feinstein** [comment]
Yeah, I am using this, but I have change a bunch of colors, I just wished there was a simpler way to do it... maybe let people share a theme, so we could get rainbow-themes for our themes? Like best colors for Dracula

**Comment by izhangzhihao** [comment]
Good idea😁

**Comment by izhangzhihao** [comment]
Closed for duplicated with #214
