### ISSUE TITLE
Choose base color

### ISSUE THREAD

**Issue by gleich** [izhangzhihao/intellij-rainbow-brackets#214]
Lets you choose what is the base color and what the levels would be. So for example right now its orange but I wanna have the base one be blue. This isn't a big deal I just think it would be nice. For me, all of the variables in my theme are the same color orange so its kinda weird

**Comment by e-belair** [comment]
:+1: In my case the base color should be white. That could mean that there is no deeper brackets and color only if contains deep.

**Comment by john5f35** [comment]
One step further, maybe add a colour palette feature. I'm using Material Darker theme and the default colour palette that the rainbow colour plugin uses makes the brackets quite invisible.
Having the colour palette will solve this base colour issue along with giving more flexibility and control to users.

**Comment by izhangzhihao** [comment]
This feature will happen in the next release. Please check [the advance options](https://izhangzhihao.github.io/rainbow-brackets-document/#use-color-generator). If you want to have a try, please download the snapshot build from [here](https://izhangzhihao.github.io/rainbow-brackets-document/#install-snapshot-build). By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.
