### ISSUE TITLE
More color options for squiggly brackets before cycle?

### ISSUE THREAD

**Issue by ktoso** [izhangzhihao/intellij-rainbow-brackets#215]
## Your programming language(s)

Scala, Java, C, C++, Swift

## Current Behavior

Currently squiggly brackets only allow for 3 colors, would it be possible to add more color options here? I would want to have more colors (like in round brackets) available here, since for better or worse I often have more nested things due to namespaces etc.

![Screen Shot 2019-03-29 at 11 21 02](https://user-images.githubusercontent.com/120979/55205083-bde16680-5214-11e9-82fd-b117536f1173.png)

## Possible Solution

We could add more colors, e.g. 6 in total; current users could have the latter 3 set exactly as the prior 3 so no change in behavior would happen for them. Users who want more colors could configure them (i.e. more colors before they cycle for squiggly brackets).

## Your Environment

* Plugin version: v5.16
* IDE & Operating System version:

```
CLion 2019.1 Beta
Build #CL-191.6183.6, built on March 13, 2019
CLion EAP User
Expiration date: April 12, 2019
macOS 10.14.2
```

**Comment by izhangzhihao** [comment]
Related to #187

**Comment by izhangzhihao** [comment]
Now numbers of color options up to 5 for square & squiggly brackets, but the colors are undecided. PR welcome!

**Comment by ktoso** [comment]
Thank you!
