### ISSUE TITLE
Disable "Want to custom your own rainbow colors?" for every single project

### ISSUE THREAD

**Issue by ruudk** [izhangzhihao/intellij-rainbow-brackets#221]
First off all, I love this plugin and you do amazing work.

But since the latest version of this plugin, I get this notificatioon in every single project I open:
<img width="432" alt="Screenshot 2019-04-24 at 19 36 12" src="https://user-images.githubusercontent.com/104180/56680868-6b3a8380-66c8-11e9-9578-acf4cc2aeac9.png">

Why? Can't it just be shown once, or not at all?

**Comment by izhangzhihao** [comment]
You just need to click the link of the notification. And it will not appear in the next time.

**Comment by ruudk** [comment]
I clicked the X, but that will keep show it in new projects.

**Comment by izhangzhihao** [comment]
Yes, try click :
![image](https://user-images.githubusercontent.com/12044174/56746798-79af9a80-67af-11e9-9904-f3bc24435c0c.png)

**Comment by izhangzhihao** [comment]
I have to admit that this is a bit annoying...

**Comment by ruudk** [comment]
Maybe it would be best to just turn it off for everyone :)
