### ISSUE TITLE
Usage as feature for special cases

### ISSUE THREAD

**Issue by mickmack1213** [izhangzhihao/intellij-rainbow-brackets#222]
For me it's a bit colorful for regular usage, but it's a great plugin for complex mathematical expressions and for searching the missing bracket.

It would be great if there's a possibility to toggle the coloring (maybe a keyboard shortcut)

## Your programming language(s)
*Java

## Expected Behavior
*Toggle the coloring with a quick option

## Possible Solution
*Maybe use a keyboard shortcut.

## Your Environment

* Plugin version: 5.18
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon): 

```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-47-generic
```

**Comment by izhangzhihao** [comment]
Can you make a explanation of "toggle the coloring"?

**Comment by mickmack1213** [comment]
Toggle the bracket color, like push a keyboard shortcut and switch between the default IntelliJ bracket colors and the rainbow bracket colors.

**Comment by izhangzhihao** [comment]
You could disable rainbow brackets in setting page: 
![image](https://user-images.githubusercontent.com/12044174/56746696-4e2cb000-67af-11e9-9dd0-d5e2d946c3fb.png)

**Comment by mickmack1213** [comment]
Yeah but that's like a lot of clicks and after changing the settings it doesn't update the editor correctly.

**Comment by izhangzhihao** [comment]
Can you upload a screenshot?

**Comment by mickmack1213** [comment]
Of what?
Not updating the editor? I think I'm quicker describing it. You've opened a file in the Editor with rainbow brackets on or off it doesn't matter, switch it then off/on in the settings and close the settings. 

The Editor ist not updated correctly and the rainbow colors are still active, after switching them off, or they are still inactive after switching them on.

Without the bug and a keyboard shurtcut to activate/deactivate the Rainbow Brackets, i think this would improve this plugin a lot.
