### ISSUE TITLE
Feature request: `Region` comments support for the WebStorm

### ISSUE THREAD

**Issue by Ariane-B** [izhangzhihao/intellij-rainbow-brackets#2243]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://izhangzhihao.github.io/rainbow-brackets-document/) before creating one.

## Please check

- [x] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming language(s)

HTML, SCSS, JS, Vue.js

## Expected Behavior

WebStorm supports region comments. They're comments formatted like this (names are optional):
```
//#region This is a region
//#endregion This is a region
```

And they allow you to fold your code between matching comments, even though they're not code constructs.

It would be nice if Rainbow Brackets supported treating those as brackets and color-matched them too. Especially when names are omitted, it would make it clearer which `#region`s and `#endregion`s match together. For example:

```
//#region
//#region
//#endregion
//#region
//#endregion
//#endregion
```

Imagining lots of code in between those comments, they would certainly be a little less confusing if color-matched. 

## Your Environment

* Plugin version: 6.18
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
WebStorm 2021.1.2
Build #WS-211.7442.26, built on May 24, 2021
Licensed to CONFORMiT Technology Inc / Ariane Bouchard
Subscription is active until August 2, 2021.
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: undo.documentUndoLimit=9999
Non-Bundled Plugins: String Manipulation (8.15.203.000.3), com.andrey4623.rainbowcsv (2.0), com.wix.sasslint (1.1.2), de.netnexus.camelcaseplugin (3.0.8), in.xiv.cs (0.1), zielu.gittoolbox (203.5.10), tv.twelvetone.intellij.plugins.intellivue (1.1.4), izhangzhihao.rainbow.brackets (6.18)
```

**Comment by izhangzhihao** [comment]
I'm sorry, I do not really know SCSS, JS, Vue.js. Could you provide a sample code for them(for code snippets of HTML, SCSS, JS, Vue.js)?

```
//#region
//#region
//#endregion
//#region
//#endregion
//#endregion
```

is NOT enough.

**Comment by Ariane-B** [comment]
Sure!

SCSS:
```scss
.component {
   //#region Header & footer styles
   @mixin header-footer-common-styles {
      &--big {
         padding-top: 10px;
         padding-bottom: 10px;
      }
   }

   &__header {
      @include header-footer-common-styles;
      margin: 0;
      background-color: red;
   }

   &__footer {
      @include header-footer-common-styles;
      margin-top: 30px;
      background-color: blue;
   }
   //#endregion Header & footer styles

   //#region Body styles
   &__description {
      margin-top: 30px;
      font-size: 0.8em;
   }

   &__details {
      margin-top: 30px;
   }
   //#endregion Body styles
}
```

JS:
```javascript
//#region Imports
import '@/polyfills'

//#region Vue-related imports

//#region Vue imports & essential plugins

import Vue from 'vue'
import App from '@/App'

import router from './router'
import store from '@/stores/store'
import { i18n } from '@/utils/customWrapper/i18n'

//#endregion Vue imports & essential plugins


//#region Vue helper plugins

import { VueLogger } from '@/utils/customWrapper/logger'
import { loggerConfig } from '@/utils/globalVar'
import {
   extend as veeValidateExtend,
   configure as veeValidateConfigure,
   ValidationProvider,
   ValidationObserver,
} from 'vee-validate'
import { required as veeValidateRequired, regex as veeValidateRegex } from 'vee-validate/dist/rules'
// Includes components <portal> and <portal-target>
import PortalVue from 'portal-vue'


//#region Vue directives

import progressDirective from '@/utils/progressDirective'
import clickOutsideDirective from '@/utils/clickOutsideDirective'
import vueInputMask from '@/services/vueInputmask'

//#endregion Vue directives


//#region Vue components

import VueTippy, { TippyComponent, tippy } from 'vue-tippy'
import { TIPPY_DEFAULT_THEME } from '@/utils/tippyConstants'
import { ObserveVisibility } from 'vue-observe-visibility'
import multiSelectCFM from '@/components/multiselect/MultiSelectCFM'
import CheckboxCFM from '@/components/forms/CheckboxCFM/CheckboxCFM'
import RadioButtonsCFM from '@/components/forms/RadioButtonsCFM'
import Multiselect from 'vue-multiselect'
import VueScrollactive from 'vue-scrollactive'
import BootstrapVue, { BModal, VBModal } from 'bootstrap-vue'

//#endregion Vue components

//#endregion Vue-related imports

//#region Third-party script imports

// Inits user tracking and creates global variable window.aptrinsic. Actual tracking is started in initAppMixin.js.
import '@/assets/3rdparty/gainsight-aptrinsic'
import $ from 'jquery'
import 'bootstrap'

import dayjs from 'dayjs'
import 'dayjs/locale/en'
import 'dayjs/locale/fr'
import utc from 'dayjs/plugin/utc'
import localeData from 'dayjs/plugin/localeData'
import timezone from 'dayjs/plugin/timezone'
import localizedFormat from 'dayjs/plugin/localizedFormat'

//#endregion Third-party script imports

//#endregion Imports

//...more code
```

HTML/Vue template:
```vue
<template>
   <li class="my-component">
      <!--#region Main component-->

      <!--#region Header-->
      <header class="my-component__header"></header>
      <!--#endregion Header-->

      <!--#region Body-->
      <div class="my-component__body">
         <h1>Title!</h1>
         <p>Hello</p>
         <p>Hello again</p>
      </div>
      <!--#endregion Body-->

      <!--#region Footers-->
      <footer class="my-component__pre-footer"></footer>
      <footer class="my-component__footer"></footer>
      <!--#endregion Footers-->

      <!--#endregion Main component-->

      <!--#region Absolutely positioned elements-->
      <ConfirmationBox
         v-if="isConfirmingDelete"
         :id="warningBoxId"
         v-model="isConfirmingDelete"
         class="critical-risk-form-section__warning-delete-box"
         size="lg"
         :confirm-button-label="$t('DELETE_SECTION')"
         :confirm-promise="deleteSection"
      >
         <template #title>
            <div
               class="critical-risk-form-section__warning-title"
               v-html="warningBoxTitle"
            />
         </template>
         <template #message>
            <p>{{ $tc('DELETE_SECTION_WARNING_INFO', section.controlMeasures.length) }}</p>
            <p>{{ $tc('DELETE_SECTION_WARNING_MESSAGE_CONFIRMATION', section.controlMeasures.length) }}</p>
         </template>
      </ConfirmationBox>
      <!--#endregion Absolutely positioned elements-->
   </li>
</template>
```

As for full Vue files they're basically just three-part files:
```vue
<script>
// This is JavaScript
</script>
<template>
<!-- This is HTML, with Mustache-style templating, etc. -->
</template>
<style lang="scss">
// This is SCSS. Could also be pure CSS.
</style>
```

**Comment by izhangzhihao** [comment]
As I see from your code snippets, `region` and `endregion` seem never *nested*, this plugin is aimed to make *nested brackets* easier to distinguish. And by the way, some theme already have proper highlight for `region` and `endregion`:

For SCSS:

![image](https://user-images.githubusercontent.com/12044174/122625622-c6196b00-d0d8-11eb-9218-1867e1bcdeb2.png)

For js: 

```
//#region Vue directives
```

will be rendered as `PsiComment(JS:END_OF_LINE_COMMENT)`


For HTML/vue:

```
<!--#region Absolutely positioned elements-->
```

will be rendered as:

```
PsiElement(XML_COMMENT)
    XmlToken:XML_COMMENT_START
    XmlToken:XML_COMMENT_CHARACTERS
    XmlToken:XML_COMMENT_END
```

So, for JS/HTML/vue there are no language support for  `region` and `endregion`. If I'm wrong with this, please provide language specifications.

**Comment by Ariane-B** [comment]
> As I see from your code snippets, region and endregion seem never nested

These are simplified examples. There is one two-level nest included in the JS example, but I've seen deeper nests. I think I've seen it go up to 4 so far.

Especially since region names are optional, it can be a little confusing when you reach 2-3 `endregion` statements in a row. 

> And by the way, some theme already have proper highlight for `region` and `endregion`:

I think that's just the normal comment color for SCSS. Looks very similar to how comments look in my IDE anyway. 

> So, for JS/HTML/vue there are no language support for region and endregion. If I'm wrong with this, please provide language specifications.

Regions are an IDE feature, supported by several programs, including VSCode and WebStorm, not the language itself. I didn't know *any* language actually understood them. It's kinda weird that they would, considering they're basically comments. 

Or maybe I misunderstood you..?

**Comment by izhangzhihao** [comment]
> Regions are an IDE feature

But according to IntelliJ, there is no special internal structure for `region` and `endregion`.(The PSI structure showed just as normal comments.). 

So, from the side of this plugin, I'm no capability of highlighting it(As nested region, even normal region comments, since it just be recognized as normal comments).

**Comment by izhangzhihao** [comment]
What I mean is the IntelliJ seems does NOT provide any IDE feature for `region` and `endregion`. It just comments.

**Comment by Ariane-B** [comment]
But how come they can be folded if the program has no knowledge of them? Or is it just that it doesn't expose the info to plugins? This is odd.

**Comment by izhangzhihao** [comment]
I have no idea how the IDE makes it foldable... I will check it when I'm free.

**Comment by izhangzhihao** [comment]
Without PSI structure support it would be a very different way to do it(which means a completely new way to implement it, it require a lot of changes), especially for this case:

```
#endregion descriptions
```

I couldn't find a way to do it with the current implementation. If you can find a way, PR welcome~

**Comment by Ariane-B** [comment]
I see. No worries then! Thanks for checking, still. :)
