### ISSUE TITLE
Stop annoying notification! Please!

### ISSUE THREAD

**Issue by bollerdominik** [izhangzhihao/intellij-rainbow-brackets#225]
I enjoyed this plugin until one of the recent updates where the  "Want to custom your own rainbow colors" bubble was introduced.

I hate it so much!

I could accept it if this notification showed up once. But EVERYTIME I start my IDE or even just switch to a different project it shows up again. Worse is I use this plugin on many Jetbrain products on multiple systems and I have to deal with this notification multiple times per day.

Why? Why do we need this notification everytime I open any project with any jetbrains product? Please make it stop!

/rant off

**Comment by izhangzhihao** [comment]
Duplicated with #221

**Comment by izhangzhihao** [comment]
Fixed in version 5.19, this update is waiting for approval of JetBrains.

**Comment by bollerdominik** [comment]
Thank you. Much appreciated
