### ISSUE TITLE
Color priority does not change in Rider

### ISSUE THREAD

**Issue by hwooo** [izhangzhihao/intellij-rainbow-brackets#229]
## Your programming language(s)
C#

## Expected Behavior
Change color priority

## Current Behavior
The first appearing color is not changed after configuring the option

## Code snippet for reproduce (for bugs)
![rainbow](https://user-images.githubusercontent.com/46282492/59084559-a91cff80-8936-11e9-932c-38b54fde03b4.PNG)
![rainbow2](https://user-images.githubusercontent.com/46282492/59084567-aae6c300-8936-11e9-84f7-624b50ee1aa0.PNG)

## Your Environment

* Plugin version: v5.19
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
JetBrains Rider 2019.1.2
Build #RD-191.7141.355, built on June 5, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by izhangzhihao** [comment]
I think I am not quite getting your problem.

**Comment by hwooo** [comment]
@izhangzhihao Color `A9B7C6` should be appeared first, but currently color `E6B422` appears first.

**Comment by izhangzhihao** [comment]
There are a couple of settings you could change for different brackets: ![image](https://user-images.githubusercontent.com/12044174/59147285-29715c80-8a2c-11e9-9f90-e09da9213ce4.png)
