### ISSUE TITLE
Inconsistent colors

### ISSUE THREAD

**Issue by koresar** [izhangzhihao/intellij-rainbow-brackets#23]
Awesome plugin! Thank you.

Very minor issue:
![image](https://user-images.githubusercontent.com/1622575/34806515-89551d60-f6d7-11e7-9699-1efa9c6f1132.png)

I believe either all four of them should be the same (purple) color, or all four color should be different.

This is very minor. Feel free to close. 👍

**Comment by izhangzhihao** [comment]
This issue just been fixed in kotlin in latest release, the approach is to add a new specific implementation for JS. Here is a specific implementation for scala, please take a look [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#implement-for-some-language-you-would-like)

**Comment by izhangzhihao** [comment]
<img width="310" alt="screen shot 2018-01-11 at 1 22 51 pm" src="https://user-images.githubusercontent.com/12044174/34809823-9409d05c-f6d2-11e7-9a7d-edcc41563a17.png">

Should been fixed in next release !
