### ISSUE TITLE
Mismatched bracket colors

### ISSUE THREAD

**Issue by bamapookie** [izhangzhihao/intellij-rainbow-brackets#230]
## Your programming language(s)
json (observed)

## Expected Behavior
Closing bracket should match opening bracket

## Current Behavior
Mismatched bracket colors

## Code snippet for reproduce (for bugs)
{
  "license": "UNLICENSED",
  "dependencies": {
    "aws-sdk": "2.335.0",
    "uuid": "^3.2.1",
    "serverless": "1.44.1"
  },
  "devDependencies": {}
}

## Your Environment

* Plugin version:
5.18 and 5.19
* IDE & Operating System version:
```
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5118.30, built on June 13, 2019
IntelliJ IDEA EAP User
Expiration date: July 13, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.mac.allowDarkWindowDecorations=true, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, CheckStyle-IDEA, IntelliTail, String Manipulation, com.codota.csp.intellij, com.github.b3er.idea.plugins.arc.browser, com.github.camork.fileExpander, mobi.hsz.idea.gitignore, net.vektah.codeglance, izhangzhihao.rainbow.brackets, org.intellij.scala, AWSCloudFormation, com.vladsch.idea.multimarkdown, org.sylfra.idea.plugins.linessorter, ru.adelf.idea.dotenv, some.awesome
```

**Comment by bamapookie** [comment]
<img width="310" alt="Screen Shot 2019-06-14 at 10 47 29 AM" src="https://user-images.githubusercontent.com/1924926/59518363-81c4b600-8e93-11e9-8746-bcb82f79abd3.png">

**Comment by izhangzhihao** [comment]
Works as expected at :

```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.7, built on May 21, 2019
JRE: 11.0.2+9-b159.59 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

![image](https://user-images.githubusercontent.com/12044174/59546691-f0257900-8f64-11e9-9086-b3f8d855f0f0.png)

Just downloading 2019.2 EAP...

**Comment by izhangzhihao** [comment]
Ah, I found it, I'm sure you enable this option "Semantic Highlighting".
![image](https://user-images.githubusercontent.com/12044174/59546808-c5d4bb00-8f66-11e9-9b30-b6e0ce3d3a91.png)

![image](https://user-images.githubusercontent.com/12044174/59546815-d6853100-8f66-11e9-905d-c8243ceec403.png)
