### ISSUE TITLE
内容过多彩虹括号就没有效果

### ISSUE THREAD

**Issue by MrJokerBoy** [izhangzhihao/intellij-rainbow-brackets#2300]
不知道开发大大那边有没有这个问题，java文件中内容过多彩虹括号就没有效果了，变为普通样式。

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/784

**Comment by izhangzhihao** [comment]
Any update?

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/125185594-5110ff80-e258-11eb-81d5-a211c8e03346.png)

Uncheck "Do Not rainbowify big files"
