### ISSUE TITLE
看着挺炫的效果，不过是不是不支持erlang语言

### ISSUE THREAD

**Issue by helloyan** [izhangzhihao/intellij-rainbow-brackets#231]
我测试发现没有效果，material oceanic主题，不过测试	HighlightBracketPair 同样无效，是语言不支持还是设置问题，如果需要进一步的消息我可以提供

**Comment by intellij-rainbow-brackets** [comment]
你的IDE版本？都装了什么插件？有没有安装、配置Erlang的sdk？

On Jun 15, 2019, at 9:22 AM, helloyan <notifications@github.com<mailto:notifications@github.com>> wrote:


我测试发现没有效果，material oceanic主题，不过测试 HighlightBracketPair 同样无效，是语言不支持还是设置问题，如果需要进一步的消息我可以提供
