### ISSUE TITLE
Option to not rainbowify brackets of first level

### ISSUE THREAD

**Issue by mikhail-dvorkin** [izhangzhihao/intellij-rainbow-brackets#233]
The current option doNOTRainbowifyBracketsWithoutContent is great, as I indeed want the usual gray color for the brackets in:
int a = f();

But! I also want the usual gray color for brackets in simple-to-parse-visually lines, such as:
int a = f(x, y, z);
and
for (int i = 0; i < n; i++) {
    k *= i;
}

So the request is to add an option that will rainbowify the brackets only of the 2nd+ level: based on the level, and not on the presence of any content.

**Comment by izhangzhihao** [comment]
Good point!

**Comment by izhangzhihao** [comment]
Try this snapshot build version, the option "Do NOT rainbowify the first level" is false by default, stay tuned!
[intellij-rainbow-brackets-5.19.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/3334699/intellij-rainbow-brackets-5.19.zip)
