### ISSUE TITLE
Question: Why is there no version tag in xml plugin definition?

### ISSUE THREAD

**Issue by tiagozc** [izhangzhihao/intellij-rainbow-brackets#2336]
Hi, first thanks for providing the plugin, it's great and very useful. 

Is there any reason why you don't include the plugin version in the xml plugin definition? From the doc, https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html?from=jetbrains.org, I was expecting to see a version tag on it. Reason I'm asking is cause it would help with automated tools to identify new plugin releases.

Thanks

**Comment by izhangzhihao** [comment]
Actually there is version tag in the `plugin.xml` file, please try:

```bash
> curl https://plugins.jetbrains.com/files/10080/127133/intellij-rainbow-brackets-6.19.zip\?updateId\=127133\&pluginId\=10080\&family\=INTELLIJ --output rainbow.brackets.zip

> unzip rainbow.brackets.zip

> cd intellij-rainbow-brackets/lib

> unzip intellij-rainbow-brackets-6.19.jar

> vi META-INF/plugin.xml
```

You will see the version tag in the second line of the file.

**Comment by tiagozc** [comment]
oh right, I've checked the source code here only, thanks... I think the issue is on my side to detect the plugin version then, thank you!
