### ISSUE TITLE
Indent guide lines support for Python

### ISSUE THREAD

**Issue by jingj5** [izhangzhihao/intellij-rainbow-brackets#2339]
### Discussed in https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2338

<div type='discussions-op-text'>

<sup>Originally posted by **jingj5** August 11, 2021</sup>
could you get python indent guide lines with difference colors, like {} in java

1. java
![java](https://user-images.githubusercontent.com/5019232/129006510-f1c83f5d-f4dc-425f-b7ca-3cf2eb2a73e1.png)

2. python
![python](https://user-images.githubusercontent.com/5019232/129006543-59430670-9221-429e-9b05-c02e6d8e1788.png)

</div>

**Comment by izhangzhihao** [comment]
similar feature request: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/943#issuecomment-772845634

**Comment by izhangzhihao** [comment]
We already support rainbowify indent guidelines for Python: 
![image](https://user-images.githubusercontent.com/12044174/129481204-deee9d51-b74c-4e08-98c5-051052aa111d.png)

```python
    a = [
        [
            [
                "a", "b", "c"
            ]
        ]
    ]

    b = (
        (
            (
                (
                    "a", "b", "c"
                )
            )
        )
    )
```


But for more complex code, eg: 

```python
def checkEmpty(input, pattern):
    # If both are empty
    if len(input) == 0 and len(pattern) == 0:
        return 'true'

    # If only pattern is empty
    if len(pattern) == 0:
        return 'true'

    while (len(input) != 0):

        # find sub-string in main string
        index = input.find(pattern)

        # check if sub-string founded or not
        if (index == (-1)):
            return 'false'

        # slice input string in two parts and concatenate
        input = input[0:index] + input[index + len(pattern):]

    return 'true'
```

*There is no break line between brackets, so we could not rainbowify it*. Some other java code could not be rainbowify either(see https://github.com/izhangzhihao/intellij-rainbow-brackets/pull/251)

For your cases, I do think [Indent Rainbow](https://plugins.jetbrains.com/plugin/13308-indent-rainbow) is a better choice.

**Comment by jingj5** [comment]
谢谢了，兄弟。
但如果大神你可以解析python的语法，将这种方法的竖线也解析出来，然后改变颜色，这种对python代码段比较长的情况，十分有用。

**Comment by jingj5** [comment]
thanks a lot.
but if you can pasre python's syntax, change the break line colors like 'def' funtions with out brackets, it's really usefull with python code that functions very long.
thanks a lot again.

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/130354285-f85f9c2e-73d9-43a5-bb4b-41f834106685.png)


![image](https://user-images.githubusercontent.com/12044174/130354295-6e309858-2bda-4540-a95d-43690f6b2835.png)

I made a prototype, please try the snapshot build: [intellij-rainbow-brackets-6.19.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/7027296/intellij-rainbow-brackets-6.19.zip)

**Please [SUPPORT US](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) if you like this plugin. Your help means a lot!**

**Comment by jingj5** [comment]
great!，
谢谢

**Comment by izhangzhihao** [comment]
#2583 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/12044174/215311750-2fd3ee22-8d3d-45d6-b4d7-6fd7916f7909.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/12044174/215311763-e7f36cbe-f61d-4b87-9bca-6450c4d7e511.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/12044174/215311899-4300755b-8c18-4cb6-95aa-095ea71382d1.png">


This feature will be delivered in the next release, and this feature depends on "Rainbowify python keywords", please try the build snapshot [intellij-rainbow-brackets-2023.1.2.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10529270/intellij-rainbow-brackets-2023.1.2.zip) and give me feedback!

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12044174/215311819-1abfdae3-e332-4b08-a21c-14c0509d1023.png">

**Comment by izhangzhihao** [comment]
#2583 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/12044174/215311750-2fd3ee22-8d3d-45d6-b4d7-6fd7916f7909.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/12044174/215311763-e7f36cbe-f61d-4b87-9bca-6450c4d7e511.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/12044174/215311899-4300755b-8c18-4cb6-95aa-095ea71382d1.png">


This feature will be delivered in the next release, and this feature depends on "Rainbowify python keywords", please try the build snapshot [intellij-rainbow-brackets-2023.1.2.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10529366/intellij-rainbow-brackets-2023.1.2.zip) and give me feedback!

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12044174/215311819-1abfdae3-e332-4b08-a21c-14c0509d1023.png">

**Comment by izhangzhihao** [comment]
#2583 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/12044174/215311750-2fd3ee22-8d3d-45d6-b4d7-6fd7916f7909.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/12044174/215311763-e7f36cbe-f61d-4b87-9bca-6450c4d7e511.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/12044174/215311899-4300755b-8c18-4cb6-95aa-095ea71382d1.png">


This feature will be delivered in the next release, and this feature depends on "Rainbowify python keywords", please try the build snapshot [intellij-rainbow-brackets-2023.1.2.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10529366/intellij-rainbow-brackets-2023.1.2.zip) and give me feedback!

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12044174/215311819-1abfdae3-e332-4b08-a21c-14c0509d1023.png">

**Comment by izhangzhihao** [comment]
Please try this build snapshot 
[intellij-rainbow-brackets-2023.2.0.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10529596/intellij-rainbow-brackets-2023.2.0.zip)
