### ISSUE TITLE
Color is displayed with wrong order in C# code

### ISSUE THREAD

**Issue by hwooo** [izhangzhihao/intellij-rainbow-brackets#234]
## Problems
![brackets](https://user-images.githubusercontent.com/46282492/60392044-9ca35580-9b36-11e9-97e7-71aa2c4b8d8d.PNG)

I've set color order like above screenshot. However, in the text editor, color order is different with my option.

![rider](https://user-images.githubusercontent.com/46282492/60392059-d2e0d500-9b36-11e9-9614-a98ca85cc998.PNG)

This is Rider screenshot. My order is `white -> green -> yellow -> blue -> red`, but displayed order is `green -> yellow -> blue -> red -> white`.

![intellij](https://user-images.githubusercontent.com/46282492/60392090-64e8dd80-9b37-11e9-8d7a-175895058961.PNG)

In IntelliJ IDEA, the color is displayed exactly as I intended.

## Your Environment

* Plugin version: v5.19
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will been closed directly.

```
JetBrains Rider 2019.1.2
Build #RD-191.7141.355, built on June 5, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by izhangzhihao** [comment]
It seems like there has one layer outside of the namespace `CSharp_Practice`.

**Comment by izhangzhihao** [comment]
Try this snapshot build.
[intellij-rainbow-brackets-5.19.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/3343015/intellij-rainbow-brackets-5.19.zip)
