### ISSUE TITLE
[C#] Colours incorrect when using "Cycle count on all brackets"

### ISSUE THREAD

**Issue by JumbleJumble** [izhangzhihao/intellij-rainbow-brackets#2354]
![image](https://user-images.githubusercontent.com/10434326/131666457-973b2fab-86c7-4ad6-8a93-188f4970241c.png)

The first round brackets are always the first colour configured, despite "Cycle count on all brackets" being switched on. The above screenshot shows this. It also shows a problem where nested square brackets are showing the same colour.

**Comment by izhangzhihao** [comment]
Hi, the update is already in the marketplace, please download and enjoy it: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/244619

By the way, I create a new Google Search plugin, please try and give me feedback: https://plugins.jetbrains.com/plugin/20230-google-search/

**Comment by JumbleJumble** [comment]
Hi there!

I installed the EAP of Rider (to get the build that the new version
requires), and then updated the plugin. But strangely, it now isn't working
at all - as if the plugin wasn't installed. I've tried disabling it,
restarting, then re-enabling it and restarting again, but nothing. Am I
doing something wrong, or forgetting something?

Thanks

Richard

**Comment by izhangzhihao** [comment]
hi, this plug-in is a paid plugin now， please goes to "help — register” to active this plugin

**Comment by izhangzhihao** [comment]
or you can check your editor enabled syntax highlighting or not， just in the right top corner of the editor

**Comment by izhangzhihao** [comment]
Make sure config like that

<img width="611" alt="image" src="https://user-images.githubusercontent.com/12044174/199035534-1b284ed3-418c-43d5-9baf-6ebca0d1526d.png">

**Comment by JumbleJumble** [comment]
Hi

I suddenly just started working after I enabled and then disabled the color
generator! All working great now, thanks for the fix!

It would be great if you put some kind of editor in that could handle any
number of colours (I always use 6, which means editing the color scheme as
xml and then reimporting it). It's not going to stop me using it though!

Richard

**Comment by izhangzhihao** [comment]
Hi, in the next version you will be able to edit up to 10 colors:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/12044174/202893817-4a88d0c8-1c9d-4442-86f1-235c2653cf60.png">

Please install the snapshot build and give me feedback!

**Comment by JumbleJumble** [comment]
Hi there

I just updated to Rider 2022.3 and it says I'm not licensed for Rainbow
Brackets - I know you did give me a licence but I'm not sure how I can tell
my IDE about it. It's logged in with my work jetbrains account, could that
be it?

Thanks


Richard

**Comment by izhangzhihao** [comment]
sorry for the late reply, for active existing license, please take a look here: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2574#issuecomment-1357892261

**Comment by JumbleJumble** [comment]
Hi there.

I still haven't managed to get this licensed. I just don't know what the
details were of the licence you gave me. Is there anything I can do?

Thanks

Richard

**Comment by izhangzhihao** [comment]
So, did you already paid for the plugin license?

**Comment by izhangzhihao** [comment]
Ah, I see, please email me @ izhangzhihao@hotmail.com, and I will give you the detail about how to active your license.
