### ISSUE TITLE
Feature requests - Improved manipulation with brackets

### ISSUE THREAD

**Issue by icaine** [izhangzhihao/intellij-rainbow-brackets#238]
## Current Behavior
IntelliJ currently lacks of some advanced brackets manipulation abilities that i think they might be useful. I know this plugin is mainly about colouring but maybe you will find my suggestions fruitful:)

## Feature 1: A shortcut to remove current and matching bracket
Lack of this one is pretty annoying. How should it works? You put the caret before a bracket and by pressing the shortcut it will remove the bracket and it's matching one:
![](https://i.imgur.com/puTlbF4.jpg) + shorcut = ![](https://i.imgur.com/690FRex.jpg)

Or when the caret is within some brackets remove the closest ones but this could be kinda dangerous in languages that uses e.g. `{}` for codeblocks, so maybe it could be optional setting?

## Feature 2: A shortcut to duplicate current and matching bracket
Same as feature 1 but instead of removing it will add brackets:
![](https://i.imgur.com/690FRex.jpg) + shorcut = ![](https://i.imgur.com/puTlbF4.jpg)

## Feature 3: A shortcut to change/cycle brackets
Similar to feature 1 but instead of removing brackets it will rotate some preselected brackets.
In options can be a manualy editable textbar that contains e.g. `()[]{}//` and inside editor when you press the shortcut it will replace current brackets with following ones.
E.g.: `a = (1,2,3,4,5)` becomes `a = [1,2,3,4,5]` then `a = {1,2,3,4,5}`, etc.

## Bonus Feature: A shortcut to select all content within brackets
I know this one can be already achieved by `expand selection`  feature but when you are really deep within nested brackets you have to repeat the action many times.

**Comment by izhangzhihao** [comment]
I think [this feature](https://twitter.com/intellijidea/status/1156210611661004800) may match some parts of your requirements.


>Complete your current statements & add missing semicolons, braces or brackets, by using 'Complete Current Statement' (Shift+Ctrl+Enter on Windows & Linux/ Shift+Cmd+Enter on macOS) 
Use it in combination with 'Choose Lookup Item' to select item & add a semicolon.

**Comment by izhangzhihao** [comment]
Oh, maybe not...

**Comment by icaine** [comment]
Hello, I have tried to find other plugins prior to posting these feature requests but without success. Also i was thinking about official feature request but it usually takes months/years if ever (since there are kinda important bugs lying there for years)..
Do you think you can/want do it? I could help you but i am python/php programmer only:/

**Comment by izhangzhihao** [comment]
I'm not looking into it yet, just seen the twitter from JetBrains so I think may relate to this feature request. But as I see, this feature may not have many scenes. So this is not a priority at this moment.

**Comment by icaine** [comment]
I can tell you that as python programmer i think about Feature 1 and 3 on daily basis but i understand that this is not a priority...

**Comment by izhangzhihao** [comment]
I think those features are able to implement, we should check out how JetBrains implement the feature in that twitter. They should be similar.

**Comment by izhangzhihao** [comment]
[Here](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/codeInsight/editorActions/smartEnter/SmartEnterAction.java) is the code from of 'Complete Current Statement'. As a quick search.

**Comment by izhangzhihao** [comment]
As I see, this should not be too hard.

**Comment by izhangzhihao** [comment]
But I'm working on fixing a complex bug right now.

**Comment by icaine** [comment]
Maybe [expand selection feature](https://www.jetbrains.com/help/rider/Selecting_Text_in_the_Editor.html#extend_selection) will be more helpful?
Because instead of nearest code block we select nearest brackets (on background) and then perform desired action..

I guess source code of the feature is [here](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/codeInsight/editorActions/ExtendWordSelectionHandlerBase.java).
