### ISSUE TITLE
Not working for PHP sources

### ISSUE THREAD

**Issue by luispabon** [izhangzhihao/intellij-rainbow-brackets#24]
I'm working on PhpStorm 2017.3.3 and Ubuntu. I can see javascript and json files with rainbox brackets working just fine, but nothing on PHP sources. Braces and stuff all appear white, as per my current theme.

I'm in Rainbow Brackets 3.1.

![image](https://user-images.githubusercontent.com/6388823/35330886-23cea350-00fd-11e8-98ee-b16a2b23928c.png)

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets.jar.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1659828/intellij-rainbow-brackets.jar.zip)

Try this: unzip the file and install from disk and select the jar file. Thanks for your feedback!

**Comment by luispabon** [comment]
This worked 👍 

Thanks for the hard work!
