### ISSUE TITLE
Feature Request: Option to turn on rainbow brackets within a string

### ISSUE THREAD

**Issue by jcjolley** [izhangzhihao/intellij-rainbow-brackets#240]
## Feature Request
I work on Excel add-ins that have long formulas like the ones included in the code snippet.  Having the option to turn on rainbow parens for strings like these would be a life saver.

## Your programming language(s)
JavaScript

## Code snippet
````
const DIFF_PERCENT = '=ABS(INDIRECT(ADDRESS(row(), column() - 1))) / (SUM(INDIRECT(ADDRESS(row(), column() - 3)), INDIRECT(ADDRESS(row(), column() - 2)), 0.00001) / 2)';
const DIFF = '=SUM(INDIRECT(ADDRESS(row(), column() - 2)), -INDIRECT(ADDRESS(row(), column() - 1)))';
````

**Comment by izhangzhihao** [comment]
Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) when you creating a feature request.

**Comment by izhangzhihao** [comment]
Close because we don't have any good solution. If you have any, please reopen it.
