### ISSUE TITLE
插件设置中未开启html选项时也渲染了html文件的问题

### ISSUE THREAD

**Issue by songjiayao** [izhangzhihao/intellij-rainbow-brackets#2400]
发现了在插件设置中未开启html选项时也渲染了html文件的问题。如下图所示。
尝试了勾选html选项并应用，再取消勾选并应用。无效。
尝试了禁用再启用本插件，重启IDE后 无效。
尝试了卸载并重新安装插件，重新IDE后测试无效。

插件版本：6.21
phpstorm版本：
PhpStorm 2021.2.3
内部版本号 #PS-212.5457.49，October 13, 2021 构建
运行时版本: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.intellij.zh (212.325), io.zhile.research.ide-eval-resetter (2.3.5), net.vektah.codeglance (1.5.4), org.jetbrains.plugins.rest (212.5457.51), net.seesharpsoft.intellij.plugins.csv (2.18.1), Key Promoter X (2021.3), de.netnexus.camelcaseplugin (3.0.8), izhangzhihao.rainbow.brackets (6.21), pers.fw.doc (1.2), pers.fw.tplugin (1.3.6), cn.yiiguxing.plugin.translate (3.2.0.1)

![image](https://user-images.githubusercontent.com/10859384/142717338-a05fab44-f0ac-4b82-a489-47654e11af49.png)

**Comment by izhangzhihao** [comment]
那个是控制tagname着色的，不想给xml着色的话，参考readme里面的黑名单功能
