### ISSUE TITLE
Code With Me / IntelliJ Remote Development / Fleet Support

### ISSUE THREAD

**Issue by freestyledork** [izhangzhihao/intellij-rainbow-brackets#2408]
Love the plugin so much it annoys me when I am in a remote session and the tags are all white. Not sure if this is known or not, but it doesnt appear to work with the 'code with me' feature of PHPstorm. The plugin installs via the market place, but when editing the tags all remain the same color. I can confirm the config shows and other plugins work.

**Comment by izhangzhihao** [comment]
This plugin depends on `com.intellij.modules.lang`:

https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/f7fb0636cd45eda563783e9ad6f4694d94f7f702/src/main/resources/META-INF/plugin.xml#L715

But the Code With Me client / Intellij Remote Development / Fleet does not have this module, so it would not be possible to support for Code With Me client at this moment.

**Comment by freestyledork** [comment]
Thanks for this!

**Comment by zmmfa** [comment]
So rainbow brackets is not compatible with remote development ?

**Comment by TheDarkTrumpet** [comment]
I know this item is closed, and we've had some responses about remote development.  I'd like to throw my hat into this ring that it'd be nice to get this working.  Either from a workaround or something else.  Many plugins, including Github CoPilot work fine in remote development mode.

**Comment by TheDarkTrumpet** [comment]
Bit of a double post, but was playing with this a bit more.  There's another linked issue: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2817

The key is the plugin needs to be installed on the host.  Don't install it also on the client.  If you install on the client, it'll give alerts saying that you need to unlock, plus giving the com xml issue mentioned here.  So nothing on the client, just install on the host and it works.

**Comment by izhangzhihao** [comment]
🎉 Remote Development Support is Coming!

Hi! I'm excited to share that Rainbow Brackets now has experimental support for JetBrains Remote Development / JetBrains Client.

To make this happen, the plugin has been largely rewritten — most core features have been reimplemented to work in the remote development environment(Still many features are missing/not working).

The current build is in a snapshot stage, so I'd really appreciate your help testing it and providing feedback on any issues you encounter. pls share your feedbacks at https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888

⚠️ Important installation note:
Please install the plugin from the **client side** (not the server/host side), and uninstall the plugin from the server/host side. This is a change from previous recommendations — the new architecture requires client-side installation to function properly in remote development sessions.

You can download the snapshot and future snapshots from https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/eap


Or you can Add the EAP Channel in Your IDE, so you will receive updateds automatically:

1. Open your JetBrains IDE and go to Settings (Windows/Linux) or Preferences (macOS).
2. Navigate to the Plugins menu.
3. Click the Gear icon and select Manage Plugin Repositories.
4. Click the + (Add) button and paste the following URL: https://plugins.jetbrains.com/plugins/eap/list
5. Click Apply and OK. Run Check for Updates or search for the plugin;
6. your IDE will now pull EAP releases


Once the feature stabilizes based on your feedback, I'll publish it to the JetBrains Marketplace as a stable release.

Thank you for your patience — I know many of you have been waiting for this for a long time! 

You can buy me a coffee: https://buymeacoffee.com/rainbowbrackets

Thank you so much for your support! Happy coding! 🎨
