### ISSUE TITLE
Colorization is applied only to left parenthesis in for loop(C#)

### ISSUE THREAD

**Issue by hwooo** [izhangzhihao/intellij-rainbow-brackets#242]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) before creating one.

## Please check
- [✔️] I already support this project.
- [✔️] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [✔️] This issue/feature request is not reported before.

## Your programming language(s)
C#

## Current Behavior
![pic](https://user-images.githubusercontent.com/46282492/63278939-2a075880-c2e3-11e9-8779-05324ac3e114.PNG)

Rainbow color is applied to `(` of for-loop , but not applied to `)`.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.
*NOTE: If you are going to report a bug but WITHOUT your env information, your issue will been closed directly.*

```
for (int i = 0; i < 5; ++i)
{
    for (int j = 0; j < 5; ++j)
    {
        Console.Write($"{i}/{j} ");
    }
    
    Console.Write("\n");
}
```

## Your Environment
* Plugin version: 5.21
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue will been closed directly.

```
JetBrains Rider 2019.2
Build #RD-192.5895.1069, built on August 8, 2019
Runtime version: 11.0.3+12-b304.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=100, lcd.contrast.value=250, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=500, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, debugger.watches.in.variables=false, ide.borderless.title.project.path=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false
Non-Bundled Plugins: com.intellij.resharper.HeapAllocationsViewer, com.microsoft.vso.idea, de.santiv.fastscrolling, net.vektah.codeglance, izhangzhihao.rainbow.brackets, PythonCore, com.intellij.resharper.azure
```

**Comment by izhangzhihao** [comment]
All rider related issues require much more time and patient. first, it's possible to fix this issue, but it takes lots of time and patience and will make this project more complex and hard to maintain. So, if someone would like to take this ticket would be great. otherwise, it requires a big donation to make it happen.

**Comment by kamronbatman** [comment]
I don't have this issue with newest Rider and Rainbow brackets.

**Comment by izhangzhihao** [comment]
Great, then.

**Comment by kamronbatman** [comment]
@izhangzhihao, I made a mistake. It is actually two separate colors instead of one hahaha.
Please open this again.

**Comment by izhangzhihao** [comment]
It seems this issue already fixed according to this plugin: https://github.com/blai30/Lotus-Theme, Am I right?

**Comment by kamronbatman** [comment]
No I still have it in 2020.1 Rider.
I will get a picture later. It happens with lambda function as a method argument.

**Comment by izhangzhihao** [comment]
Please try this build snapshot:
[intellij-rainbow-brackets-6.10.1.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5226099/intellij-rainbow-brackets-6.10.1.zip)
