### ISSUE TITLE
Disable coloring for simple brackets

### ISSUE THREAD

**Issue by mariussoutier** [izhangzhihao/intellij-rainbow-brackets#2425]
Would it be possible to provide an option that disables coloring for simple opening and closing brackets (e.g. `object.method()`)? I think it only distracts from reading code and has no real advantage.

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/148383233-a93be492-39a2-4b9d-8f2e-86b0f3152036.png)

**Comment by mariussoutier** [comment]
Thanks, I missed these settings, only saw the Editor settings for coloring. This in combination with not rainbowifying first level makes the plugin perfect.
