### ISSUE TITLE
Suggestion: can the intent guide thickness changed? Would be a huge plus.

### ISSUE THREAD

**Issue by makiwata** [izhangzhihao/intellij-rainbow-brackets#2428]
Thank you for the extension, I really like it.

My suggestion is: the intent guides are already colored, which is very helpful, but an option to make those lines thicker would bring the experience to a much higher level. Because it would be awesome to see in which block I stand by using a thick colored intend line.

Would it be possible? What do you think?

Thank you very much, have a nice day!

**Comment by izhangzhihao** [comment]
Yes, you could change this line, maybe increase from 0.2 to 0.5
https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/fcdacd13f3e5a23726d59be658cb2340f5b5f373/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/indents/RainbowIndentGuideRenderer.kt#L96

PR wellcome~

**Comment by makiwata** [comment]
Thank you, it would be nice. I am trying to figure out how to modify it, I am a newbie. If you think that it would be useful for a lot of other people as well then maybe adding an option to change this value would be very nice. But I will find out how to modify it myself, so you helped already a lot. Thank you and have a nice day

**Comment by izhangzhihao** [comment]
close for no more update
