### ISSUE TITLE
Does not work with IntelliJ Remote Development

### ISSUE THREAD

**Issue by kinland** [izhangzhihao/intellij-rainbow-brackets#2442]
## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
TypeScript, Java

## Expected Behavior
When Rainbow Brackets is installed while using Remote Development, brackets should be colorized ( https://www.jetbrains.com/help/idea/remote-development-starting-page.html )

## Current Behavior
Brackets do not show rainbow colors, despite plugin being installed and enabled. It works if running locally in IntelliJ IDEA rather than using remote development. The Jetbrains Client did not report any errors

## Possible Solution
As a temporary workaround, I installed Nested Brackets Colorer. This works, but I do not like it as much as Rainbow Brackets.

## Code snippet for reproduce (for bugs)
N/A

## Your Environment

* Plugin version: 6.21

```
JetBrains Client 2021.3
Build #JBC-213.6777.52, built on January 27, 2022
Licensed to (removed for privacy)

Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    rdclient.backend.actionHandlers=false
```
Additionally, the remote host is running Linux and has IntelliJ IDEA.

**Comment by izhangzhihao** [comment]
Related to #2408 and will be related to [JetBrains Fleet IDE](https://www.jetbrains.com/fleet).
I will merge them to #2048

**Comment by kinland** [comment]
I am not using Code With Me, for what it's worth. not sure whether that changes anything

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
