### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zhanggang807** [izhangzhihao/intellij-rainbow-brackets#2449]
very helpful. btw, I want to know the algorithm of Rainbow Brackets. that is different from vs code's ??? How We Made Bracket Pair Colorization 10,000x Faster In Visual Studio Code https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization

**Comment by izhangzhihao** [comment]
You could check the logic [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/visitor/DefaultRainbowVisitor.kt)
It's not complex, and yes, the VS code did way better performance improvement, If you are interested in improve performance for this plugin, pull request are welcome!

**Comment by izhangzhihao** [comment]
Close for no update here.
