### ISSUE TITLE
Highlighting doesnt work on Webstorm 2019.2

### ISSUE THREAD

**Issue by roi007leaf** [izhangzhihao/intellij-rainbow-brackets#245]
Am I doing something wrong? shouldn't it work OOTB?
I see webstorm scope highlighting on the left of the code but not Rainbow Brackets highlighting which I loved to see in VScode.
- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ X] This issue/feature request is not reported before.

## Your programming language(s)
Javascript
## Expected Behavior
Should show highlighting lines for the scope under\above the code
![40234968-46593fe2-5adb-11e8-8ea8-0026fad86ca9](https://user-images.githubusercontent.com/17231451/64071581-ec60e300-cc85-11e9-9b8d-81720df61c4e.gif)

## Current Behavior
Does Not

## Possible Solution
Tried to mess with the settings including Webstorm own settings

[https://imgur.com/3dpu2wI
![Screen Shot 2019-09-01 at 6 42 19](https://user-images.githubusercontent.com/17231451/64071483-e833c600-cc83-11e9-8220-09e42bd6d095.png)
](url)

## Your Environment
```
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5118.30, built on June 13, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, bigger.font.in.project.view=true, search.everywhere.settings=true, ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: izhangzhihao.rainbow.brackets, com.chrisrm.idea.MaterialThemeUI
```

**Comment by intellij-rainbow-brackets** [comment]
I don’t think I’m getting your idea. Can you please make more explanations?

**Comment by roi007leaf** [comment]
Hey, edited my ticket with the gif you post on the marketplace.. im using webstorm latest version is 2019.2
I'm trying to get it to highlight the scope as you guys show on the gif but for some reason, it doesn't do that.

**Comment by izhangzhihao** [comment]
So, did you mean `Command + Button3(Secondary Click /click or tap with two fingers)` does not work?

**Comment by izhangzhihao** [comment]
I'm using the latest IntelliJ IDEA 2019.2.2 Preview (Ultimate Edition), it works as expected.

**Comment by roi007leaf** [comment]
So that's how you do it... I knew I'm missing something.. You guys should
put that key combo on the description or something.. I totally missed that

**Comment by izhangzhihao** [comment]
Just press `Command + Button3`

**Comment by izhangzhihao** [comment]
Close for inactive.
