### ISSUE TITLE
Feature : add a button to apply the color code to all kind of brackets

### ISSUE THREAD

**Issue by alain57** [izhangzhihao/intellij-rainbow-brackets#247]
Currently if a user want to change the brakets color he needs to change it at 4 different places (round brackets, square brackets and so on)
Of course it is nice to have the ability to change each kind of bracketscolor individually.
But they are for sure some people (like me) who apply the same code to all kind of brackets.
It would in that case be very helpfull to have some kind of way to apply the 5 colors dirrectly to all kind of braces

Maybe with a global brackets line or a button that would fill all lines with the same colors as the currently selected bracket.

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/73164561-234ffd80-412d-11ea-9aa2-8af73ed71b7f.png)

**Comment by izhangzhihao** [comment]
Please consider donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this feature.
@alain57 @MisterJD @adriano66
