### ISSUE TITLE
Edge case for key.Split(")")

### ISSUE THREAD

**Issue by ghost** [izhangzhihao/intellij-rainbow-brackets#2476]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
C#, Typescript

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

<img width="124" alt="image" src="https://user-images.githubusercontent.com/59643335/167839994-16ec2357-d3e6-4687-bf7d-cdaa3699b3ce.png">
I would expect the third paranthesis to be red matching the first opening parathesis and the one between the quotes in the string should be brown, the same color as the quotes since it is part of the string. 

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, explain the difference from current behavior
The parenthesis in between code is being interpreted as the closing parenthesis of the Split function.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.
Could you make an edge case for when parenthesis, brackets etc. are being used within a string. To not show as rainbow color. This issue happens also for [ ] ( ) { } within strings. It would make sense to give them the same color as the string. 

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.
`key.Split(")")`

## Your Environment
VSCode

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.
V0.0.6 
https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets
```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to IntelliJ Rainbow Brackets / Zhang Zhihao
Subscription is active until February 3, 2022.
For non-commercial open source development only.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: ide.tooltip.initialDelay=900, ide.balloon.shadow.size=0, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: com.intellij.properties.bundle.editor (212.4746.57), com.markskelton.one-dark-theme (5.3.0), lermitage.intellij.extra.icons (1.59.0.203), org.nik.presentation-assistant (1.0.9), kotest-plugin-intellij (1.1.36-IC-2021.1), Pythonid (212.4746.96), org.intellij.scala (2021.2.15), izhangzhihao.rainbow.brackets (6.19), com.intellij.bigdatatools (212.4037.55)
Kotlin: 212-1.5.10-release-IJ4746.92
```

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by izhangzhihao** [comment]
Are you using the VSCode editor? Because in IntelliJ it works well: 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/12044174/168190303-a5e43df2-f2d0-479c-af18-837c28351609.png">

**Comment by izhangzhihao** [comment]
And this repo does NOT respond to issues of the VSCode plugin because this repo is the plugin for the IntelliJ plugin, going to close.
