### ISSUE TITLE
Rainbow brackets scope highlighting not working with Hiberbee Theme

### ISSUE THREAD

**Issue by ryanjmortenson** [izhangzhihao/intellij-rainbow-brackets#2478]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
C/Python

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work
Scope highlight should be highlighted with color of brace/bracket for the encapsulates scope.

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, explain the difference from current behavior
Braces/Brackets and scope text color is turned gray and color is not used to highlight scope

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

This seems to have broken between Rainbow Brackets 6.18 and Rainbow Brackets 6.21.  I tested on CLion version 2020.3.4 because it can run both Rainbow Brackets 6.18 and Rainbow Brackets 6.21.

// Rainbow brackets 6.18 on CLion 2020.3.4 where scope highlighting works correctly
![image](https://user-images.githubusercontent.com/21166472/171062911-519dd489-af90-4491-9606-39596d40223b.png)

// Rainbow brackets 6.21 on CLion 2020.3.4 where scope highlighting just turns text gray
![image](https://user-images.githubusercontent.com/21166472/171062658-d569f461-1a79-48b2-b6ee-a9e45e92bf85.png)

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.

int test(void)
{
  return 0;
}

## Your Environment

* Plugin version: 6.23
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
CLion 2020.3.4
Build #CL-203.8084.11, built on April 13, 2021
Licensed to Ryan Mortenson
You have a perpetual fallback license for this version.
Subscription is active until April 2, 2023.
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.3.0-7625-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 4
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Non-Bundled Plugins: IdeaVIM, color.scheme.Molokai, com.hiberbee.intellij.hiberbee-theme, name.kropp.intellij.makefile, izhangzhihao.rainbow.brackets
Current Desktop: GNOME
```

**Comment by izhangzhihao** [comment]
It works well without hiberbee theme, please report this issue to https://github.com/hiberbee/jetbrains-ide-theme/issues

**Comment by ryanjmortenson** [comment]
I took a deeper look at this, and it seems to be due to use the DefaultRainbowVisitor using defaultAttributes while AnnotatorUtil uses the color scheme.  There is a mismatch between what is used for scope highlighting and parenthesis/brackets/curly braces.  You can re-create this on Monokai Pro and Hiberbee themes. I think you are able to re-create this with any theme that provides their only rainbow colors.

// DefaultRainbowVisitor calls setHighLightInfo which uses defaultAttributes (I think this is the default colors provided by rainbow brackets plugin)
![image](https://user-images.githubusercontent.com/21166472/172086126-897d5d29-1599-4c0d-8a98-2c8625b6c9c1.png)

// Annotator Util uses the currently active theme
![image](https://user-images.githubusercontent.com/21166472/172086431-dff3a7d3-0b45-43d1-b5bb-5d80edcd6a4d.png)

// Monokai pro example where curly braces are purplish while the highlight scope is blue
![image](https://user-images.githubusercontent.com/21166472/172086957-d2c93d5c-45eb-46f6-a362-020d00546c71.png)

// I think it is using Darkula colors as the 3rd level of Darcula is blue
![image](https://user-images.githubusercontent.com/21166472/172087150-63792984-c3df-43e8-9e10-5d0f990c59e3.png)

// While the 3rd level of Monokai pro is purplish
![image](https://user-images.githubusercontent.com/21166472/172087187-087a0045-350e-448e-801b-cc59b9adb5c2.png)

**Comment by izhangzhihao** [comment]
Monokai pro : 

<img width="406" alt="image" src="https://user-images.githubusercontent.com/12044174/172093807-9c1aec05-9181-475c-8f0f-43c006b166f9.png">

**Comment by izhangzhihao** [comment]
With hiberbee:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/12044174/172301577-9739affb-4e18-421b-b340-8a1e698d96d1.png">

**Comment by ryanjmortenson** [comment]
Thanks for the fixes!  They are working well for me.
