### ISSUE TITLE
Support PHP Twig brackets

### ISSUE THREAD

**Issue by jb-lopez** [izhangzhihao/intellij-rainbow-brackets#248]
The PHP template language Twig is not getting its brackets colored correctly.

## Your programming language(s)
Twig

## Expected Behavior
The Twig brackets should either be rainbow or should be the default editor color.

## Current Behavior
The Twig brackets at all levels are the first rainbow color

## Possible Solution
Perhaps the twig brackets can be ignored.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.
```twig
{% if foo %}
    {% for bar in foo %}
        {{ bar }}
    {% endfor %}
{% endif %}
```

![image](https://user-images.githubusercontent.com/8528028/64893278-8122f380-d62b-11e9-9d66-e765060f3cf2.png)

## Your Environment

* Plugin version: 5.22
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
PhpStorm 2019.2.1
Build #PS-192.6262.66, built on August 22, 2019
Licensed to Joshua Lopez
You have a perpetual fallback license for this version
Subscription is active until July 31, 2020
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, documentation.show.toolbar=true, debugger.watches.in.variables=false, tabs.alphabetical=true
Non-Bundled Plugins: CMD Support, String Manipulation, com.alayouni.ansiHighlight, com.github.b3er.idea.plugins.arc.browser, com.godwin.json.parser, com.intellij.ideolog, com.tang, in.thekalinga.snippet.intellij, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, org.intellij.RegexpTester, BashSupport, com.jetbrains.php.framework.structure, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, net.king2500.plugins.PhpAdvancedAutoComplete, izhangzhihao.rainbow.brackets, com.intellij.plugin.adernov.powershell, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, org.toml.lang, org.rust.lang, ru.adelf.idea.dotenv, zielu.gittoolbox
```

**Comment by izhangzhihao** [comment]
Related to: https://youtrack.jetbrains.com/issue/WI-52134

**Comment by izhangzhihao** [comment]
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/12044174/211736894-26641361-b1f8-4b31-837b-aa0cba296bb0.png">

With [the Twig plugin](https://plugins.jetbrains.com/plugin/7303-twig) installed,

<img width="549" alt="image" src="https://user-images.githubusercontent.com/12044174/211736961-74f2aa1a-1617-48c9-b8b1-a08e6139e230.png">

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/12044174/211739936-17504332-ea77-41bd-b010-b0a952c952eb.png">

**Comment by jb-lopez** [comment]
This works. Thanks!
