### ISSUE TITLE
show rainbow bracket in parameter hint

### ISSUE THREAD

**Issue by xianzheTM** [izhangzhihao/intellij-rainbow-brackets#2483]
## Please check

- [x] already support this project.
- [x] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
Java,Sacla,Kotlin
## Expected Behavior
show rainbow bracket in IDEA's parameter hints

## Current Behavior
![image](https://user-images.githubusercontent.com/25103583/174218794-96b97f65-a092-4c08-b65b-eba759050588.png)
Currently IDEA does not colour the brackets in the parameter hints. As the diagram shows, readability is reduced once more bracket nesting occurs.

## Your Environment

* Plugin version: 6.24
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2022.1.2 (Ultimate Edition)
Build #IU-221.5787.30, built on June 1, 2022
Licensed to ******
Subscription is active until March 24, 2023.
For educational use only.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    ide.balloon.shadow.size=0
    scala.erase.compiler.process.jdk.once=false

Kotlin: 221-1.7.0-release-281-IJ5591.52
```

**Comment by izhangzhihao** [comment]
Closed because there was not possible to implement in the intellij platform.
