### ISSUE TITLE
Scope highlighting doesn't work in rider with c#

### ISSUE THREAD

**Issue by sevelee** [izhangzhihao/intellij-rainbow-brackets#249]
Rider 2019.2
rainbow brackets vertion 5.22
Scope highlighting doesn't work.
I tried ctrl + right click but nothing happends.
![image](https://user-images.githubusercontent.com/8036235/65218808-d9556c00-dae9-11e9-9361-961d713cf034.png)

**Comment by sevelee** [comment]
It works with my pycharm. So I think it is a bug with rider.

**Comment by izhangzhihao** [comment]
Yes, Scope highlighting won't work for C#

**Comment by sevelee** [comment]
Could this be added as a new function?

**Comment by izhangzhihao** [comment]
It's not possible at this moment.
