### ISSUE TITLE
do you have plans to support swift?

### ISSUE THREAD

**Issue by Bohr-H** [izhangzhihao/intellij-rainbow-brackets#250]
such as the title
I keep getting errors when I wrote swift code
for example:
![image](https://user-images.githubusercontent.com/29001268/65475006-80525300-deb0-11e9-860f-218da2ebfb5f.png)

**Comment by izhangzhihao** [comment]
Your IDE version?

**Comment by izhangzhihao** [comment]
It seems a bug of IDE itself.

**Comment by izhangzhihao** [comment]
You should report this as a bug to JetBrains.
