### ISSUE TITLE
Not working on IntelliJ IDEA 2022.1.3

### ISSUE THREAD

**Issue by KayleighWasTaken** [izhangzhihao/intellij-rainbow-brackets#2508]
## Your Programming Languages
I have tested with Scala, Python, JS, and Java

## Expected Behaviour
Brackets become rainbow

## Current Behaviour
Brackets are not rainbow

## Your Environment
Plugin Version: `6.25`

```IntelliJ IDEA 2022.1.3 (Community Edition)
Build #IC-221.5921.22, built on June 21, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2038M
Cores: 12
Non-Bundled Plugins:
    indent-rainbow.indent-rainbow (2.0.2)
    com.jetbrains.darkPurpleTheme (1.3)
    izhangzhihao.rainbow.brackets (6.25)
    org.intellij.scala (2022.1.17)

Kotlin: 221-1.6.21-release-337-IJ5921.22```

**Comment by izhangzhihao** [comment]
Can you make sure all these options are checked? and if you have a new installation, please restart.
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/12044174/180915336-50fa9e2b-4e26-44b6-a368-bb3a890de7eb.png">

**Comment by KayleighWasTaken** [comment]
All of those are checked, yes. I have restarted as well. Another thing is that it just works in my PyCharm install with identical settings if that's worth anything.

**Comment by izhangzhihao** [comment]
Did rainbow brackets work for your PyCharm? any screenshots of not working?

**Comment by KayleighWasTaken** [comment]
Yeah it works in PyCharm, but not IDEA.

Screenshot of it not working in IDEA:
![image](https://user-images.githubusercontent.com/41625824/181132712-38a91cba-0848-4163-9897-6e94254f2b56.png)

Screenshot of it working in PyCharm:
![image](https://user-images.githubusercontent.com/41625824/181132907-758d142c-3e2c-4e47-b6f9-6855a76791a8.png)

**Comment by izhangzhihao** [comment]
Just scala files does not work in IDEA or even other files does not work?

**Comment by KayleighWasTaken** [comment]
With some further testing I've narrowed it down to being something to do with needing brackets outside of an object. Here are three example screenshots to demonstrate, the only thing I did between them is add and then remove the brackets shown at the bottom of the second screenshot:
![image](https://user-images.githubusercontent.com/41625824/181310024-98a3e3d2-ddd0-45a4-bb02-acfceff3dccc.png)
![image](https://user-images.githubusercontent.com/41625824/181310334-3c114ec8-8b89-4f43-8d3d-2f865c135bfa.png)
![image](https://user-images.githubusercontent.com/41625824/181310421-ae2e0774-d0a5-468a-81fe-30404497bbaa.png)

Once you remove the brackets again the highlighting stays, but you need them there to get it to start highlighting.

**Comment by izhangzhihao** [comment]
It works for me without adding extra brackets outside of the object, rainbowify instantly happened.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/12044174/181403656-2d7d17e3-4288-45a2-8da5-10b85f56c3fd.png">


```
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to IntelliJ Rainbow Brackets / Zhang Zhihao
Subscription is active until January 20, 2023.
For non-commercial open source development only.
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    ide.tooltip.initialDelay=900
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    net.seesharpsoft.intellij.plugins.csv (2.19.0)
    com.mallowigi.idea (18.1.0)
    com.intellij.plugins.expui (0.4)
    atom-one (1.5.1)
    String Manipulation (9.5.0)
    com.mallowigi (65.1.0)
    org.intellij.scala (2022.2.10)
    izhangzhihao.rainbow.brackets (6.25)

Kotlin: 222-1.7.10-release-334-IJ3345.118
```
