### ISSUE TITLE
no effect

### ISSUE THREAD

**Issue by jiansite** [izhangzhihao/intellij-rainbow-brackets#2524]
![image](https://user-images.githubusercontent.com/33872552/190308536-6fa3d259-9235-46b6-a19e-627e81c72990.png)
![image](https://user-images.githubusercontent.com/33872552/190308625-f5036d65-a095-417e-9a94-03c322a1d6cc.png)
![image](https://user-images.githubusercontent.com/33872552/190308675-0eb85d60-f258-470f-8db2-974c0a8cfdd2.png)

IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022

Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10240M
Cores: 8
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    org.elasticsearch4idea (2022.2.1-222)
    leetcode-editor (8.3)
    de.netnexus.camelcaseplugin (3.0.12)
    com.shuzijun.markdown-editor (2.0.2)
    com.mroche.JsonHelper (1.2.0)
    com.intellij.ideolog (203.0.30.0)
    org.jetbrains.plugins.spotbugs (1.2.5)
    net.hexar.json2pojo (1.1.0)
    io.codearte.props2yaml (1.0.2)
    com.linsage (1.0.7)
    com.intellij.guice (222.3739.24)
    com.godwin.json.parser (1.4.2)
    com.github.setial (4.0.2)
    com.github.obiscr.exceleditor (2022.8.1-212.222)
    com.github.chencn.yamlandprops (1.0.5)
    com.ankit.mahadik.json.dart.class (2.15)
    cn.olange.rule (1.0.4)
    cn.jxzhang.plugin.json-formatter (1.4)
    PMDPlugin (1.8.23)
    GsonFormatPlus (1.6.1)
    GrepConsole (12.15.211.6693.1)
    com.jetbrains.upsource (2020.1.2005.13)
    org.jetbrains.plugins.vue (222.3739.61)
    com.obroom.plugin.toolset (2022.9.1)
    Restart (1.0.0)
    MyBatisLog (2022.7.9)
    JRebelPlugin (2022.3.2)
    izhangzhihao.rainbow.brackets (6.26)
    com.ccnode.codegenerator.MyBatisCodeHelperProMarketPlace (3.0.8)
    com.bruce.intellijplugin.generatesetter (2.8.1)
    cn.yiiguxing.plugin.translate (3.3.5)
    lermitage.intellij.extra.icons (2022.1.10)
    AceJump (3.8.8)

Kotlin: 222-1.7.10-release-334-IJ3739.54

**Comment by izhangzhihao** [comment]
Does your IDE run indexing?  It not work for Java only or not work for all other langs? Does a restart fix this?

**Comment by micky2333** [comment]
![image.png](https://pic.rmb.bdstatic.com/bjh/9b7cb1e20af1600153bd7777002a7db7.png)
显示灰色应该是Idea代码检查的问题
请重新测试

**Comment by izhangzhihao** [comment]
Feel free to re-open it or raise a new one if you still have this issue.
