### ISSUE TITLE
Exception encountered when using on WebStorm 2022.2

### ISSUE THREAD

**Issue by sandeepsauravdas** [izhangzhihao/intellij-rainbow-brackets#2525]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
- TypeScript
- HTML
- JavaScript
- CSS

## Expected Behavior
* That it doesn't cause the exception anymore. A few weeks ago I was still using WebStorm 2021.3 and it worked perfect there.

## Current Behavior
* Ends up with an error exception on random code snippets.
* [RainbowBrackets_error.txt](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/9578046/RainbowBrackets_error.txt)

## Possible Solution
I wish I could help in anyway!

## Code snippet for reproduce (for bugs)
Since it happens at random code snippets, unable to do a RCA.

## Your Environment

* Plugin version:  (6.25) & (6.26)

* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
WebStorm 2022.2
Build #WS-222.3345.108, built on July 22, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Non-Bundled Plugins:
    lermitage.intellij.worldclock (1.4.0)
    io.karma.kromatic (1.10)
    ent.brainstorm.galizur.theme (1.2.2)
    com.vecheslav.darculaSolidTheme (1.0.3)
    com.samdark.intellij-visual-studio-code-dark-plus (2.6)
    com.nasller.CodeGlancePro (1.5.1)
    com.markskelton.one-dark-theme (5.6.0)
    com.gmike.visual-studio-2019-dark (1.5.3)
    coderpillr.theme (1.0.0-rc.3)
    Rider UI Theme Pack (0.10.3)
    com.mallowigi (65.1.0)
    izhangzhihao.rainbow.brackets (6.25)
    com.hasintech.intellij.angularTemplates (1.1.3)
    com.github.dinbtechit.vscodetheme (1.6.2)

```

**Comment by sandeepsauravdas** [comment]
Really love your work & I'm already missing the feel of Rainbow Brackets in WebStorm 2022.2

Please, help me out here!

**Comment by izhangzhihao** [comment]
Thanks for your report! But actually, it's not a bug of this plugin, you can report it to [JetBrains](https://youtrack.jetbrains.com), that should be a new bug introduced in 2022.2. Thanks again for your support~

**Comment by izhangzhihao** [comment]
And I guess this plugin still works, excpt complain this error.

**Comment by sandeepsauravdas** [comment]
Cool! Will do that. In fact I feel that this 2022.2 is bugged. Lots of bugs almost everywhere. I'd better roll back to 2021.3, it was more stable and Rainbow Brackets works like a charm there.
Thanks for your time mate! Keep up with the great work!
