### ISSUE TITLE
Ability to permanently store the current colors palette

### ISSUE THREAD

**Issue by zartc** [izhangzhihao/intellij-rainbow-brackets#2526]
I use to set the "Use color generator" to let Rainbow Brackets generates a new color palette on each working session. 
More often than not the generated palette are ... mei!
But once in a time the generated palette is yeah!
In those rare case I would like to be able to 1) see the current palette colors and 2) store the palette in the Editor/Color Scheme/Rainbow Brackets to be able to use it permantly for the next couple of days/weeks.
Of course I would like to have a list of all persisted palettes at my disposal in the Editor/Color Scheme/Rainbow Brackets to be able to switch from one palette to another one.

**Comment by izhangzhihao** [comment]
Great idea, persists the randomly generated color scheme.

**Comment by izhangzhihao** [comment]
<img width="1009" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/ef2de897-7a61-4dfc-9d6d-d53603c02fd6">

Please try this build snapshot(required 2022.3 or above)

[intellij-rainbow-brackets-2023.2.7.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/11521361/intellij-rainbow-brackets-2023.2.7.zip)

**Comment by izhangzhihao** [comment]
<img width="1005" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/b32faf16-79f6-4b38-9432-1120ccdd7768">

Please try this build snapshot(required 2022.3 or above)
