### ISSUE TITLE
Cannot mark ticket as priority despite being a backer

### ISSUE THREAD

**Issue by RichardIrons-neo4j** [izhangzhihao/intellij-rainbow-brackets#2533]
This issue:
https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2354

I opened quite a while ago, the "cycle on all brackets" feature has stopped working. I already contributed (I'm "Richard Irons") but I'm at a different place of work now and can't log in with those details any more.

Is it possible to get this issue looked at? It's been quite a long time.

**Comment by izhangzhihao** [comment]
I will try fix it in the next release. And thanks for your support, it's really important to me.

**Comment by izhangzhihao** [comment]
I think that works for you.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/12044174/197786778-9d07ea50-154d-4efd-a70a-f454951b4ea6.png">

**Comment by izhangzhihao** [comment]
Starting from Rider 2022.3, there a many internal changes, it seems the front-end parser has changed a LOT, so I'm entirely re-writing the C# support now. And in the next release, it will be a freemium plugin. Since you already contributed to this plugin, I will give you a license then.

Thanks again for your contribution!

**Comment by RichardIrons-neo4j** [comment]
Thanks for the reply! I use it all the time so when the new release comes I'll be happy to contribute again.

**Comment by izhangzhihao** [comment]
Hi, the update is already in the marketplace, please download and enjoy it: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/244619

By the way, I create a new Google Search plugin, please try and give me feedback: https://plugins.jetbrains.com/plugin/20230-google-search/

**Comment by RichardIrons-neo4j** [comment]
Hi there

This version says that it needs the EAP version - is it possible to do a
version that only requires 222?

Thanks!

**Comment by izhangzhihao** [comment]
No, because lots of changes made in side from the Rider 2022.3, and now the plugin is not compatible with 2022.2 and before.

**Comment by RichardIrons-neo4j** [comment]
OK, understandable. Thanks for the quick reply!
