### ISSUE TITLE
Plugin not available in Clion EAP 2022.3

### ISSUE THREAD

**Issue by AnnalenaHolz** [izhangzhihao/intellij-rainbow-brackets#2534]
## Your programming languages
c++, c, c#, java

## Expected Behavior
* tell us how it will work
* Just the plugin working on Clion

## Current Behavior
Not able to download or install

**Comment by izhangzhihao** [comment]
Same with #2529, will be fixed after a few days.

**Comment by izhangzhihao** [comment]
Hi, the update is already in the marketplace, please download and enjoy it: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/244619

By the way, I create a new Google Search plugin, please try and give me feedback: https://plugins.jetbrains.com/plugin/20230-google-search/
