### ISSUE TITLE
Highlight current indent guide line

### ISSUE THREAD

**Issue by nomanfound** [izhangzhihao/intellij-rainbow-brackets#2536]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
C++

## Expected Behavior
when rainbow brackets enabled, clion settings 'current scope' in 'highlight on caret movement' works, the current scope highlighted
![image](https://user-images.githubusercontent.com/6092959/198961498-d34264fb-a016-41f5-b3e9-c066b5821a62.png)

## Current Behavior
when it's enabled, highlight current scope function breaks
![Snipaste_2022-10-31_16-07-41](https://user-images.githubusercontent.com/6092959/198961645-dab51669-89b4-4411-b246-f9ca6f1f7991.png)

## Code snippet for reproduce (for bugs)
```cpp
class child : public parent {
public:
    void eat() override {
        printf("child eat");
        printf("child eat");
        printf("child eat");
        printf("child eat");
        printf("child eat");

    }
};
```

## Your Environment

```
CLion 2022.2.4
Build #CL-222.4345.21, built on October 10, 2022
Licensed to shijiu liu
You have a perpetual fallback license for this version.
Subscription is active until August 6, 2023.
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-126-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 10000M
Cores: 16
Registry:
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    manjaro.mpb (1.7)
    idea.plugin.protoeditor (222.4345.14)
    color.scheme.GapStyle (4.1)
    com.mallowigi (73.0.0)
    artsiomch.cmake (222.6.0)
    izhangzhihao.rainbow.brackets (6.26)
    BrowseWordAtCaret (3.0.5)

Current Desktop: Undefined
```

**Comment by izhangzhihao** [comment]
Duplicated with https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/380

**Comment by izhangzhihao** [comment]
Please check the comments at https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/380#issuecomment-1296938427

**Comment by nomanfound** [comment]
thanks a lot 😁
