### ISSUE TITLE
Wondering about a function in RainbowUpdateNotifyActivity

### ISSUE THREAD

**Issue by chylex** [izhangzhihao/intellij-rainbow-brackets#2537]
Hi, when I was looking at [RainbowUpdateNotifyActivity.kt](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/RainbowUpdateNotifyActivity.kt) I saw this function that seems to uninstall or delete another plugin:

```kt
private fun removeIfInstalled() {
    val pluginId = PluginId.getId("com.github.jadepeng.rainbowfart")
    val isInstalled = isPluginInstalled(pluginId)
    if (isInstalled) {
        val pluginDescriptor = PluginManagerCore.getPlugin(pluginId)
        if (pluginDescriptor != null) {
            //disablePlugin(pluginId)
            StartupActionScriptManager.addActionCommand(DeleteCommand(pluginDescriptor.path))
        }
    }
}
```

It was introduced in https://github.com/izhangzhihao/intellij-rainbow-brackets/commit/022abbc8c55d7ec94481ac6205bf17b32fae335a. The commit does not explain the change, and I don't see it documented in the plugin's description or change log. Is there any context for this change?

Thanks.

**Comment by izhangzhihao** [comment]
Hi, all open-source features are still keep free in future versions. So if you only fork and re-compile, that will be exactly the same as with current Rainbow Brackets.

**Comment by chylex** [comment]
That was not my question.
