### ISSUE TITLE
Advanced guides highlighting may not working properly when moving cursor

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#2540]
## Please check

- [x] I already support this project.
- [x] If you are submitting a feature request, please consider donating (Paid plan)
- [x] This issue/feature request is not reported before.

## Expected Behavior
Indents guides should highlight current, and only current scope

## Current Behavior
A few scopes may be highlighted at a time. Only part of a scope can be highlighted

## Code snippet to reproduce
```Solidity
pragma solidity ^0.8.0;

contract test {
  function test(uint[] nums) returns (uint) {
    uint sum;

    for (uint i = 0; i < nums.length; i++) {
      sum += nums[i];
    }

    return sum;
  }
}
```

https://user-images.githubusercontent.com/6392013/200282758-844ec30c-b46e-4068-8bd9-b272582d84c1.mp4

As you may note at the end of the video, scrolling the editor is fixing the broken highlight. I may assume it means that the logic of highlighting is working properly - it seems it's something with the visualization part

## Your Environment

* Plugin version: 2022.3.2-ij

<details>

<summary>IDE & Operating System version</summary>

```
WebStorm 2022.2.3
Build #WS-222.4345.14, built on October 5, 2022
Licensed to Oleksii Bobyr
You have a perpetual fallback license for this version.
Subscription is active until November 2, 2023.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4128M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false
    ide.mac.file.chooser.native=false
    ide.mac.native.save.dialog=false
    ide.mac.inplaceDialogMnemonicsFix=true
    js.debugger.webconsole=false

Non-Bundled Plugins:
    wallaby.js (1.0.253)
    socrates.tabshifter (0.33)
    quokka.js (1.0.363)
    org.toml.lang (222.4345.14)
    org.para.plugin.openInSplittedTab (0.2)
    org.nik.presentation-assistant (1.0.10)
    me.serce.solidity (2.3.10)
    com.tang (1.3.7.2-IDEA222)
    com.mnw.tabmover (1.4.1)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.microservices.ui (222.4345.14)
    com.fwdekker.randomness (2.7.5)
    String Manipulation (9.6.1)
    mobi.hsz.idea.gitignore (4.4.2)
    com.nekofar.milad.intellij.hardhat (1.2.4)
    com.intellij.lang.jsgraphql (3.3.0)
    com.intellij.database (222.4345.14)
    izhangzhihao.rainbow.brackets (2022.3.2-ij)
    MetricsReloaded (1.12)
    org.asciidoctor.intellij.asciidoc (0.37.54)
    ru.adelf.idea.dotenv (2022.2)
    lermitage.intellij.extra.icons (2022.1.12)
```
</details>

**Comment by izhangzhihao** [comment]
Thanks for the report, I will dig into this later.

**Comment by izhangzhihao** [comment]
And I didn't even know that Rainbow Brackets supports the Solidity language, thanks.

**Comment by JakubKahovec** [comment]
I'm having a similar problem in a Python file

https://user-images.githubusercontent.com/32606/226559301-4bf6daa8-8336-4889-87a7-9ca87ad8ab9f.mov


IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Build #IU-223.8836.41, built on March 10, 2023
Licensed to Cisco Systems, Inc / Jakub Kahovec
Subscription is active until May 7, 2023.
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 10
Metal Rendering is ON
Registry:
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    cn.jxzhang.plugin.json-formatter (1.4)
    lermitage.intellij.extratci (1.24.0)
    me.lensvol.blackconnect (0.6.0)
    com.crunch42.openapi (1.52)
    ski.chrzanow.foldableprojectview (1.1.4)
    zielu.gittoolbox (500.0.5+213)
    mobi.hsz.idea.gitignore (4.4.4)
    com.jetbrains.lang.ejs (223.7571.117)
    Pythonid (223.8836.41)
    izhangzhihao.rainbow.brackets (2023.2.6)
    com.leinardi.pycharm.mypy (0.14.0)
    com.leinardi.pycharm.pylint (0.14.0)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.koxudaxi.pydantic (0.4.0)
    com.dmarcotte.handlebars (223.7571.117)
    com.intellij.plugins.html.instantEditing (223.8214.16)

Kotlin: 223-1.8.0-release-345-IJ8836.41

**Comment by ilbrando** [comment]
I have the same issue in C#. I have tried various settings for "Indent guides", also the new "Focus" and all the ones I have tried seems to have this render problem. Scrolling the editor fixes the rendering.

Version: 2023.2.8
Rider: Build #RD-231.9011.39, built on May 17, 2023
OS: MacOS Ventura 13.2.1

**Comment by sitaktif** [comment]
Same issue with YAML

PyCharm 2023.1
Build #PY-231.8109.197, built on March 29, 2023
OS: MacOS Ventura 13.3

**Comment by JakubKahovec** [comment]
@izhangzhihao do you plan to address this issue ?

**Comment by izhangzhihao** [comment]
I have tried various ways of implementation, but still haven't found a good solution to this issue. I will continue to try.

**Comment by izhangzhihao** [comment]
Through testing in series 2024.1, this situation has become increasingly rare, as the IDE itself now provides smoother rendering support.
