### ISSUE TITLE
Brackets are not highlighted (C#)

### ISSUE THREAD

**Issue by destiny14** [izhangzhihao/intellij-rainbow-brackets#2545]
I bought the full version after upgrading from the free one. Brackets are no longer highlighted in C# files.

## Your programming languages
C#

## Expected Behavior
Brackets should be colored

## Current Behavior
No brackets are colored

## Possible Solution
I tried reinstalling and changing the Rider Theme to default, but nothing helped.

## Your Environment

* Plugin version: 2022.3.3

JetBrains Rider 2022.2.3
Build #RD-222.4167.23, built on September 9, 2022
Licensed to Marco Stambor
Subscription is active until May 17, 2023.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    some.awesome (1.14)
    com.nasller.CodeGlancePro (1.5.3)
    com.markskelton.one-dark-theme (5.7.0)
    com.intellij.resharper.HeapAllocationsViewer (2022.2.0)
    com.intellij.javafx (1.0.4)
    com.4lex4.intellij.solarized (2.4.0)
    cognitivecomplexity-rider (2022.2.0)
    com.mallowigi (73.0.0)
    izhangzhihao.rainbow.brackets (2022.3.3-ij)
    Abc.MoqComplete.Rider (2022.2.0.2)

## Subscription Status
![image](https://user-images.githubusercontent.com/2909249/200573161-8d2f597d-1789-42be-bd9c-cbc08ef2853a.png)

**Comment by izhangzhihao** [comment]
Hi, if you are using Rider 2022.3 and newer, please use this: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/248274

If you are using Rider 2022.2 and older, please use this : https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/222834

**Comment by destiny14** [comment]
The first one is the version I have installed, if I'm not mistaken?

**Comment by izhangzhihao** [comment]
Sorry, is my mistaken to forget to make it incompatible with rider.

**Comment by destiny14** [comment]
So the paid version is incompatible with rider? And the free version no longer supports C#?

**Comment by izhangzhihao** [comment]
Short one is, you could start using the Rider 2022.3 from now, and the paid version works.

**Comment by izhangzhihao** [comment]
Because there are lots of changes from Rider 2022.3, it is hard to maintain two versions of C# support.

**Comment by izhangzhihao** [comment]
Hi, if you are using Rider 2022.3 and newer, please use this: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/248274 **(this need paid for the new version of Rider)**

If you are using Rider 2022.2 and older, please use this : https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/222834 **(this is still FREE for older version of Rider)**

**Comment by destiny14** [comment]
Ah sorry my bad, I mistook Rider Version 2022.2.3 for 2022.3. I'll try the EAP, thank you.
