### ISSUE TITLE
Update plugin cause 2022.3.3-IJ runtime exception

### ISSUE THREAD

**Issue by evanwangace** [izhangzhihao/intellij-rainbow-brackets#2546]
![image](https://user-images.githubusercontent.com/37762337/200578029-d83dd586-12ae-4dce-ab2b-b73727426330.png)
**My Idea version: IntelliJ IDEA 2022.1.2**
**My Jdk version: jdk1.8.0_221**
**My os version: Windows 10**
Just did a plugin update, then I can not use this plugin, and the exception message as shown in the image.
This is a really sad thing😭.

**Comment by izhangzhihao** [comment]
Hi, jdk 1.8 is no longer supported. you will need install jdk 11 with this one

**Comment by evanwangace** [comment]
> Hi, jdk 1.8 is no longer supported. you will need install jdk 11 with this one
I will try it, thanks~😊
