### ISSUE TITLE
Rainbow variables settings are not reflected

### ISSUE THREAD

**Issue by webgoto** [izhangzhihao/intellij-rainbow-brackets#2548]
thanks for the great plugin.
I don't think changing the settings will change the color.
In addition, colors not included in the settings are also used.

![rb](https://user-images.githubusercontent.com/4490262/200708073-663b9d8b-65f8-4237-b70e-2d5a4a8a5732.png)

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages

javascript in .html

## Your Environment

```
Rainbow Brackets v2022.3.3

IntelliJ IDEA 2022.3 Beta (Ultimate Edition)
Build #IU-223.7401.7, built on November 2, 2022
Licensed to IntelliJ IDEA EAP user: XXXXXXXXX
Expiration date: December 2, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    run.processes.with.pty=true
    ide.new.color.picker=false

Non-Bundled Plugins:
    com.intellij.apacheConfig (223.7401.19)
    org.jetbrains.plugins.rest (223.7401.10)
    AceJump (3.8.8)
    com.jetbrains.php (223.7401.19)
    izhangzhihao.rainbow.brackets (2022.3.3)
    com.jetbrains.php.wordPress (223.7401.19)

Kotlin: 223-1.7.20-release-201-IJ7401.7
```

**Comment by izhangzhihao** [comment]
Colors are generated from user-defined 5 colors:

For dark theme:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/12044174/202695860-cdd2dd95-ac6b-41f9-bd46-7b3012ab75f5.png">

For light theme:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/12044174/202696158-63bc2b5b-5659-4e1c-999b-49fc4bb6280c.png">

**Comment by izhangzhihao** [comment]
new options added


<img width="749" alt="image" src="https://user-images.githubusercontent.com/12044174/202852094-2da6945b-598e-4def-ab0c-331abdd6d3f8.png">

**Comment by webgoto** [comment]
thank you 👍

I got the following error when I did "install plugin from Disk..."

ERROR
Plugin 'Rainbow Brackets' (version '2022.3.4') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is IU-223.7571.4

**Comment by izhangzhihao** [comment]
Hi, the new version is already in the marketplace, please download and try it.
