### ISSUE TITLE
Why 'enable rainbow variables' and 'rainbowify python keywords' can't  be checked both?

### ISSUE THREAD

**Issue by danny-su** [izhangzhihao/intellij-rainbow-brackets#2549]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/12178855/200752708-904238c7-a3f7-4b12-8bd4-82adbb9cf898.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/12178855/200752599-adecfb8f-eaee-40b5-a891-10452f32c877.png">

**Comment by izhangzhihao** [comment]
Yes, I did this on purpose because the two functions are duplicate and conflicting

**Comment by danny-su** [comment]
> 

Which option should I check if I want to rainbow both variables and python keywords?

**Comment by izhangzhihao** [comment]
Do you think is a good idea that rainbow them both?

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-2022.3.3.2-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/9967974/intellij-rainbow-brackets-2022.3.3.2-ij.zip)

please try this snapshot build and give me feedback~

**Comment by izhangzhihao** [comment]
Fixed in 2022.3.4
