### ISSUE TITLE
AS雪狐版本下载最新版插件，ide会异常哦

### ISSUE THREAD

**Issue by gt562559842** [izhangzhihao/intellij-rainbow-brackets#2550]
安装最新版后，as的setting无法打开，且无法实时对报错代码进行提醒。

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-2022.3.3.2-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/9965946/intellij-rainbow-brackets-2022.3.3.2-ij.zip)

this one works for you

**Comment by izhangzhihao** [comment]
the latest version is already in the market place.
