### ISSUE TITLE
Android Crash after updates

### ISSUE THREAD

**Issue by osh91** [izhangzhihao/intellij-rainbow-brackets#2552]
After updating twice this week my Android Studio Dolphin began to crash and can't compile because of the latest update. 

## Your Environment

Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    some.awesome (1.14)
    com.vermouthx.idea (1.13.3)
    com.markskelton.one-dark-theme (5.7.0)
    com.jetbrains.darkPurpleTheme (1.3)
    com.google.d2c.androidstudio.plugin (0.3.00)
    com.clutcher.comments_highlighter (2.4.1)

**Comment by izhangzhihao** [comment]
Which version? It should not happen anymore in the latest update.

**Comment by izhangzhihao** [comment]
Feel free to re-open it or raise a new one if you have any issues.
