### ISSUE TITLE
Rainbow Brackets not giving a license to students

### ISSUE THREAD

**Issue by richardotomislav** [izhangzhihao/intellij-rainbow-brackets#2554]
## Summary
As stated in issue https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2538; a pro license of the extension is provided to student accounts. However, there's not a way to request a license and the license modal window is not getting a license. 

## Your programming languages
I use Python, C# and C/C++

## Expected Behavior
It should give a license for studnets, and the licenses windows should say "activated" in the extension.

## Current Behavior
[Image of current behaviour](https://user-images.githubusercontent.com/113539857/201624534-334ecfe0-073a-40fc-bce3-7e4c18539e8a.png)

There's no license available and refreshing the license windows doesn't give one. 

## Your Environment

As mentioned in issue: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2538
Students will have a free pro license for this extension. However, it's not giving one to student accounts.

* Plugin version: _I will check later, but it's latest version._
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon): _Sorry again, I don't have the Programm info right now, I'll provide it later. But all IDE's are on the latest EAP version._

- PyCharm Proffesional, EAP 2022.3
- Rider, EAP 2022.3

- CLion , EAP 2022.3

**Comment by kamronbatman** [comment]
Per my comment [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2538#issuecomment-1314082569), make sure you try to _buy_ the license on your education account. At final checkout, the price should say zero.

**Comment by izhangzhihao** [comment]
Thanks for the reply @kamronbatman !
