### ISSUE TITLE
Variables colors contrast too low for light theme

### ISSUE THREAD

**Issue by SQReder** [izhangzhihao/intellij-rainbow-brackets#2555]
- [x] This issue/feature request is not reported before.

## Your programming languages
JS, Typescript

## Expected Behavior
Have enough contrast for light theme

## Current Behavior
Low contrast for variables with light theme

## Code snippet for reproduce (for bugs)
![image](https://user-images.githubusercontent.com/1519753/201857354-bdc5159a-ef53-4fb6-b23f-85e8ec54ab35.png)

## Your Environment

* Plugin version:
```
WebStorm 2022.2.3
Build #WS-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    some.awesome (1.14)
    rasarts.espresso.light.theme (1.3.2)
    monokai-pro (1.9)
    light.flat.theme (0.14)
    com.vermouthx.idea (1.14.0)
    com.thvardhan.gradianto (4.5)
    com.jetbrains.CyanTheme (1.3)
    com.hiberbee.intellij.hiberbee-theme (2022.5.16.1805)
    com.github.openmindculture.intellijcutepinklighttheme (0.6.4)
    cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    PlantUML integration (5.19)
    izhangzhihao.rainbow.brackets (2022.3.4-ij)
    com.intellij.swagger (222.4345.14)
    ru.adelf.idea.dotenv (2022.2)

Registry: ide.tooltip.initialDelay=900, ide.balloon.shadow.size=0, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: com.intellij.properties.bundle.editor (212.4746.57), com.markskelton.one-dark-theme (5.3.0), lermitage.intellij.extra.icons (1.59.0.203), org.nik.presentation-assistant (1.0.9), kotest-plugin-intellij (1.1.36-IC-2021.1), Pythonid (212.4746.96), org.intellij.scala (2021.2.15), izhangzhihao.rainbow.brackets (6.19), com.intellij.bigdatatools (212.4037.55)
Kotlin: 212-1.5.10-release-IJ4746.92
```

**Comment by izhangzhihao** [comment]
Related to #2548

**Comment by izhangzhihao** [comment]
new options added


<img width="749" alt="image" src="https://user-images.githubusercontent.com/12044174/202852094-2da6945b-598e-4def-ab0c-331abdd6d3f8.png">

**Comment by izhangzhihao** [comment]
Hi, the new version is already in the marketplace, please download and try it.

**Comment by YouHusam** [comment]
variables are too dark even in dark mode:

This one has almost the same color as unused variables:
![image](https://user-images.githubusercontent.com/5736950/208938114-36a7fa65-71a6-469d-8737-5ec346ad0aa8.png)

This one is just hard to read:
![image](https://user-images.githubusercontent.com/5736950/208938156-35c66e5b-65f1-4ceb-9102-8e9df0558a8e.png)

**Comment by izhangzhihao** [comment]
Hi, @YouHusam are you using the color generator?

**Comment by YouHusam** [comment]
@izhangzhihao No, I am using the free version

**Comment by izhangzhihao** [comment]
You can still change the color scheme here:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/12044174/209100432-d7dc761a-994a-4bbb-a44d-a8de566b8ef4.png">

It will be great if you can share your color scheme with me.

**Comment by YouHusam** [comment]
@izhangzhihao I am using this theme: https://plugins.jetbrains.com/plugin/12255-visual-studio-code-dark-plus-theme
I am not sure if i edited something so I'll upload my theme here
[Visual_Studio_Code_Dark_Plus.icls.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10286439/Visual_Studio_Code_Dark_Plus.icls.zip)

![image](https://user-images.githubusercontent.com/5736950/209123740-041ee7b8-4dc4-4ea1-b863-c52fc283d92b.png)

**Comment by izhangzhihao** [comment]
You can adjust the color, choose other color.
