### ISSUE TITLE
Disabling 'Semantic highlighting' should disable rainbow variables

### ISSUE THREAD

**Issue by Elliot67** [izhangzhihao/intellij-rainbow-brackets#2556]
## Expected Behavior
Disabling the default `Semantic highlighting` option should also disable the plugin `Enable rainbow variable` option.

## Current Behavior
Disabling the default `Semantic highlighting`  works for the current project, but the option gets activated back when you open a new project/restart the editor.

---

Got a notification suggesting to use rainbow variables, wanted to try it but didn't understood it was coming from this plugin because I had to activate an option in the default editor settings.
Didn't liked the way it looked so I tried to disabled it, but couldn't figure out why the editor couldn't keep the setting disabled.

Don't know if there is a good fix for that but other people might have the same issue.

Thx for the great work on the plugin !

**Comment by izhangzhihao** [comment]
Hi, you must disable `Enable rainbow variable` to disable the `Semantic highlighting` option. There is no plan for the reverse disable for now.
