### ISSUE TITLE
Rainbow variables在超过规定行数以后依然生效，并导致卡死

### ISSUE THREAD

**Issue by zqr95518** [izhangzhihao/intellij-rainbow-brackets#2557]
## Your programming languages
JAVA

## Expected Behavior
Rainbow variables在超过规定行数以后不生效

## Current Behavior
在反编译的class超过规定行数以后Rainbow brackets自动停用了，但是Rainbow variables依然生效并导致卡死。（反编译的是io.reactivex.rxjava3.core.Observable）

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    String Manipulation (9.5.0)
    izhangzhihao.rainbow.brackets (2022.3.4-ij)
```

**Comment by izhangzhihao** [comment]
I could not understand, any screenshots?

**Comment by izhangzhihao** [comment]
If your file is more than 1000 lines, rainbow brackets will stop work only after you disable the option or change the line numbers:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/12044174/203452883-1185d7f6-85fd-4855-a6e0-503f7ccaae1b.png">

**Comment by zqr95518** [comment]
![image](https://user-images.githubusercontent.com/18632169/203454492-29d82cc6-7f86-445a-9373-199a0e23c642.png)
![截图_1669167952636](https://user-images.githubusercontent.com/18632169/203454542-db2fb5f9-f770-4ee9-a15a-f47e3195cf25.png)

**Comment by zqr95518** [comment]
把AS的Render documentation comments关掉以后不卡死了，但是变量在超过行数以后变了颜色。 @izhangzhihao
