### ISSUE TITLE
Incompatible for webstorm 2022.3

### ISSUE THREAD

**Issue by languanghao** [izhangzhihao/intellij-rainbow-brackets#2559]
Please supprot webstorm 2022.3

![image](https://user-images.githubusercontent.com/3765379/204410019-8c9d9146-0a9b-4ca4-9ec1-673ce8c5ad7e.png)

**Comment by izhangzhihao** [comment]
Please check for an update, 2022.3 is already supported.

**Comment by languanghao** [comment]
@izhangzhihao No new version: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions 

![image](https://user-images.githubusercontent.com/3765379/204455818-4db613d4-795e-437f-8da8-86132fba419f.png)

**Comment by intellij-rainbow-brackets** [comment]
For 2022.3， you should use: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/249484

发件人: languanghao ***@***.***>
日期: 星期二, 2022年11月29日 下午2:32
收件人: izhangzhihao/intellij-rainbow-brackets ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [izhangzhihao/intellij-rainbow-brackets] Incompatible for webstorm 2022.3 (Issue #2559)

@izhangzhihao<https://github.com/izhangzhihao> No new version: https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions

[image]<https://user-images.githubusercontent.com/3765379/204455818-4db613d4-795e-437f-8da8-86132fba419f.png>

―
