### ISSUE TITLE
pyCharm terrible colors

### ISSUE THREAD

**Issue by andprov** [izhangzhihao/intellij-rainbow-brackets#2560]
Plugin changed colors and I can't get it back. This is not amenable to any configuration. Removing the plugin does not help. Theme Darcula.
![image](https://user-images.githubusercontent.com/90068458/204647462-5e76a326-323e-4e3b-80f5-d939627f472b.png)

**Comment by intellij-rainbow-brackets** [comment]
hi, please disable "rainbow variables" in setting page

在 2022年11月30日，上午5:07，open-collective-bot[bot] ***@***.***> 写道：

﻿

Hey @andipron<https://github.com/andipron> 👋,

Thank you for opening an issue/feature request. We will get back to you as soon as we can.

Please consider support us by buying a license here<https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M> or donating from OpenCollective https://opencollective.com/intellij-rainbow-brackets.

And we have a special plan<https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2538> for paid users, if you are a paid user, your issue or feature request will have a higher priority.

If you are creating a issue, please make sure you already read the latest change log here<https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/CHANGELOG.md>.

**Comment by izhangzhihao** [comment]
same with #2541
