### ISSUE TITLE
Round brackets don't work without angle brackets enabled

### ISSUE THREAD

**Issue by Camble** [izhangzhihao/intellij-rainbow-brackets#2561]
## Your programming languages
C#

## Expected Behavior
- [x] Enable rainbow round brackets
- [ ] Enable rainbow angle brackets
Should colorize round brackets and not angle brackets.

## Current Behavior
Round brackets have no color unless rainbow angle brackets are enabled.

## Workaround
- [x] Enable rainbow round brackets
- [x] Enable rainbow angle brackets
Set angle brackets color to white.

## Your Environment
Plugin v6.26 for Rider on MacOS 12.5.1

**Comment by izhangzhihao** [comment]
Could you use the latest version? https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions

**Comment by Camble** [comment]
Sorry, not sure where I got 2.0.2 from. I'm using v6.26

**Comment by intellij-rainbow-brackets** [comment]
hi please use v2022.3.5
