### ISSUE TITLE
Plugin affects the `New Dark` color scheme

### ISSUE THREAD

**Issue by Rezrazi** [izhangzhihao/intellij-rainbow-brackets#2562]
## Please check
- [x] This issue/feature request is not reported before.

## Your programming languages
PHP, Typescript, JSX

## Current Behavior
When using the plugin in combination with the New Dark color scheme, things are rendering weird: 
<img width="637" alt="CleanShot 2022-11-30 at 18 56 50@2x" src="https://user-images.githubusercontent.com/2086576/204872688-0841e938-45df-4ffa-8e84-7e9f3de556fb.png">

Without the plugin enabled:
<img width="590" alt="CleanShot 2022-11-30 at 18 57 27@2x" src="https://user-images.githubusercontent.com/2086576/204872817-3f13b87b-dfb9-42e6-9bf1-bd6714dc5899.png">

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.

## Your Environment

- Plugin version 2022.3.5

```
PhpStorm 2022.3 RC
Build #PS-223.7571.147, built on November 25, 2022
Licensed to xxxx
Subscription is active until December 14, 2022.
Runtime version: 17.0.5+1-b653.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.lppedd.idea-conventional-commit (0.21.0)
    com.github.copilot (1.1.35.2063)
    org.intellij.plugins.postcss (223.7571.117)
    com.intellij.ideolog (203.0.30.0)
    com.wakatime.intellij.plugin (14.1.2)
    ski.chrzanow.foldableprojectview (1.1.4)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-223)
    com.intellij.lang.jsgraphql (3.3.0)
    ru.adelf.idea.dotenv (2022.3)
    de.espend.idea.php.annotation (8.2.3)
    com.laravel_idea.plugin (6.1.1.223)
    com.pestphp.pest-intellij (1.8.3)
    dev.ekvedaras.laravelquery (3.3.3)
    com.mallowigi (80.0.0)
    mobi.hsz.idea.gitignore (4.4.4)
```

**Comment by izhangzhihao** [comment]
The first screenshot shows that you enabled the option "Enable rainbow variables", if you don't want your variables rainbowed, you could disable it in `settings -> rainbow brackets -> Enable rainbow variables`.
