### ISSUE TITLE
Incompatibility with Semantic highlighting

### ISSUE THREAD

**Issue by luis-alves** [izhangzhihao/intellij-rainbow-brackets#2563]
## Your programming languages
Java & Kotlin

## Expected Behavior
Should be able to uncheck semantic highlighting and persist this setting after restart.

## Current Behavior
When I uncheck the semantic highlighting (SH) with rainbow brackets (RB) enabled, after restarting Intellij the semantic highlighting appears checked again.
If I disable RB and uncheck SH it remains unchecked after restarting IntelliJ.

## Your Environment

* Plugin version: 2022.3.4-ij
```
IntelliJ IDEA 2022.2.4 (Ultimate Edition)
Build #IU-222.4459.24, built on November 22, 2022
You have a perpetual fallback license for this version.
Runtime version: 17.0.5+7-b469.71 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (222.4459.16)
    krasa.CpuUsageIndicator (1.14)
    dev.patrickpichler.darculaPitchBlackTheme (1.0.0)
    de.docs_as_co.intellij.plugin.diagramsnet (0.1.14)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.navigatetomodule (0.32)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.watcher (222.4459.16)
    org.intellij.plugins.hcl (222.4459.16)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    com.intellij.nativeDebug (222.4459.16)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.properties.bundle.editor (222.4459.16)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    net.orekyuu.java8postfix (1.0.0)
    com.poratu.idea.plugins.tomcat (4.3.8)
    com.github.leomillon.uuidgenerator (4.5.1)
    com.intellij.selenium (222.4459.16)
    String Manipulation (9.6.1)
    Quick Notes (3.3)
    Pomodoro-tm (0.70)
    InnerBuilder (1.3.0)
    org.sonarlint.idea (7.2.0.56810)
    com.crunch42.openapi (1.41)
    com.intellij.kubernetes (222.4459.16)
    com.nekofar.milad.intellij.nextjs (1.2.3)
    com.github.iguissouma.nxconsole (0.51.0)
    Pythonid (222.4459.24)
    net.ashald.envfile (3.4.1)
    CheckStyle-IDEA (5.73.0)
    com.thoughtworks.gauge (222.4459.16)
    de.endrullis.idea.postfixtemplates (2.15.0.222)
    AceJump (3.8.8)
    IdeaVIM (1.11.1)
    org.jetbrains.IdeaVim-EasyMotion (1.9)

Kotlin: 222-1.7.21-release-272-IJ4167.29
```

**Comment by izhangzhihao** [comment]
same with #2556

**Comment by luis-alves** [comment]
> same with #2556

It's not the same issue

**Comment by jodyhoonstarr** [comment]
Same issue on webstorm 2022.3. Multiple users reporting similar issues on [youtrack](https://youtrack.jetbrains.com/issue/WI-69719/Cannot-disable-Semantic-Highlighting-mode)

**Comment by luis-alves** [comment]
> Same issue on webstorm 2022.3. Multiple users reporting similar issues on [youtrack](https://youtrack.jetbrains.com/issue/WI-69719/Cannot-disable-Semantic-Highlighting-mode)

Yes this is the same issue

**Comment by izhangzhihao** [comment]
you can disable `Enable rainbow variable` to disable the `Semantic highlighting` option
![image](https://user-images.githubusercontent.com/12044174/205187339-1f7bf88c-650e-4e36-8abb-d898cc54df4f.png)

**Comment by Eminanza** [comment]
The problem is when you have "Enable rainbow variables" unchecked because you don't want to use them via the plugin and try to activate them in IntelliJ. Each time you restart IJ, the "semantic highlighting" will revert to unchecked in IntelliJ itself.

There is clearly an interaction between both which should not happen.
So for now, I disabled the plugin.

**Comment by izhangzhihao** [comment]
hi @Eminanza please use version 2022.3.5, in this version, the issue of configuration conflict has been fixed, if you are using 2022.3.5, please let me know.

**Comment by izhangzhihao** [comment]
hi @Eminanza , sorry, I misunderstood your reply, please ignore it. for now, please if you want the "semantic highlighting" works, please make the option "Enable rainbow variables" checked.

**Comment by izhangzhihao** [comment]
In the next version, a new option added, please enable it if you want to enable Semantic Highlighting but don't want Rainbow Brackets to control it. (please make sure both are checked, and then you could disable or enable it under "Editor -> Color Scheme -> Language Defaults -> Semantic Highlighting"), By the way, to make this option work, you may need to uncheck (and save) and re-check (and save) again the "Semantic Highlighting" option.

And, Merry Christmas.


<img width="952" alt="image" src="https://user-images.githubusercontent.com/12044174/209469963-665bd995-8e53-41b3-b04b-02b90bb0e4f7.png">

**Comment by izhangzhihao** [comment]
Please check out the latest release.

**Comment by duncte123** [comment]
> In the next version, a new option added, please enable it if you want to enable Semantic Highlighting but don't want Rainbow Brackets to control it. (please make sure both are checked, and then you could disable or enable it under "Editor -> Color Scheme -> Language Defaults -> Semantic Highlighting"), By the way, to make this option work, you may need to uncheck (and save) and re-check (and save) again the "Semantic Highlighting" option.
> 
> And, Merry Christmas.
> 
> <img alt="image" width="952" src="https://user-images.githubusercontent.com/12044174/209469963-665bd995-8e53-41b3-b04b-02b90bb0e4f7.png">

Leaving "enable rainbow variables" unchecked still disables semantic highlighting if "I will enable semantic highlighting myself" is checked, this should not happen IMO

**Comment by izhangzhihao** [comment]
hi, you may need a restart and try again.

**Comment by duncte123** [comment]
> hi, you may need a restart and try again.

Restarting causes rainbow brackets to disable semantic highlighting with this configuration. Tested across PHPStorm, GoLand and IntelliJ ultimate

**Comment by izhangzhihao** [comment]
can you show any screenshots of your config page?

**Comment by duncte123** [comment]
Before restart:
![](https://im.going-g.host/9RMJRbfyB7.png)
![](https://im.going-g.host/3ZAeHADMB1.png)

After restart:
![](https://im.going-g.host/5RNfHnF0XU.png)
![](https://im.going-g.host/Hx5NQvLNyD.png)

**Comment by izhangzhihao** [comment]
I mean, you should check "Enable rainbow variables" and "I will check..." both, then, this plugin will not change your settings anymore.

**Comment by duncte123** [comment]
> I mean, you should check "Enable rainbow variables" and "I will check..." both, then, this plugin will not change your settings anymore.

Then this is 100% a bug. A plugin should ***never*** randomly alter other settings than its own. Shit like this makes me want to uninstall it
