### ISSUE TITLE
Rainbow variables support for C# lang

### ISSUE THREAD

**Issue by izhangzhihao** [izhangzhihao/intellij-rainbow-brackets#2570]
In my Rider 2022.3, rainbow variables option is not working at all.

![screenshot](https://user-images.githubusercontent.com/46282492/206824973-9a445f3d-3de9-4492-9e01-efa9f692f0f6.png)

_Originally posted by @hwooo in https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2569#issuecomment-1344988716_

**Comment by izhangzhihao** [comment]
Hi @hwooo , please try the build snapshot(it's still developing, feedbacks are welcome!):

**Comment by hwooo** [comment]
![unnamed](https://user-images.githubusercontent.com/46282492/207362330-70aa55fc-50cd-48ad-ae72-4bf3c9de979a.png)

@izhangzhihao It looks very good!
It would be better if variables and properties do not have same color. Green color seems to be used repeatedly.
Other than that I like everything.

**Comment by izhangzhihao** [comment]
Oh, great catch, I will try to fix it later.

**Comment by izhangzhihao** [comment]
I think this issue might same with #2569, to repeat it, use `ctrl-a` and `ctrl-x` to cut all content from the current file and restore all content to the file again using `ctrl-v`, and all seems to look fine.

I think this is caused by the non-deterministic of the parser, I will report an issue on YouTrack(https://youtrack.jetbrains.com/) later.

**Comment by izhangzhihao** [comment]
Please check out the latest release.

**Comment by hwooo** [comment]
Thanks! Nice work 👍👍👍
