### ISSUE TITLE
This plugin will not work for cracked IDE

### ISSUE THREAD

**Issue by Satan1c** [izhangzhihao/intellij-rainbow-brackets#2571]
## Please check

- [x] I already support this project.
- [x] Paid plan from JetBrains Marketplace.
- [x] This issue/feature request is not reported before.

## Your programming languages
C#

## Expected Behavior
Colorized brackets by different colors for different levels

## Current Behavior
Any brackets are with default colors, and before I suppress, permanent message about premiun on top of opened file

## Possible Solution
/

## Code snippet for reproduce (for bugs)
```cs
var no_matter = new [] {(new NoMatter()
{
	
})};

public class NoMatter
{
	public NoMatter()
	{
		if ()
		{
			
		}
	}
}
```
![image](https://user-images.githubusercontent.com/51721290/207159335-daa4218f-050a-45d2-9c94-822e31d84b6b.png)

## Your Environment

* Plugin version: 2022.3.5
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
JetBrains Rider 2022.3
Build #RD-223.7571.232, built on December 5, 2022
Licensed to 
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 12
Registry:
    ide.lookup.shrink=true
    platform.projectModel.workspace.model.file.index=false
    ide.workspace.model.rbs.as.tree=false
    database.show.search.tab=false
    vcs.empty.toolwindow.show=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    nsubstitutecomplete-rider (1.8.3)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.ideolog (203.0.30.0)
    com.godwin.json.parser (1.4.1)
    fluentvalidation-rider (2022.3.0)
    com.intellij.resharper.HeapAllocationsViewer (2022.3.0-eap04)
    com.settler.rider.specflow (1.15.3)
    fluentassertions-rider (2022.3.0)
    some.awesome (1.14)
    Abc.MoqComplete.Rider (2022.3.0.2)
    me.seclerp.rider.plugins.efcore (223.1.0)
    com.intellij.resharper.StructuredLogging (2022.3.0.276-eap07)
    izhangzhihao.rainbow.brackets (2022.3.5)
    zielu.gittoolbox (213.10.3)
    mobi.hsz.idea.gitignore (4.4.4)
 ```

**Comment by izhangzhihao** [comment]
Hi, you might need to turn on this option(it's from the Rider IDE)
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/12044174/207206127-6aae89ac-e4ab-4aa2-9375-42a1a719cc79.png">

After that, you will see:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/12044174/207206171-1ea703ae-6393-4bc1-ae2e-ceec2287b3ed.png">

**Comment by kibble1** [comment]
Same issue as OP, suggested solution above does not change anything, it was already set to "All Problems".

Still no rainbow brackets in C#, **but they are present in js**.

Plugin version: 2022.3.5
Paid plan from JetBrains Marketplace.

JetBrains Rider 2022.3
Build #RD-223.7571.232, built on December 5, 2022
Licensed to 
Subscription is active until August 31, 2023.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
    rdclient.asyncActions=false
    rider.enable.designer.winForms=false
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    vcs.empty.toolwindow.show=false
    ide.workspace.model.rbs.as.tree=false
    database.show.search.tab=false
    platform.projectModel.workspace.model.file.index=false

Non-Bundled Plugins:
    com.villains.intelij.plugin.trashpandatheme (2.0.3)
    color.scheme.Cobalt 2 (1.0)
    me.seclerp.rider.plugins.efcore (223.1.0)
    org.intellij.plugins.postcss (223.7571.117)
    com.markskelton.one-dark-theme (5.7.2)
    org.pydemia.theme.cobalt9 (1.1.8)
    eu.gillissen.rider.usersecrets (1.2.0)
    Key Promoter X (2022.3)
    Abc.MoqComplete.Rider (2022.3.0.2)
    com.intellij.resharper.StructuredLogging (2022.3.0.276-eap07)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.jetbrains.lang.ejs (223.7571.117)
    com.intellij.kubernetes (223.7571.175)
    ru.adelf.idea.dotenv (2022.3)
    com.rspn.git (1.9)
    mobi.hsz.idea.gitignore (4.4.4)
    izhangzhihao.rainbow.brackets (2022.3.5)

**Comment by Satan1c** [comment]
> Hi, you might need to turn on this option(it's from the Rider IDE) <img alt="image" width="1109" src="https://user-images.githubusercontent.com/12044174/207206127-6aae89ac-e4ab-4aa2-9375-42a1a719cc79.png">
> 
> After that, you will see:
> 
> <img alt="image" width="1114" src="https://user-images.githubusercontent.com/12044174/207206171-1ea703ae-6393-4bc1-ae2e-ceec2287b3ed.png">

![image](https://user-images.githubusercontent.com/51721290/207434144-b8d94e77-fe4c-44e1-80f4-cb2c0948486b.png)

it was enabled for me by default

**Comment by Satan1c** [comment]
May it be cuz of IDE license is binded to one acc, but brackets license binded to another ?
May be it can't aprove license by some reasons

As I say, "I suppress, permanent message about premiun on top of opened file", I buy license, and in "Plugins" tab I see "Purchased" status, but any time when I open C# file, it shows me that... warning or smth, idk how to call it

**Comment by kibble1** [comment]
My license is bound to the same account as my ide license.

**Comment by izhangzhihao** [comment]
> May it be cuz of IDE license is binded to one acc, but brackets license binded to another ? May be it can't aprove license by some reasons
> 
> As I say, "I suppress, permanent message about premiun on top of opened file", I buy license, and in "Plugins" tab I see "Purchased" status, but any time when I open C# file, it shows me that... warning or smth, idk how to call it

I don't think this should cause a problem, as long as “purchased" is shown in the plugin tab.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/12044174/207473383-3c9f76ca-c80d-4083-bc36-5a9e8a4f2819.png">

**Comment by Satan1c** [comment]
> > May it be cuz of IDE license is binded to one acc, but brackets license binded to another ? May be it can't aprove license by some reasons
> > As I say, "I suppress, permanent message about premiun on top of opened file", I buy license, and in "Plugins" tab I see "Purchased" status, but any time when I open C# file, it shows me that... warning or smth, idk how to call it
> 
> I don't think this should cause a problem, as long as “purchased" is shown in the plugin tab.
> 
> <img alt="image" width="629" src="https://user-images.githubusercontent.com/12044174/207473383-3c9f76ca-c80d-4083-bc36-5a9e8a4f2819.png">

then what can I do to solve the problem, or it's somethng in plugin ?

**Comment by izhangzhihao** [comment]
Can you check:

- did an IDE restart help?
- can you show me the plugin config page?
- does the plugin works for other files? like JSON file?

**Comment by Satan1c** [comment]
> 

1. yep, I tried multiple restarts

2. 
![image](https://user-images.githubusercontent.com/51721290/208147916-d8243e73-df7e-47a4-9b73-8ebeea29b1c1.png)

3. yep, as I see, it works fine on the JSON etc, but on the C#

**Comment by izhangzhihao** [comment]
Can you change the config again and check if the IDE still shows the pop-up notification? it the config `suppressDisabledCheck ` exist in the XML file, please update it to false. And restart your IDE.

config path:

If you want to customize the advanced configuration, you could edit the config file and then restart your IDE. The config file path in APP_CONFIG/rainbow_brackets.xml.

In MAC OS env maybe like ~/Library/Preferences/Rider2022.3/options/rainbow_brackets.xml.

If you are using the ToolBox, then it will be like ~/Library/ApplicationSupport/JetBrains/Rider2022.3/options/rainbow_brackets.xml

In Linux env maybe like ~/.Rider/config/options/rainbow_brackets.xml.

In Windows env maybe like C:\Users\izhangzhihao\.Rider2022.3\config\options\rainbow_brackets.xml.


**NOTE: If you're hacking the IDE, the plugin won't work anyway. In addition, please keep the normal network connection, do not modify the `hosts` file, do not use custom DNS, and do not use anti-advertising products, to ensure normal activation**

**Comment by Satan1c** [comment]
> Can you change the config again and check if the IDE still shows the pop-up notification? it the config `suppressDisabledCheck ` exist in the XML file, please update it to false. And restart your IDE.
> 
> config path:
> 
> If you want to customize the advanced configuration, you could edit the config file and then restart your IDE. The config file path in APP_CONFIG/rainbow_brackets.xml.
> 
> In MAC OS env maybe like ~/Library/Preferences/Rider2022.3/options/rainbow_brackets.xml.
> 
> If you are using the ToolBox, then it will be like ~/Library/ApplicationSupport/JetBrains/Rider2022.3/options/rainbow_brackets.xml
> 
> In Linux env maybe like ~/.Rider/config/options/rainbow_brackets.xml.
> 
> In Windows env maybe like C:\Users\izhangzhihao.Rider2022.3\config\options\rainbow_brackets.xml.
> 
> **NOTE: If you're hacking the IDE, the plugin won't work anyway. In addition, please keep the normal network connection, do not modify the `hosts` file, do not use custom DNS, and do not use anti-advertising products, to ensure normal activation**

~I can't find that pathes~
~I have no `JetBrains/Rider2022.3/options` path~
Found it in `Roaming`
![image](https://user-images.githubusercontent.com/51721290/208377694-ed2955d7-02bd-4e9b-b820-342b199be662.png)

**Comment by Satan1c** [comment]
I also checked plugin in other IDEs, PhpStorm, PyCharm etc, in all of them all works fine, but in Rider

**Comment by Satan1c** [comment]
Nope, still see this

![image](https://user-images.githubusercontent.com/51721290/208379850-8026e881-c3bd-407b-9fb0-26b750863012.png)
![image](https://user-images.githubusercontent.com/51721290/208379895-d91a6e31-1482-4d8d-a180-ca569aefa9de.png)


for test, I tried to activate some other plugins, and they are activates and works

**Comment by izhangzhihao** [comment]
Is your IDE cracked? if true, then you could not activate this plugin.

**Comment by izhangzhihao** [comment]
Did this help you fix the issue? https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2574#issuecomment-1357892261

**Comment by Satan1c** [comment]
> Did this help you fix the issue? [#2574 (comment)](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2574#issuecomment-1357892261)

In Rider it named `Manage Licenses`
![image](https://user-images.githubusercontent.com/51721290/208516424-7c69c31c-c7d1-4edf-a157-74c4e58f0122.png)


I Activated it by Account, and it still don't work
![image](https://user-images.githubusercontent.com/51721290/208516193-dc27a9cc-54b8-4ee0-8904-84eb8e7c6857.png)

**Comment by Satan1c** [comment]
> Is your IDE cracked? if true, then you could not activate this plugin.

Idk, cuz on this pc was installed all Jet Brains IDEs, with activated plugins, by fallback licenses
if that the case, there no way to use the plugin ?
I can't understand, why another plugins are working, but the brackets, that has "Purchased" status in settings

**Comment by izhangzhihao** [comment]
Sorry for the late reply, using the fallback license for the IDE is ok.

Can I see your `VM options` on your setting page?:

![image](https://user-images.githubusercontent.com/51721290/208516424-7c69c31c-c7d1-4edf-a157-74c4e58f0122.png)

**Comment by Satan1c** [comment]
> Sorry for the late reply, using the fallback license for the IDE is ok.
> 
> Can I see your `VM options` on your setting page?:
> 
> ![image](https://user-images.githubusercontent.com/51721290/208516424-7c69c31c-c7d1-4edf-a157-74c4e58f0122.png)

sry too
![image](https://user-images.githubusercontent.com/51721290/209442216-8a8379da-f11b-4880-bf3d-946caf83dc51.png)

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/51721290/209442216-8a8379da-f11b-4880-bf3d-946caf83dc51.png)


According to your config, you are cracking the IDE, this plugin will definitely not work. I will close this issue, if you really paid for this plugin, can you provide your purchase record? If you really paid for this plugin, you need a fresh install of Rider IDE, then this plugin will work for you.
