### ISSUE TITLE
Swift Language Support

### ISSUE THREAD

**Issue by ICULikeMac** [izhangzhihao/intellij-rainbow-brackets#2572]
Hi There,

Are there any plans to support Swift?

Thanks

**Comment by izhangzhihao** [comment]
Hi, which IDE you are using? Cuz I don't have an XCode installation, I can confirm that the CLion with clion-swift plugin works for me: 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/12044174/207567828-fe7ad14c-a876-42a2-9167-48e4c0a44349.png">

```
CLion 2022.3
Build #CL-223.7571.171, built on November 29, 2022
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 16
Metal Rendering is ON
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    izhangzhihao.rainbow.brackets (2022.3.5)
    com.intellij.clion-swift (223.7571.208)

```

**Comment by izhangzhihao** [comment]
Hi, seems the AppCode IDE is ended, and there will be no more updates. So I guess this issue could be closed. if you have other issues, please leave comments or create a new one.

 https://blog.jetbrains.com/zh-hans/appcode/2022/12/appcode-2022-3-release-and-end-of-sales-and-support/
