### ISSUE TITLE
I paid for a yearly license plan, but in Webstorm I see "No License".

### ISSUE THREAD

**Issue by martijnsenden** [izhangzhihao/intellij-rainbow-brackets#2574]
Hi,

I have just paid for a yearly license plan, but in Webstorm I see "No License". What do I need to do to let the plugin recognize the license?

Regards,
Martijn

**Comment by izhangzhihao** [comment]
Did an IDE restart help you?

**Comment by martijnsenden** [comment]
It did not.

**Comment by izhangzhihao** [comment]
can you show me the page `Help` -> `Register`?
<img width="419" alt="image" src="https://user-images.githubusercontent.com/12044174/208468876-5e8d9aa3-b9d8-4a24-835c-d609b73d59f7.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/12044174/208468675-36a74584-7839-4297-b957-39f347c0cd1b.png">

**Comment by martijnsenden** [comment]
Ah, thanks, that solved it. I had to activate it there. I was not aware. Thanks.

**Comment by mtpilarek** [comment]
![image](https://user-images.githubusercontent.com/25985009/211539162-03cae6c6-2ef4-4eda-8c50-18ee3612487f.png)
It didn't help, maybe it's because I have installed build from previous comments?
