### ISSUE TITLE
Full customization of colors for variables similar to brackets color customization

### ISSUE THREAD

**Issue by thenajjar** [izhangzhihao/intellij-rainbow-brackets#2576]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

## Please check
- [x] I already support this project.
- [x] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
Python/Pycharm

## Expected Behavior
* Be able to fully choose "Color Scheme" for variables colors like we already do with brackets.

## Current Behavior
* We are unable to choose the color scheme for variables

## Code examples
```
    <option name="VARIABLES_RAINBOW_COLOR0">
        <value>
            <option name="FOREGROUND" value="E8BA36"/>
        </value>
    </option>
    <option name="VARIABLES_RAINBOW_COLOR1">
        <value>
            <option name="FOREGROUND" value="7FFFFE"/>
        </value>
    </option>
```

**Comment by thenajjar** [comment]
![Screenshot 2023-01-03 at 12 47 01 PM](https://user-images.githubusercontent.com/101046920/210333384-6b29b885-a4f8-422e-ab7d-4d1691a2873b.png)

**Comment by izhangzhihao** [comment]
Hi, I could not get your idea exactly, what do you mean exactly about "Be able to fully choose "Color Scheme" for variables colors", now users could define up to 10 colors like this:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/12044174/202893817-4a88d0c8-1c9d-4442-86f1-235c2653cf60.png">

**Comment by thenajjar** [comment]
Correct, but these only work for brackets, and not "variables" colors. Can you add one more section here in this same screen where we can choose colors for "variables" colors?

**Comment by izhangzhihao** [comment]
hi, rainbow variables colors could be configured here: 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/12044174/210367686-1e722b0a-61ba-4521-98c1-838bddafa2cb.png">


And, BTW, you can only config 5 colors, but the IDE will generate 20 colors from the 5 colors.

**Comment by thenajjar** [comment]
Oh I see, but can't you override this and add a section to customize the variables colors like you done for brackets?

**Comment by izhangzhihao** [comment]
> Oh I see, but can't you override this and add a section to customize the variables colors like you done for brackets?

That sounds not a bad idea, I can try to create a soft link jump to this page or overwrite it with the rainbow brackets' setting page. I will sleep on it.

**Comment by ivanalmasi** [comment]
@izhangzhihao Please consider adding separate color options for indent guides as well.
I like rainbow colors for brackets, but I would prefer to keep indent guides in a single color (I can turn it off, but then I lose the indent guides highlight).

![image](https://user-images.githubusercontent.com/35292893/210633332-26896be8-282a-413c-80fb-6c248cf6ec05.png)

**Comment by izhangzhihao** [comment]
hi, both, I added two new options for you:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/12044174/211297244-a3d9d431-e10d-4ab4-9b40-71b2128b37f3.png">

<img width="716" alt="image" src="https://user-images.githubusercontent.com/12044174/211297286-43b9592c-10c1-4fc7-9efa-cebaa7ca27f7.png">

please have a try for this build snapshot

**Comment by ivanalmasi** [comment]
@izhangzhihao Thanks! Any chance you can build it for this version as well:
![image](https://user-images.githubusercontent.com/35292893/211321145-e1550c0c-5eb0-4698-88b7-ff046969b185.png)

~~I can install an older version, but only later today.~~
Not going to work as my settings is not synced any more due to using new settings sync feature.

**Comment by izhangzhihao** [comment]
Hi, please use this build snapshot
[intellij-rainbow-brackets-2023.1.0-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10373841/intellij-rainbow-brackets-2023.1.0-ij.zip)

**Comment by ivanalmasi** [comment]
Thanks! If I turn off "Rainbow highlighting" for "Indent Guides Line" in "Color scheme", they are still colored. Should I set custom monochrome color there instead?

**Comment by izhangzhihao** [comment]
hi, this setting page is for custom indent guide color, if you want single color for all indent guides, please enable it and set all colors to one same color

**Comment by ivanalmasi** [comment]
Got it. It works like that. Only downside is that it needs to be done for each color scheme, but it's not switched very often.
