### ISSUE TITLE
Round and square brackets highlighting does not work in C#

### ISSUE THREAD

**Issue by viruseg** [izhangzhihao/intellij-rainbow-brackets#2577]
Rider 2022.3.1
Rainbow Bracket 2023.1.0
Round and square brackets highlighting does not work in C#. The curly brackets are highlighted as expected.
![image](https://user-images.githubusercontent.com/919215/210191033-15e1eb1e-321b-4be2-8b6d-6d198eebd826.png)

**Comment by izhangzhihao** [comment]
Related to #2569

**Comment by izhangzhihao** [comment]
This issue will be closed, I will follow this case in #2569 , these two issues are reporting the same issue, which was highlighting suddenly stop working when you start editing the codes, but if you just open the file and never edit it, the highlighting seems to work well(you can try this after you restart your IDE).
