### ISSUE TITLE
Rainbow variables in C# shouldn't color types

### ISSUE THREAD

**Issue by mtpilarek** [izhangzhihao/intellij-rainbow-brackets#2578]
## Your programming language
C#

## Expected Behavior
Types, interfaces and enums shouldn't be colored, but have one static color.
For enums and interfaces it should be this one:
![image](https://user-images.githubusercontent.com/25985009/210223068-4661fd8e-47c3-4b9d-8a3d-ee8a352ed7ce.png)
For classes it should be this one:
![image](https://user-images.githubusercontent.com/25985009/210223705-d03f806d-6d50-4200-8536-51bed5071c23.png)

Coloring types is really confusing and makes file less readible. I suggest at least to make it configurable. In my opinion it's a bug, but maybe some would concider it as a feature.

## Current Behavior
Types, interfaces and enums are treated like a variable.
![image](https://user-images.githubusercontent.com/25985009/210222984-97c79ddd-6e12-4dc0-9f64-5a81d247909b.png)
![image](https://user-images.githubusercontent.com/25985009/210223030-e754e166-23cc-41b4-ba91-e3c4ccf70bfc.png)

## Code snippet for reproduce (for bugs)
Open any C# file.

## Your Environment
JetBrains Rider 2022.3.1
* Plugin version:
Rainbow Brackets 2023.1.0

**Comment by izhangzhihao** [comment]
True, since the dummy C sharp light parser from the Rider IDE could not tell me the real stuff behind the PSI tree, what this plugin could find is only something created by `IDENTIFIER`s, but I will have to try to find some pattern, and handle some cases.


<img width="977" alt="image" src="https://user-images.githubusercontent.com/12044174/210223814-921613a1-3c88-4b59-92a3-e619fe0c0ad1.png">

**Comment by jansviland** [comment]
Just want to add to this, I have the same issue. Can not use this feature in C#. 

This should be highlighted:
![bilde](https://user-images.githubusercontent.com/114911422/210411382-f5142cc2-6138-4d4a-a3b6-93af64803675.png)

This is the result. Everything is highlighted. 
![bilde](https://user-images.githubusercontent.com/114911422/210411547-4fb2f328-0f33-43e9-94d6-12d6c8a71b1e.png)

**Comment by izhangzhihao** [comment]
Hi @jansviland please provide your code sample, so I could reproduce this issue and fix.

**Comment by jansviland** [comment]
> Hi @jansviland please provide your code sample, so I could reproduce this issue and fix.

Of course, the example above can be found here:
https://github.com/jansviland/AdventOfCode/blob/main/2022/AdventOfCode.2022.Day7.Tests/Tests.cs

**Comment by izhangzhihao** [comment]
please try this build snapshot:
[intellij-rainbow-brackets-2023.1.0-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10373326/intellij-rainbow-brackets-2023.1.0-ij.zip)

**Comment by mtpilarek** [comment]
Better, but not there yet.
![image](https://user-images.githubusercontent.com/25985009/211420272-5a79098a-5201-40b9-a2f9-6aabaa9c1761.png)
Still coloring types here.

![image](https://user-images.githubusercontent.com/25985009/211420319-79011571-a419-4005-8d42-079457285c5e.png)
Here some variables not colored (_settings)
Some strange coloring for initializer of first prop (TotalCount)
Coloring constructor (ArchitectsTeamsDto)
Still coloring types in method definition.

**Comment by izhangzhihao** [comment]
please try this build snapshot
[intellij-rainbow-brackets-2023.1.0-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10378148/intellij-rainbow-brackets-2023.1.0-ij.zip)

**Comment by mtpilarek** [comment]
Better, but:
![image](https://user-images.githubusercontent.com/25985009/211522541-4c67a562-74b1-4ac6-ab93-65703ca48b0b.png)
Private variables not colored
![image](https://user-images.githubusercontent.com/25985009/211522635-3e8578e1-d284-4d36-8fdc-c56cc07b28e4.png)
totalCount changed coloring in conditional statement

Also sometimes variables next to each other have same colors:
![image](https://user-images.githubusercontent.com/25985009/211525186-c491bb37-ca29-4f9a-a5aa-b8cd6d4b8dba.png)
settingsInterfaceType and factoryMethod
![image](https://user-images.githubusercontent.com/25985009/211525258-fcb1922d-e9fc-43f5-825e-016e868e791f.png)
searchableType and searchableTypeGeneric

I think plugin should try to differ colors for variables close to each other/in the same scope. Don't really know if it's possible, but it would be nice.

**Comment by izhangzhihao** [comment]
Ah, are you using the color generator for rainbow variables or the default color config?

**Comment by mtpilarek** [comment]
![image](https://user-images.githubusercontent.com/25985009/211537947-28a30ed4-1714-438c-89ed-1d67f8dd436d.png)
Do u mean this feature? I can't select this, because after saving and entering settings afterwards it is not selected again. After restart it is also deselected.
![image](https://user-images.githubusercontent.com/25985009/211538093-1f606ed6-d9d2-4a2d-9687-71416210a0e6.png)
And as you can see I have purchased Rainbow Brackets.

**Comment by izhangzhihao** [comment]
Does [this](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2574#issuecomment-1357892261) help you?

**Comment by mtpilarek** [comment]
![image](https://user-images.githubusercontent.com/25985009/211539532-4b5ad949-5e3b-4400-b82d-ff7c8929188e.png)
It didn't help, maybe it's because I have installed build from your previous comments?
It's something with this specifing options, because other paid features work. For example color generator lumosity works.

**Comment by izhangzhihao** [comment]
Thanks! this is another bug, I will fix it later!

**Comment by izhangzhihao** [comment]
Please try this build snapshot
[intellij-rainbow-brackets-2023.1.0-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10382333/intellij-rainbow-brackets-2023.1.0-ij.zip)

**Comment by mtpilarek** [comment]
![image](https://user-images.githubusercontent.com/25985009/211545077-00619e4f-0f59-4ca2-a3d6-c967357b5fc9.png)
Option is now working, but the issue with same coloring persists.

**Comment by izhangzhihao** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/12044174/211708487-4c6f5d3e-082d-4963-9a8e-7b946c0af150.png">

**Comment by mtpilarek** [comment]
Much better now.
The only persisting issue I can find is this one:
![image](https://user-images.githubusercontent.com/25985009/211808866-c406bb60-d779-4adc-a674-68ce2c910572.png)
totalCount changed coloring in conditional statement

**Comment by mtpilarek** [comment]
Did you manage to fix conditional statement?
![image](https://user-images.githubusercontent.com/25985009/212045850-396c8e45-c536-4f49-8034-868fa28493b6.png)
The easiest way to reproduce it is make simple statement with ? and :

![image](https://user-images.githubusercontent.com/25985009/212162222-fb985587-7c91-4cc8-8f93-5388513005e1.png)
I've just also spotted that similar bug appears in constructor arguments. If we use same variable in constructor arguments it changes coloring.
