### ISSUE TITLE
Rainbow Variables code coloring reappears after uninstalling/disabling plugin

### ISSUE THREAD

**Issue by habizzle** [izhangzhihao/intellij-rainbow-brackets#2579]
## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages

Java

## Expected Behavior

1. Enable Rainbow Variables
2. Optionally: Disable it
3. Deactivate (or uninstall) Rainbow Brackets plugin
4. Code coloring from Rainbow Variables is (still) off

## Current Behavior

Code coloring is on again after deactivating or uninstalling the plugin. Code coloring was off after having disabled the feature in step 2 but is now on again after step 3.

## Your Environment

* Plugin version:

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to me
Subscription is active until February 6, 2023.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.1.1-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    editor.focus.mode.color.light=697098
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=697098
    workspace.model.spring.facet.bridge=false

Non-Bundled Plugins:
    name.kropp.intellij.makefile (223.8214.6)
    com.intellij.properties.bundle.editor (223.7571.203)
    org.asciidoctor.intellij.asciidoc (0.38.4)
    izhangzhihao.rainbow.brackets (2023.1.0)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    org.sonarlint.idea (7.3.0.59206)

Kotlin: 223-1.7.21-release-272-IJ8214.52
Current Desktop: XFCE
```

**Comment by izhangzhihao** [comment]
Hi, you can disable it here: 
<img width="997" alt="image" src="https://user-images.githubusercontent.com/12044174/210359902-d08bc959-205b-40d3-be67-0c9cb907c823.png">

and make sure two of these options not checked, then this plugin will keep your variables not touched.
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/12044174/210360122-5afdc53d-eeb0-449d-800b-666e5673f806.png">

**Comment by habizzle** [comment]
Thanks for your reply!

I think this is a problem with your deactivate/uninstall hook (I am not accustomed to writing IDEA plugins, but I guess there is some kind of hook to clean things up):

After I have _disabled_ your plugin, the Rainbow Variables reappear - even if I have configured everything as you proposed above.

**Comment by izhangzhihao** [comment]
Rainbow Variables even works after you disable the Semantic Highlighting option?
<img width="997" alt="image" src="https://user-images.githubusercontent.com/12044174/210359902-d08bc959-205b-40d3-be67-0c9cb907c823.png">

**Comment by habizzle** [comment]
Well, I just wanted to check and disabled the plugin again completely - this time the code colors did not switch back to the Rainbow Variables style...I don't know, what was different this time.

I am pretty sure, that I was experiencing some kind of bug when I disabled your plugin for the first 3 times and the code color changed back to the Rainbow Variables style (as described in first post) - but I am glad disabling worked now :).

So I keep this ticket open (as I _think_ there is a bug) but my problem is resolved, so feel free to close.

Thanks for your support!
