### ISSUE TITLE
I can't enable color generator option for rainbw variables

### ISSUE THREAD

**Issue by hwooo** [izhangzhihao/intellij-rainbow-brackets#2582]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [X] I already support this project.
- [ ] If you are submitting a feature request, please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [X] This issue/feature request is not reported before.

## Your programming languages

- JavaScript / TypeScript / C#

## Expected Behavior
* Check `Use color generator for rainbow variables(restart required)` in Settings
* Option should be enabled after restart IDE

<img width="279" alt="pic1" src="https://user-images.githubusercontent.com/46282492/211973743-a2116211-3cdf-4013-9974-f3f6f981f77b.png">

<img width="909" alt="pic2" src="https://user-images.githubusercontent.com/46282492/211973768-21326b99-5689-44f2-9e7a-b746470062a7.png">

## Current Behavior
* **Option returns to unchecked state.**
* However some colors for rainbow brackets (not variables) has changed.

## Your Environment

* Plugin version: 2023.1.0
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to James Hyun
Subscription is active until February 21, 2023.
Runtime version: 17.0.5+1-b653.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 6
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.intellij.plugins.macoskeymap (223.7571.117)
    com.khmelyuk.multirun (1.13)
    com.intellij.nativeDebug (223.8214.16)
    com.intellij.spring.batch (223.7571.182)
    com.jetbrains.plugins.jade (223.7571.117)
    com.intellij.javaee.batch (223.7571.182)
    Pythonid (223.8214.52)
    izhangzhihao.rainbow.brackets (2023.1.0)
    com.intellij.bigdatatools (223.8214.65)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

**Comment by izhangzhihao** [comment]
Please use this build snapshot: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2578#issuecomment-1378226686
