### ISSUE TITLE
Better Indent guides for Python 

### ISSUE THREAD

**Issue by JakubKahovec** [izhangzhihao/intellij-rainbow-brackets#2583]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [X] I already support this project.
- [ ] If you are submitting a feature request, please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ ] This issue/feature request is not reported before.

## Your programming languages
Python

## Expected Behavior
I would expect indent guides to appear in the nested blocks

## Current Behavior
Indent guides do not appear in the nested blocks. They appear though sometimes in certain blocks.

<img width="557" alt="Screenshot 2023-01-19 at 10 04 18" src="https://user-images.githubusercontent.com/32606/213402244-dd5c2562-0cb0-4196-984f-22ae4c98811b.png">

<img width="368" alt="Screenshot 2023-01-19 at 10 15 48" src="https://user-images.githubusercontent.com/32606/213402759-006073c2-a974-47c6-8cff-24d62496059f.png">

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.
```
try:
    if cond:
        print("test")
        print("test")
        if another_cond:
            print("test")
            print("tst")
            for i in []:
                print(i)
                print(i)
    else:
        print("test")
        print("aaaa")
except NameError as e:
    print(e)
```

## Your Environment

* Plugin version:
2023.1.1
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to Cisco Systems, Inc / Jakub Kahovec
Subscription is active until May 7, 2023.
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 10
Metal Rendering is ON
Registry:
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.4)
    me.lensvol.blackconnect (0.5.0)
    cn.jxzhang.plugin.json-formatter (1.4)
    lermitage.intellij.extratci (1.24.0)
    com.crunch42.openapi (1.46)
    mobi.hsz.idea.gitignore (4.4.4)
    zielu.gittoolbox (213.10.5)
    Pythonid (223.8214.52)
    com.koxudaxi.pydantic (0.3.17)
    com.leinardi.pycharm.mypy (0.14.0)
    com.leinardi.pycharm.pylint (0.14.0)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.jetbrains.lang.ejs (223.7571.117)
    com.dmarcotte.handlebars (223.7571.117)
    izhangzhihao.rainbow.brackets (2023.1.1)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

**Comment by JakubKahovec** [comment]
<img width="595" alt="Screenshot 2023-01-19 at 10 19 12" src="https://user-images.githubusercontent.com/32606/213403493-385d244d-74d2-46f0-9696-d7593bf5a807.png">

**Comment by izhangzhihao** [comment]
Hi, this must first done at IDE side, this plugin does not creat new indent guide lines, but just highlighting it with different colors.

**Comment by JakubKahovec** [comment]
I see, ok, thanks for the update.

**Comment by izhangzhihao** [comment]
For your first image, because Python does not have{}, so we could not find color cross lines, but only you did like image two, only then we know how to highlighting the indent guide lines.

**Comment by JakubKahovec** [comment]
Would it be possible to somehow colorize the colon and take it into account for the related guideline ?

<img width="557" alt="Screenshot 2023-01-19 at 10 04 18 - colorized" src="https://user-images.githubusercontent.com/32606/213470225-c16b4f3c-0dd9-48e7-835e-c295d0848e2e.png">

**Comment by izhangzhihao** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/12044174/215311750-2fd3ee22-8d3d-45d6-b4d7-6fd7916f7909.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/12044174/215311763-e7f36cbe-f61d-4b87-9bca-6450c4d7e511.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/12044174/215311899-4300755b-8c18-4cb6-95aa-095ea71382d1.png">


This feature will be delivered in the next release, and this feature depends on "Rainbowify python keywords", please try the build snapshot [intellij-rainbow-brackets-2023.1.2.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10529270/intellij-rainbow-brackets-2023.1.2.zip) and give me feedback!

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12044174/215311819-1abfdae3-e332-4b08-a21c-14c0509d1023.png">

**Comment by izhangzhihao** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/12044174/215311750-2fd3ee22-8d3d-45d6-b4d7-6fd7916f7909.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/12044174/215311763-e7f36cbe-f61d-4b87-9bca-6450c4d7e511.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/12044174/215311899-4300755b-8c18-4cb6-95aa-095ea71382d1.png">


This feature will be delivered in the next release, and this feature depends on "Rainbowify python keywords"

<img width="687" alt="image" src="https://user-images.githubusercontent.com/12044174/215311819-1abfdae3-e332-4b08-a21c-14c0509d1023.png">

**Comment by JakubKahovec** [comment]
Hello,

Thanks for the update, I've tried to install the plugin but it says the
plugin is explicitly marked as incompatible with the current version of the
IDE (2022.3.2).
I have a question regarding the Rainbowify Python keywords, is it possible
to make the colors somehow similar to the palette of the IDE semantic
highlighting as currently the colors are a bit too bright for me

Best regards
Jakub

**Comment by izhangzhihao** [comment]
I don't know why because I could not build a compatible version now... I will try fix this later

**Comment by izhangzhihao** [comment]
Please try this build snapshot 
[intellij-rainbow-brackets-2023.2.0.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10529596/intellij-rainbow-brackets-2023.2.0.zip)

**Comment by JakubKahovec** [comment]
The ident guides work now for the Python keywords, but stopped working on some brackets blocks.
<img width="476" alt="Screenshot 2023-01-29 at 15 10 28" src="https://user-images.githubusercontent.com/32606/215332146-c5992630-ac35-4132-af9e-3ceeb66e7da4.png">

**Comment by izhangzhihao** [comment]
> Hello, Thanks for the update, I've tried to install the plugin but it says the plugin is explicitly marked as incompatible with the current version of the IDE (2022.3.2). I have a question regarding the Rainbowify Python keywords, is it possible to make the colors somehow similar to the palette of the IDE semantic highlighting as currently the colors are a bit too bright for me Best regards Jakub

By the way, you can try to enable the random color generator or config your own color

<img width="595" alt="image" src="https://user-images.githubusercontent.com/12044174/216969689-b3dad5a8-2b25-439b-bff0-f5c031d3df94.png">

<img width="987" alt="image" src="https://user-images.githubusercontent.com/12044174/216970031-f02d7db0-a083-4ead-b09d-5880f5ce1639.png">

**Comment by JakubKahovec** [comment]
Are you going to fix the indent guides for bracket blocks ?  (as mentioned in https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2583#issuecomment-1407674860)

**Comment by izhangzhihao** [comment]
> Are you going to fix the indent guides for bracket blocks ?  (as mentioned in https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2583#issuecomment-1407674860)

I will try it in next release
