### ISSUE TITLE
Rainbow Variables not working in Gateway

### ISSUE THREAD

**Issue by MrMatch246** [izhangzhihao/intellij-rainbow-brackets#2584]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Expected Behavior
Rainbow Variables in Gateway client

## Current Behavior
Doesnt Work. When having everything with semantic highlighting unselected, but rainbow variables enabled variables have a different color but all the same. Unsure if this is due to Gateway/Jetbrains Stuff but i havent found anything on it yet so im reporting this here. 
I tried it with the current Up-To-Date Version of Gateway and currently the EAP Version

Code language : Python

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
JetBrains Client 2022.3 Preview
Build #JBC-223.8617.8, built on January 10, 2023
Licensed to ---
Subscription is active until January 3, 2024.
For educational use only.
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
Controller in Remote Development (PY)
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    indent-rainbow.indent-rainbow (2.1.0)
    com.intellij.plugins.github.colorscheme (223.7571.117)
    com.markskelton.one-dark-theme (5.7.2)
    com.wakatime.intellij.plugin (14.1.3)
    izhangzhihao.rainbow.brackets (2023.1.1)
    com.jetbrains.darkPurpleTheme (1.3)
    com.intellij.plugins.warmneon.colorscheme (223.7571.123)
    com.mallowigi (85.1.0)
    com.intellij.plugins.monokai.colorscheme (223.7571.123)
    com.github.copilot (1.1.38.2229)
    org.rust.lang (0.4.186.5143-223)
    org.toml.lang (223.8214.6)
    com.intellij.plugins.twilight.colorscheme (223.7571.123)

```

**Comment by izhangzhihao** [comment]
This plugin depends on `com.intellij.modules.lang`:

https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/f7fb0636cd45eda563783e9ad6f4694d94f7f702/src/main/resources/META-INF/plugin.xml#L715

But the Intellij Remote Development / Gateway does not have this module, so it would not be possible to support it at this moment.

Related to #2408

**Comment by Avamander** [comment]
@izhangzhihao Has JetBrains been informed or asked about this shortcoming?

**Comment by izhangzhihao** [comment]
I do think this is by design, so JetBrains kown the shortcomings for sure.
