### ISSUE TITLE
[Clojure] [Bug] Set literal inside map literal not colored correctly

### ISSUE THREAD

**Issue by rostopira** [izhangzhihao/intellij-rainbow-brackets#26]
I've recently started to learn Clojure, and this is code from sample:

![screen shot 2018-02-02 at 12 55 12 am](https://user-images.githubusercontent.com/16724952/35705601-feb0a790-07b3-11e8-9400-664fec9888aa.png)

Looks like IDE overrides coloring of `#{` it should be yellow. Maybe related to #19

**Comment by izhangzhihao** [comment]
Please provide the code segment.

**Comment by izhangzhihao** [comment]
And which plugin for Clojure you are using.

**Comment by izhangzhihao** [comment]
Reproduced on latest version (3.1.1) on intellij 2017.3 EAP.

**Comment by izhangzhihao** [comment]
Reproduced on development branch on intellij 2017.3 EAP.

**Comment by YiiGuxing** [comment]
![img](https://user-images.githubusercontent.com/10737066/35764025-7a4c6a98-08f3-11e8-9d8c-7bb7135bf39a.png)
