### ISSUE TITLE
HTML and JSX tag colour constantly change when reformat

### ISSUE THREAD

**Issue by primerch** [izhangzhihao/intellij-rainbow-brackets#2605]
This happens on .tsx files, the tag colour in inconsistent. please see the GIF below

![CleanShot 2023-03-14 at 00 35 57](https://user-images.githubusercontent.com/31989133/224767628-d498d5c0-fbfd-4812-8227-18f54582929e.gif)

**Comment by izhangzhihao** [comment]
I don't think is inconsistent, since the reformat code changes the PSI tree, the highlighter needs re-highlighting tags, and before and after the re-highlighting, tags keep the same color.(only changes to default tag color when re-formating happens.)
