### ISSUE TITLE
IDEA: Plugin 'Rainbow Brackets' (version '2023.2.6-ij') is not compatible

### ISSUE THREAD

**Issue by zainzhoucom** [izhangzhihao/intellij-rainbow-brackets#2609]
Plugin 'Rainbow Brackets' (version '2023.2.6-ij') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is IU-223.8836.41

IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Build #IU-223.8836.41, built on March 10, 2023
Licensed to Zain Zhou
订阅有效期至 2024年1月10日。
For educational use only.
Runtime version: 17.0.6+1-b653.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.zh (223.228)
    com.intellij.ideolog (203.0.30.0)
    com.tabnine.TabNine (0.8.13)
    com.dubreuia (2.3.0)
    com.fofund.jgt.jiyu-test (1.0-SNAPSHOT)
    com.github.wangji92.arthas.plugin (2.40)
    com.alibaba.p3c.smartfox (2.1.1)
    VisualVMLauncher (1.21.211.6085.0)
    MavenRunHelper (4.23.222.2964.0)
    com.sjhy.plugin.easycode (1.2.7-java.RELEASE)
    com.tianlei.plugin.mybatis (2.1.3)
    org.sonarlint.idea (8.0.0.63273)
    idea-yapi (2.1.0)

Kotlin: 223-1.8.0-release-345-IJ8836.41

**Comment by izhangzhihao** [comment]
please download version 2023.2.6 https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/299108
