### ISSUE TITLE
Why does unhighlighting not work anymore? Pressing Esc does not work

### ISSUE THREAD

**Issue by a13135556916** [izhangzhihao/intellij-rainbow-brackets#2610]
I am using the free version

**Comment by izhangzhihao** [comment]
it's free feature. could you please provide a GIF and the screenshot of your setting page？

**Comment by a13135556916** [comment]
![Kapture 2023-03-23 at 13 51 48](https://user-images.githubusercontent.com/26322089/227115774-17dc3a30-f05a-4f12-95a0-fe745ace6203.gif)
<img width="1592" alt="Xnip2023-03-23_13-54-07" src="https://user-images.githubusercontent.com/26322089/227115930-8ead4cd6-c066-4b10-93f8-b47df3a34eea.png">
These are my screenshots

**Comment by a13135556916** [comment]
我更新了2023.1之后，这个bug消失了
