### ISSUE TITLE
Licencing issue for Jetbrains products version 2023.1

### ISSUE THREAD

**Issue by catalin260** [izhangzhihao/intellij-rainbow-brackets#2617]
Hello,

There is a bug related to Jetbrains products, version 2023.1
I have installed on my system the IntelliJ Ultimate edition and I also have a licence acquired for Rainbow Brackets.
Apparently there is something messed up between the last version of IntelliJ Ultimate and this plugin (which I really like and I'm also too used to it at the moment to get rid of it).

Please see this link. Apparently there are other users that are reporting this issue also.
https://youtrack.jetbrains.com/issue/IDEA-316993/Not-able-to-license-following-upgrade.

If I rollback to 2022.3.3 version, everything is working just great.

**Comment by izhangzhihao** [comment]
What specific issue are you encountering?

**Comment by catalin260** [comment]
If you opened the link which I provided you already, there you can see.
I can't use my Jetbrains product because of this plugin. It says that my product is not licensed (and it is).
If I remove the plugin, from the plugins folder, everything is just great.

It's somehow interrupting the IDE licence checking (or something like this).

**Comment by izhangzhihao** [comment]
Oh, I see. Thanks for the update~~~

**Comment by izhangzhihao** [comment]
I just made a freshly installed PyCharm Pro by the toolbox, And even without a click, the plugin is activated and works fine.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/12044174/230879921-6440eeb9-2704-482b-ace4-60bd85ea0673.png">

**Comment by catalin260** [comment]
Yes, I also managed to have it installed with my Jetbrains product, but when I restarted the computer I had the issue described above.
This is happening on 2 different PCs of mine, so it's not an isolated issue.

**Comment by izhangzhihao** [comment]
It seems that JB merged the ticket to a [new ticket](https://youtrack.jetbrains.com/issue/IDEA-315534/Plugin-is-not-registered-with-no-details), and the new ticket is already fixed. It should be delivered in the next release of the IDEs.

Are you still encountering the licensing issue?

**Comment by catalin260** [comment]
Hopefully it's fixed now (but I saw that the update is planned for the end of April).
In the last 2 days I didn't encounter this issue.

Maybe we can consider this ticket closed.
Thank you for your time :)
