### ISSUE TITLE
I cannot buy the plugin (bad link to JetBrains shop).

### ISSUE THREAD

**Issue by joel-edwards-lark** [izhangzhihao/intellij-rainbow-brackets#2618]
## Please check

- [ ] I already support this project.
- [ ] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [x] This issue/feature request is not reported before.

## Your programming languages
N/A

## Expected Behavior
When I click `buy` on the summary page I should be directed to a Jetbrains page where I can license the product. Instead I see `Error 400 Bad Request`

The URL I am sent to is:
https://www.jetbrains.com/shop/buy?item=P%3AN%3APRAINBOWBRACKET%3AM%22&utm_source=product&utm_medium=link&utm_campaign=IU&utm_content=2022.2

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to IntelliJ Rainbow Brackets / Zhang Zhihao
Subscription is active until February 3, 2022.
For non-commercial open source development only.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: ide.tooltip.initialDelay=900, ide.balloon.shadow.size=0, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: com.intellij.properties.bundle.editor (212.4746.57), com.markskelton.one-dark-theme (5.3.0), lermitage.intellij.extra.icons (1.59.0.203), org.nik.presentation-assistant (1.0.9), kotest-plugin-intellij (1.1.36-IC-2021.1), Pythonid (212.4746.96), org.intellij.scala (2021.2.15), izhangzhihao.rainbow.brackets (6.19), com.intellij.bigdatatools (212.4037.55)
Kotlin: 212-1.5.10-release-IJ4746.92
```

**Comment by izhangzhihao** [comment]
please use https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/pricing
