### ISSUE TITLE
Always highlight current scope/block in Indent-based languages

### ISSUE THREAD

**Issue by s5bug** [izhangzhihao/intellij-rainbow-brackets#2619]
## Your programming languages

Python (I mainly program in Scala, but I would _really_ like this for Python; I'm taking a course at the moment which requires Python usage and I have a hard time without this feature)

## Expected Behavior

The current scope lines are great, and work really well for me.

![image](https://user-images.githubusercontent.com/7751296/232674893-20f1aac0-64d8-4714-8a3b-8b891a73ac2a.png)

However, I recall having a plugin in the past that would do something like

![image](https://user-images.githubusercontent.com/7751296/232675267-8a5d5095-fffa-4473-816f-35fd01f43001.png)

![image](https://user-images.githubusercontent.com/7751296/232675450-560664db-ce8e-41c9-a68d-57e877aa4f05.png)

I no longer seem to be able to find it, but I think it fits in pretty well with this plugin's Highlight Scope feature, so I've requested it here.

--

I use this plugin as a student, and it really helps my coding efficiency. Thank you for continuing to develop it!

**Comment by s5bug** [comment]
![image](https://user-images.githubusercontent.com/7751296/232675875-37cf153f-4cc5-4d32-9294-7bc2e25f021c.png)

**Comment by byTangs** [comment]
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/34257233/9d324c7f-9c1a-4f24-96e0-2f76945eff37)

同样的问题，Rider 2023.1.2 C++ 中不起作用

**Comment by izhangzhihao** [comment]
> ![image](https://user-images.githubusercontent.com/34257233/239413813-9d324c7f-9c1a-4f24-96e0-2f76945eff37.png)
> 
> 同样的问题，Rider 2023.1.2 C++ 中不起作用

Hi, this is a feature request. Are you requesting the same feature or reporting a bug?

**Comment by izhangzhihao** [comment]
Similar with https://github.com/dima74/intellij-indent-rainbow/issues/24

**Comment by izhangzhihao** [comment]
Hi, please try this https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2644

**Comment by s5bug** [comment]
(Sorry for not replying: Haven't had the time to test. Looks good from the screenshots, though)
