### ISSUE TITLE
Setting to disable the changelog after update

### ISSUE THREAD

**Issue by rlnt** [izhangzhihao/intellij-rainbow-brackets#2620]
## Expected Behavior
Don't open a window with the changelog after the plugin updates. Or at least add a setting for it.

## Current Behavior
It opens a window with the changelog after updating.

**Comment by izhangzhihao** [comment]
Please follow https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/279#issuecomment-694782959

```xml
<application>
  <component name="RainbowSettings">
    <option name="showNotificationOnUpdate" value="false" />
  </component>
</application>
```

The config path is here: https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path

**Comment by rlnt** [comment]
Well, it's marked a closed, that's why I made a new one.

**Comment by izhangzhihao** [comment]
Did you follow the comment to config?

**Comment by izhangzhihao** [comment]
it's closed because it already supposed
