### ISSUE TITLE
How do you change colors for XML/HTML tags?

### ISSUE THREAD

**Issue by ahait** [izhangzhihao/intellij-rainbow-brackets#2623]
it's not possible with current UI.
Editor just selects something standard, even after I changed all the colors for all the other kind of brackets in the settings.

**Comment by izhangzhihao** [comment]
Change the colors by:
<img width="982" alt="image" src="https://user-images.githubusercontent.com/12044174/234530510-e56686a4-655a-455c-8cf0-d1f42fb6d0af.png">


Or if you want a random color pattern:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/12044174/234530629-1d5d418a-1cab-466b-b333-749959faf510.png">
