### ISSUE TITLE
已经是付费了, 设置里面还是显示paid feature

### ISSUE THREAD

**Issue by sinict** [izhangzhihao/intellij-rainbow-brackets#2627]
<img width="955" alt="截屏2023-05-04 09 24 31" src="https://user-images.githubusercontent.com/26921154/236088092-fb642991-56c5-4920-944b-a152a9ab9d71.png">

<img width="746" alt="截屏2023-05-04 09 25 42" src="https://user-images.githubusercontent.com/26921154/236088128-cc9eb1ff-4972-488e-af0f-0ec8e57a2f2b.png">

IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Build #IU-223.8836.41, built on March 10, 2023
Subscription is active until July 17, 2023.
Runtime version: 17.0.6+1-b653.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    com.nasller.CodeGlancePro (1.6.0)
    com.alayouni.ansiHighlight (22.3.5)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.dubreuia (2.3.0)
    String Manipulation (9.7.1)
    org.jetbrains.kotlin (223-1.8.21-release-380-IJ8836.35)
    MavenRunHelper (4.23.222.2964.0)
    izhangzhihao.rainbow.brackets (2023.2.7)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    com.mallowigi (85.1.0)
    mobi.hsz.idea.gitignore (4.4.4)
    de.endrullis.idea.postfixtemplates (2.16.2.223)
    com.ccnode.codegenerator.MyBatisCodeHelperPro (3.1.9)
    cn.yiiguxing.plugin.translate (3.4.2)

Kotlin: 223-1.8.21-release-380-IJ8836.35

**Comment by izhangzhihao** [comment]
Hi, thanks for supporting Rainbow Brackets, for how to config the numbers of the colors, please visit https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2628#discussioncomment-5798106
