### ISSUE TITLE
Highlighting round brackets

### ISSUE THREAD

**Issue by ghost** [izhangzhihao/intellij-rainbow-brackets#2632]
I purchase Rainbow brackets for a JetBrains Rider, but the highlighting for a round bracket doesn't work correctly.

When start a Rider its all work fine, but when I edit a .cs file the highlighting sets the same first color for all round brackets.

After starting a Rider - ![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/61457866/41b3ebed-e3c7-4740-b461-b52c430d5b75)
After editing a .cs file -
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/61457866/9efbc7b0-c980-40a6-9d68-ca5871607122)

**Comment by izhangzhihao** [comment]
Known issue #2569

**Comment by izhangzhihao** [comment]
Closed for duplicated with #2569
