### ISSUE TITLE
Paid feature does not enable after purchasing plugin plan

### ISSUE THREAD

**Issue by ImtiazEpu** [izhangzhihao/intellij-rainbow-brackets#2636]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) and [discussions](https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions) before creating one.

## Please check

- [x] I already support this project.
- [x] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [ ] This issue/feature request is not reported before.

## Your programming languages
PHP
## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
The paid feature does not enable after purchasing the plugin plan.
![CleanShot 2023-05-24 at 13 05 07](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/27789950/c8ed9848-213e-4c0c-92b6-a262a4011c30)

![CleanShot 2023-05-24 at 12 51 44](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/27789950/f87459db-9267-487d-9ccb-f71b6bcc97c1)

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
PhpStorm 2023.1.2
Build #PS-231.9011.38, built on May 17, 2023
Licensed to Imtiaz Epu
Subscription is active until December 5, 2023.
For educational use only.
Runtime version: 17.0.6+10-b829.9 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 4
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6a737d
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6a737d

Non-Bundled Plugins:
    com.paperetto.dash (3.3)
    com.faebeee.vuecomponentcreator (2.7.3)
    com.intellij.ideolog (203.0.30.0)
    lermitage.intellij.extra.icons (2023.2.4-231)
    com.alayouni.ansiHighlight (23.1.0)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.3.1)
    de.beyondco.tinkerwell.tinkerwell (2.5.0)
    com.laravel_idea.tailwind (1.4.1)
    izhangzhihao.rainbow.brackets (2023.2.7)
    fr.adrienbrault.idea.symfony2plugin (2022.1.250)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
    com.dmarcotte.handlebars (231.8770.3)
    tv.twelvetone.intellij.plugins.intellivue (1.1.32)
    com.laravel_idea.plugin (7.1.1.231)
    com.mallowigi (90.0.0)
```

**Comment by izhangzhihao** [comment]
hi, you need increase the number of colors to 10 at settings -> rainbow brackets -> number of colors

**Comment by ImtiazEpu** [comment]
Thank you so much.
