### ISSUE TITLE
Option to only supply colored indent guides if currently highlighted

### ISSUE THREAD

**Issue by Frosthaven** [izhangzhihao/intellij-rainbow-brackets#2637]
I played with the default IDE settings, color scheme settings, and "other options" settings for this and couldn't quite get what I was hoping for. If I missed something, let me know!

## Please check

- [x] current subscriber
- [x] This issue/feature request is not reported before.

## Your programming languages
Typescript, PHP, Javascript, React, Svelte

## Expected Behavior
I'd like the ability to keep my default indent guide colors *UNLESS* they should be highlighted by this plugin. This is because I generally have my guides very subdued and only really care about the current block.

## Current Behavior
Currently, all guides are given rainbow colors AND will highlight as those colors.

## Code examples

Currently:
![current](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5412207/2d330a0d-4c29-410c-a9c1-df4b884dc655)

Preferred:
![preferred](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5412207/a1038a90-3529-4ca0-82cc-048701ff9baf)

**Comment by izhangzhihao** [comment]
Great idea! Let's call it the Focus mode.

<img width="859" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/99e7753a-98ea-45e3-b584-3da359e07929">

<img width="1233" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/9808dbae-93ea-4a8b-857c-fd7dfb50710b">

**Comment by Frosthaven** [comment]
This is perfect!
