### ISSUE TITLE
Settings don't persist across IDE restarts; and color generator hue/luminosity doesn't happen (paid version)

### ISSUE THREAD

**Issue by david-bakin-sl** [izhangzhihao/intellij-rainbow-brackets#2640]
## Please check

- [ ] I already support this project.
- [x] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [x] This issue/feature request is not reported before.

## Your programming languages

Java, JSON, Protobuf (not supported by R.B.), TypeScript/JavaScript, YAML

## Expected Behavior

**Have color generator settings work and persist over IntelliJ restarts**

## Current Behavior

Color generator settings for hue and luminosity are not persisted across restarts (licensed copy of Rainbow Brackets).

I start at this point (with paid license activated) color generator is active, hue is set to "random" and luminosity to "auto":

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/117694041/e82692d8-ebd9-459d-bfbf-d1481f898bcf)

Now I set the color generator hue to "orange" and luminosity to "bright" - but notice that even though I changed settings "Apply" button doesn't get enabled:

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/117694041/db20ddae-045d-4a93-a2a0-20f540b05957)

But I hit "OK" anyway and there's really no change in coloring:

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/117694041/25170ba6-7caa-4eb0-a84d-812636f1b75f)

But that's ok, it warned me I needed to restart, so I quit IntelliJ and launch it again. I wait until it is done scanning its index, etc., and see ... no change in bracket colors.  So I open the settings and find:

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/117694041/11ad7607-9b4f-4103-9de0-94981e2e7dd4)

Color generator hue is back at "random" and luminosity at "auto".

(I also tried the following:  Having the idea that if the "Apply" button wasn't enabled perhaps the dialog-box code didn't understand that those particular settings had changed so didn't save them when hitting "OK".  So I changed a different setting ("Rainbowify Python keywords") to get the "Apply" button enabled, _then_ hit "OK", _then_ restarted.  But the settings were still not persisted.)

P.S. I haven't actually used the color generator feature before.  Just turned it on after activating the license.  So don't know how it really works.  But it doesn't _appear_ to work.

## Your Environment

* MacOS 13.4
* IntelliJ IDEA 2023.1.2 (ultimate).  (Runtime version: 17.0.6+10-b829.9 aarch64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o) 
* Rainbow Brackets 2023.2.11

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/117694041/792987bb-c612-4c03-8588-704f43a30d2e)

```
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 15, 2023
Licensed to Swirlds Labs. / David Bakin
You have a perpetual fallback license for this version.
Subscription is active until May 22, 2024.
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Registry:
    debugger.new.tool.window.layout=true
    debugger.valueTooltipAutoShowOnSelection=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    intellij-awk (0.4.0)
    com.intellij.ideolog (203.0.30.0)
    com.kikimanjaro (0.0.4)
    com.github.ragurney.spotless (2.0.0)
    google-java-format (1.16.0.2)
    PlantUML integration (6.1.0-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.38.17)
    me.serce.solidity (2.4.1)
    com.nekofar.milad.intellij.hardhat (1.2.19)
    org.sonarlint.idea (8.3.0.71062)
    izhangzhihao.rainbow.brackets (2023.2.11)
    dev.arunkumar.scabbard.idea-plugin (0.5.0)

Kotlin: 231-1.8.21-IJ9011.34
```

**Comment by izhangzhihao** [comment]
I just tested it in my env and it works, did you click the "Apply" or "Save" button after the config changed?
<img width="970" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/373b9d3d-e0de-4b5a-a5b4-1b0451c1e553">


my env:

```
IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.7295.16, built on June 9, 2023
Licensed to IntelliJ IDEA EAP user: Zhang Zhihao
Expiration date: July 9, 2023
Runtime version: 21+9-b126.4 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    ide.plugins.snapshot.on.unload.fail=true
    ide.tooltip.initialDelay=900
    ide.experimental.ui=true
    ide.balloon.shadow.size=15
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    PsiViewer (232.2-SNAPSHOT)
    com.jetbrains.gerryThemesPro (2023.1.52)
    com.github.copilot (1.2.8.2631)
    com.github.izhangzhihao.intellijgooglesearch (0.0.2)
    org.nik.presentation-assistant (1.0.10)
    String Manipulation (9.9.0)
    com.virtuslab.git-machete (4.0.0)
    com.intellij.bigdatatools.core (232.7295.16)
    com.intellij.bigdatatools.kafka (232.7295.16)
    com.intellij.bigdatatools.binary.files (232.7295.16)
    com.intellij.bigdatatools.rfs (232.7295.16)
    Pythonid (232.7295.16)
    org.intellij.scala (2023.2.5)
    izhangzhihao.rainbow.brackets (2023.2.11)
    com.mallowigi (90.0.0)
    zielu.gittoolbox (500.0.10+213)
Kotlin: 232-1.8.21-release-380-IJ7295.16
```

**Comment by izhangzhihao** [comment]
I see, you can try just click the "Ok" button.

**Comment by izhangzhihao** [comment]
Closed for no update, if this issue still persists, please leave a comment.

**Comment by jonaswouters** [comment]
I can reproduce this issue as well.

I had to disable "Reopen projects on startup" in system settings, or it would reset this feature back to "random/auto" because the licence seems to be picked up after the plugin is started.  I always got the paid version pop-up after changing these settings and restarting the IDE.  

After disabling the option, I was able to persist these settings. 

Tried with GoLand and WebStorm, both had this issue.

**Comment by izhangzhihao** [comment]
Please try this build snapshot: 
[intellij-rainbow-brackets-2023.3.1.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12090203/intellij-rainbow-brackets-2023.3.1.zip)

**Comment by jonaswouters** [comment]
the new snapshot build fixes the issue!

1. I tried with the version from the marketplace: issue persists
2. Installed snapshot, changing settings multiple times: works without issues
3. Uninstalled completely and reinstalled marketplace version: Issue is back.
4. Disabled automatic project opening with marketplace version: Issue solved again.

**Comment by izhangzhihao** [comment]
A new release will be available within two business days. 🎉
