### ISSUE TITLE
Different colors for the same variable in GoLand

### ISSUE THREAD

**Issue by vistart** [izhangzhihao/intellij-rainbow-brackets#2641]
Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.3/README.md) and [discussions](https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions) before creating one.

## Please check

- [ ] I already support this project.
- [ ] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [x] This issue/feature request is not reported before.

## Your programming languages
Go

## Current Behavior
* Different colors for the same variable.
In the image below, the variables `results` and `wg` are colored differently in the coroutine.
<img width="707" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/864657/d5eaace3-e53e-49ee-951e-3ba21b9d820d">

## Expected Behavior
* Within a coroutine, the same variable is marked with the same color.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.

## Code snippet for reproduce (for bugs)
[rhosocial/go-dag](https://github.com/rhosocial/go-dag/blob/59fd039ffe146677e709dd842bb0377ba970f88b/main.go#L219)

## Your Environment

* Plugin version: 2023.2.11
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
GoLand 2023.1.2
Build #GO-231.9011.34, built on May 16, 2023

Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
    suggest.all.run.configurations.from.context=true
    debugger.new.tool.window.layout=true
    ide.completion.variant.limit=500
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (231.9011.41)
    com.jetbrains.php.framework (231.9011.41)
    com.mzyupc.a-redis (beta-0.9.0)
    com.intellij.javafx (1.0.4)
    com.intellij.tasks (231.8770.3)
    com.intellij.zh (231.283)
    com.huangmb.idea (1.1)
    org.rust.lang (0.4.196.5423-231)
    org.toml.lang (231.8109.91)
    com.intellij.apacheConfig (231.9011.41)
    dal-mpe (1.283.2305)
    com.tang (1.4.7-IDEA231)
    com.jetbrains.edu (2023.5-2023.1-646)
    IdeaVIM (2.3.0)
    generatedsoft.mps.xmlph (1.0)
    com.intellij.ideolog (203.0.30.0)
    com.markskelton.one-dark-theme (5.8.0)
    com.godwin.json.parser (1.4.1)
    String Manipulation (9.9.0)
    Key Promoter X (2023.1.0)
    com.jetbrains.twig (231.9011.41)
    org.jetbrains.erlang (0.11.1197)
    com.wakatime.intellij.plugin (14.1.5)
    GrepConsole (12.18.211.6693.0)
    com.intellij.kubernetes (231.9011.4)
    PlantUML integration (6.2.2-IJ2022.2)
    Dart (231.9065)
    izhangzhihao.rainbow.brackets (2023.2.11)
    org.exbin.deltahex.intellij (0.2.8.1)
    com.github.jk1.ytplugin (2023.1.38)
    net.seesharpsoft.intellij.plugins.csv (3.2.0-231)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.0)
    ru.adelf.idea.dotenv (2023.1)
    cn.yiiguxing.plugin.translate (3.5.0)
    com.intellij.plugins.html.instantEditing (231.8770.15)

```

**Comment by izhangzhihao** [comment]
Hi, the feature 'Rainbow Variables for Go' comes from the 'Semantic Highlighting for Go', a built-in IDE GoLand feature. So you should report this issue to GoLand [here](https://youtrack.jetbrains.com/issues/GO).
