### ISSUE TITLE
Rainbow Variables not correctly identifying Typescript Class variables and Dependency Injection variables inside methods

### ISSUE THREAD

**Issue by absantanna2412** [izhangzhihao/intellij-rainbow-brackets#2642]
## Please check

- [ ] I already support this project.
- [X] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [X] This issue/feature request is not reported before.

## Your programming languages
Angular 9.0

## Expected Behavior
Class and Dependency Injection variables must have the same color inside method as they are when we are declaring them.

## Current Behavior
Class Variables are correctly _Rainbowfied_, but when I use it inside any methods I need to put **this.** in front of the variable and now the plugin does not work, and the variables receives a standard color. 
The same happens with Dependency Injection variables.

## Possible Solution
Not a clue.

## Code snippet for reproduce (for bugs)
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/20236895/d5cc1eac-8292-495f-a02c-df29ba86409c)
```
import {Injectable, OnInit} from '@angular/core';
import {MenuItem} from 'primeng';
import {Subject} from 'rxjs';

@Injectable()
export class TestService {
    private itemsSource = new Subject<MenuItem[]>();
    setItems(items: MenuItem[]) {
        this.itemsSource.next(items);
    }
}

export class TestClass implements OnInit {
    loading = false;
    processing = false;
    constructor(private testService: TestService) {
        this.processing = true;
        this.testService.setItems([{label: 'Demonstrativo Editor'}]);
    }
    ngOnInit() {
        this.loading = true;
    }
}
```
## Your Environment

* Plugin version: 2023.2.11
```
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Alexandre Sant'Anna
Subscription is active until June 23, 2023.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (231.8109.91)
    com.intellij.ideolog (203.0.30.0)
    com.crunch42.openapi (1.56)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    com.intellij.properties.bundle.editor (231.8109.91)
    org.jetbrains.plugins.go (231.9011.4)
    com.tabnine.TabNine (1.0.16)
    com.samdark.intellij-visual-studio-code-dark-plus (2.7)
    String Manipulation (9.9.0)
    com.chylex.intellij.inspectionlens (1.3.0)
    com.intellij.jsf (231.8109.90)
    izhangzhihao.rainbow.brackets (2023.2.11)
    com.intellij.javaee.batch (231.8109.90)
    com.ifengxue.plugin.jpa-support (2.1.0-RC3)
    com.haulmont.jpab (2023.2.4-231)
    tv.twelvetone.intellij.plugins.intellivue (1.1.32)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.0)
    com.intellij.spring.batch (231.8770.17)

Kotlin: 231-1.8.21-IJ9011.34
```

**Comment by izhangzhihao** [comment]
Hi, the feature 'Rainbow Variables for TypeScript' comes from the 'Semantic Highlighting for TypeScript', a built-in IDE WebStorm feature. So you should report this issue to WebStorm [here](https://youtrack.jetbrains.com/issues/WEB).

**Comment by absantanna2412** [comment]
I`ve paid for your plugin and I hoped a better support.

The Semantic Highlighting for TypeScript does not colorize Class variables or Dependency Injection variables, your plugin does! 

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/20236895/6720947f-464c-4fcc-b168-398345f74ffd)

Look at the same file with your plugin turned off.

So, if your plugin colorizes the variables it should colorizes in all places. Or not colorize at all.

**Comment by izhangzhihao** [comment]
Ok, good to know, can you highlight the difference between the two screenshots? I can look into this later.

**Comment by absantanna2412** [comment]
Hi Thanks.

With your plugin turned on, I`ve the the **loading** and **processing** class variables colorized, the **testService** injection also colorized (red arrow), but not colorized inside methods (yellow arrows)

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/20236895/9879af30-d43c-49ef-bc43-383129be2b72)

But when I turn the plugin off, the variables stay in the _Semantic Highlighting for TypeScript_ default color. Same color red and yellow arrows.

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/20236895/1d486965-6938-48f2-8a79-1df10c0e5264)

If you are not able to colorize the variable usage inside methods, I think you shouldn't colorize at declaration.

Hope this helps.

Best.

**Comment by izhangzhihao** [comment]
Hi, I tested these two cases:

- disable color generator for rainbow variables, the issue still persists
- disable the plugin Rainbow Brackets, the issue still persists(With the IDE built-in `Semantic Hightlinght` enabled)

<img width="450" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/4cfa64d4-651e-4f92-9e5e-1f8a81d29cb3">

<img width="866" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/9f1983d1-67a5-4e58-ae0b-7e3e2ca3f33b">

<img width="860" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/71a2f3b0-f41f-4fd2-97be-8c9b39ba26da">

So, I can say this issue is not because of this plugin, I already reported a [YouTrack](https://youtrack.jetbrains.com/issue/WEB-61625/Semantic-Highlighting-not-correctly-identifying-Typescript-Class-variables-and-Dependency-Injection-variables-inside-methods) ticket for JetBrains, we can follow up there.

Thanks again for reporting issues.
