### ISSUE TITLE
Adjustable Scope highlighting intensity

### ISSUE THREAD

**Issue by ZipBrandon** [izhangzhihao/intellij-rainbow-brackets#2649]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

## Please check

- [x] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
Python, TypeScript

## Expected Behavior
* Ability to reduce intensity of the scope highlighting

## Current Behavior
* The ability to lessen the intensity of the colors.  Rainbow Indent has this and I confusedly misfiled a feature request for them 😁: https://github.com/dima74/intellij-indent-rainbow/issues/60

**Comment by izhangzhihao** [comment]
does 'Broder  Highlight' makes you happy?

https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2644#discussioncomment-6459959

**Comment by izhangzhihao** [comment]
Closed for no update.
