### ISSUE TITLE
Rainbow indent at yaml file

### ISSUE THREAD

**Issue by schrek1** [izhangzhihao/intellij-rainbow-brackets#2651]
## Please check

- [x] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ ] This issue/feature request is not reported before.

## Your programming languages

yaml

## Expected Behavior
add option for enable rainbow indent in yaml files too, it is useful for better moving with tabulator in line

## Current Behavior
* only coloring keys by idents, but it enought when I move by tabulator...

## Code examples
* provide your code examples so I could start doing faster

**Comment by schrek1** [comment]
I must supply by other plugin:

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/17483576/3f6ca637-f724-48ae-9289-3abfa144fb0e)

**Comment by izhangzhihao** [comment]
Pls update to the latest version.

**Comment by schrek1** [comment]
looks good, thanks
