### ISSUE TITLE
Disable "What's new in Rainbow Brackets" via IDE configuration

### ISSUE THREAD

**Issue by TheDevMinerTV** [izhangzhihao/intellij-rainbow-brackets#2652]
## Please check

- [x] This issue/feature request is not reported before.

## Your programming languages

TypeScript, Golang, Java

## Expected Behavior

- Enable setting in configuration
- When the plugin updates, it won't pop up with the "What's new in Rainbow Brackets" page

## Current Behavior

- When the plugin updates, it always pops up the "What's new in Rainbow Brackets" page

**Comment by izhangzhihao** [comment]
Duplicated with https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2621

**Comment by TheDevMinerTV** [comment]
It's not reflected in the UI though.
