### ISSUE TITLE
Add strength of effect slider for the "current scope highlight options".

### ISSUE THREAD

**Issue by jjchmielowiec** [izhangzhihao/intellij-rainbow-brackets#2653]
## Please check

- [X] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [X] This issue/feature request is not reported before.

## Your programming languages
Irrelevant for this feature.

## Expected Behavior
* When using the "Current Scope Highlighting" allow the user to be able to control the strength of the effect.
For Example: I find the all of the modes to be too extreme and would like to be able to turn the strength of the highlighting down to about maybe 20% of what it is. As is the highlighting makes the underlying code harder to read. 
* I also really like the restrain option but it dims the out of scope text too much. I want to have my attention focused on the scope I am in but also would like to be able to more easily read the other code. Ideally the code outside the scope would retain its color but just be dimmed by an adjustable amount.
* The border is also much too bright and I find it constantly distracting. 

## Current Behavior
* The strength of the effect is too strong leading to eye discomfort and a dislike for using the scope highlighting despite finding it to be a very useful tool.

## Code examples
* None, just add a slider or percentage box that controls how extreme these effects are, You already must be selecting the colors for the highlighting and how dim the restrained text is.

**Comment by izhangzhihao** [comment]
<img width="1018" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/37cc25ca-4c1d-4881-8ab0-08e611d7425e">

**Comment by jjchmielowiec** [comment]
Sorry for the late reply, this works great and makes the feature much nicer
to use.  The one potential improvement would be to also add a similar
feature to the restrain option but I realize this is likely a
more complicated task.

**Comment by izhangzhihao** [comment]
For the restrain, I added a new option as well, just not released yet. It will happen in the next release.
