### ISSUE TITLE
Different variables get the same colors

### ISSUE THREAD

**Issue by jansviland** [izhangzhihao/intellij-rainbow-brackets#2655]
## Current Behavior

![bilde](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/114911422/7f111595-6575-4aa0-a91f-085d16d493a0)

As you can se different variables get the same colors, even when they are right after each other. This kind of defeats the point of this plugin. 

## Your Environment

```
JetBrains Rider 2023.2
Build #RD-232.8660.212, built on July 31, 2023
Licensed to xxxxxxx
Subscription is active until May 24, 2024.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET Core v7.0.7 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4082M
Cores: 12
Registry:
    ide.experimental.ui=true
    ide.new.project.model.index.case.sensitivity=true
    database.show.search.tab=false
    vcs.empty.toolwindow.show=false

Non-Bundled Plugins:
    com.intellij.javafx (1.0.4)
    Batch Scripts Support (1.0.13)
    com.intellij.resharper.HeapAllocationsViewer (2023.2.0)
    IdeaVIM (2.4.1)
    org.intellij.plugins.hcl (232.8660.88)
    com.github.copilot (1.2.21.2995)
    avalonia-rider (1.1.0)
    nsubstitutecomplete-rider (1.10.0)
    com.intellij.ideolog (222.1.0.0)
    com.markskelton.one-dark-theme (5.8.0)
    fr.socolin.application-insights-debug-log-viewer (1.9.0)
    krasa.CpuUsageIndicator (1.17.2023)
    com.intellij.resharper.StructuredLogging (2023.2.0.305)
    com.samdark.intellij-visual-studio-code-dark-plus (2.8)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.intellij.kubernetes (232.8660.158)
    me.seclerp.rider.plugins.efcore (232.0.0-rc1)
    com.intellij.bigdatatools.core (232.8660.206)
    com.intellij.bigdatatools.binary.files (232.8660.206)
    com.intellij.bigdatatools.rfs (232.8660.206)
    com.intellij.ml.llm (232.9613)
    com.intellij.resharper.azure (3.50.0.1664-2023.2)
    izhangzhihao.rainbow.brackets (2023.3.3)

```

**Comment by izhangzhihao** [comment]
Can you show me your color setting page?  like this
<img width="1119" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/b47a7f72-82d8-4112-8dc8-2c2c6ccf0b4f">

**Comment by jansviland** [comment]
![bilde](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/114911422/5b616326-2bd2-4824-90d9-c775b815e96e)

I also tried 

![bilde](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/114911422/4aff948d-be3f-443d-8af8-56b9a16beb51)

Same result, just different colors

**Comment by izhangzhihao** [comment]
This situation will rarely happen if you change the hue option to "random". Considering that the color is limited to a small range, the same or similar colors will inevitably appear in the generation, which is difficult to avoid completely.
