### ISSUE TITLE
Add match-case highlighting for Python

### ISSUE THREAD

**Issue by srazumov** [izhangzhihao/intellij-rainbow-brackets#2657]
## Please check

- [x] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M)
- [x] This issue/feature request is not reported before.

## Your programming languages
* Python (match-case introduced in 3.11)

## Expected Behavior
* Highlighting for the match case as for nested conditions, or at least fix the indentation highlighting in the match block.

## Current Behavior
* Currently, match-case is not highlighted and has a default color. Indents are not highlighted in the match block.

## Code examples
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/75245733/f8b662bd-fa13-433d-9f83-aa3e2bd0e9e0)

**Comment by izhangzhihao** [comment]
Pls update to the latest version.
