### ISSUE TITLE
Show generated rainbow variables colors in the color scheme page

### ISSUE THREAD

**Issue by jansviland** [izhangzhihao/intellij-rainbow-brackets#2660]
## Expected Behavior

For the other options, random colours are generated, but for variables it is not set to 10 different colours and they are not generated. 

## Current Behavior

https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/114911422/69739160-5a5d-421a-9dcc-f5289a0370b1

**Comment by izhangzhihao** [comment]
The five colors displayed here directly showcase the IDE's five basic built-in color schemes. The IDE will generate 20 colors based off of these five colors. If you select to use the random color generator to generate colors, the five basic color schemes will not be applied. Instead, the generator will generate 20 colors directly. It is true that the 20 colors generated for practical use are not displayed here.

**Comment by izhangzhihao** [comment]
Related to https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2576

**Comment by izhangzhihao** [comment]
Please try this build snapshot: 
[intellij-rainbow-brackets-2023.3.4.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12565622/intellij-rainbow-brackets-2023.3.4.zip)
