### ISSUE TITLE
YAML tags don't get rainbowified

### ISSUE THREAD

**Issue by mikybars** [izhangzhihao/intellij-rainbow-brackets#2661]
## Please check

I already paid for this plugin.

## Expected Behavior

I expect to have YAML tag names coloured as in https://github.com/izhangzhihao/intellij-rainbow-brackets?utm_source=product&utm_medium=link&utm_campaign=IU&utm_content=2023.2#yaml

## Current Behavior

My `application.yml` file (Spring Boot) is coloured as if the config option wouldn't be checked:
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/43891734/184e250a-e0cd-491a-bb22-681af08081b0)

## Code snippet for reproduce (for bugs)

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/43891734/73d0d5b0-2d1e-44ce-99ed-ed247efc5ac5)

## Your Environment

```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to Miguel Ibars
Subscription is active until September 12, 2023.
Evaluation purpose only.
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    manjaro.mpb (1.8)
    net.sf.opk.avro-schema-support (213.5.2)
    IdeaVIM (2.4.1)
    com.github.copilot (1.2.21.2995)
    com.jetbrains.packagesearch.intellij-plugin (232.8660.142)
    izhangzhihao.rainbow.brackets (2023.3.4)
    org.mapstruct.intellij (1.6.1)

Kotlin: 232-1.9.0-IJ8660.185
```

**Comment by izhangzhihao** [comment]
Please check:

- Did you have the YAML plugin installed and enabled?
- Try edit the YAML file
- try the 'Overwrite file type' to yaml in IDE  
<img width="553" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/ebdef4f6-c1fb-46aa-b306-c397cee9e266">

- check your license status: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2630

**Comment by mikybars** [comment]
YAML plugin installed and enabled

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/43891734/81ceade8-78a4-4ce9-b421-20eab1475b00)

I overrode the file type to YAML and nothing happened

My license status

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/43891734/5a95f74e-6568-4db2-aa87-bbb137bb36be)

**Comment by izhangzhihao** [comment]
Did an IDE restart help? or add a new line to the YAML file and remove it (to trigger the IDE refresh the highlighting)

**Comment by mikybars** [comment]
I did both and still no results

**Comment by izhangzhihao** [comment]
Please check this, make sure `yaml` is not here 
<img width="1058" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/ab683d2c-f8d1-48c5-b9b8-152584c2270f">

Or, please try uncheck the "Rainbowify yaml tag name" and "Save" and "Close" And open the setting and check it again, after that, please try edit your yaml files.

**Comment by mikybars** [comment]
Didn't work

**Comment by izhangzhihao** [comment]
By the way, did other paid features works or not?

**Comment by mikybars** [comment]
Indent guides highlight is NOT working either.
Current scope highlight IS working 🤷🏾

**Comment by izhangzhihao** [comment]
Indent guides highlight did not work might because you didn't check the option. In your first screenshot the indent guide highlights option is not checked.

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/43891734/73d0d5b0-2d1e-44ce-99ed-ed247efc5ac5)


edit, sorry I misread the screenshot.

**Comment by izhangzhihao** [comment]
Any update? Is the Rainbow yaml tag name still does not work for you?

**Comment by mikybars** [comment]
Nope. I even tried to create a new project from scratch and add a yml file.

**Comment by izhangzhihao** [comment]
Do you have other/older IDE installations? Can you try with other IDE instances?

**Comment by mikybars** [comment]
I tried with the Community Edition as well (same version though)

**Comment by abimarank** [comment]
I have the same issue in IntelliJ IDEA but working fine with PyCharm for the same project with the same account. I have a paid license for the plugin. @izhangzhihao 

Following are the details 

**IntelliJ IDEA**

```
IntelliJ IDEA 2023.2.1 (Community Edition)
Build #IC-232.9559.62, built on August 23, 2023
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.9559.64)
    com.andrey4623.rainbowcsv (2.0.2)
    com.godwin.json.parser (1.7)
    org.intellij.plugins.hcl (232.8660.88)
    idea.plugin.protoeditor (232.9559.10)
    Lombook Plugin (232.9559.34)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    String Manipulation (9.11.3)
    izhangzhihao.rainbow.brackets (2023.3.4)
    com.haulmont.jpab (2023.3.5-232)
    mobi.hsz.idea.gitignore (4.5.1)
    aws.toolkit (1.78-232)

Kotlin: 232-1.9.0-IJ9559.62
```

**PyCharm**

```
PyCharm 2023.2.1 (Community Edition)
Build #PC-232.9559.58, built on August 23, 2023
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.9559.64)
    com.andrey4623.rainbowcsv (2.0.2)
    com.godwin.json.parser (1.7)
    String Manipulation (9.11.3)
    org.intellij.plugins.hcl (232.8660.88)
    idea.plugin.protoeditor (232.9559.10)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    izhangzhihao.rainbow.brackets (2023.3.4)
    mobi.hsz.idea.gitignore (4.5.1)
    aws.toolkit (1.78-232)

```

**Comment by izhangzhihao** [comment]
ok, let me try with your envs and plugins.

**Comment by izhangzhihao** [comment]
Pls try this build snapshot: 
[intellij-rainbow-brackets-2023.3.4.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12607732/intellij-rainbow-brackets-2023.3.4.zip)

**Comment by izhangzhihao** [comment]
Please try this build snapshot and make sure your YAML plugin is enabled:

**Comment by mikybars** [comment]
Sorry but how am I supposed to install this new version?

**Comment by izhangzhihao** [comment]
> Sorry but how am I supposed to install this new version?

yes, please try and give me feedback.

**Comment by izhangzhihao** [comment]
Please follow this screenshot to install the build snapshot: (you don't need to unzip the file)
<img width="984" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/47f26996-b25e-4957-a3ee-d18e536d2036">

**Comment by mikybars** [comment]
Yes! It works like a charm now.

**Comment by abimarank** [comment]
Working fine now.
