### ISSUE TITLE
In Real-time-Data-Warehouse getting the error while inserting data in hudi. Please help

### ISSUE THREAD

**Issue by HarjeetSinghGoldy** [izhangzhihao/intellij-rainbow-brackets#2663]
https://github.com/izhangzhihao/Real-time-Data-Warehouse/issues/5

[INFO] Submitting SQL update statement to the cluster...
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassCastException: class org.codehaus.janino.CompilerFactory cannot be cast to class org.codehaus.commons.compiler.ICompilerFactory (org.codehaus.janino.CompilerFactory is in unnamed module of loader org.apache.flink.util.ChildFirstClassLoader @fd8294b; org.codehaus.commons.compiler.ICompilerFactory is in unnamed module of loader 'app')

**Comment by izhangzhihao** [comment]
Hi, this issue does not belong to this project, so I will close it.
