### ISSUE TITLE
Cannot disable pug files

### ISSUE THREAD

**Issue by satoshionoda** [izhangzhihao/intellij-rainbow-brackets#2664]
## Please check

- [x] I already paid for this plugin.
- [x] This issue/feature request is not reported before.

## Your programming languages
PUG

## Expected Behavior
Pug files are ignored since "Do NOT rainbowify" option is set.

## Current Behavior
rainbowify is enabled even though the option is set.
<img width="751" alt="CleanShot 2023-09-01 at 11 36 53@2x" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/4291354/6e641639-da43-43a7-af52-59dd949f47fc">

## Your Environment
<img width="725" alt="CleanShot 2023-09-01 at 11 38 16@2x" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/4291354/bd74296f-04aa-43e7-a8dc-efb82d5906a2">

**Comment by izhangzhihao** [comment]
Hi, please try this build snapshot

**Comment by satoshionoda** [comment]
@izhangzhihao 
Thanks! It's working as expected now.
