### ISSUE TITLE
Separate color schemes for Light and Dark modes

### ISSUE THREAD

**Issue by hirozed** [izhangzhihao/intellij-rainbow-brackets#2670]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

## Please check

- [x] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming languages
PHP

## Expected Behavior

* The colors will adjust colors when Intellij switches from light to dark when "Sync with OS" is selected.

## Current Behavior

* The color scheme for detected for a light theme will mostly not work on a dark color scheme.
* The only way to correct it is to restart Intellij

## Code examples
* My apologies, I don't have any code that I'm free to share.

**Comment by izhangzhihao** [comment]
Hi, I tested two cases:

1. Without enabling the Color Generator
<img width="1163" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/5b2083ad-b54a-4f50-bbcb-77fddca1e4bc">
and with the "Sync with OS" enabled, after switching the light/dark, the brace colors changed automatically without restarting the IDE.



2. With the Color Generator and the "Sync with OS" enabled, the brace colors do not change automatically after switching the light/dark.

**Comment by izhangzhihao** [comment]
I can make brackets automatically updated after switching light/dark, but for Rainbow Variables, there is still an open issue from JB: [Incorrect Semantic Highlighting colors when switching to dark mode](https://youtrack.jetbrains.com/issue/IDEA-281281/Incorrect-Semantic-Highlighting-colors-when-switching-to-dark-mode)

And do please try this build snapshot

**Comment by hirozed** [comment]
Hi @izhangzhihao, 

Thank you for looking into this. I bounced around the settings with color generator activated and not, and it looked like the colors were changing with the theme, but it felt inconsistent. I'll stay with a single color theme and see if the next release solves things.
