### ISSUE TITLE
幾個問題

### ISSUE THREAD

**Issue by Sol-LZX** [izhangzhihao/intellij-rainbow-brackets#2674]
1.  pycharm 突然的發生所有key都變成灰色(if else finally等關鍵字)，我不確定是不是我設定的問題，但我不知道該如何設定，現在太多設定了，有沒有最簡單也最通用付費的設定可直接參考，並且包含多階層(之前發現到某一巢狀階層都會為灰色)
2. 無法使用reset 還原設定

```
PyCharm 2023.2.1 (Professional Edition)
Build #PY-232.9559.58, built on August 23, 2023
Licensed to Lin Zong-Sian
Subscription is active until October 12, 2023.
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.nasller.CodeGlancePro (1.7.5)
    com.hiberbee.intellij.hiberbee-theme (2023.9.24.2323)
    com.github.copilot (1.3.0.3323)
    com.mroche.JsonHelper (1.3.0)
    indent-rainbow.indent-rainbow (2.2.0)
    com.intellij.ml.llm (232.9826)
    izhangzhihao.rainbow.brackets (2023.3.5)
    com.mallowigi (93.1.0)
    zielu.gittoolbox (500.0.21+222)
    mobi.hsz.idea.gitignore (4.5.1)

```

**Comment by izhangzhihao** [comment]
Does this help? https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2665

Please provide your screenshots of the setting page

**Comment by Sol-LZX** [comment]
我沒有勾選1000行的選項，不過我想請教如何穩健的讓他自動產生色碼？

顏色的設定如下，我發現我只要再勾上use color generator ，所有的色碼全都灰色

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47168477/a60b40a7-951f-41c2-a16f-e404c8032857)


![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47168477/18f6f4b5-cd3b-4435-8fce-1fd7c6c1c438)

**Comment by izhangzhihao** [comment]
如果你刚刚修改了 number of colors, 你需要重新启动 IDE。
如果你想看生成的颜色，请勾选：show generated colors

**Comment by izhangzhihao** [comment]
pls try this build snapshot: 
[intellij-rainbow-brackets-2023.3.5.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12791825/intellij-rainbow-brackets-2023.3.5.zip)

**Comment by izhangzhihao** [comment]
你可以升级到最新 2023.3.6 版本，或者参考这里删除本地配置(如果你想重置到默认配置)https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path

**Comment by Sol-LZX** [comment]
感謝～我晚點回去試試～
