### ISSUE TITLE
Jinja2 Template support

### ISSUE THREAD

**Issue by nliechti** [izhangzhihao/intellij-rainbow-brackets#2677]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

## Please check

- [x] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Expected Behavior
* Support for Jinja2 Templates would be awesome, as you cannot indent the crontroll flow elements in the Templates.

## Current Behavior
* Currently no Rainbow is applied.

## Code examples

```
{% if item.nginx_locations|default('') != '' %}
{% for location in item.nginx_locations %}

    location {{ location.path }} {
{% for location_option in location.options | default([]) %}
{% if location_option|regex_search('.*({|})$') %}
        {{ location_option }}
{% else %}
        {{ location_option }};
{% endif %}
{% endfor %}
{% if location.options_block|default('') != '' %}
        {{ location.options_block | indent(8) }}
{% endif %}
{% if location.in_path|default('') != '' %}
        location {{ location.in_path }} {
{% for in_opts in location.in_options %}
            {{ in_opts }};
{% endfor %}
      }
{% endif %}
    }
{% endfor %}
{% endif %}
```

**Comment by izhangzhihao** [comment]
I spent several days trying to implement support for Jinja2 templates and found that IntelliJ's support for the Jinja2 template language PSI tree is quite limited. Calculating element hierarchy on my own was a bit challenging, and it was difficult to achieve correctness without built-in IDE support. After trying various workarounds, I have finally found what seems to be a viable implementation. Please install it and provide me with feedback.

<img width="676" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/7d181b85-4af8-4b20-a6df-ec28ab76231f">

If it does not work, please config your IDE as follows: https://stackoverflow.com/a/53168017

**Tested with Intellij 2020.3 and 2022.3 and 2023.2**

**Comment by nliechti** [comment]
Hey man. Thank you very much for the work you are doing. 

Seems to be working perfect on small to medium complex files. Large 150+ lines with dozens of if/for there seem to be some just left uncolored.

Doesn't bother me that much as it is "clearly" not working there and not wrongly colored.

Maybe we get better IDE Support in the future.

**Comment by izhangzhihao** [comment]
Just made some enhancements, and it looks great with HTML right now: 
<img width="642" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/59f2372b-554c-494b-8405-b665bbbbbb2f">
