### ISSUE TITLE
Goland highlighting only current indent guide options not working

### ISSUE THREAD

**Issue by trancong12102** [izhangzhihao/intellij-rainbow-brackets#2678]
## Please check

- [ ] I already support this project.
- [x] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [x] This issue/feature request is not reported before.

## Your programming languages
Golang
## Expected Behavior
* Only the current indent guide will be highlighted.

Expected behavior in webstorm:
![expected](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52101938/0033e8d2-d402-4677-a3b0-208ec3163119)

## Current Behavior
* All related indent guide colors lost.

![settings](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52101938/8cc07d1b-bf4c-4320-9451-c131dc2b5498)
![behaviour](https://s6.gifyu.com/images/S6jfo.gif)

## Code snippet for reproduce (for bugs)
```
	for _, detail := range st.Details() {
		if t, ok := detail.(*errdetails.BadRequest); ok {
			for _, violation := range t.GetFieldViolations() {
				list = append(list, models.FieldError{
					Field:       violation.GetField(),
					Description: violation.GetDescription(),
				})
			}
		}
	}
```	

## Your Environment

```
GoLand 2023.2.3
Build #GO-232.10072.27, built on October 11, 2023
Licensed to Tran Cong
Subscription is active until September 2, 2024.
For educational use only.
Runtime version: 17.0.8.1+7-b1000.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.github.catppuccin.jetbrains (2.2.0)
    com.github.copilot (1.3.2.3479)
    String Manipulation (9.11.3)
    Key Promoter X (2023.2.0)
    some.awesome (1.14)
    org.toml.lang (232.8660.88)
    com.jetbrains.space (232.10072.29)
    awesome.console (0.1337.12)
    com.intellij.grazie.pro (0.3.256)
    com.mallowigi (93.1.0)
    zielu.gittoolbox (500.0.21+222)
    mobi.hsz.idea.gitignore (4.5.2)
    izhangzhihao.rainbow.brackets (2023.3.6)
    ru.adelf.idea.dotenv (2023.2)
    cn.yiiguxing.plugin.translate (3.5.5)
```

**Comment by trancong12102** [comment]
@izhangzhihao I'm sorry for providing incorrect bug information. It seems like this bug has recently emerged because I didn't encounter it before when using WebStorm, but now I've noticed this issue occurring even in WebStorm.
![CleanShot 2023-10-17 at 00 23 02](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/52101938/56d0520f-e5f1-41fb-9017-9155102ca3ce)

**Comment by izhangzhihao** [comment]
I'm trying to reproduce it, but I haven't successfully reproduced it.


The code I'm using

```javascript
function Person() {

    const password = "123456"

    if (password) {
        this.a = password
    }
    
    setInterval(() => {
        this.age++;
    }, 1000);
}
```

<img width="770" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/ef9f686d-2f29-45d7-b111-68d4aad1add4">

**Comment by trancong12102** [comment]
When editing, all indent guides should not have color. Is this the normal behavior?

**Comment by izhangzhihao** [comment]
Can you set up a new project with minimal code to reproduce this issue?

**Comment by izhangzhihao** [comment]
closed for no update, if you still have issue please leave a comment.
