### ISSUE TITLE
Indent guides break once the contents of a scope is edited (non-structurally) and don't reappear until the file is closed and re-opened

### ISSUE THREAD

**Issue by shayded-exe** [izhangzhihao/intellij-rainbow-brackets#2682]
## Please check
- [ ] I already support this project.
- [x] I already paid for this plugin.
- [ ] I'm on a trial of this plugin.
- [x] This issue/feature request is not reported before.

## Your programming languages
C#

## Expected Behavior
The indent guides should update as the code is edited. At minimum they should update when the file is saved.

## Current Behavior
Editing the file causes indent guides in the current scope to disappear until the file is closed and reopened. Saving the file doesn't do anything.

Please see the below video:
https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/1417838/2e36230a-933e-4c15-affb-44d9d2448d7c

I've already tried invalidating caches and multiple restarts. It doesn't matter if I'm in distraction free mode or not.

## Possible Solution
🤷‍♂️ 

## Code snippet for reproduce (for bugs)
Any nested code

## Your Environment

* Plugin version: 2023.3.6
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
JetBrains Rider 2023.2.2
Build #RD-232.9921.83, built on September 24, 2023
Licensed to Ryan Shea
You have a perpetual fallback license for this version.
Subscription is active until September 1, 2024.
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET Core v7.0.7 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 16
Registry:
    lcd.contrast.value=200
    undo.documentUndoLimit=200
    folding.signature.validation=true
    undo.globalUndoLimit=20
    editor.scale.gutter.icons=false
    search.everywhere.structure=true
    navBar.show.icons=true
    search.everywhere.configurations=false
    editor.distraction.free.mode=true
    ide.navBar.v2=false
    new.search.everywhere.use.editor.font=true
    vcs.empty.toolwindow.show=false
    search.everywhere.footer.extended.info=true
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.intellij.resharper.HeapAllocationsViewer (2023.2.0)
    com.github.nicsilver.jumpertest (0.1.4)
    com.berzanmikaili.intellij.monokai_pro (2.0.2c)
    com.intellij.plugin.adernov.powershell (2.3.0)
    MultiHighlight (3.1.0)
    org.toml.lang (232.8660.88)
    io.github.frykher.jetbrains-kanagawa-theme (1.1.3)
    ca.rightsomegoodgames.GoldenRatio (1.1.0)
    izhangzhihao.rainbow.brackets (2023.3.6)
    AceJump (3.8.16)
    dev.lankydan.palenightintellijtheme (1.0.1)
    dev.feedforward.tldrintellij (0.0.2)
    com.hiberbee.intellij.hiberbee-theme (2023.10.29.1816)
    ski.chrzanow.foldableprojectview (2.0.0-EAP.1)
    com.clutcher.comments_highlighter (2023.8.2)
    artsiomch.cmake (232.1.1)
    com.mnw.tabmover (1.5.2)

Note that the theme I'm using is Kangawa.
I have Hiberbee installed but I'm not using it (I noticed there were some issues with it). I disabled it just to be sure it wasn't a factor.

**Comment by izhangzhihao** [comment]
Hi,can you upgrade to 2023.3.7?

**Comment by shayded-exe** [comment]
Thank you so much for fixing quickly!!! It was incredibly annoying
