### ISSUE TITLE
Not working on Clion Nova

### ISSUE THREAD

**Issue by MAXZVER** [izhangzhihao/intellij-rainbow-brackets#2684]
Not working on Clion Nova, tested on Ubuntu 23.10

**Comment by izhangzhihao** [comment]
pls provide more info.

**Comment by izhangzhihao** [comment]
I don't know which version you are using, pls upgrade to https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/436804

**Comment by datasone** [comment]
It seems the rainbow variables and indent guides related features (indent and scope highlight) are not functioning even with plugin version `2023.3.9-233` on C/CPP files.

These featuers works normally on CMake scripts in CLion Nova though.

**Comment by izhangzhihao** [comment]
> It seems the rainbow variables and indent guides related features (indent and scope highlight) are not functioning even with plugin version `2023.3.9-233` on C/CPP files.
> 
> 
> 
> These featuers works normally on CMake scripts in CLion Nova though.

The changes in Clion Nova are quite significant. The previous rainbow brackets can no longer be used. The new plugin version uses the same approach as Rider to support cpp (please note that the same functionality is paid in Rider). Considering that not everyone is familiar with the extent of the implementation changes in Clion Nova, and for better acceptance, the rainbow brackets for cpp remains free. As for rainbow variable and indent guideline support, it seems that Clion Nova is not yet ready, but it should be added in future updates.
