### ISSUE TITLE
Pipe / Closure for Rust

### ISSUE THREAD

**Issue by MikeMitterer** [izhangzhihao/intellij-rainbow-brackets#2685]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Rust

### Free or paid?

Paid users

### Expected Behavior

Pipe in Rust should be highlighted / colorized when used as Closure

### Code snippet for test

```rust
   let vec = vec![
        String::from("1 2 3"),
        String::from("4 5 6"),
        String::from("7 8 9"),
    ];

    println!("vec: {:?}", vec);

    let mapped1 : Vec<Vec<i32>> = vec.iter()
        .map(|input| { input.split_whitespace()
            .map(|s| s.parse::<i32>().unwrap())
            .collect::<Vec<i32>>() }
        ).collect();
```

### Your Environment

RustRover 2023.3 EAP
Build #RR-233.10527.39, built on November 4, 2023
Licensed to RustRover EAP user: Mike Mitterer
Expiration date: January 3, 2024
Runtime version: 17.0.8.1+7-b1072.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  editor.focus.mode.color.light=777777
  wolf.the.problem.solver=false
  debugger.new.tool.window.layout=true
  ide.animate.toolwindows=true
  documentation.show.toolbar=true
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.balloon.shadow.size=0
  editor.focus.mode.color.dark=777777
  jest.test.tree.use.jasmine.reporter=false
  js.debugger.webconsole=false
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (233.10527.39)
  com.markskelton.one-dark-theme (5.9.0)
  net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
  com.intellij.properties (233.10527.7)
  com.github.copilot (1.4.1.3828)
  String Manipulation (9.11.3)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  elegant-theme (1.1.20)
  ru.adelf.idea.dotenv (2023.3)
  com.github.aleksandrsl.intellijbrowserslist (1.0.2)
  izhangzhihao.rainbow.brackets (2023.3.9-233)
  org.jetbrains.plugins.docker.gateway (233.10527.39)

**Comment by izhangzhihao** [comment]
How would you like to highlight Rust's pipe and closure? Could you provide an example image, please? I'm not very familiar with Rust.

**Comment by izhangzhihao** [comment]
Closed because of no updates.
