### ISSUE TITLE
Why hasn't the color of the variable changed in my code

### ISSUE THREAD

**Issue by JonnyJiang123** [izhangzhihao/intellij-rainbow-brackets#2686]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

Java

### Free or paid?

Paid users

### Expected Behavior

According to the official demo, the variables, methods, and classes in my sample code should be different colors, but that's not the case at the moment. However, when I tried to develop a Go program using Goland, I found that the variables of Golang could change the presentation. At the same time, in IntelliJ Idea, there are different colors for the nodes in xml and html, but there is still no color for the variables in JavaScript.
<img width="1001" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/add101ca-f722-47a0-b77e-1a43a4e12ea6">

### Code snippet for test

<img width="920" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/3b04aa00-cf04-4cf2-857d-8e1c637d513a">

### Your Environment

<img width="320" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/7326e5ca-39b8-4c37-bff8-a1689ee98ae9">
<img width="777" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/ebef4f56-f7a0-46b5-b3b3-a3f7bdd545d3">
<img width="511" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/6feb42bf-f666-476a-bb9a-247bf0040aa3">
<img width="762" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/35ebda1f-24b3-45bb-8ed8-c73c88850f75">
<img width="784" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/981d6500-23b4-4e98-be01-63f3f2e37386">
<img width="709" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/efe13580-905c-4c6e-8688-abfe3365843e">
<img width="794" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/fe6761af-b92c-43ff-8c97-ea5a3891ab05">
<img width="920" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/c207b080-d56f-41f1-932e-c2dcfc7fbd3c">

**Comment by izhangzhihao** [comment]
pls uncheck this option first and try again.
<img width="344" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/d998d232-2756-4361-b263-2895d97fef98">

**Comment by JonnyJiang123** [comment]
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/56102991/7fa50ce9-dbeb-4d32-b366-eeb999094aac)
It works!! Thank you!

**Comment by alexanderfilipzik** [comment]
@izhangzhihao same for me, I was using this (payed) plugin before in AndroidStudio and now installed it in IntellJ Ultimate. But I can't make rainbow variables work for me. 
![Bildschirmfoto 2024-04-04 um 16 15 56](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/761f6495-d5c7-4c16-ac7c-74c70f9bc4ca)

![Bildschirmfoto 2024-04-04 um 16 14 52](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/e1e05756-2a25-46d4-8338-dd65519b6429)

![Bildschirmfoto 2024-04-04 um 16 14 54](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/a2503488-5a6f-414a-9a93-5a5b95259453)

![Bildschirmfoto 2024-04-04 um 16 14 58](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/0b72fe09-f28c-48a9-845c-4ff368192d26)

![Bildschirmfoto 2024-04-04 um 16 15 01](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/6ddf5815-58c4-46f8-b73a-6467aaedb683)

![Bildschirmfoto 2024-04-04 um 16 15 08](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/454baa5d-e232-4479-92df-efe8c958de4c)

![Bildschirmfoto 2024-04-04 um 16 16 49](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/b14485f9-7b03-4d34-abe6-5558e69b47ff)
local variable declaration has no color - I also observed that for a short amount of time (<1s) the declaration has a color and then, from one moment to another, the color will applied to the references of this variables. So kind of swapping is happening here

![Bildschirmfoto 2024-04-04 um 16 14 32](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/7afe1c34-ed40-4b7c-a8ca-efff21d74515)
function parameter has no color

Could you please help me

**Comment by izhangzhihao** [comment]
pls uncheck this option and restart your IDE: 
<img width="741" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/6b4955dd-32bc-4822-bd51-8bc084b72b04">

**Comment by alexanderfilipzik** [comment]
I already did this, nothing has changed then

**Comment by izhangzhihao** [comment]
So what other plugins or themes you have installed? Maybe a conflict between the plugin highlighting function?

**Comment by alexanderfilipzik** [comment]
only 3 
![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/47328778/f8e5d1be-515f-4a3c-b635-66c5d64bc9e1)

**Comment by izhangzhihao** [comment]
Can you disable the other two plugins and restart your IDE then give it a try? Or try start editing the files to trigger the Editor re-highlighting?
I need to reproduce your issue but I don't know how.

**Comment by alexanderfilipzik** [comment]
no luck with that, i tried semantic highlight with a vanilla installation of 2024.1 of IntelliJ Ultimate, and there it was broken also - so seems to be an issue on Jetbrains side.

I'm using this version now and everything works:

IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Licensed to Alexander Filipzik
Subscription is active until May 3, 2024.
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by izhangzhihao** [comment]
> no luck with that, i tried semantic highlight with a vanilla installation of 2024.1 of IntelliJ Ultimate, and there it was broken also - so seems to be an issue on Jetbrains side.
> 
> 
> 
> I'm using this version now and everything works:
> 
> 
> 
> IntelliJ IDEA 2023.3.6 (Ultimate Edition)
> 
> Build #IU-233.15026.9, built on March 21, 2024
> 
> Licensed to Alexander Filipzik
> 
> Subscription is active until May 3, 2024.
> 
> Runtime version: 17.0.10+1-b1087.23 aarch64
> 
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Ok, you can raise a ticket to JB here https://youtrack.jetbrains.com/issue/

**Comment by alexanderfilipzik** [comment]
discovered that there is already an issue for that https://youtrack.jetbrains.com/issue/KTIJ-29348
