### ISSUE TITLE
插件会使亮色主题和灰色主题的代码颜色错乱.

### ISSUE THREAD

**Issue by semanticDao** [izhangzhihao/intellij-rainbow-brackets#2690]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

html

### Free or paid?

None

### Expected Behavior

亮色背景会搭配亮色代码配色.

### Current Behavior

亮色背景会搭配亮色灰色代码配色.

### Code snippet for reproduce

无

### Your Environment

webstorm 2023.2.5

**Comment by izhangzhihao** [comment]
Any images?

**Comment by izhangzhihao** [comment]
Closed for no update.
