### ISSUE TITLE
No support in Gateway 2023.3

### ISSUE THREAD

**Issue by Ghjk94522** [izhangzhihao/intellij-rainbow-brackets#2694]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

c++

### Free or paid?

Free users

### Expected Behavior

在 Clion 使用 ssh 连接远程主机时，需要使用 Gateway，支持正常的颜色显示

### Current Behavior

没有颜色显示，可以下载插件，但是显示没有变化，不清楚是因为免费版本的问题，还是本身就不支持 Gateway。插件下载页面的显示如下：
<img width="693" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/45459326/bd99d3ef-3f7f-4aad-86fa-39d0cebbdd0d">
在软件内的插件状态是：
<img width="532" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/45459326/391c0395-e366-49a3-994d-01fa617c33b0">

### Code snippet for reproduce

NA

### Your Environment

JetBrains Client 2023.3
Build #JBC-233.11799.238, built on December 2, 2023
Runtime version: 17.0.9+7-b1087.7 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
远程开发中的控制器 (CL), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
  rdclient.backend.actionHandlers=false
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.9.0)
  izhangzhihao.rainbow.brackets (2023.3.9-233)
  com.intellij.zh (233.199)

**Comment by izhangzhihao** [comment]
Please check this issue for why gateway does not supported: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2584#issuecomment-1399424131

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
