### ISSUE TITLE
"Suppress Paid Feature Suggestion Until The Next Release" not actually doing anything

### ISSUE THREAD

**Issue by robzsaunders** [izhangzhihao/intellij-rainbow-brackets#2697]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Java

### Free or paid?

Free users

### Expected Behavior

When the "register rainbow brackets" pops up and I select the checkbox to suppress  until next release, it should not bother me until the next update.

### Current Behavior

It pops up on every single launch of intellij IDEA regardless of how many times I select the checkbox

### Code snippet for reproduce

Open any project

Register rainbow bracket popup appears

Select the suppress features checkbox and then select "No"

Close intelliJ IDEA

Open any project

*repeat forever*

### Your Environment

IntelliJ IDEA 2023.2.4 (Community Edition)
Build #IC-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    debugger.valueTooltipAutoShowOnSelection=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.9.0)
    com.jetbrains.edu (2023.10-2023.2-955)
    Lombook Plugin (232.10203.10)
    PythonCore (232.10203.2)
    io.github.donkirkby.livepycharm (4.11.0)
    izhangzhihao.rainbow.brackets (2023.3.7)
    ru.adelf.idea.dotenv (2023.2)

Kotlin: 232-1.9.0-IJ10203.10

**Comment by robzsaunders** [comment]
I should add that I tried adding your manual config fix and it did nothing.

**Comment by izhangzhihao** [comment]
Pls post your configs,I guess some paid features have been enabled in your configs.

**Comment by robzsaunders** [comment]
```
<application>
<component name="RainbowSettings">
<option name="bigFilesLinesThreshold" value="3000"/>
<option name="customIndentGuides" value="true"/>
<option name="disableRainbowIndentsInZenMode" value="false"/>
<option name="doNOTRainbowifyBigFiles" value="false"/>
<option name="doNOTRainbowifyBracketsWithoutContent" value="true"/>
<option name="doNOTRainbowifyTheFirstLevel" value="true"/>
<option name="enableRainbowVariables" value="true"/>
<option name="indentGuidesOptions" value="Only selected indent guide"/>
<option name="rainbowifyPythonKeywords" value="true"/>
<option name="rainbowifyTagNameInXML" value="true"/>
<option name="showNotificationOnUpdate" value="false"/>
<option name="suppressAdvancedIndentGuidesBanner" value="true"/>
<option name="suppressLicenseBanner" value="true"/>
<option name="useColorGeneratorForRainbowVariables" value="true"/>
<option name="version" value="2023.3.7"/>
</component>
</application>
```

**Comment by izhangzhihao** [comment]
`useColorGeneratorForRainbowVariables` is a paid feature, can you delete this line or disable here: 
<img width="840" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/eada72c2-81dc-45e9-9e0e-ce6d8041d867">

**Comment by izhangzhihao** [comment]
Closed for no update, If this still not fix your issue, Pls leave a comment.

**Comment by robzsaunders** [comment]
That appears to be it, I didn't enable it so I'm not sure why it was on.

Thanks!
