### ISSUE TITLE
<> colouring in markdown table

### ISSUE THREAD

**Issue by dukedagmor** [izhangzhihao/intellij-rainbow-brackets#2699]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

Markdown

### Free or paid?

Free users

### Expected Behavior

```text
|heading|heading|
|-|-|
|<span>||
```

Should colour ‘<span>’ at least ‘<‘ & ‘>’ the rest should be dependant on settings

### Current Behavior

Does not colour <span>
it does colour ‘<‘ & ‘>’ if I change it to < span>
but doesn’t seem to recognise it as HTML/XML

### Code snippet for reproduce

```text
|heading|heading|
|-|-|
|<span>||
```

### Your Environment

Writerside 2023.2 EAP
Build #WRS-232.10275

**Comment by izhangzhihao** [comment]
I checked the PSI tree structure built by the IDE, and it shows that the HTML element was not built as a PSI tree, but inlined as one psi element, so there is no way to highlight < or > right now.

<img width="1462" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/a1976d2d-0a93-44cd-889e-0a87559cdee8">
