### ISSUE TITLE
[5.0-RC0] Settings no longer works

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#27]
Consider settings with disabled squiggly brackets:
![conf](https://user-images.githubusercontent.com/6392013/36032989-609eb3a2-0db8-11e8-80b0-419945da708b.png)
But in the code they are still colorized:
![bug](https://user-images.githubusercontent.com/6392013/36032963-51019d56-0db8-11e8-85d4-39d3eed98be6.png)

And BTW some of them are white. Other brackets are not using white. Is it ok?

**Comment by izhangzhihao** [comment]
Try close and reopen the tab :wink:

**Comment by Alexsey** [comment]
I had try to reopen tabs and even restart the IDE before posting this issue - it doesn't work :(

**Comment by izhangzhihao** [comment]
Got it! Great catch! https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/caa65ea3dbfd9ffdfab39af788281229a022e179/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/RainbowHighlighter.kt#L66-L67

**Comment by Alexsey** [comment]
Glad to help! At list with testing :)
