### ISSUE TITLE
Override matched brace colour

### ISSUE THREAD

**Issue by KGroenendijk** [izhangzhihao/intellij-rainbow-brackets#270]
## Programming language
I noticed this in a twig file

## Expected result
Should pickup the selected matched brace colour from settings
![image](https://user-images.githubusercontent.com/42764875/66580312-7e5de480-eb7e-11e9-8f08-9f4f5039ea0c.png)

## Current result
Everytime when I restart phpStorm, this resets and I have to change it manually. When I disable the plugin and restart phpStorm, this problem has disappeared.
![image](https://user-images.githubusercontent.com/42764875/66580081-1c9d7a80-eb7e-11e9-97e8-f91415cc0f0e.png)

## Possible solution
Saw online that this might have to do with the override_brace_color in the xml of the rainbow brackets which should be false, but couldn't find this file.

## Code snippet
``` twig
<h5 class="my-0 mr-md-auto font-weight-normal">Forum</h5>
```

## My Environment
Plugin version: 5.2.5
```
PhpStorm 2019.2.3
Build #PS-192.6817.20, built on September 25, 2019
Licensed to Kevin Groenendijk
Subscription is active until October 9, 2020
For educational use only.
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1971M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.almightyalpaca.intellij.plugins.discord, com.chrisrm.idea.MaterialThemeUI, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, izhangzhihao.rainbow.brackets, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv
```

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path

**Comment by KGroenendijk** [comment]
@izhangzhihao That makes phpStorm crash, instead I added this to the same file:
 ```xml
<option name="overrideMatchedBraceAttributes" value="false"/>
```
Now I've fixed it, I'm actually wondering why this isn't set by default...
If you want to leave it this way, I would like to recommend you to change your documentation

**Comment by izhangzhihao** [comment]
What makes phpStorm crash?

**Comment by izhangzhihao** [comment]
I don't set it false by default because I want to override the matched color.

**Comment by KGroenendijk** [comment]
> What makes phpStorm crash?

Adding this to the rainbow_brackets.xml file:
```xml
<option name="rainbowifyHTMLInsideJS" value="false" />
```

**Comment by izhangzhihao** [comment]
Do you have any stacktrace?

**Comment by KGroenendijk** [comment]
> I don't set it false by default because I want to override the matched color.

But users can change it themselves, you don't need to force change the matched braces for e.g. html tags. I think your plugin is only meant to change the matched braces in php files for example.

**Comment by KGroenendijk** [comment]
> Do you have any stacktrace?

No, I don't. It only gave me an empty plugin error box, which gave me the option to press 'OK'.
Had to manually restart phpStorm and the plugin was disabled.

**Comment by izhangzhihao** [comment]
ok, I don't have a phpStorm, but IDEA works just fine. That's strange...
