### ISSUE TITLE
[WRS-3974] <> colouring in markdown table 

### ISSUE THREAD

**Issue by dukedagmor** [izhangzhihao/intellij-rainbow-brackets#2702]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

markdown

### Free or paid?

Free users

### Expected Behavior

```text
|heading|heading|
|-|-|
|<span>||
```

Should colour '\<span>' at least ‘<‘ & ‘>’ the rest should be dependant on settings

### Current Behavior

Does not colour \<span>
it does colour ‘<‘ & ‘>’ if I change it to < span>
but doesn’t seem to recognise it as HTML/XML

I checked the PSI and it is registered as HTML_TAG

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/49711949/96529d68-1e98-4aca-a319-be9148d89586)

with the added space "< span>" I get the following PSI

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/49711949/3f3ca9f5-32e1-4321-af75-73a192d1de15)

### Code snippet for reproduce

Does not colour \<span> or '<' & '>':
```text
|heading|heading|
|-|-|
|<span>||
```

Does colour '<' & '>':
```text
|heading|heading|
|-|-|
|< span>||
```

### Your Environment

Writerside 2023.2 EAP
Build #WRS-232.10275
The jetbrains Markdown plugin is bundled with Writerside

**Comment by izhangzhihao** [comment]
Thanks for investing, I will looking into this later

**Comment by izhangzhihao** [comment]
> Does not colour <span>
it does colour ‘<‘ & ‘>’ if I change it to < span>
but doesn’t seem to recognise it as HTML/XML

Hi, this is behavior of the IDE itself, not this plugin. This plugin can only render something that the IDE build first. Once the IDE building something wrong the rainbowify will broken. You can submit an issue for Jetbrains here https://youtrack.jetbrains.com

**Comment by dukedagmor** [comment]
created issue https://youtrack.jetbrains.com/issue/WRS-3974/colouring-in-markdown-table-in-intellij-rainbow-brackets to gether feedback from the writerside devs

**Comment by dukedagmor** [comment]
youtrack still no response :'(

**Comment by izhangzhihao** [comment]
Closed since no updates from the youtrack tickets.
