### ISSUE TITLE
Cant find valid license in account when using IntelliJ Client (remote client)

### ISSUE THREAD

**Issue by hans-d** [izhangzhihao/intellij-rainbow-brackets#2703]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

n/a

### Free or paid?

Paid users

### Expected Behavior

Valid license in account is found and applied when using the IntelliJ Client (Remote development)

### Current Behavior

Plugin reports that valid license cannot be found.
Using the fat/local IntelliJ, the plugin reports having a valid license.

### Code snippet for reproduce

n/a

### Your Environment

IntelliJ IDEA 2023.3.2
Build #JBC-233.13135.103, built on December 20, 2023
Licensed to Hans Donner
Subscription is active until May 5, 2024.
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
Controller in Remote Development (IU), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  rdclient.backend.actionHandlers=false
Non-Bundled Plugins:
  com.intellij.plugins.eclipsekeymap (233.11799.165)
  izhangzhihao.rainbow.brackets (2023.3.9-233)
  com.intellij.plugins.visualstudiokeymap (233.11799.165)
  com.intellij.plugins.netbeanskeymap (233.11799.165)
  lechuck.intellij-plugin.task (1.5.0)

**Comment by izhangzhihao** [comment]
the JetBrains Client/Gateway does not support paid plugins for now, so only free features works: https://youtrack.jetbrains.com/issue/GTW-2304/JetBrains-Client-does-not-allow-me-to-use-paid-plugin

**Comment by izhangzhihao** [comment]
Duplicateed with https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2656

**Comment by izhangzhihao** [comment]
I'm consider to make this plugin incompatible with JetBrains Client. any thoughts? pls leave a comment here: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2708#issuecomment-1940685388

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
