### ISSUE TITLE
RB not functioning in PyCharm 2023.3.2 (Professional Edition)  REOPEN, PLEASE

### ISSUE THREAD

**Issue by awardblvr** [izhangzhihao/intellij-rainbow-brackets#2705]
### Have you checked the issues and discussions to ensure there are no duplicates?

superficially

### Your programming languages

Python

### Free or paid?

PAID

### Expected Behavior

I expected to see colored brackets, braces, parentheses

### Current Behavior

No colorization.

I have:

1. PAID for the 1 yr license
2. Downloaded / installed manually
3. Observed that Pycharm says I have a (purchased) Rainbow Brackets
4. Notice. I purchased this on my own account, but my company-paid license (but in my name) has been paid through a purchasing dept, but this RB license was paid by me with my credit card.
5. Running on MAC OS Sonoma

### Code snippet for reproduce

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5324667/537e9250-e273-4216-ba7e-00719e5c0438)

### Your Environment

PyCharm 2023.3.2 (Professional Edition)
Build #PY-233.13135.95, built on December 19, 2023
Licensed to <my employer-redacted> Inc. / Andrew Ward
Subscription is active until March 28, 2024.
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2304M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
  com.ultrahob.zerolength.plugin (0.95)
  com.andrewbrookins.wrap_to_column (1.8.0)
  IdeaVIM (2.7.5)
  cn.jxzhang.plugin.json-formatter (1.4)
  com.intellij.ideolog (222.2.0.0)
  com.godwin.json.parser (1.7.1)
  com.toan2.yapf (1.2)
  com.shuzijun.markdown-editor (2.0.5)
  net.seesharpsoft.intellij.plugins.csv (3.2.3-233)
  com.intellij.ml.llm (233.13135.116)
  izhangzhihao.rainbow.brackets (2024.1.0-233)
  ru.adelf.idea.dotenv (2023.3)

**Comment by izhangzhihao** [comment]
Hi can You show me your license status?  pls follow this https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2630

**Comment by izhangzhihao** [comment]
Or can do this?

- Did you log in to the IDE with the same JB account where you buy this plugin?
- try to refresh the license as below:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/12044174/208468876-5e8d9aa3-b9d8-4a24-835c-d609b73d59f7.png">

<img width="544" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/d7cf738d-023b-402e-b6db-20feef7a306f">

<img width="536" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/a85de4fd-95d3-456f-af3b-756ae1c4c9ce">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/12044174/208468675-36a74584-7839-4297-b957-39f347c0cd1b.png">

**Comment by izhangzhihao** [comment]
Closed for no updates, If your issue still exist pls leave a comment.

**Comment by awardblvr** [comment]
HI Zhihao

Sorry for the delay in getting this issue resolved. But back on it now..
Still a problem.. No Rainbow Brackets effect.

PyCharm 2023.3.2 (Professional Edition)
Build #PY-233.13135.95, built on December 19, 2023
Licensed to Andrew Ward
macOS 14.1.2

[image: Screenshot 2024-06-06 at 8.52.40 AM.png][image: Screenshot
2024-06-06 at 8.52.23 AM.png]

I've:
restarted,
Uninstalled / reinstalled
license refresh
Walked through ALL settings looking for anything Rainbow -related
Updated to the latest Pycharm, re-licensed everything:

[image: pycharm_rainbow_licensing.png]

Examined logs  Here are all the lines in the 2024 version with "rainbow"

2024-06-06 09:38:14,111 [   3190]   INFO - #c.i.o.u.i.PluginDownloader -
tryDownloadPlugin: izhangzhihao.rainbow.brackets | 2024.2.4-233 |
https://plugins.jetbrains.com/pluginManager?id=izhangzhihao.rainbow.brackets&build=PY-241.17011.127&uuid=30092128aacc8fa-cfbd-4bec-80bb-1c1e2eb6e112&updatedFrom
2024-06-06 09:38:14,111 [   3190]   INFO - #c.i.o.u.i.PluginDownloader -
tryDownloadPlugin: izhangzhihao.rainbow.brackets | 2024.2.4-233 |
https://plugins.jetbrains.com/pluginManager?id=izhangzhihao.rainbow.brackets&build=PY-241.17011.127&uuid=30092128aacc8fa-cfbd-4bec-80bb-1c1e2eb6e112&updatedFrom
2024-06-06 09:38:14,112 [   3191]   INFO - #c.i.u.i.HttpRequests -
Application is not initialized yet; Using default SSL configuration to
connect to
https://plugins.jetbrains.com/pluginManager?id=izhangzhihao.rainbow.brackets&build=PY-241.17011.127&uuid=30092128aacc8fa-cfbd-4bec-80bb-1c1e2eb6e112&updatedFrom
2024-06-06 09:38:14,289 [   3368]   INFO - #c.i.u.i.HttpRequests -
Application is not initialized yet; Using default SSL configuration to
connect to
https://plugins.jetbrains.com/files/10080/548802/intellij-rainbow-brackets-2024.2.4-241.zip?updateId=548802&pluginId=10080&family=INTELLIJ&uuid=30092128aacc8fa-cfbd-4bec-80bb-1c1e2eb6e112&updatedFrom=&code=PY&build=241.17011.127
2024-06-06 09:38:14,425 [   3504]   INFO - #c.i.u.i.HttpRequests -
Application is not initialized yet; Using default SSL configuration to
connect to
https://downloads.marketplace.jetbrains.com/files/10080/548802/intellij-rainbow-brackets-2024.2.4-241.zip?updateId=548802&pluginId=10080&family=INTELLIJ&uuid=30092128aacc8fa-cfbd-4bec-80bb-1c1e2eb6e112&updatedFrom=&code=PY&build=241.17011.127
2024-06-06 09:38:14,564 [   3643]   INFO - #c.i.p.i.b.AppStarter -
Downloaded and unpacked compatible version of plugin
'izhangzhihao.rainbow.brackets'
2024-06-06 09:38:16,125 [    740]   INFO - #c.i.i.p.PluginManager - Loaded
custom plugins: Zero Width Characters locator (0.95), Wrap to Column
(1.8.0), IdeaVim (2.12.0), Json Formatter (1.4), Ideolog (222.3.2.0), Json
Parser (1.7.1), yapf-pycharm (1.2), Markdown Editor (2.0.5), CSV Editor
(3.3.0-241), JetBrains AI Assistant (241.17011.2), Rainbow Brackets
(2024.2.4-241), .env files support (2024.1)
2024-06-06 09:38:17,791 [   2406]   INFO - #c.i.i.p.DisabledPluginsState -
Plugins to enable: [izhangzhihao.rainbow.brackets]
2024-06-06 09:38:22,919 [   7534]   WARN - #c.i.i.s.i.StartupManagerImpl -
Migrate Ţஜ to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
com.intellij.diagnostic.PluginException: Migrate Ţஜ to ProjectActivity
[Plugin: izhangzhihao.rainbow.brackets]
2024-06-06 09:38:22,929 [   7544]   WARN - #c.i.i.s.i.StartupManagerImpl -
Migrate ڣП to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
com.intellij.diagnostic.PluginException: Migrate ڣП to ProjectActivity
[Plugin: izhangzhihao.rainbow.brackets]
2024-06-06 09:39:10,109 [  54724]   INFO - #c.i.i.p.DisabledPluginsState -
Plugins to enable: [izhangzhihao.rainbow.brackets]
2024-06-06 09:40:01,450 [ 106065]   INFO - #c.i.i.p.m.MarketplaceRequests -
Cannot load data from
https://plugins.jetbrains.com/api/icon?pluginId=izhangzhihao.rainbow.brackets&theme=DARCULA
(statusCode=403)
2024-06-06 10:00:13,110 [1317725]   INFO - #c.i.i.p.DisabledPluginsState -
Plugins to enable: [izhangzhihao.rainbow.brackets]

**Comment by izhangzhihao** [comment]
I can't see your screenshots, can you post them from github?

**Comment by awardblvr** [comment]
Still Need help!

[LicenseCertificate-A5834201.pdf](https://github.com/user-attachments/files/16020866/LicenseCertificate-A5834201.pdf)
[Log_dump.txt](https://github.com/user-attachments/files/16020868/Log_dump.txt)
![Versioning](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5324667/fdd2d484-3c05-4c33-acf1-8c99563ab541)
![License2_proof](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5324667/7e04951a-afde-4c8b-936a-da64ed22d171)
![License1_proof](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5324667/817efc21-d6d7-49cc-bca4-eb0fbfbcb3a9)

**Comment by awardblvr** [comment]
![Screenshot 2024-06-27 at 1 32 16 PM](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5324667/fcb6b3a7-0c65-4a6e-932a-717495695a0d)
