### ISSUE TITLE
Hello, Although I bought the Licence for Rainbow Brackts I still get the notice that I should by the licence to unlock all the advanced features.

### ISSUE THREAD

**Issue by Delgado1974** [izhangzhihao/intellij-rainbow-brackets#2706]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Python

### Free or paid?

Paid users

### Expected Behavior

No messagem should appear

### Current Behavior

 I still get the notice that I should by the licence to unlock all the advanced features.

### Code snippet for reproduce

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/32310294/95c57fd2-277d-4f40-8c88-b871622cce4f)

### Your Environment

PyCharm

**Comment by izhangzhihao** [comment]
Can you check https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2630

Or can do this?

- Did you log in to the IDE with the same JB account where you buy this plugin?
- try to refresh the license as below:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/12044174/208468876-5e8d9aa3-b9d8-4a24-835c-d609b73d59f7.png">

<img width="544" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/d7cf738d-023b-402e-b6db-20feef7a306f">

<img width="536" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/a85de4fd-95d3-456f-af3b-756ae1c4c9ce">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/12044174/208468675-36a74584-7839-4297-b957-39f347c0cd1b.png">

**Comment by izhangzhihao** [comment]
Closed for no updates, If your issue still exist pls leave a comment.
