### ISSUE TITLE
Rainbow Brackets not working for some files of same type

### ISSUE THREAD

**Issue by CrypticArtsLaboratory** [izhangzhihao/intellij-rainbow-brackets#2711]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

javascript

### Free or paid?

Paid users

### Expected Behavior

items should be colored 

### Current Behavior

no color for syntax

### Code snippet for reproduce

it happens with some files and not othersfile

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5160950/80398aa1-00e5-421b-a049-0e767aadbc1a)

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/5160950/3ffbcf96-4f97-410b-991b-4feee17c6e63)

### Your Environment

IntelliJ IDEA 2023.3.4 (Ultimate Edition)

Build #IU-233.14475.28, built on February 12, 2024

Licensed to Donald Tinsley
Subscription is active until March 16, 2024.

Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by izhangzhihao** [comment]
Related to #2604


Try uncheck this option or increase the number of lines:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/12044174/224517403-2c5aef9a-7946-4fcf-9312-fc2109d6aef3.png">

**Comment by izhangzhihao** [comment]
Closed for no update. If your issue still persist pls leave a comment.

**Comment by dominik-mrugalski** [comment]
I have a very similar (or even the same) problem. I've tried to find what caused the problem and I found something interesting. It's caused by some tags, please check an example:


https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/22166267/1df18c27-5cf9-42c0-961f-605c882704f1

Another example I found is `<ViewShot></ViewShot>` from `react-native-view-shot` lib.

I'm also paid user.

```
PyCharm 2023.3.5 (Professional Edition)
Build #PY-233.15026.15, built on March 21, 2024
Licensed to Dominik Mrugalski
Subscription is active until November 25, 2024.
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  performance.watcher.unresponsive.interval.ms=2000
  ide.experimental.ui=true
Non-Bundled Plugins:
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  com.amazon.codewhisperer.jetbrains (1.0.1)
  Key Promoter X (2023.3.0)
  com.wakatime.intellij.plugin (14.3.13)
  com.jetbrains.space (233.15026.16)
  Dart (233.15026.12)
  com.github.beansoftapp.flutter.storm (2023.2.0)
  andrasferenczi.dart-data-plugin (0.2.0)
  com.mobiledi.flutter_plugins (1.4.0)
  gr.jchrist.gitextender (0.8.1)
  com.ppolivka.plugin.gitcleaner (1.1.4)
  mobi.hsz.idea.gitignore (4.5.2)
  izhangzhihao.rainbow.brackets (2024.2.2-233)
  ru.adelf.idea.dotenv (2024.1)
  com.mallowigi.colorHighlighter (18.0.0)
  com.intellij.react.css.modules (1.0.1)



```

**Comment by izhangzhihao** [comment]
> I have a very similar (or even the same) problem. I've tried to find what caused the problem and I found something interesting. It's caused by some tags, please check an example:
> 
> 
> 
> 
> 
> https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/22166267/1df18c27-5cf9-42c0-961f-605c882704f1
> 
> 
> 
> Another example I found is `<ViewShot></ViewShot>` from `react-native-view-shot` lib.
> 
> 
> 
> I'm also paid user.
> 
> 
> 
> ```
> 
> PyCharm 2023.3.5 (Professional Edition)
> 
> Build #PY-233.15026.15, built on March 21, 2024
> 
> Licensed to Dominik Mrugalski
> 
> Subscription is active until November 25, 2024.
> 
> Runtime version: 17.0.10+1-b1087.23 aarch64
> 
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> 
> macOS 14.1.1
> 
> GC: G1 Young Generation, G1 Old Generation
> 
> Memory: 4096M
> 
> Cores: 10
> 
> Metal Rendering is ON
> 
> Registry:
> 
>   performance.watcher.unresponsive.interval.ms=2000
> 
>   ide.experimental.ui=true
> 
> Non-Bundled Plugins:
> 
>   krasa.CpuUsageIndicator (1.18.0-IJ2023)
> 
>   com.amazon.codewhisperer.jetbrains (1.0.1)
> 
>   Key Promoter X (2023.3.0)
> 
>   com.wakatime.intellij.plugin (14.3.13)
> 
>   com.jetbrains.space (233.15026.16)
> 
>   Dart (233.15026.12)
> 
>   com.github.beansoftapp.flutter.storm (2023.2.0)
> 
>   andrasferenczi.dart-data-plugin (0.2.0)
> 
>   com.mobiledi.flutter_plugins (1.4.0)
> 
>   gr.jchrist.gitextender (0.8.1)
> 
>   com.ppolivka.plugin.gitcleaner (1.1.4)
> 
>   mobi.hsz.idea.gitignore (4.5.2)
> 
>   izhangzhihao.rainbow.brackets (2024.2.2-233)
> 
>   ru.adelf.idea.dotenv (2024.1)
> 
>   com.mallowigi.colorHighlighter (18.0.0)
> 
>   com.intellij.react.css.modules (1.0.1)
> 
> 
> 
> 
> 
> 
> 
> ```

after the tag renamed, the editor will re highlight the files(or some part of the file). So it may take some time to re highlight the tags

**Comment by dominik-mrugalski** [comment]
@izhangzhihao I'm afraid it's not the case... I can leave it for even for a whole week and nothing happened. The highlight disappears and won't work anymore in this particular file. I'm using Macbook Pro M1 so it's quite powerful device and as you can see, re-highlighting the file takes few milliseconds.

**Comment by izhangzhihao** [comment]
I could not reproduce your issue @dominik-mrugalski , could you pls provide your code example so I can reproduce it?

**Comment by dominik-mrugalski** [comment]
Today I updated PyCharm to PyCharm 2024.1 and I had a problem with all of the plugins. I needed to remove all of configurations for all of them and right now everything is working fine. For now we can assume that problem was with cache/settings or something like that. Will check that more deeply and let you now if I found that problem again! 
Thanks for your immediately response!
