### ISSUE TITLE
Current scope highlight is not take effect in `.vue` file

### ISSUE THREAD

**Issue by Chieffo2021** [izhangzhihao/intellij-rainbow-brackets#2712]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

Vue

### Free or paid?

Paid users

### Expected Behavior

It take effect in `.vue` file.

### Current Behavior

It only take effect in `template` section, invalid in the `script` and `style` section

in template 
<img width="908" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/85914490/8ab968af-42e4-427d-bcb3-841da3ae8096">

in script
<img width="889" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/85914490/650387c2-ac4a-4921-8f23-160346a05167">

in style
<img width="826" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/85914490/6fba06df-ad42-452e-9881-bae540f6d015">

### Code snippet for reproduce

none

### Your Environment

Webstorm Info
<details>

```
WebStorm 2023.3.5
Build #WS-233.14808.24, built on March 14, 2024
Licensed to Chieffo Chieffo
Subscription is active until March 15, 2025.
For educational use only.
Runtime version: 17.0.10+1-b1087.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
This IDE is not managed via Toolbox Enterprise because no configuration was specified.
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.experimental.ui.inter.font=true
  eslint.additional.file.extensions=svelte
  editor.minimap.enabled=true
Non-Bundled Plugins:
  some.awesome (1.15)
  org.toml.lang (233.13135.67)
  de.netnexus.camelcaseplugin (3.0.12)
  de.ax.powermode (105.501)
  org.jetbrains.plugins.stylus (233.11799.172)
  com.intellij.ideolog (222.3.2.0)
  com.markskelton.one-dark-theme (5.10.0)
  Statistic (4.2.14)
  String Manipulation (9.12.0)
  com.intellij.plugin.adernov.powershell (2.5.0)
  org.jetbrains.toolbox-enterprise-client (2024.2.2152-ij233)
  GrepConsole (12.25.0-IJ2023.3)
  com.intellij.kubernetes (233.13135.104)
  ru.adelf.idea.dotenv (2024.1)
  me.rerere.unocss-intellij (1.4.7)
  com.mallowigi (94.1.0)
  zielu.gittoolbox (500.2.1+233)
  mobi.hsz.idea.gitignore (4.5.2)
  izhangzhihao.rainbow.brackets (2024.2.1)
```

</details>

Plugin Info
<img width="982" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/85914490/7cf3064c-4d86-4dda-bf33-128ed6be22de">

<img width="1262" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/85914490/0c2235fe-6602-48ac-9882-ed0b28455d8e">

**Comment by izhangzhihao** [comment]
This will be fixed in next version.
