### ISSUE TITLE
Not working on Fleet 1.32.122

### ISSUE THREAD

**Issue by danny-su** [izhangzhihao/intellij-rainbow-brackets#2716]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

Kotlin

### Free or paid?

Paid users

### Expected Behavior

N/A

### Current Behavior

Fleet version: build 1.32.122
OS: Mac OS X (14.4.1, aarch64)

<img width="781" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/53d8d2b0-acbf-441a-a273-a6fe53566785">

<img width="509" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/a95bfc1a-44bb-40af-8892-1afa35f78c2d">

<img width="519" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/8d7e5156-1bed-4baf-be6d-29ca12a761ad">

### Code snippet for reproduce

N/A

### Your Environment

Fleet version: build 1.32.122
OS: Mac OS X (14.4.1, aarch64)

**Comment by izhangzhihao** [comment]
Can you check your plugin page and make sure you installed and approved it?
<img width="546" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/603ddc00-72f4-4c88-ba27-46d958a7d394">

**Comment by danny-su** [comment]
@izhangzhihao 
<img width="857" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/b50078a9-2a2b-42e9-a45b-8e26d72f7dfa">

**Comment by danny-su** [comment]
突然它又work了。。。
<img width="901" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/8761641b-98a6-4f1c-8893-9c29e6b90734">
