### ISSUE TITLE
This plugin does not work in JetBrains IDEs of version 2024.1

### ISSUE THREAD

**Issue by qiang-xie-work** [izhangzhihao/intellij-rainbow-brackets#2719]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Java, Python

### Free or paid?

Paid users

### Expected Behavior

This plugin should work in JetBrains IDEs of version 2024.1.

### Current Behavior

This plugin does not work in JetBrains IDEs of version 2024.1 but works in the IDEs of version 2023.3.4.

### Code snippet for reproduce

1. Settings > Plugins > Install the plugin "Rainbow Brackets".
2. Check the code editor windows in the JetBrains IDEs, such as the IntelliJ IDEA 2024.1.
3. No bracket coloring in the code editor windows.

### Your Environment

JetBrains IDEs, e.g.  IntelliJ IDEA, and PyCharm, 2024.1,

**Comment by izhangzhihao** [comment]
it supported, pls provide screenshots if still does not work

**Comment by qiang-xie-work** [comment]
The plugin works as expected now.
