### ISSUE TITLE
Special paired brackets for TypeScript

### ISSUE THREAD

**Issue by upadsamay387** [izhangzhihao/intellij-rainbow-brackets#2722]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

TypeScript + many others

### Free or paid?

On trial

### Expected Behavior

Right now, each type of bracket is treated separately/as its own set. However, when editing some TypeScript, I came across a cool effect. Since TypeScript often requires using pairs of brackets instead of single brackets (e.g. opening with ({ and closing with }) ), it's easy to run into situations where the {} and the () are different colors, but also easy to run into situations where {} and () are the same colors. I was hoping that this could be a toggleable option - specifically, I could choose whether ({ or any other combination of brackets would be a single color is the same combination is used to end a code block.

### Code snippet for test

return db.employees.create({
        data: {
          employeeid: input.employeeid,
          employeetype: input.employeetype,
          employeename: input.employeename,
        },
      });

### Your Environment

WebStorm 2024.1
Build #WS-241.14494.235, built on March 27, 2024
Licensed to Samay Upadhyay
Subscription is active until November 13, 2024.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 16
Registry:
  debugger.valueTooltipAutoShowOnSelection=true
  documentation.show.toolbar=true
  ide.intellij.laf.enable.animation=true
Non-Bundled Plugins:
  manjaro.epb (1.8)
  com.intellij.javafx (1.0.4)
  Batch Scripts Support (1.0.13)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.1.1)
  com.fabio (1.2)
  com.jetbrains.space (241.14494.150)
  monokai-pro (1.10)
  com.jetbrains.ide.streamdeck (2024.1.0)
  com.andrey4623.rainbowcsv (2.0.2)
  bundled-webstorm-help (241.14494.235)
  com.intellij.ideolog (222.3.2.0)
  name.kropp.intellij.makefile (241.14494.150)
  com.intellij.properties (241.14494.150)
  CMD Support (1.0.5)
  com.wakatime.intellij.plugin (14.3.13)
  XPathView (241.14494.140)
  com.intellij.aqua (241.14494.288)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.ml.llm (241.14494.240)
  com.github.copilot (1.5.2.5345)
  git-extended-update-index (0.1.3)
  com.intellij.database (241.14494.180)
  com.haulmont.rcb (241.14494.140)
  mobi.hsz.idea.gitignore (4.5.3)
  izhangzhihao.rainbow.brackets (2024.2.2-241)

**Comment by izhangzhihao** [comment]
Because there is no support for double special brackets in the IDE, this feature cannot be implemented.
