### ISSUE TITLE
Combining with Kubernetes plugins breaks yaml guide lines.

### ISSUE THREAD

**Issue by scphantm** [izhangzhihao/intellij-rainbow-brackets#2723]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

yaml

### Free or paid?

Paid users

### Expected Behavior

When you have the kuberntes plugin installed and create a helm chart, Open the yaml file and i would expect the tags and the guide lines to be rainbowifyed

### Current Behavior

When you open a file that IntelliJ determines to be a regular old yaml file, both the tag name and guide line rainbows work properly.  But when you open a file that IntelliJ determines to be a helm file (with a helm icon), the rainbow tag names work, but the rainbow guide lines and highlighting does not work.

### Code snippet for reproduce

not really a snip, but file type issue.

### Your Environment

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to willie slepecki
Subscription is active until April 16, 2024.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
Jenkins Plugin 0.13.20-2023.2
GC: G1 Young Generation, G1 Old Generation
Memory: 5096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=2e5861
  editor.focus.mode.color.dark=2e5861
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  ru.sadv1r.ansible-vault-editor-idea-plugin (1.21)
  com.nasller.CodeGlancePro (1.8.3-241)
  com.jetbrains.space (241.14494.150)
  co.notime.intellijPlugin.backgroundImagePlus (1.2.1)
  org.jetbrains.plugins.go-template (241.14494.150)
  com.github.mikesafonov.jenkins-linter-idea-plugin (0.6.0)
  com.maxifom.pyenv-integration (0.0.2)
  name.kropp.intellij.makefile (241.14494.150)
  com.redhat.devtools.intellij.telemetry (1.1.0.52)
  com.redhat.devtools.intellij.kubernetes (1.2.3.294)
  ir.msdehghan.plugins.ansible (0.92)
  org.jetbrains.plugins.go (241.14494.240)
  de.achimonline.ansible_lint (1.6.2)
  org.jetbrains.plugins.ruby (241.14494.240)
  Pythonid (241.14494.240)
  Stapler plugin for IntelliJ IDEA (3.0.3)
  Jenkins Control Plugin (0.13.20-2023.2)
  com.intellij.mermaid (0.0.21+IJ.232)
  org.asciidoctor.intellij.asciidoc (0.41.13)
  com.intellij.ml.llm (241.14494.240)
  org.jboss.tools.intellij.openshift (1.8.0)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.mallowigi (95.0.0)
  mobi.hsz.idea.gitignore (4.5.3)
  com.github.blarc.gitlab-template-lint-plugin (1.13.2)
  com.chrisrm.idea.MaterialThemeUI (9.2.0)
Kotlin: 241.14494.240-IJ

**Comment by izhangzhihao** [comment]
Any screenshots?  because I tried a simple chart it works as expected:
<img width="1150" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/ab89f694-f4a1-4be4-9117-6f246a0f45e5">

**Comment by scphantm** [comment]
![Uploading Screenshot 2024-04-10 at 9.19.36 AM.png…]()

**Comment by scphantm** [comment]
My machine isn't letting me upload images, probably the corp firewall.  gimme some time and ill get em uploaded.

**Comment by izhangzhihao** [comment]
Any update? is your issue resolved?

**Comment by scphantm** [comment]
it is not.  im on a corp network and can;'t upload images.  But the icon i have for my helm files is different than yours.  I do have another project where the helm files are the same icon as yours and that one works correctly.  One of my plugins is changing the file type to another flavor of helm and screwing me up

**Comment by izhangzhihao** [comment]
Closed because of no updates.
