### ISSUE TITLE
免费版的，每次打开pycharm必弹窗，勾上也没用。

### ISSUE THREAD

**Issue by aflyingnoob** [izhangzhihao/intellij-rainbow-brackets#2724]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

Python 

### Free or paid?

Free users

### Expected Behavior

勾上下版本提醒没用

### Current Behavior

每次都弹
![QQ截图20240410154326](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/30976978/d9e8767c-23a6-40b4-88d4-41f69d95199b)

### Code snippet for reproduce

打开pycharm

### Your Environment

PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
Licensed to
Subscription is active until September 5, 2024.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 12000M
Cores: 12
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  com.intellij.ideolog (222.3.2.0)
  String Manipulation (9.12.0)
  nl.rubensten.texifyidea (0.9.4)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.github.copilot (1.5.2.5345)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.xxxtai.coding.SmartInputSourceIntelliJ (5.2.2-pycharm)
  mobi.hsz.idea.gitignore (4.5.3)
  cn.yiiguxing.plugin.translate (3.5.7)
  com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.15.0)

**Comment by izhangzhihao** [comment]
应该是启用了付费功能但是没有 license，你可以去https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path 找到rainbow_brackets.xml的配置，然后删除该文件，重启 IDE。

**Comment by izhangzhihao** [comment]
试了一下确实有问题，请使用这个版本，无需解压：
[241.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/14931284/241.zip)

**Comment by izhangzhihao** [comment]
也可以使用这个 build（无需解压）：
[241.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/14965327/241.zip)
