### ISSUE TITLE
PyCharm变量名颜色不生效

### ISSUE THREAD

**Issue by davichi11** [izhangzhihao/intellij-rainbow-brackets#2729]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Python

### Free or paid?

Paid users

### Expected Behavior

变量名颜色不变 如图
![WX20240418-091353@2x](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/6285677/ab137fa6-f666-42af-9fa1-cee5db14b25b)
当变量所在行变化时,颜色会改变如图:
![111](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/6285677/c801a837-fe74-4c06-87d7-23965fcd907e)
但是只会改变交换位置的两行的变量名,引用的还是不变

### Current Behavior

期望颜色能正常改变,目前只在pycharm上发生,idea和Goland正常

### Code snippet for reproduce

![111](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/6285677/229d8a87-54c4-4ef3-8911-6fa1e83858df)
![WX20240418-091353@2x](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/6285677/29858340-95a5-4476-88f9-0138749feed2)

### Your Environment

PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
Licensed to 春亮 胡
You have a perpetual fallback license for this version.
Subscription is active until April 11, 2025.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  js.debugger.webconsole=false
  editor.minimap.enabled=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  cn.olange.rule (1.0.5.2)
  String Manipulation (9.12.0)
  co.bito.bito-intellij (1.3.1)
  lermitage.intellij.extra.icons (2024.3.4)
  nl.rubensten.texifyidea (0.9.4)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  com.intellij.bigdatatools.core (241.14494.240)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.14494.240)
  com.intellij.bigdatatools.metastore.core (241.14494.158)
  mobi.hsz.idea.gitignore (4.5.3)
  cn.yiiguxing.plugin.translate (3.5.8)
  com.intellij.bigdatatools.spark (241.14494.158)

**Comment by izhangzhihao** [comment]
Duplicated with https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2720

**Comment by Locter9001** [comment]
在Goland中也是一样，变量颜色不稳定，换行就消失，2024.2 EAP并没有修复这个问题
