### ISSUE TITLE
Rider CFW support?

### ISSUE THREAD

**Issue by jinyue-0525** [izhangzhihao/intellij-rainbow-brackets#2730]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

C#

### Free or paid?

Paid users

### Expected Behavior

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/164129991/601f9ea1-ebb1-4240-8276-d6ff55034f6f)

正常应该是这样的

### Current Behavior

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/164129991/d6a91bcc-b06a-4860-92fc-727bd552ee8d)

这里插件没有工作

### Code snippet for reproduce

windows窗体服务中,无法显示
按钮点击时间事件

### Your Environment

JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
授权给 方悦 冀
您有此版本的永久回退许可证。
订阅有效期至 2025年4月20日。
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4022M
Cores: 16
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
  eslint.additional.file.extensions=svelte
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  club.nutsoft.Github3Theme (1.2.0)
  com.intellij.javafx (1.0.4)
  PythonCore (241.14494.240)
  com.intellij.zh (241.230)
  lermitage.intellij.extratci (1.35.0)
  com.intellij.resharper.HeapAllocationsViewer (2024.1.0)
  leetcode-editor (8.11)
  com.jetbrains.space (241.14494.150)
  monokai-pro (1.10)
  com.andrey4623.rainbowcsv (2.0.2)
  SerialPortMonitor (241.14494.288)
  quokka.js (1.0.442)
  com.jetbrains.rider.android (241.14494.325)
  com.mroche.JsonHelper (1.3.2)
  com.intellij.gradle (241.14494.288)
  DevKit (241.14494.247)
  Key Promoter X (2024.1.0)
  hunspell (241.14494.288)
  com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete (0.4.1)
  com.intellij.resharper.StructuredLogging (2024.1.0.323-eap01)
  HighlightBracketPair (1.4.3)
  com.intellij.ml.llm (241.14494.320)
  com.intellij.bigdatatools.core (241.14494.240)
  dev.blachut.svelte.lang (241.14494.140)
  com.xxxtai.coding.SmartInputSourceIntelliJ (6.0.2)
  com.zxy.ijplugin.wechat-miniprogram (3.5.17)
  com.github.jk1.ytplugin (2024.1.94)
  cn.fjdmy.uniapp (1.0.14-241.1)
  com.github.copilot (1.5.2.5345)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  ai.codegeex.plugin (2.7.3.11223)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.2.5+233)
  com.intellij.resharper.azure (3.50.0.1773-2024.1)
  cn.yiiguxing.plugin.translate (3.5.8)
  Jetbrains TeamCity Plugin (2024.03.156166)
  me.rafaelldi.aspire (0.5.0)
  izhangzhihao.rainbow.brackets (2024.2.3-241)

**Comment by izhangzhihao** [comment]
What is 'CFW'? How can I reproduce your issue?

**Comment by jinyue-0525** [comment]
windows应用程序
框架版本:.NETFramework V4.6
语言版本:C#7.3,
试着创建一个桌面应用然后添加一个按钮的点击事件

**Comment by izhangzhihao** [comment]
我尝试了但没有重现，你能打包给我一份可以重现的代码吗？

**Comment by izhangzhihao** [comment]
Closed because of no updates.
