### ISSUE TITLE
The highlight function de-highlights the same properties

### ISSUE THREAD

**Issue by Tautvis88** [izhangzhihao/intellij-rainbow-brackets#2733]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

JavaScript, Typescript

### Free or paid?

Paid users

### Expected Behavior

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/61901627/0b0d31b1-52c7-48ec-86f0-21928fa93f23)

### Current Behavior

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/61901627/66b42ba8-f4a6-412b-a4a5-a72c21c62deb)

### Code snippet for reproduce

```
  describe('case with locked fields', () => {
    beforeEach(() => {
      setBaseData();

      component.onCampaignDetailsChange(
        hirePurchaseForm.group<CreditSubsidyFormGroup>({
          [CreditFormFields.IsSubsidyActivated]: hirePurchaseForm.nonNullable.control(false),
          [CreditFormFields.SubsidizedBy]: hirePurchaseForm.nonNullable.control(undefined),
          [CreditFormFields.SubsidyDuration]: hirePurchaseForm.nonNullable.control(undefined),
          [CreditFormFields.SubsidizedValue]: hirePurchaseForm.nonNullable.control('0'),
        })
      );
      component.onPaymentDetailsChange(
        hirePurchaseForm.nonNullable.group<CreditPaymentFormGroup>({
          [CreditFormFields.PaymentModel]: hirePurchaseForm.nonNullable.control(paymentModelArrears.value),
          [CreditFormFields.PaymentPeriod]: hirePurchaseForm.nonNullable.control(paymentDetailsInit.paymentPeriod),
          [CreditFormFields.DirectDebit]: hirePurchaseForm.nonNullable.control(paymentDetailsInit.directDebit),
          [CreditFormFields.PlanStartDate]: hirePurchaseForm.nonNullable.control(paymentDetailsInit.planStartDate),
          [CreditFormFields.ContractNumber]: hirePurchaseForm.nonNullable.control('123'),
        })
      );
      component.onInterestDetailsChange(
        hirePurchaseForm.nonNullable.group<CreditInterestFormGroup>({
          [CreditFormFields.Rate]: hirePurchaseForm.nonNullable.control('10'),
          [CreditFormFields.RateType]: hirePurchaseForm.nonNullable.control(interestDetailsInit.rateType),
          [CreditFormFields.Date]: hirePurchaseForm.nonNullable.control(interestDetailsInit.date),
          [CreditFormFields.Period]: hirePurchaseForm.nonNullable.control(interestDetailsInit.period),
        })
      );
    });
 }

```

### Your Environment

WebStorm 2024.1.2
Build #WS-241.15989.105, built on April 23, 2024

Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
  ide.check.windows.defender.rules=false
Non-Bundled Plugins:
  de.espend.idea.localization (0.0.6)
  com.jetbrains.edu (2024.4-2024.1-742)
  com.intellij.properties (241.14494.150)
  XPathView (241.15989.65)
  com.intellij.ml.llm (241.15989.102)
  me.mbolotov.cypress (1.6.2)
  zielu.gittoolbox (500.2.6+233)
  dev.nx.console (1.21.0)
  izhangzhihao.rainbow.brackets (2024.2.3-241)

**Comment by izhangzhihao** [comment]
Can you try to give me a minimized example? because I could not reproduce your issue easily:

<img width="1321" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/f95cf9eb-c34a-4422-a636-e6985b894a25">

And BTW, this plugin does not highlight functions, can you try disabling this plugin and check the function highlighting?

**Comment by Tautvis88** [comment]
Hi.
WebStorm highlights properties/variables with same name, but the Rainbow
Brackets plugin overrides that highlighting with plugin highlighting:
You need to turn on this feature, because now I see that you are using
*Border* option, but you need to change it to *Highlight*. And then you
will see that plugin highlighting overrides that highlighting which comes
from IDE.
[image: image.png]
[image: image.png]
[image: image.png]
--
Regards,
Tautvydas Pagalys
+37062928313


2024-04-30, an, 16:08 Zhihao Zhang ***@***.***> rašė:

**Comment by izhangzhihao** [comment]
I see, but if you are using the *Highlight* option, which means you may accept that current highlighting will be overwritten right? And BTW, the IntelliJ platform does *not* support highlighting co-existing with prev existing highlighting at the same time, which means the first highlighting will be overwritten by the last one.

**Comment by Tautvis88** [comment]
I understood, it's a pity then, because I won't be able to use the
highlight function :(
--
Pagarbiai,
Tautvydas Pagalys
862928313


2024-04-30, an, 17:22 Zhihao Zhang ***@***.***> rašė:

**Comment by izhangzhihao** [comment]
Maybe the *Border* option is suitable for you?

also, link this issue to https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2644 since this may help users understand how it works.

**Comment by Tautvis88** [comment]
Yes, the border I was using all the time, but was thinking how it would be
nice to use the highlight option. But yes, nothing can be done.
--
Pagarbiai,
Tautvydas Pagalys
862928313


2024-04-30, an, 17:32 Zhihao Zhang ***@***.***> rašė:
