### ISSUE TITLE
[IJPL-59368 ][RIDER-111854] IDE crashes due to "chrome-sandbox is owned by root and has mode" error when IDE is launching the JCEF in a sandbox

### ISSUE THREAD

**Issue by albinalm** [izhangzhihao/intellij-rainbow-brackets#2734]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

C#

### Free or paid?

Paid users

### Expected Behavior

It should start right up

### Current Behavior

Entire Rider crashes with no detailed error logging.
I've isolated the problem to Rainbow Brackets.

If i load my solution with it disabled > It starts and loads, if I enable the plugin it crashes. Disabling it again, solution loads.
Seems to have bricked my old solution somehow when I cloned it from my repository using the addon. I had to make a new solution, then add all projects again. 
It was at that point, when I finally had a working solution I managed to isolate the problem to this plugin.

### Code snippet for reproduce

This is a startup error and thus I have no code snippets to provide.

### Your Environment

JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
Licensed to Albin Alm
Subscription is active until January 28, 2025.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.0-31-generic
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 3980M
Cores: 24
Registry:
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  com.wakatime.intellij.plugin (14.3.13)
  com.mallowigi (95.0.0)
Current Desktop: ubuntu:GNOME

**Comment by albinalm** [comment]
I found this message through my idea.log
```
com.intellij.diagnostic.PluginException: Migrate طẉ to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:275)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by izhangzhihao** [comment]
Pls find and upload logs here by following https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by albinalm** [comment]
[rider-logs.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/15164191/rider-logs.zip)

**Comment by izhangzhihao** [comment]
> I found this message through my idea.log
> 
> ```
> com.intellij.diagnostic.PluginException: Migrate طẉ to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:275)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:68)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:191)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
> 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
> 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
> 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:190)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> ```

this is a warn actually:

2024-04-30 14:55:21,687 [   6530]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate طẉ to ProjectActivity [Plugin: izhangzhihao.rainbow.brackets]

And I could not reproduct it with 

```
JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
Evaluation purpose only.
Runtime version: 17.0.10+8-b1207.12 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.plugins.snapshot.on.unload.fail=true
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  PsiViewer (241.14494.158-EAP-SNAPSHOT)
  PythonCore (241.14494.240)
  org.toml.lang (241.14494.150)
  izhangzhihao.rainbow.brackets (2024.2.3-241)

```

**Comment by albinalm** [comment]
[Screencast from 2024-04-30 15-12-16.webm](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/70197523/afd41822-e137-4dea-9f53-91ba17d56e2e)
Weird... Rider and my OS is just installed.

Here's a video demo:ing the issue

**Comment by izhangzhihao** [comment]
Pls try to *uncheck* this option before opening your project:
<img width="1029" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/44464a0a-77d0-4588-9f6f-5822076bb68e">

**Comment by albinalm** [comment]
Just did, seems to have resolved the issue. Good catch from the video, I just saw you can see it crashing right after displaying the changelog.

No clue what element in the readme that could've caused this issue, but might be good to keep in mind if you encounter this for other users as well.

Thanks!

**Comment by izhangzhihao** [comment]
Very interesting... because I already added a try-catch here:

<img width="1010" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/018c22a8-fb83-41be-a4d2-8088c83004af">

**Comment by izhangzhihao** [comment]
Just created a new issue for the Rider IDE: [RIDER-111854](https://youtrack.jetbrains.com/issue/RIDER-111854/Rider-crashes-when-executing-HTMLEditorProvider.openEditor)

**Comment by albinalm** [comment]
> Very interesting... because I already added a try-catch here:
> 
> <img alt="image" width="1010" src="https://private-user-images.githubusercontent.com/12044174/326823493-018c22a8-fb83-41be-a4d2-8088c83004af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQzODksIm5iZiI6MTcxNDQ4NDA4OSwicGF0aCI6Ii8xMjA0NDE3NC8zMjY4MjM0OTMtMDE4YzIyYTgtZmI4My00MWJlLWE0ZDItODA4OGM4MzAwNGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEzMzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OTc1NTc3OTRhNTcyZTM3MmQ2NDY0YzhkZGZhM2Y0OWQ4ZmQ2ZDc4OTEzMDFlMTRlZTVlM2EyYWViMWUyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wnWz15IP6dswj2Dyi0eYLMV7ziNmxXICWjEvwbLo6gY">

Yep! Seems to be an IDE issue in that case!

**Comment by ajanke** [comment]
For what its worth, this same thing happened to me with IntelliJ 2024.1.1. Disabling the changelog page fix it for me also so it seems the bug is not limited to Rider.

**Comment by izhangzhihao** [comment]
> This is now clear: this is a JCEF issue. The workaround is to disable JCEF in the IDE registry (ide.browser.jcef.sandbox.enable key).

**Comment by izhangzhihao** [comment]
The latest release of PyCharm seems to have this issue fixed, but I didn't have a Linux machine to test: https://youtrack.jetbrains.com/issue/IJPL-59368/IDE-crashes-due-to-chrome-sandbox-is-owned-by-root-and-has-mode-error-when-IDE-is-launching-the-JCEF-in-a-sandbox
