### ISSUE TITLE
使用IDEA的ssh远程开发时插件报错

### ISSUE THREAD

**Issue by Rebuilding127** [izhangzhihao/intellij-rainbow-brackets#2736]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

java

### Free or paid?

Free users

### Expected Behavior

正常启动运行

### Current Behavior

启动时插件报错

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/26793016/a2313f8d-fef9-4bb1-9340-4d525593a1e9)

本地环境启动运行是没问题的，远程开发时才报错。

### Code snippet for reproduce

无

### Your Environment

IntelliJ IDEA 2024.1.2 Preview
Build #JBC-241.17011.2, built on May 7, 2024
Licensed to xx
You have a perpetual fallback license for this version.
Subscription is active until April 21, 2025.
Runtime version: 17.0.11+1-b1207.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
Controller in Remote Development
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
  ide.experimental.ui=true
  editor.minimap.enabled=true
  terminal.new.ui=true
  rdclient.backend.actionHandlers=false
Non-Bundled Plugins:
  com.intellij.plugins.visualstudiokeymap (241.14494.150)
  com.intellij.plugins.netbeanskeymap (241.14494.150)
  com.intellij.plugins.eclipsekeymap (241.14494.150)
  Key Promoter X (2024.1.0)

**Comment by izhangzhihao** [comment]
This plugin depends on `com.intellij.modules.lang`:

https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/f7fb0636cd45eda563783e9ad6f4694d94f7f702/src/main/resources/META-INF/plugin.xml#L715

But the Intellij Remote Development / Gateway does not have this module, so it would not be possible to support it at this moment.

Related to #2408

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
