### ISSUE TITLE
Can't enable plugin in gateway client for idea

### ISSUE THREAD

**Issue by Jarvvski** [izhangzhihao/intellij-rainbow-brackets#2737]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Java

### Free or paid?

Free users

### Expected Behavior

Plugin should load

### Current Behavior

![image](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/6012840/d2065429-fa46-415b-b148-2487e75cd49b)

### Code snippet for reproduce

N.A

### Your Environment

IntelliJ IDEA 2024.1.1
Build #JBC-241.15989.150, built on April 29, 2024
Licensed to null null 
Subscription is active until October 11, 2024.
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
Controller in Remote Development
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 22
Registry:
  ide.balloon.shadow.size=0
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  rdclient.backend.actionHandlers=false
Non-Bundled Plugins:
  com.mallowigi (96.0.0)
  com.intellij.plugins.visualstudiokeymap (241.14494.150)
  com.intellij.plugins.netbeanskeymap (241.14494.150)
  com.intellij.plugins.eclipsekeymap (241.14494.150)
  com.chrisrm.idea.MaterialThemeUI (9.2.1)

**Comment by izhangzhihao** [comment]
This plugin depends on `com.intellij.modules.lang`:

https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/f7fb0636cd45eda563783e9ad6f4694d94f7f702/src/main/resources/META-INF/plugin.xml#L715

But the Intellij Remote Development / Gateway does not have this module, so it would not be possible to support it at this moment.

Related to #2408

**Comment by izhangzhihao** [comment]
plsdownload experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
