### ISSUE TITLE
Not working on Fleet 1.35.115

### ISSUE THREAD

**Issue by danny-su** [izhangzhihao/intellij-rainbow-brackets#2738]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Kotlin

### Free or paid?

Paid users

### Expected Behavior

Work as expected.

### Current Behavior

After updating Fleet to 1.35.115, there was an error about Rainbow Brackets that occurred when Fleet launched, so I removed the Rainbow Brackets and tried to reinstall it, but I failed to find it again.

<img width="419" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/efe378ea-a850-42da-b22a-5b878e0d58ae">

<img width="547" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/29cd532e-c51c-4772-8b81-f91172f61d2a">

### Code snippet for reproduce

N/A

### Your Environment

Fleet version: build 1.35.115
OS: Mac OS X (14.5, aarch64)

**Comment by izhangzhihao** [comment]
Just tested it, and it works for me: 
<img width="879" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/d1657e4e-2df5-4057-8973-4988d8ac8953">

Can you open your `settings.json` and make sure you have the internal mode on? 
<img width="543" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/6ffc434a-9bbb-43a4-83a4-882adc232387">

**Comment by danny-su** [comment]
@izhangzhihao The internal mode is enabled.

<img width="556" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12178855/76fe28b9-b7fe-43b8-912c-72f89d8fe827">

**Comment by izhangzhihao** [comment]
I see, you can add this section to your settins.json

```
 "plugins": [
        {
            "type": "add",
            "pluginName": "izhangzhihao.fleet.rainbow.brackets"
        }
    ],
```

**Comment by danny-su** [comment]
@izhangzhihao Got the following error:
```
Hash mismatch (https://plugins.jetbrains.com/files/fleet/izhangzhihao.fleet.rainbow.brackets/0.2.4/modules/izhangzhihao.fleet.rainbow.brackets-frontendImpl-0.2.4.jar). Expected: 32f3351bdb1bf317e1532979a6950c0478ffa68710b5332780f59cafe942b2dd, actual: f4575e23788b104dceca4fe68af501babe832c264c1518fb3a944b63390471ca, downloaded file size: 41.85kB, target: true, tmp: true, content: `PK»N¦X	META-INF/PK»N¦X²îMETA-INF/MANIFEST.MFóMÌËLK-.Ñ
K-*ÎÌÏ³R0Ô3àåâåPK¹N¦XÇuûÐGmodule-info.classQËn1=·@Ó÷·(P-ïÚH!!øgâdÌØ#ÏTY!>ÀG!{¥,±äcûÞs¯}~ÿùùÀô:X"¬vÐäêT¡%¬}±KÕ;+ÂÎBåWIXþBÂYj>ÒuÖô¹fÒ¦Î¤åNjÓ·ßxßÉt¢ê5µ2÷E3¬Vgj¼/+K§û'¼ÛeØ l
s¥êyÃa#Æ&ÊåËwæ,c¼Ñ×	Û1æ2=µôö»å÷sK3	ÞÊªæ©uþy·	û1V¥*$/­mj=ýá`bë\óÙ6µ6ªjëîØ?wæþcîûõÒUÚZöCÂQdy3Ò¦â(Ea
Ã1a3üM9·ÃcÂu#>®¬ñÛ^Ò{ô3gÞÁó"Ê1¼ð¿¾z ªImË=FßDôM,ú&ZßÄobÑ·á04"¢¢mZ|
k]ÂÿÒcömßÂÅXÂWqÍ¯?°¢»Xñ¬5¬ÓfÀí63,à~À·¼ð(àøùOÃþ9fúóNÜÏä/PK·N¦Xcom/PK·N¦Xcom/github/PK·N¦Xcom/github/izhangzhihao/PK·N¦X com/github/izhangzhihao/rainbow/PK·N¦X)com/github/izhangzhihao/rainbow/brackets/PK·N¦X6com/github/izhangzhihao/rainbow/brackets/frontendImpl/PK·N¦X×ÛÓeXcom/github/izhangzhihao/rainbow/brackets/frontendImpl/RainbowBracketsPlugin$load$2.classÍVëSUÿÝ%H¤H+m}D!ÍÒVmJKyØØð@_õf¹$K6»}¯:ã'?ú/8ãýRi;vF?úø?8çnG!6í3ÌÝ={ïÍùó;çsÿøû_\ÄWsUVº[ôòª¾Qäfa£¨¹¥Ú\7óÖ·¹V®£®Øé
s9S®ê\mõJ°8kxÝL_N
1lfKkè¦ªY¶å¹º)uµZVuÒaÜPsS!mY^Î/ó¡íÝrËgj®n:Hgõõ½êÆ¶ÅfUÄPÀ1²X7=.uÞÞ°`êîÐÈPvW¹jÇêL~Uhr!õ8fbxîá¦ÑÂÐ2¬èÃ7}ÙC$|(»báª%²MjÅtÔÚâ#±2ÔáÏ'Ì(
Õág%EWúÚâu'1È0u¨>GqÑ6(hg&*»¾2¼Ø(:ÿ>ÊèË4Y­x*ft3¤Góÿgm	[hB¯
áH *F0ÄÉÐ®U«$3ÃðJßÁC×p!Ý¨z¼W._æ.§?°º®¤K.-MTð2$è4-F°2
­VÓ5âÒ{KÄ¥·Kï%.ý0â(YË.¨«ÂÍK-ÊMÓry­6L{Áó »_zØ6Ë;iWÿA6	þ kÙ¯¹a$;637³0¸[ÈÍNLO3t÷Õa;NG04C3Ù%¢%Å ÎÈ$_:ø9áx+A^eèp¶µ6cNrÝðlÊócõKú:ÎGð.ìVÊI0Þd¸vYÆ0Ãó\Óã$ÿ_ÕEåÑ¢edZû¿zG"\PË¾LÇpOã
Ckf:7?:=6A'î&Å8&Ú0IâaWgÆ0D9J41±®Jý«ªÆ
#îZñ^b]½ñ¼X±lï­äÞø±ß1¼oï|Næb!(QÙ2b'l?uºêöØþ¹0Þ¡J­Ù¤ÊV'±SØ°8­<¾ÚáäHCÍÃû®¶$j>ÍUnxäQKMÅ¾ÿ~±©_A ùÀ©nbæ0/Ýû SxFJ1(3²¶5¶@n¥
s¡^,­U¼Ð$å(ð´ÚÄÑm§ö´¥\
ÉG«|j`I
M´¸®KîÊ2¹õìÖ­HS"JÛºuRdIeP¹úû×å&rèÈ07-ófÙòºõ¶ltëè«_$í¶÷$íAlyÆªX#ÝcÖ²gË¢ã{Ûºl.óòAý;§LîúºN¼Vâ`­3KM{å¼°Ss¿,2fUwtÝíGÔÓö¯ÎrÒ¶E3¦)ì1; ÏÎ	S3,ª^´HÎòlMLêòD ôú@ê@
]q¨|ÀçgXL^´ü7]h¶YF²QÝ$ivè}49°dj]ÉæÓwqìG?¤ôLÖ6à8q&©2_*_:¤êDèR¾%Ä)ÍÉÝ:üç¾÷Õ`´öò5õÐ8?poÐz®ä¡M»Ñ¥Ôw¤nËåÅðÖíûÈ,u]»éßd¾áSzv ôâaÌ=7N>£¹ã>p	iÓ¿
M¡ù§¤4Y2åsúj¡w½¿ ¦´F¿ï![bBz4xÔ}ÊÒ¶Å©»X$£oïð¯íÙá­ïúRl)[; ýh»X°
Mg1¾BJ¥ÚXr unA!BîàÆ~ØØlû°1ä÷À¾ÀW¶ßWDS±QÕH°ØöäÀDü¼Â~ÌöÌvÂ¬¹ÚN³Ö[ô¡9ÅßÑ/é¢¸¬ö4ýPK·N¦X>ÎñUPcom/github/izhangzhihao/rainbow/brackets/frontendImpl/DefaultHighlighterKt.classR[OA>³»m·µe±Ah¢Þ Æ,¸`|0³ít;t:K¶³Hxâ·øä£c¢!<ú£gÚ*Z0qÙùæï\æóýÇoðx^Û^ÄU3
=~Ð¤2:hò&½rÆo¼0¡µS¯ÄR1Y_iï
ï)kÐT¨e5.ÅUBÀÙ¡{ÔÇÛwX
­&bÄÔc|ÞQ§gü./U\xSónÚüTJ¸æ7åÇIäí0ê;2VTññz¬ÖS!Oª

Ô*B
y0à6¶Ý=bn¿PêØ5Á%WÌé­¿.Øë*Ð·½æÛ0BÀZÞÔhÑË%ÊèÜJ
cÊ­Xa6¯Òt{Æ:Z»+2¦6nL¿òeT¬×`¢WáºÖäöûå×¢uª(Úö£@ôÏÖ? @ZèÜçÍ"ªÏX;:,3«T0ìÌä¨stX±]Ë5fYrü6k#£bÙ¦c¡/s+ëXÇï²9ôÑõÊ
Áºµ+ÒË×Óv»Ox$©JF`ìE*o³¹Ç;<léd$ðÄu¦K¶¶ClRäàÓqÔØ3®å~­S`ÁÒ@Eîw»§)¸{/`ã^Ñ3ó	eÈàÉûxG«þ¬P|ßüAp¾û+¾ö3¢ÁèÒÑ6XGocÍ\È}«UÓ½T-÷rPÍ¸ uÇêgüÅì)ÿ/óáwU}_ÝóVPK·N¦Xïtlcom/github/izhangzhihao/rainbow/brackets/frontendImpl/RainbowBracketsPlugin$rainbowHighlighterWorker$3.class½V[SÛFþVv08N°É¥¤Z·q°È¥4
iC0Ò[*Ë-,KY4½^gòÔ_Ñ>ÑNsf¦e:ÓþþvzVÉ4Ã´G»G{¾óí¹ì_ÿþúK¸Ç° e¹ ÙE''kwQ¸SÔ)[fäÌe9g…
```

**Comment by izhangzhihao** [comment]
Have you tried restarting after editing the json file?

**Comment by danny-su** [comment]
@izhangzhihao of course.

**Comment by izhangzhihao** [comment]
I tried uninstalling and editing the JSON files as the same as you, and without error.

**Comment by izhangzhihao** [comment]
Can you try uninstall it maunally and install it by json file?

**Comment by danny-su** [comment]
@izhangzhihao I just did as you said: removed it, failed to find it, and then updated the settings JSON file manually.

**Comment by danny-su** [comment]
@izhangzhihao I downloaded the file “izhangzhihao.fleet.rainbow.brackets-frontendImpl-0.2.4.jar”, can I install it manually?

**Comment by izhangzhihao** [comment]
No, it not possible right now, JetBrains does not provide a way to manually install a plugin for Fleet now.

**Comment by izhangzhihao** [comment]
Or you can wait until 5.28, because I just released 0.2.5
I guess there are some release issues in ver 0.2.4

**Comment by izhangzhihao** [comment]
ver 0.2.5 available now, pls try again

**Comment by tyumen-777** [comment]
I have same problem. Color brackets is not working. 
my settings json is 
`{
     "plugins": [
        {
            "type": "add",
            "pluginName": "izhangzhihao.fleet.rainbow.brackets"
        }
     ],
    "rainbow.brackets.version": "0.6.1",
    "theme": "dark-edited",
    "editor.ligatures": false,
    "internalMode": true
}`
