### ISSUE TITLE
Failed to rainbowify tag name in .tsx files

### ISSUE THREAD

**Issue by nanlan2017** [izhangzhihao/intellij-rainbow-brackets#2740]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Typescript, Vue

### Free or paid?

Paid users

### Expected Behavior

I checked 'rainbowify tag name' and has customized colors for angle brackets, It works as expected in .vue files, but in .tsx files, the bracket '<>' and the tag name are in different colors. Is .tsx supported?
![rainbow-set-1](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/25033914/00a94739-bb23-4180-9e93-a4aeed167ac8)
![rainbow-set-2](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/25033914/d98012f8-0497-4eb6-8538-569a65f5a89d)
![rainbow-custom](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/25033914/f86d64c4-f526-4bdc-8f35-a020b7bc2db1)

### Current Behavior

![rainbow-problem](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/25033914/a68131df-789b-4ce8-8d97-1d412678a26a)

### Code snippet for reproduce

.tsx file:
export default defineComponent({
  name: 'loginBanner',
  setup() {
    return () => (

      <div>
        <div>
          <div>
            <div>
              <div>
                <div>
                  <div>
                    <div>
                      <div>
                        <div>
                          dsdfdssd
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
})

### Your Environment

WebStorm 2024.1
Build #WS-241.14494.235, built on March 27, 2024
Licensed to json yin
Subscription is active until March 8, 2025.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  MultiHighlight (3.1.0)
  com.nasller.CodeGlancePro (1.8.3-241)
  com.myoutdesk.tailwind_formatter (2.0.10)
  com.amazon.codewhisperer.jetbrains (1.0.3)
  com.mallowigi.imageicon (14.0.0)
  com.wakatime.intellij.plugin (14.3.13)
  com.laravel_idea.tailwind (1.4.2)
  com.clutcher.comments_highlighter (2024.1.15)
  com.vlnabatov.alabaster (1.0.76)
  tv.twelvetone.intellij.plugins.intellivue (1.2.0)
  com.shen.plugin.element (2.0)
  izhangzhihao.rainbow.brackets (2024.2.3-241)

**Comment by izhangzhihao** [comment]
Pls try the latest version（an update already got published）
