### ISSUE TITLE
[IDEA-328501] Support semantic highlighting for Dart / Support Rainbow Variables for Dart

### ISSUE THREAD

**Issue by Arbureva** [izhangzhihao/intellij-rainbow-brackets#2741]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Dart

### Free or paid?

Paid users

### Expected Behavior

Dart variables color

### Code snippet for test

```dart
import 'package:flutter/material.dart';
import 'dart:io';

class WiFiSerialCommunication extends StatefulWidget {
  @override
  _WiFiSerialCommunicationState createState() => _WiFiSerialCommunicationState();
}

class _WiFiSerialCommunicationState extends State<WiFiSerialCommunication> {
  Socket? _socket;

  void connectToDevice(String ip, int port) async {
    try {
      _socket = await Socket.connect(ip, port);
      print('Connected to: ${_socket!.remoteAddress.address}:${_socket!.remotePort}');

      // Listen for responses from the server
      _socket!.listen((data) {
        print('Received: ${String.fromCharCodes(data)}');
      });
    } catch (e) {
      print('Failed to connect: $e');
    }
  }

  void sendMessage(String message) {
    if (_socket != null) {
      _socket!.add(utf8.encode(message));
    }
  }

  @override
  void dispose() {
    _socket?.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Wi-Fi Serial Communication'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                connectToDevice('192.168.1.100', 23); // Replace with your device IP and port
              },
              child: Text('Connect to Device'),
            ),
            ElevatedButton(
              onPressed: () {
                sendMessage('Hello Device');
              },
              child: Text('Send Message'),
            ),
          ],
        ),
      ),
    );
  }
}

```

### Your Environment

Android Studio Koala | 2024.1.1 RC 1
Build #AI-241.15989.150.2411.11887322, built on May 25, 2024
Runtime version: 17.0.10+0--11609105 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 20
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.marketplace (241.15989.199)
  Dart (241.17502)
  izhangzhihao.rainbow.brackets (2024.2.4-241)
  io.flutter (79.2.3)
  cn.yiiguxing.plugin.translate (3.6.1)

**Comment by izhangzhihao** [comment]
I made some searches, I found that: [IDEA-328501  Support semantic highlighting for Dart ](https://youtrack.jetbrains.com/issue/IDEA-328501) opened 7 years before.

So, without IDE's support, I can only do rule-based syntax highlighting, similar issues may happen like #2709

Currently, a modified version:
<img width="835" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/c404e4a6-5477-4839-89d7-a13886b20d85">



[intellij-rainbow-brackets-2024.2.4-241.zip](https://github.com/user-attachments/files/15586560/intellij-rainbow-brackets-2024.2.4-241.zip)
