### ISSUE TITLE
Most Indent Guides Do Not Appear on Blade Files.

### ISSUE THREAD

**Issue by krlmrr** [izhangzhihao/intellij-rainbow-brackets#2742]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

PHP / Laravel

### Free or paid?

On trial

### Expected Behavior

I would expect to see all indent guide (ideally except the outer most indent guide)

### Current Behavior

<img width="749" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/34105282/0cd331ee-cc24-4b64-a0cb-629be02a3e40">

For some reason, only the inner most indent guides show up.

### Code snippet for reproduce

<div>
    <div class="hidden lg:block absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
        <img
            class="aspect-[3/2] object-cover lg:aspect-auto lg:h-full lg:w-full"
            src="{{ asset('assets/lotus.jpg') }}"
            alt="Lotus8 Event Photo"
        >
    </div>
</div>

### Your Environment

PhpStorm 2024.1.1
Build #PS-241.15989.102, built on April 23, 2024
Licensed to Karl Murray
You have a perpetual fallback license for this version.
Subscription is active until May 12, 2025.
Runtime version: 17.0.10+1-b1207.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  project.tree.structure.show.url=false
  run.processes.with.pty=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.myoutdesk.tailwind_formatter (2.0.10)
  com.github.catppuccin.jetbrains_icons (1.4.0)
  tailwind.fold.tailwind-fold (1.1)
  IdeaVIM (2.12.0)
  com.intellij.ml.llm (241.15989.195)
  ru.adelf.idea.dotenv (2024.1)
  izhangzhihao.rainbow.brackets (2024.2.4-241)
  com.chrisrm.idea.MaterialThemeUI (9.3.1)
  com.laravel_idea.plugin (8.1.4.241)

**Comment by izhangzhihao** [comment]
I do believe this is an IDE issue, pls raise a ticket here: https://youtrack.jetbrains.com/issues/WI

**Comment by izhangzhihao** [comment]
This plugin only highlights existing indent guidelines, but does not create it. if the indent guide lines do not exist, pls raise a ticket for JetBrains.
