### ISSUE TITLE
REOPEN REQUEST: Please: RB not functioning in PyCharm 2023.3.2 (Professional Edition)  #2705

### ISSUE THREAD

**Issue by awardblvr** [izhangzhihao/intellij-rainbow-brackets#2746]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

See Original #2705

### Free or paid?

Paid users

### Expected Behavior

See Original #2705

### Current Behavior

See Original #2705

### Code snippet for reproduce

See Original #2705

### Your Environment

See Original #2705

**Comment by izhangzhihao** [comment]
please check:

- [ ] does it works with other IDE for you? is it only does not work with PyCharm?
- [ ] can you check Python is not in the blacklist? and mark sure you didn't check the first level options
<img width="735" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/72a24466-0285-4316-b24c-25cb72cc846f">

- [ ] can you check the color numbers not 0 or less? 
<img width="713" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/0526594d-b221-4d6e-a321-9eb30c7c7680">

- [ ] can you check you didn't change all the colors to white? open `settings -> Edirot -> Color Schemes -> Rainbow Brackets` , can you try reset to the default color ans restart? 
<img width="702" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/6f623e79-d414-4c16-ab9c-ecc4f18a715c">

- [ ] can you try Random color generator?  
<img width="721" alt="image" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/12044174/7e51dd89-b65f-4574-aee0-a22bc889c79a">

**Comment by izhangzhihao** [comment]
Closed for no updates
