### ISSUE TITLE
Bug colors in Blade template

### ISSUE THREAD

**Issue by olegopro** [izhangzhihao/intellij-rainbow-brackets#2749]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

php

### Free or paid?

None

### Expected Behavior

Normal highlight in blade templates

### Current Behavior

<img width="1383" alt="Снимок экрана 2024-07-04 в 17 25 28" src="https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/73001865/6da161c8-4599-4261-8317-71cdaf84430f">

### Code snippet for reproduce

Bracket highlighting is not working correctly in Blade templates (.blade.php). The syntax highlighting breaks, particularly around Blade directives such as  **foreach**,  **if**, etc.

### Your Environment

Build #PS-241.18034.69, built on June 21, 2024
RainbowBrackets 2024.2.4-241

**Comment by izhangzhihao** [comment]
Duplicated with #2742
