### ISSUE TITLE
In HTML, the vertical color will not appear if there is commented code.

### ISSUE THREAD

**Issue by jayesh-bhadani** [izhangzhihao/intellij-rainbow-brackets#2751]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

Java, thymeleaf

### Free or paid?

Free users

### Expected Behavior

The color of the vertical line needs to be visible.

### Current Behavior

![image](https://github.com/user-attachments/assets/e66f9bf8-ca14-4b83-863e-c46c03eb4d90)

### Code snippet for reproduce

![image](https://github.com/user-attachments/assets/e66f9bf8-ca14-4b83-863e-c46c03eb4d90)

### Your Environment

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 20, 2024
Licensed to kiddy inseams
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.xwinkeymap (211.4961.30)
  com.jetbrains.space (241.18034.4)
  com.intellij.plugins.gnomekeymap (213.4250.391)
  org.dnltsk.mapfileplugin (7.0#0.5.2)
  com.intellij.spring.websocket (241.14494.158)
  String Manipulation (9.14.1)
  com.intellij.ml.llm (241.18034.12)
  com.haulmont.jpab (241.15989.21)
  izhangzhihao.rainbow.brackets (2024.2.4-241)
  zielu.gittoolbox (500.2.10+233)
Kotlin: 241.18034.62-IJ

**Comment by izhangzhihao** [comment]
Ah, I see, you mean 'commented' code, then this is the IDE issue since this plugin does not create new indent lines or vertical lines, this plugin highlights it, if the IDE won't generate indent lines or vertical lines, this plugin could not possible to highlighting.

**Comment by izhangzhihao** [comment]
You can report this to JetBrains: https://youtrack.jetbrains.com/issues
