### ISSUE TITLE
Incorrect Rainbow Bracket Coloring in TypeScript and Vue Files

### ISSUE THREAD

**Issue by olegopro** [izhangzhihao/intellij-rainbow-brackets#2754]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

TypeScript, Vue

### Free or paid?

Paid users

### Expected Behavior

When the "Enable rainbow angle brackets" option is disabled, angle brackets should not be highlighted in different colors.

### Current Behavior

Even with the "Enable rainbow angle brackets" option disabled, angle brackets are still highlighted in different colors in TypeScript and Vue files.

### Code snippet for reproduce

Record<SensorConditionType, BadgeColor>

### Your Environment

Build #PS-241.18034.69,  Rainbow Brackets 2024.2.5-241

**Comment by izhangzhihao** [comment]
Any screenshots? because I could not reproduce this:  

when enable rainbow angle brackets: <img width="832" alt="image" src="https://github.com/user-attachments/assets/5583063d-8790-4579-9603-8b24478afeb8">  


when disable rainbow angle brackets: <img width="848" alt="image" src="https://github.com/user-attachments/assets/4bcf612d-a56e-4351-9dcd-88429d42ac87">  it works as expected.

**Comment by olegopro** [comment]
<img width="721" alt="Снимок экрана 2024-07-22 в 12 34 47" src="https://github.com/user-attachments/assets/140f25a3-823d-4e28-8b93-88c7b0034738">
<img width="1329" alt="Снимок экрана 2024-07-22 в 12 36 53" src="https://github.com/user-attachments/assets/bec9e4f3-d744-439e-b441-5008f8cec8c3">

**Comment by izhangzhihao** [comment]
Can you provide your IDE env? click copy and post it here.

<img width="474" alt="image" src="https://github.com/user-attachments/assets/83f54db1-3b56-4e25-a0fb-ee3ff5e232da">

**Comment by olegopro** [comment]
PhpStorm 2024.1.4
Build #PS-241.18034.69, built on June 21, 2024
Licensed to Trial User
Subscription is active until August 11, 2024.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  project.tree.structure.show.url=false
  run.processes.with.pty=TRUE
  toolwindow.disable.overlay.by.double.key=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.ideolog (222.3.2.0)
  monokai-pro (1.10)
  ru.adelf.idea.dotenv (2024.1)
  de.espend.idea.php.annotation (10.0.0)
  com.mallowigi (97.0.0)
  izhangzhihao.rainbow.brackets (2024.2.5-241)
  tv.twelvetone.intellij.plugins.intellivue (1.2.10)
  com.laravel_idea.plugin (8.2.1.241)

**Comment by izhangzhihao** [comment]
If you think this is highlighted by this plugin, pls try  nested angle brackets or adjust the color to red and check what happened after it's disabled

**Comment by olegopro** [comment]
I found the issue: the "Apply colors of round for all brackets" state causes the problem. When I disable "Apply colors of round for all brackets," everything works as expected.

**Comment by izhangzhihao** [comment]
Cool
