### ISSUE TITLE
Indent guides not working on CLion if `Use the ReSharper C++ language engine(Clion Nova)` turns one

### ISSUE THREAD

**Issue by grhawk** [izhangzhihao/intellij-rainbow-brackets#2757]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

C++

### Free or paid?

Paid users

### Expected Behavior

I would expect the indent guidelines to be colored according to the rainbowbrackets colors. Attached the settings screenshots.

<img width="969" alt="image" src="https://github.com/user-attachments/assets/3bbb3194-3269-482e-b757-4df1469d8a27">
<img width="974" alt="image" src="https://github.com/user-attachments/assets/bb77444e-9309-484a-8a35-d7522ac8d516">
<img width="970" alt="image" src="https://github.com/user-attachments/assets/919942f7-7eea-4afc-8e00-bf644ae34911">

### Current Behavior

The indent guides are not colored. 
Possibly important detail: Changing the "paid features" in the "indent and scope" tab does not trigger the `apply` button change that remains greyed out and not clickable. 

example: 
<img width="657" alt="image" src="https://github.com/user-attachments/assets/6dcadef5-d112-4d35-b552-2f6e64c44b73">

### Code snippet for reproduce

I posted the screenshot of the settings above

### Your Environment

CLion 2024.1.4
Build #CL-241.18034.45, built on June 18, 2024
Licensed to Meteomatics AG / Riccardo Petraglia
Subscription is active until August 17, 2024.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.18034.82)
  dk.cego.gitlab_ci_local_plugin (0.0.5)
  plantuml-parser (0.0.9)
  idea.plugin.protoeditor (241.15989.49)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  me.lensvol.blackconnect (0.6.2)
  com.intellij.mermaid (0.0.22+IJ.232)
  ru.adelf.idea.dotenv (2024.1)
  PlantUML integration (7.10.1-IJ2023.2)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  pro.bashsupport (4.2.1.241)
  com.mallowigi (97.0.0)
  zielu.gittoolbox (500.2.10+233)
  mobi.hsz.idea.gitignore (4.5.3)
  org.ideplugins.gitlab-yaml-pipeline-lint (0.0.10)
  org.sonarlint.idea (10.7.0.78874)

**Comment by izhangzhihao** [comment]
<img width="507" alt="image" src="https://github.com/user-attachments/assets/2557662c-037d-4fbb-94c6-efddff80fdb4">
Could not reproduce.

**Comment by grhawk** [comment]
@izhangzhihao , Thank you for your answer! 

Do you have any suggestions on what I should check to make it working?

**Comment by izhangzhihao** [comment]
does this sample code works for you?

```
class Vehicle {
        public:
        string brand = "Ford";
        void honk() {
            cout << "Tuut, tuut! \n" ;
            if (1 > 2) {
                cout << "Tuut, tuut! \n" ;
            }
        }
};
```

**Comment by grhawk** [comment]
@izhangzhihao I also tried disabling all "downloaded" plugin... but nothing change :(

**Comment by izhangzhihao** [comment]
- [ ] does this sample code work for you?

```
class Vehicle {
        public:
        string brand = "Ford";
        void honk() {
            cout << "Tuut, tuut! \n" ;
            if (1 > 2) {
                cout << "Tuut, tuut! \n" ;
            }
        }
};
```

- [ ] does it work for other languages? eg, yaml, javascript, html

**Comment by grhawk** [comment]
> * [ ]  does this sample code work for you? 

Nope :(

> 
> ```
> class Vehicle {
>         public:
>         string brand = "Ford";
>         void honk() {
>             cout << "Tuut, tuut! \n" ;
>             if (1 > 2) {
>                 cout << "Tuut, tuut! \n" ;
>             }
>         }
> };
> ```
> 
>  * [ ]  does it work for other languages? eg, yaml, javascript, HTML

I tried yaml. It works but it is a bit weird: for example, is this situation normal (the blue line is interrupted at the top: it was all colored in the bold way but once I move the cursor on that line,  this is what happened)?
<img width="279" alt="image" src="https://github.com/user-attachments/assets/5dcddc2a-7236-41ff-8a91-d6b1bfc8c0ca">
Something similar happens when I move the cursor down: instead of highlight the entire "guide", the highlight is constantly only on line below the cursor.

Is there a way to reset the rainbow preference to default?

**Comment by izhangzhihao** [comment]
to reset config, you need find your config and delete it then restart your IDE: https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path

**Comment by grhawk** [comment]
mmm I resetted the preferences and now ti does not even work with yaml.... :)

**Comment by izhangzhihao** [comment]
pls make sure it's checked:
<img width="751" alt="image" src="https://github.com/user-attachments/assets/50f6f1b2-f5b6-4120-995c-13ff6871fec4">

**Comment by grhawk** [comment]
@izhangzhihao 
Thank you to your suggestion. The settings were already active but restarting the IDE made the "rainbow indentation" work again with yaml file... still nothing with C++ :( 

Do you have any other suggestion? Could you share your CLion settings so that I could compare with mine and try to understand the difference?

**Comment by izhangzhihao** [comment]
```
<application>
  <component name="RainbowSettings">
    <option name="indentGuidesOptions" value="Only selected indent guide" />
    <option name="rainbowifyTagNameInXML" value="true" />
    <option name="version" value="2024.2.6-241" />
  </component>
</application>
```

**Comment by grhawk** [comment]
I tried the following steps:
1. Resetting CLion to factory settings: https://www.jetbrains.com/help/clion/configuring-project-and-ide-settings.html#restore-defaults
2. Installing only the RainbowBrackets plugin from the plugin manager
3. Copying your settings to the right file (I am quite sure that is the right file because the yaml file works fine)
4. Restarting CLion 

Yaml works fine
C++ does not

Are you sure you tested the same version of CLion?

I can also send you the entire CLion settings folder at this point... (it is anyway completely new)

![image](https://github.com/user-attachments/assets/858216cf-b691-41bd-ae4f-46737d36fa72)

**Comment by izhangzhihao** [comment]
I was using 2024.1.1, I'm right now using 2024.1.4 the same as you.

<img width="672" alt="image" src="https://github.com/user-attachments/assets/3984b7f2-b045-45f0-839f-cb9c525e9634">

**Comment by izhangzhihao** [comment]
Maybe you can contact me at izhangzhihao@hotmail.com and we can schedule a zoom meeting?

**Comment by izhangzhihao** [comment]
This [post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009746540-Vertical-indent-guides-not-working) said if using the power save mode, indent guide lines will stop working.

**Comment by izhangzhihao** [comment]
This [JB ticket](https://youtrack.jetbrains.com/issue/IJPL-26415/Cant-change-visual-guides-since-updating-to-2023.3) said, you may need to disable `File | Settings | Editor | General | Appearance | Show hard wrap and visual guides`

**Comment by izhangzhihao** [comment]
I guess this ticket may help, [Visual guides not visible with hard wrapping at 1000 set in the code style scheme](https://youtrack.jetbrains.com/issue/IDEA-355872/Visual-guides-not-visible-with-hard-wrapping-at-1000-set-in-the-code-style-scheme)

> thank you for the provided details. It seems that Hard wrap at: in your code stype settings breaks visual guides.
As a workaround you can set 999 there instead of 1000 - for me it helps to ge the visual guides back

![image](https://github.com/user-attachments/assets/5c26f30e-c2ba-4dba-941f-d8ded65b25d1)

**Comment by grhawk** [comment]
@izhangzhihao I tried both the things you suggested... but nothing works... :( I am going to contact you by email. Thank you very much!

Please, would you write it once more... It seems i cannot find it :(

**Comment by izhangzhihao** [comment]
izhangzhihao@hotmail.com

**Comment by izhangzhihao** [comment]
I can reproduce this now, after enabling CMake for the project

**Comment by izhangzhihao** [comment]
Without any code changes, just installed from the Marketplace, both CLion 2024.2 RC and Clion Nova 2024.2 RC works fine.

<img width="771" alt="image" src="https://github.com/user-attachments/assets/db8cf390-0104-4ed7-87f1-f67d85c3a939">


<img width="782" alt="image" src="https://github.com/user-attachments/assets/5a2e9c16-c90c-4b86-b69f-e5b2989fae32">

**Comment by izhangzhihao** [comment]
If anyone encounters this issue, pls **turn off** this option `Use the ReSharper C++ language engine(Clion Nova)`

<img width="672" alt="image" src="https://github.com/user-attachments/assets/8dd8e311-998b-498e-a7c5-a4879ba78a0d">

I will create a new issue for feature supporting tracking.
