### ISSUE TITLE
Make correct Compatibility Range for 0.2.4 and 0.2.5

### ISSUE THREAD

**Issue by OljaKli** [izhangzhihao/intellij-rainbow-brackets#2759]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Have you checked the internal mode turns on?

Yes

### Your programming languages

Kotlin

### Expected Behavior

In case version of Fleet is too fresh for the plugin to be supported, don't suggest 0.2.4 and 0.2.5 versions of plugin (which comparability ranges are defined until 1.99.999).
Please fix the compatibility range if possible.
Also seems that only 0.3.4. will work with Fleet now.

### Current Behavior

Old version of plugin suggested for the latest Fleet versions

### Code snippet for reproduce

=)

### Your Environment

=)

**Comment by izhangzhihao** [comment]
just hideed them, BTW, when I tried to update the compatibility range, pop-up said it succeeded, but actually, nothing happened.

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/ba3792b3-ee0b-4103-a86c-68b527dddff3">
