### ISSUE TITLE
[IJPL-159940] Rainbow Variables is still broken in 2024.2

### ISSUE THREAD

**Issue by Chieffo2021** [izhangzhihao/intellij-rainbow-brackets#2760]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Vue

### Free or paid?

Paid users

### Expected Behavior

keep Rainbow Variables works well in the .vue file

### Current Behavior

Variables will change their color between rainbow or unrainbow
<img width="695" alt="image" src="https://github.com/user-attachments/assets/ef00447c-6ae5-4b65-988e-3cd0fe8024e6">

### Code snippet for reproduce

```vue
<script setup lang="ts">
import { ProjectsCompare } from '@orginjs/oss-evaluation-components/projects-compare';

const router = useRouter();
const route = useRoute();

const repositories = (() => {
  const repos = route.query.repos as string;
  if (!repos) {
    return [];
  }
  if (typeof repos === 'string') {
    return [repos];
  }
  return repos;
})();

const removeRepo = (repoName: string) => {
  let repos = route.query.repos;
  if (!repos) return;
  repos = typeof repos === 'string' ? [repos] : repos;
  repos = repos?.filter(repo => repo !== repoName);
  router.push({
    path: route.path,
    query: { repos },
  });
};

const addRepo = (repoName: string) => {
  let repos = route.query.repos;
  if (!repos) return;
  repos = typeof repos === 'string' ? [repos] : repos;
  router.push({
    path: route.path,
    query: { repos: [...repos, repoName] },
  });
};
</script>

<template>
  <ProjectsCompare :repositories="repositories" @remove-repo="removeRepo" @add-repo="addRepo" />
</template>

<style scoped lang="less"></style>
```

### Your Environment

WebStorm 2024.2
Build #WS-242.20224.342, built on August 9, 2024
Licensed to Chieffo Chieffo
Subscription is active until March 15, 2025.
For educational use only.
Runtime version: 21.0.3+13-b509.4 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6000M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.experimental.ui.inter.font=true
  eslint.additional.file.extensions=svelte
  typescript.service.lsp.node.arguments=--max_old_space_size=4096
  terminal.new.ui=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  org.toml.lang (242.20224.155)
  de.ax.powermode (105.501)
  com.markskelton.one-dark-theme (5.11.0)
  com.intellij.ideolog (242.20224.361)
  Statistic (4.3.0)
  String Manipulation (9.14.1)
  AceJump (3.8.19)
  com.hand.ikunProgress (1.0.1)
  ru.adelf.idea.dotenv (2024.2)
  com.alibabacloud.intellij.cosy (1.3.10)
  me.rerere.unocss-intellij (1.7.1)
  com.mallowigi (97.0.0)
  zielu.gittoolbox (500.2.14+242)
  mobi.hsz.idea.gitignore (4.5.3)
  izhangzhihao.rainbow.brackets (2024.2.6-241)

**Comment by izhangzhihao** [comment]
Still an IDE issue, please vote and follow this [ticket](https://youtrack.jetbrains.com/issue/IJPL-159940/2024.2-Semantic-highlighting-work-not-fine).

**Comment by dokasheng** [comment]
> 仍然是 IDE 问题：https://youtrack.jetbrains.com/issue/IJPL-159940/2024.2-Semantic-highlighting-work-not-fine

ok，thanks

**Comment by izhangzhihao** [comment]
[UPDATE: 2024.3 EAP and 2024.2.2 and 2024.1.6 and 2023.3.8 fixed this issue.](https://youtrack.jetbrains.com/issue/IJPL-159940/2024.2-Semantic-highlighting-work-not-fine#focus=Comments-27-10654841.0-0)
