### ISSUE TITLE
rainbow variables active in a minute but soon disable

### ISSUE THREAD

**Issue by dokasheng** [izhangzhihao/intellij-rainbow-brackets#2763]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

go

### Free or paid?

On trial

### Expected Behavior

rainbow variables work

### Current Behavior

rainbow variables work a while than don't work

### Code snippet for reproduce

no code

### Your Environment

GoLand 2024.2
Build #GO-242.20224.306, built on August 7, 2024

Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.5
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 16384M
Cores: 10
Metal Rendering is ON
Registry:
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  thrift-syntax-fork (2.0.0)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  org.byted.bytesuite (2.2.2-242)
  com.codeverse (2.2.0.42)
  zielu.gittoolbox (500.2.14+242)
  cn.yiiguxing.plugin.translate (3.6.4)

**Comment by izhangzhihao** [comment]
<img width="916" alt="image" src="https://github.com/user-attachments/assets/5ae526da-7a51-470a-99c2-2887af15ad63">

**Comment by izhangzhihao** [comment]
if you mean some variables are not rainbowified, then duplicate with #2760

**Comment by dokasheng** [comment]
![20240815-204813](https://github.com/user-attachments/assets/f7989bac-1f2e-46ef-a027-ea4c3e721282)
一样的配置

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by dokasheng** [comment]
![image](https://github.com/user-attachments/assets/c33dcc07-bce0-44d5-b2ce-55dbb69bc2ec)
不是个别没有，是过一会儿就全没了，刚开始还有，有时候编辑一下代码又能变回来

**Comment by dokasheng** [comment]
![image](https://github.com/user-attachments/assets/b85134b7-768b-4531-a87c-1799ceb7b83a)
不确定是不是goland的问题

**Comment by izhangzhihao** [comment]
It's an IDE issue, duplicated with #2760
