### ISSUE TITLE
Allow random hue color + exclude color(s), all together

### ISSUE THREAD

**Issue by jonathanlermitage** [izhangzhihao/intellij-rainbow-brackets#2766]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Java, Python, Kotlin

### Free or paid?

Paid users

### Expected Behavior

When using a color generator for rainbow variables, we can set the hue color to a specific color, or random.  
![image](https://github.com/user-attachments/assets/29b7cd5d-1712-41ec-bc7a-4d5b952c5646)
-> Ideally, I would like to set it to random, but I also want to exclude the red color, because red variables may look like errors, which is a bit confusing 😅  . So, having an option like "random, without given color(s)" would be amazing. Otherwise, an option to select multiple colors in the list. 
Thanks!

### Code snippet for test

any code

### Your Environment

IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Build #IU-242.20224.387, built on August 13, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
Kotlin analyzer version: 2.0.20-ij242-29
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 6
Registry:
  ide.slow.operations.assertion=false
  llm.generate.commit.summary=true
  feature.suggester.enable.suggesters=true
  markdown.open.vcs.log.link=true
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.intellij.classic.ui (242.20224.159)
  lermitage.ij.all.pack (2024.7.2)
  com.ultrahob.zerolength.plugin (0.95)
  lermitage.intellij.ilovedevtoys (1.11.0)
  lermitage.intellij.iconviewer (1.30.0)
  name.kropp.intellij.makefile (242.20224.155)
  DevKit (242.20224.159)
  lermitage.intellij.worldclock (1.8.0)
  String Manipulation (9.14.1)
  com.intellij.properties.bundle.editor (242.20224.155)
  lermitage.jetbrains.darcula.sombre (1.12.0.192)
  com.intellij.spring.batch (242.20224.159)
  com.intellij.ml.llm (242.20224.393)
  com.intellij.grazie.pro (0.3.326)
  lermitage.intellij.nightandday (1.8.0)
  lermitage.intellij.battery.status (2.4)
  MavenRunHelper (4.28.0-IJ2022.2)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  org.mapstruct.intellij (1.7.0)
Kotlin: 242.20224.387-IJ

**Comment by izhangzhihao** [comment]
Please add red color to :
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/259bb0eb-1f93-45ff-bacd-5f43afacadf7">

from the next release, the default options would be:

```
FF0000
C02525
F88686
FFFFFF
000000
```
