### ISSUE TITLE
Temporary interaction limits enabled because Phishing Attempt via Issue Comments

### ISSUE THREAD

**Issue by izhangzhihao** [izhangzhihao/intellij-rainbow-brackets#2772]
Notice: Phishing Attempt via GitHub Issue Comments

We have identified a phishing attack initiated through comments on GitHub issues. Please do not trust or download any content from these comments. If you need any assistance or have concerns, please contact me directly via email.

有人通过 github issue 的 comments 发起钓鱼攻击，请任何人不要相信或者下载 comments 的内容，如果有需要，请通过邮件和我联系。

<img width="815" alt="image" src="https://github.com/user-attachments/assets/bad8d8b9-de14-4614-bea0-23b13ddc822a">

**Comment by izhangzhihao** [comment]
mediafire

**Comment by izhangzhihao** [comment]
gcc

**Comment by YiiGuxing** [comment]
？？？
