### ISSUE TITLE
There is no colored indent highlighting in Clion

### ISSUE THREAD

**Issue by alvolturbo** [izhangzhihao/intellij-rainbow-brackets#2774]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

C/C++

### Free or paid?

Paid users

### Expected Behavior

I have ordered a license to see colored  indents. 
Enabled this option: "Show rainbow indent guides"
Ident guides highight option: "All indent guide related"
Current scope highlight option: "Highlight"
Seted highlight effect strength approximate in the middle of the range
I'd like to see result like on the help info screenshots.

![image](https://github.com/user-attachments/assets/6d211410-244f-457e-b12d-6565cc85f39b)

### Current Behavior

Instead of indent highlight with different colours i can see the same default colour everywhere. I still could see just different colors for brackets pairs only.

![image](https://github.com/user-attachments/assets/66cd6138-4a0f-44ae-ba1a-337a41c90fee)

### Code snippet for reproduce

```shell
for (u8 i = 0; i < condition; i++) {
	if ((((data.state[pos].state_cur.data.bit_cur >> (i + CONST)) & 0x01) > 0) && (((data.state[pos].state_cur.data.bit_old >> i) & 0x01) == 0)) {
		data.state[pos].parameter[i] = 1; // comment
	} else {
		data.state[pos].parameter[i] = 0;
		if (((data.state[pos].state_cur.sl.bit_cur >> (i + CONST)) & 0x01) != ((data.state[pos].state_old.sl.bit_cur >> (i + CONST)) & 0x01)) {
			// if was pressed make release
			memset(&obj, 0, sizeof(cfg_obj_t));
			obj.fields.chan   = chan;
			obj.fields.index  = index;
			obj.fields.num    = i;
			obj.fields.type   = sig_type;
			if (((data.state[pos].state_cur.sl.bit_cur >> SELECTOR_SHIFT) & 0x01) > 0) {
				obj.fields.sub_fun_type = CFG_FUN;
			}
			_cfg_process(&obj, ((data.state[pos].state_cur.sl.bit_cur >> i) & 0x01),  &cfg_events);
		}
	}
```

### Your Environment

CLion 2024.2.1
Build #CL-242.21829.173, built on August 30, 2024
Licensed to Alexey
You have a perpetual fallback license for this version.
Subscription is active until August 15, 2025.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4080M
Cores: 12
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  debugger.watches.in.variables=false
  debugger.attach.dialog.enabled=true
  documentation.show.toolbar=true
  run.processes.with.pty=TRUE
  terminal.use.conpty.on.windows=false
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
  cache.folding.model.on.disk=false
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.21829.162)
  org.editorconfig.editorconfigjetbrains (242.20224.214)
  Scratch (1.13)
  Batch Scripts Support (1.0.13)
  de.platon42.m68k (0.10)
  MultiHighlight (3.2.0)
  BrowseWordAtCaret (3.0.5-custom)
  com.nasller.CodeGlancePro (1.9.0)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  SerialPortMonitor (242.21829.220)
  org.jetbrains.plugins.stylus (242.20224.155)
  cn.jxzhang.plugin.json-formatter (1.4)
  com.intellij.ideolog (242.21829.162)
  com.godwin.json.parser (1.7.1)
  com.intellij.properties (242.20224.155)
  String Manipulation (9.14.1)
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  com.intellij.plugin.adernov.powershell (2.7.0)
  GrepConsole (13.1.0-IJ2023.3)
  com.intellij.ml.llm (242.21829.196)
  com.dethlex.numberconverter (2.1.1)
  de.femtopedia.openocd (0.3.8)
  net.seesharpsoft.intellij.plugins.csv (3.4.0-242)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  org.exbin.deltahex.intellij (0.2.10.1)
  com.mallowigi.colorHighlighter (18.0.0)
  cn.yiiguxing.plugin.translate (3.6.4)
  zielu.gittoolbox (500.2.15+242)
  artsiomch.cmake (242.0.1-EAP)

**Comment by izhangzhihao** [comment]
Duplicate with #2762

**Comment by izhangzhihao** [comment]
### Current workaround

disable the option: ReSharper C++ language engine

<img width="672" alt="image" src="https://github.com/user-attachments/assets/8dd8e311-998b-498e-a7c5-a4879ba78a0d">

**Comment by izhangzhihao** [comment]
Closed since no update and duplicated.
