### ISSUE TITLE
com.intellij.module.xml is needed for IJ 2024.3

### ISSUE THREAD

**Issue by jonathanlermitage** [izhangzhihao/intellij-rainbow-brackets#2775]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Java

### Free or paid?

Paid users

### Expected Behavior

Just for info, IDE 2024.3 (a first EAP has been published today) now requires the com.intellij.module.xml module. Please see attached screenshot: 
![image](https://github.com/user-attachments/assets/a4cb5f00-e289-4875-b766-050686135896)

### Current Behavior

*

### Code snippet for reproduce

```shell
*
```

### Your Environment

IntelliJ IDEA 2024.3 EAP (Community Edition)
Build #IC-243.12818.47, built on September 11, 2024
Runtime version: 21.0.4+8-b589.3 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
Kotlin plugin: K2 mode (Beta)
Kotlin analyzer version: 2.1.0-dev-5765
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4060M
Cores: 6
Registry:
  ide.text.fractional.metrics=[Auto|Disabled*|Enabled]
  editor.text.fractional.metrics=[Auto|Disabled*|Enabled]
  ide.slow.operations.assertion=false
  i18n.locale=
  markdown.open.vcs.log.link=true
  llm.generate.commit.summary=true
Non-Bundled Plugins:
  com.intellij.classic.ui (243.12818.47)
  org.jetbrains.plugins.workspace (243.12818.47)
  DevKit (243.12818.47)
  lermitage.intellij.iconviewer (1.31.0)
  lermitage.jetbrains.darcula.sombre (1.12.0.192)
  Lombook Plugin (243.12818.47)
  com.intellij.uiDesigner (243.12818.47)
  lermitage.ij.all.pack (2024.9.1)
  com.intellij.grazie.pro (0.3.329)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  com.intellij.ml.llm (243.12818.47)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
Kotlin: 243.12818.47-IJ

**Comment by izhangzhihao** [comment]
I installed both the Community and Ultimate of 2024.3, didn't see this pop up

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/5f2008c3-7b53-4875-ad8a-ceafe8ca2fe8">

Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

Might related to https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2408

**Comment by izhangzhihao** [comment]
Add requires plugin 'com.intellij.modules.xml' to be installed for SEO.

**Comment by jonathanlermitage** [comment]
Hum, weird. After an IDE restart, I no longer see the error message. Tag names are rainbowified in YAML files and XML files, but variable names are no longer rainbowified in Java files. No error or warnings in idea.log.  
I'm not using JetBrains Client / Code With Me / IntelliJ Remote Development.

**Comment by izhangzhihao** [comment]
To enable rainbow variables,you may need enable the option in the settings

**Comment by izhangzhihao** [comment]
Closed since can not reproduce, even reproduced it's still an IDE issue.

**Comment by rparree** [comment]
I have the same problem. Restart does not help. It only occurs when using a Remote SSH session.

**Comment by TheChilliPL** [comment]
Happened to me when running RustRover on WSL2. Rainbow Brackets was installed on the client IDE but not the server. Installing it on the server as well fixed it.

**Comment by heyitsmdr** [comment]
> Happened to me when running RustRover on WSL2. Rainbow Brackets was installed on the client IDE but not the server. Installing it on the server as well fixed it.

Worked for me! Thank you very much :)

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
