### ISSUE TITLE
Color variant not working on Android Studio Preview  

### ISSUE THREAD

**Issue by ThuanPx** [izhangzhihao/intellij-rainbow-brackets#2776]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

kotlin

### Free or paid?

On trial

### Expected Behavior

I have enabled rainbow variables but it is not working.
<img width="752" alt="image" src="https://github.com/user-attachments/assets/57cdf7dd-da69-4294-ac49-766e1e004f11">
<img width="751" alt="image" src="https://github.com/user-attachments/assets/2d7d3642-61cd-48b0-a558-fe1467ea2106">
<img width="814" alt="image" src="https://github.com/user-attachments/assets/d06ecd3a-7163-4b37-857b-33f3b8e49d2d">

### Current Behavior

Nothing happens when this feature is enabled

### Code snippet for reproduce

```shell
None.
```

### Your Environment

Android Studio Ladybug | 2024.2.1 Beta 2

**Comment by izhangzhihao** [comment]
If this is your first time enable this option, you may need restart. this may related to https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2760 since Android Studio based on Intellij.

**Comment by ThuanPx** [comment]
I tried restarting, deleting the app, and reinstalling it but the feature still doesn't work.

**Comment by izhangzhihao** [comment]
Pls don't check "I will enable semantic highlights  myself", because you didn't enable it yourself.

**Comment by ThuanPx** [comment]
I did it and it worked, thank you very much.
