### ISSUE TITLE
Jetbrains Gateway can not enable

### ISSUE THREAD

**Issue by sinoon** [izhangzhihao/intellij-rainbow-brackets#2777]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

JavaScript

### Free or paid?

Free users

### Expected Behavior

<img width="1209" alt="image" src="https://github.com/user-attachments/assets/7fe614e4-ef4e-4e00-b852-fe8d4852fd38">
By Gateway stated Client, can not enable this plugin

### Current Behavior

default can not enable and with error:

需要安装 com.intellij.modules.xml

### Code snippet for reproduce

```shell
nope
```

### Your Environment

WebStorm 2024.1

**Comment by izhangzhihao** [comment]
Duplicate with https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2656

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
