### ISSUE TITLE
Rainbow variables don't work in Rider

### ISSUE THREAD

**Issue by tbeest** [izhangzhihao/intellij-rainbow-brackets#2778]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

C#

### Free or paid?

Paid

### Expected Behavior

I would expect variables to be rainbowified when the setting is turned on.

### Current Behavior

However that doesn't appear to work. 

I have turned off all downloaded plug-ins, save for Rainbow Brackets.  
I have tried re-enabling the setting, as well as turning on/off the color generator options.
I am using the default dark theme for Rider.
![image](https://github.com/user-attachments/assets/53df617d-666b-47a4-a54b-b953fb8456c0)
![image](https://github.com/user-attachments/assets/eb92f682-a2b6-42ab-b295-213b01faa0f1)

### Code snippet for reproduce

```shell
public class MyClass
{
    public void MyMethod()
    {
        string myString = "";
        int myInt = 0;
        bool myBool = false;
        
        Console.WriteLine(myString + myInt + myBool);
    }
}
```

### Your Environment

JetBrains Rider 2024.2.4
Build #RD-242.21829.210, built on September 6, 2024
Licensed to [...]
Subscription is active until [...]
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4054M
Cores: 16
Registry:
  ide.balloon.shadow.size=15
  ide.lookup.shrink=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  izhangzhihao.rainbow.brackets (2024.2.6-241)

**Comment by izhangzhihao** [comment]
Pls don't check "I will enable semantic highlights myself"

**Comment by tbeest** [comment]
I have that option disabled.

<details>
<summary> Settings screenshots </summary>

![image](https://github.com/user-attachments/assets/54c55f40-0a90-439a-92f6-a2799157f7dc)
![image](https://github.com/user-attachments/assets/4bdffded-633e-41ec-8349-5f2193c0cd6a)
![image](https://github.com/user-attachments/assets/21319cd5-61c7-4106-9d8a-803e488142a4)
![image](https://github.com/user-attachments/assets/d8b64dd8-9363-4566-85dc-2ca606522678)
![image](https://github.com/user-attachments/assets/568d9b41-d4ef-4c27-928a-778d15a38677)
![image](https://github.com/user-attachments/assets/2f4fb7f2-0829-4024-80c5-e2d5c6b74a0f)

</details>

**Comment by izhangzhihao** [comment]
please search "semantic highlights" and check it checked

<img width="976" alt="image" src="https://github.com/user-attachments/assets/4b453321-63a4-4d43-8bae-6d708a4e20e1">

**Comment by izhangzhihao** [comment]
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/d2b0948e-b258-4d34-8ce0-a39b84520226">

<img width="984" alt="image" src="https://github.com/user-attachments/assets/b6161988-0dd7-47ed-90a9-8d4f642b826a">

**Comment by izhangzhihao** [comment]
ref #2656

**Comment by tbeest** [comment]
![image](https://github.com/user-attachments/assets/18f55e47-13c6-4cef-9ee5-c6d0425d4e4a)

**Comment by izhangzhihao** [comment]
please check:
<img width="971" alt="image" src="https://github.com/user-attachments/assets/ad6a9117-e794-4397-8576-6750293977c9">

Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

**Comment by izhangzhihao** [comment]
Closed since no update, if still not working, pls leave comments.
