### ISSUE TITLE
requires com.intellij.modules.xml on Pycharm pro when opend through gateway. Free version works

### ISSUE THREAD

**Issue by Liquidmasl** [izhangzhihao/intellij-rainbow-brackets#2779]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

Python

### Free or paid?

Paid users

### Expected Behavior

Rainbow brackets shoudl work on remote pycharm startet via gateway 

Especially because the free version works fine, and the paid does not?

### Current Behavior

![image](https://github.com/user-attachments/assets/e5c98602-d0e4-450d-9a8f-be4049044d15)

### Code snippet for reproduce

```shell
-
```

### Your Environment

PyCharm 2024.2.1
Build #JBC-242.21829.153, built on August 29, 2024
Licensed to Marcel Winklmüller
Subscription is active until November 10, 2024.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
Controller in Remote Development
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 1500M
Cores: 20
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.intellij.plugins.github.colorscheme (242.20224.159)
  com.intellij.plugins.warmneon.colorscheme (242.20224.155)
  ru.adelf.idea.dotenv (2024.2.1)
  com.intellij.plugins.monokai.colorscheme (242.20224.159)
  com.github.copilot (1.5.22.6765)
  com.intellij.plugins.twilight.colorscheme (242.20224.159)

**Comment by izhangzhihao** [comment]
ref #2656

**Comment by izhangzhihao** [comment]
Important note https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2656#discussioncomment-7209151

> Just did some research, and I found that the JetBrains Client/Gateway does not support paid plugins at all: https://youtrack.jetbrains.com/issue/GTW-2304/JetBrains-Client-does-not-allow-me-to-use-paid-plugin

**Comment by Liquidmasl** [comment]
> Important note [#2656 (reply in thread)](https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2656#discussioncomment-7209151)
> 
> > Just did some research, and I found that the JetBrains Client/Gateway does not support paid plugins at all: https://youtrack.jetbrains.com/issue/GTW-2304/JetBrains-Client-does-not-allow-me-to-use-paid-plugin

oh wow.. how does that make sense.. thanks for finding that!

**Comment by izhangzhihao** [comment]
pls download experimental JetBrains Client support from https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888@@===
