### ISSUE TITLE
Have to restart Rider often to get the colors back

### ISSUE THREAD

**Issue by jansviland** [izhangzhihao/intellij-rainbow-brackets#2785]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

No

### Your programming languages

C#

### Free or paid?

Paid users

### Expected Behavior

That colors work

## DEMO
https://github.com/user-attachments/assets/df6d24ff-c483-44df-896d-f178f350c5e3

### Code snippet for reproduce

```shell
Happens to the entire project, not a snippet of code
```

### Your Environment

```shell
JetBrains Rider 2024.2.1
Build #RD-242.20224.418, built on August 19, 2024
Licensed to xxx
Subscription is active until May 24, 2025.
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4082M
Cores: 12
Registry:
  ide.lookup.shrink=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  IdeaVIM (2.16.0)
  avalonia-rider (1.5.1)
  fr.socolin.application-insights-debug-log-viewer (2024.2.0)
  com.samdark.intellij-visual-studio-code-dark-plus (2.9.0)
  com.intellij.plugin.adernov.powershell (2.7.0)
  com.github.copilot (1.5.24.6840)
  com.intellij.resharper.azure (4.2.0)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
```

**Comment by izhangzhihao** [comment]
Duplicate with #2760

**Comment by izhangzhihao** [comment]
Please do search before you open an issue.

[UPDATE: 2024.3 EAP and 2024.2.2 and 2024.1.6 and 2023.3.8 fixed this issue.](https://youtrack.jetbrains.com/issue/IJPL-159940/2024.2-Semantic-highlighting-work-not-fine#focus=Comments-27-10654841.0-0)

**Comment by jansviland** [comment]
I see that you set this issue to fixed, but I still have the same issue: 

![Screenshot 2024-10-28 at 12 35 18](https://github.com/user-attachments/assets/0425c7da-4089-4c95-bb2f-efc350a5b32b)

This is from today, I use version 2024.2.6-241 of the plugin and the latest version of Rider.

**Comment by izhangzhihao** [comment]
Pls do leave your comment [here](https://youtrack.jetbrains.com/issue/IJPL-159940/2024.2-Semantic-highlighting-work-not-fine#focus=Comments-27-10654841.0-0)
