### ISSUE TITLE
Disable rainbow brackets for specific languages not working

### ISSUE THREAD

**Issue by dang-coralogix** [izhangzhihao/intellij-rainbow-brackets#2789]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

No

### Your programming languages

TS

### Free or paid?

Free users

### Expected Behavior

If I add html to the disable rainbow brackets for specific languages I expect no brackets color in html files.

### Current Behavior

It still color the brackets

<img width="988" alt="image" src="https://github.com/user-attachments/assets/a6cdd045-fde7-4b9f-8b3e-97f5bddc83a0">

### Code snippet for reproduce

```shell
see img
```

### Your Environment

```shell
WebStorm 2024.2.4
Build #WS-242.23726.96, built on October 22, 2024
Subscription is active until October 26, 2025.
Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 11
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  String Manipulation (9.14.1)
  com.mallowigi (97.0.0)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  com.github.dinbtechit.vscodetheme (1.10.12)
```

**Comment by izhangzhihao** [comment]
You can try disable this option if you like:
<img width="460" alt="image" src="https://github.com/user-attachments/assets/c8dcfcd8-c569-4244-ab79-f4d7bf09bb10">

**Comment by dang-coralogix** [comment]
Thats a nice work around but will not solve the main issue.

**Comment by izhangzhihao** [comment]
pls try this build snapshot: 
[intellij-rainbow-brackets-2024.2.7-241.zip](https://github.com/user-attachments/files/17782685/intellij-rainbow-brackets-2024.2.7-241.zip)
