### ISSUE TITLE
Disable update notification

### ISSUE THREAD

**Issue by ruudk** [izhangzhihao/intellij-rainbow-brackets#279]
I love rainbow brackets and love it that you make so many new releases. But after installing 4 updates over the last 2 weeks, I am notified with "you are now on version X" popup 4 times.

Is there a way to disable these notifications?

**Comment by vvreutskiy** [comment]
@ruudk you can disable it in IDE Settings/Appearance & Behaviour/Notifications by setting group "izhangzhihao.rainbow.brackets" to "No popup"

**Comment by ruudk** [comment]
I have this disabled:
<img width="706" alt="Screenshot 2019-12-20 at 12 07 40" src="https://user-images.githubusercontent.com/104180/71251007-698d9200-2321-11ea-9637-8c9c37e6f688.png">

But today I saw this again:
<img width="541" alt="Screenshot 2019-12-20 at 12 07 48" src="https://user-images.githubusercontent.com/104180/71251025-71e5cd00-2321-11ea-963c-f27c1c8d2f6b.png">

**Comment by ruudk** [comment]
I guess this happened when I updated to the latest PHPStorm. Somehow, some settings were lost :(

**Comment by izhangzhihao** [comment]
This is because the notification channel had been changed. Now the channel id won't be changed. So you could block the update notification safely.

**Comment by aloker** [comment]
I'm still getting pop-ups after updates even though I've disabled them in the settings. What am I missing? I'd really appreciate if the plugin honored my choices.

![image](https://user-images.githubusercontent.com/140714/92306041-a4595800-ef8c-11ea-9255-013f656edaa8.png)

![image](https://user-images.githubusercontent.com/140714/92306051-ae7b5680-ef8c-11ea-9456-edd71e73f7b8.png)

WebStorm 2020.2.1

**Comment by ruudk** [comment]
Same here, annoying

**Comment by ralfbiedert** [comment]
I have the same issue; even more, since 6.11 I can't even dismiss the popup anymore. The `x` button does not work; clicking it repeatedly just resizes overall IDE window (CLion 2020.2.3).

**Comment by izhangzhihao** [comment]
> I have the same issue; even more, since 6.11 I can't even dismiss the popup anymore. The `x` button does not work; clicking it repeatedly just resizes overall IDE window (CLion 2020.2.3).

Any screenshots? and what is your environment? like this:
```
CLion 2020.2.1
Build #CL-202.6948.80, built on August 25, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.7.15-100.fc31.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.allow.merge.buttons=false, search.everywhere.settings=true, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=600000
Non-Bundled Plugins: name.kropp.intellij.makefile, org.jetbrains.plugins.localization, org.toml.lang, tanvd.grazi, org.rust.lang, rs.pest, izhangzhihao.rainbow.brackets
Current Desktop: KDE
```

**Comment by ralfbiedert** [comment]
```
CLion 2020.2.3
Build #CL-202.7319.72, built on September 17, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4035M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false
Non-Bundled Plugins: CMD Support, GLSL, GrepConsole, String Manipulation, com.jpospisil.gototabs, in.xiv.cs, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, mobi.hsz.idea.gitignore, izhangzhihao.rainbow.brackets, org.toml.lang, org.rust.lang, pl.szymonprz.idea-cheatsh-plugin, some.awesome
```

https://i.imgur.com/CIynxnB.mp4

(And to clarify, like the posters above, I also have pop up notifications disabled for Rainbow Brackets)

**Comment by izhangzhihao** [comment]
From the next release, you could disable the update nofitication by config this:

```xml
<application>
  <component name="RainbowSettings">
    <option name="showNotificationOnUpdate" value="false" />
  </component>
</application>
```

The config path is here: https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path

**Comment by izhangzhihao** [comment]
If you want to give a try, please follow: https://github.com/izhangzhihao/intellij-rainbow-brackets#install-snapshot-build

**Comment by ralfbiedert** [comment]
Hey, thanks for the quick turnaround. Is there any chance you could just make this a setting in here instead?

![image](https://user-images.githubusercontent.com/301288/93587024-81c23880-f9a9-11ea-89ec-4bdbe460bb8a.png)

Update - I just tried to use the preview build as described, but I ran into two issues. Since 2020.0x the paths have apparently changed; while I found the main path again under `AppData`, there was no config path and I had to create it manually; not sure if I got that one right. In addition, the link to CircleCI told me that the linked dashboard was legacy, but following the link they suggested I had to sign in with an account which I don't have. Long story short, I gave up on this for now. Once a new version is released with the fix I'll try again.

**Comment by izhangzhihao** [comment]
Add to the config page? Possibly not. It depends on how many people need it. From my view, I don't see many people who need it on the config page.

For the config path, if you didn't found the `options` path, you might run into a wrong path.

You can just sign in with your Github account.

**Comment by ralfbiedert** [comment]
> From the next release, you could disable the update nofitication by config this:

I've now added 

```
<application>
  <component name="RainbowSettings">
    <option name="showNotificationOnUpdate" value="false" />
  </component>
</application>
```

to the file 

`C:\Users\rb\AppData\Local\JetBrains\CLion2020.2\config\options\rainbow_brackets.xml`

which I believe is the proper config file. However, after the latest update to 6.12.1 I _still_ got a notification.

**Comment by robzsaunders** [comment]
Necroing because I am having this issue.

Rainbow Brackets prompts me to upgrade after every fresh idea launch despite me selecting the checkbox to stop
