### ISSUE TITLE
可以支持datagrip吗，console写sql的时候关键词高亮

### ISSUE THREAD

**Issue by sushirong** [izhangzhihao/intellij-rainbow-brackets#2790]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Your programming languages

java，python，sql

### Free or paid?

Paid users

### Expected Behavior

1

### Code snippet for test

select ROLE
from AI_DATASET_SUBSCRIBE;

### Your Environment

DataGrip 2024.2.2
Build #DB-242.21829.162, built on August 30, 2024
Licensed to 苏 世荣
Subscription is active until October 13, 2025.
For educational use only.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.nasller.CodeGlancePro (1.9.3)
  bundled-datagrip-help (242.21829.162)
  com.intellij.ml.llm (242.21829.196)
  izhangzhihao.rainbow.brackets (2024.2.7-241)

**Comment by izhangzhihao** [comment]
duplicated with #2659

**Comment by izhangzhihao** [comment]
you can try this build snapshot [intellij-rainbow-brackets-2024.2.7-241.zip](https://github.com/user-attachments/files/17783684/intellij-rainbow-brackets-2024.2.7-241.zip)
