### ISSUE TITLE
Plugin causes unified diff to lose syntax highlighting

### ISSUE THREAD

**Issue by rakusvn-dhan** [izhangzhihao/intellij-rainbow-brackets#2791]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

No

### Your programming languages

Java

### Free or paid?

Free users

### Expected Behavior

Unified diff have syntax highlighted

### Current Behavior

Unified diff have no syntax highlighted

Jetbrains blamed Rainbow Bracket: https://youtrack.jetbrains.com/issue/IJPL-101036/Advanced-syntax-highlighting-doesnt-work-in-unified-diff

I've tried disabling Rainbow Brackets and it works as expected.

### Code snippet for reproduce

```shell
none
```

### Your Environment

```shell
IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Licensed to An Duong Hong
Subscription is active until June 4, 2025.
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3072M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  documentation.show.toolbar=true
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  i18n.locale=
  wsl.proxy.connect.localhost=false
  editor.minimap.enabled=true
  coverage.filter.based.on.feature.branch=false
Non-Bundled Plugins:
  some.awesome (1.15)
  com.intellij.properties.bundle.editor (243.21565.122)
  CheckStyle-IDEA (5.98.0)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.6)
  PlantUML integration (7.11.2-IJ2023.2)
  izhangzhihao.rainbow.brackets (2024.2.7-241)
  com.chrisrm.idea.MaterialThemeUI (9.7.0)
  com.nasller.CodeGlancePro (1.9.4)
  net.labymod.intellij.singlehotswap (2.9)
  com.github.copilot (1.5.29.7524)
  zielu.gittoolbox (600.0.7+242)
  cn.yiiguxing.plugin.translate (3.6.7)
Kotlin: 243.21565.193-IJ
```

**Comment by izhangzhihao** [comment]
please download this build snapshot and give it a try: 
[intellij-rainbow-brackets-2024.2.7-241.zip](https://github.com/user-attachments/files/17748923/intellij-rainbow-brackets-2024.2.7-241.zip)

**Comment by rakusvn-dhan** [comment]
I've tried the snapshot build and it works as expected.
Thanks!
