### ISSUE TITLE
Editable theme not found when using Jetbrains Toolbox

### ISSUE THREAD

**Issue by caspre24** [izhangzhihao/intellij-rainbow-brackets#2793]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

all

### Expected Behavior

* Install Fleet via Jetbrains Toolbox
* Install Rainbow Brackets plugin
* Select "Edit Color Theme..." from Fleet plugins menu
* Save editable theme
* Restart Fleet
* Rainbow Bracket applies its changes and brackets are colorful

### Current Behavior

* After restarting, there is a popup: "Rainbow Brackets: You may need to re-create a editable copy of your current theme by action: Edit Color Theme...(And delete current theme)"
* Brackets are not colorful

Additional Info:
* When Fleet is installed via Jetbrains Toolbox, it stores the edited themes in `~/Library/Application Support/JetBrains/Fleet/themes` (on Mac). It seems like the Rainbox Brackets plugins is searching for themes in the fixed location `<home>/.fleet/themes/` (which in this case doesn't even exist)
* Creating the folder and copying the editable theme file manually to `<home>/.fleet/themes/` and restarting Fleet gives the same popup mentioned above

### Code snippet for reproduce

```shell
N/A
```

### Your Environment

Fleet version: build 1.42.88
OS: Mac OS X (14.7, aarch64)

**Comment by izhangzhihao** [comment]
You don't need creating <home>/.fleet/themes/

Just use IDE short cuts to edit a color scheme and choose the edited one.

**Comment by caspre24** [comment]
Yeah, but that doesn't work. The popup "Rainbow Brackets: You may need to re-create a editable copy of your current theme by action: Edit Color Theme...(And delete current theme)" always comes up on application start and brackets are not colored! Not matter how often I edit the theme and select the edited theme

**Comment by izhangzhihao** [comment]
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/22c31875-991a-4650-84b4-648215590aec">


<img width="1029" alt="image" src="https://github.com/user-attachments/assets/8cfb8678-6f73-4456-a5c7-00be23fac162">


<img width="465" alt="image" src="https://github.com/user-attachments/assets/8ac39832-a6ba-4795-bb54-18f6191dee4d">
