### ISSUE TITLE
[Fleet] initial setup fails sometimes 

### ISSUE THREAD

**Issue by caspre24** [izhangzhihao/intellij-rainbow-brackets#2794]
### Have you checked the issues and discussions to ensure there are no duplicates?

Yes

### Your programming languages

all

### Expected Behavior

See description of https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2793

Buddy @izhangzhihao !
I'm not stupid! I did exactly as your screenshots show and it just doesn't work, neither on MacOs nor on Linux!

<img width="1007" alt="Screenshot 2024-11-16 at 11 04 19" src="https://github.com/user-attachments/assets/16b93225-e601-41ed-b53d-c9ece71e2688">
<img width="1007" alt="Screenshot 2024-11-16 at 11 04 35" src="https://github.com/user-attachments/assets/a4919dc5-eff0-47de-9e56-a9cf650e44aa">
<img width="1288" alt="Screenshot 2024-11-16 at 11 04 54" src="https://github.com/user-attachments/assets/d5c597a1-5960-4265-b5c1-100e0bc6ce40">
<img width="1008" alt="Screenshot 2024-11-16 at 11 05 41" src="https://github.com/user-attachments/assets/8cc80eb3-acc2-40b6-ab57-e3ed68050e7b">

I used to like your work, but just closing a valid bugreport like that is just bad.

### Current Behavior

See https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2793

### Code snippet for reproduce

```shell
See https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2793
```

### Your Environment

See https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2793

**Comment by izhangzhihao** [comment]
First of all, there is nothing to do with the Toolbox.
And, I tried two times and could not reproduce your issue.

Last, maybe a restart can help.

**Comment by caspre24** [comment]
I don't really like how you're trying to frame it as if I'm too stupid to follow a few simple steps. Maybe think about what that says about your instructions.
I tried on two different computers and was not able to get it working on neither.
And of course, I tried restarting, that didn't change anything.

**Comment by izhangzhihao** [comment]
I just want to clarify that I have no idea what's causing the issue, and I simply cannot reproduce it. There’s nothing unfriendly about my approach, so please don’t take this as a personal attack. The issue is straightforward: if it can’t be consistently reproduced, we can't resolve it. That’s all there is to it.

**Comment by caspre24** [comment]
Posting a bunch of screenshots with a condescending red arrow and then closing all comments on a clearly not solved issue felt very rude. You say you don't know whats causing the issue but you also didn't even consider asking for more information to try solving it 🤷 

Since then, I tried the plugin on a third system, there it worked right away. So there seems to be something that sometimes makes the initial setup fail. I'll try finding what the difference between the systems might be. But I also kinda stopped using fleet for now since it (being still in beta) had some other issues for me, so don't expect more info soon.
