### ISSUE TITLE
Support freemarker

### ISSUE THREAD

**Issue by lexlibra88** [izhangzhihao/intellij-rainbow-brackets#2797]
### Have you checked the issues and discussions to ensure there are no duplicates?

Forks

### Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

No

### Your programming languages

java, fremarker

### Free or paid?

Paid users

### Expected Behavior

It should work when paying the annual license. I used the trial version before. When it ran out I tried the Lite and seeing that it wasn't worth it, I paid for the license. I have uninstalled the lite version and I only have the normal version but it does not work

### Current Behavior

Not working. 

### Code snippet for plays

```shell
It is not possible due to company privacy
```

### Your Environment

```shell
Intellij Ultimate
```

**Comment by lexlibra88** [comment]
![Captura desde 2024-12-09 12-28-12](https://github.com/user-attachments/assets/4e96954a-d0a2-48ff-9a6d-cef703da6cb0)

**Comment by lexlibra88** [comment]
![Captura desde 2024-12-09 12-30-10](https://github.com/user-attachments/assets/f67e0ecc-8f31-4d56-9bcf-359bfecd688f)

**Comment by izhangzhihao** [comment]
Duplicate with #2698

freemarker is not supported yet.

**Comment by lexlibra88** [comment]
The trial version worked with freemarker

**Comment by lexlibra88** [comment]
When will it be available in the paid version?

**Comment by izhangzhihao** [comment]
> The trial version worked with freemarker

Any screenshots? I’ve looked into the FreeMarker PSI tree implementation, and it’s quite a mess, making it really challenging to implement proper FreeMarker support.

**Comment by lexlibra88** [comment]
The second screenshot sent yesterday was of ftl code with fremarker

**Comment by izhangzhihao** [comment]
Syntax highlighting relies on the IDE parsing the syntax tree of the file. From your screenshot, the IDE isn't applying any syntax highlighting at all, which means it hasn't parsed the syntax tree. Without this, there's no way for rainbow brackets to work.  

Moreover, rainbow brackets currently do not support **FreeMarker** syntax. I'll merge this issue into another related one shortly.  

For now, I recommend following the IDE's steps to assign the correct file type. Right-click on the file name and let the IDE associate it with an appropriate file type. This will at least enable the built-in syntax highlighting provided by the IDE.

<img width="630" alt="image" src="https://github.com/user-attachments/assets/2c265b2a-4ddf-43bc-982d-7707a29c851b">
