### ISSUE TITLE
Support for JSX syntax

### ISSUE THREAD

**Issue by szpone** [izhangzhihao/intellij-rainbow-brackets#28]
It would be really nice to have JSX syntax supported, are there any plans to implement it?

**Comment by izhangzhihao** [comment]
Please follow the [ISSUE_TEMPLATE](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/IC-2017.2/ISSUE_TEMPLATE.md) or make a explanation for your ideas, so that I could understand your ideas clearly, thanks.

**Comment by izhangzhihao** [comment]
Going to close cause no response. Feel free to re-open it or raise a new one if you have any issue.
