### ISSUE TITLE
In the commented code, the symbols still display colors

### ISSUE THREAD

**Issue by heisajoker** [izhangzhihao/intellij-rainbow-brackets#2800]
### Have you checked the issues and discussions to ensure there are no duplicates?

No

### Are you using JetBrains Client / Code With Me / IntelliJ Remote Development?

Code With Me

### Your programming languages

Java

### Free or paid?

None

### Expected Behavior

In commented code, symbols still show color

### Current Behavior

In commented code, symbols still show color

### Code snippet for reproduction

```shell
In commented code, symbols still show color
```

### Your Environment

```shell
In commented code, symbols still show color
```

**Comment by izhangzhihao** [comment]
Duplicate with #2799

**Comment by heisajoker** [comment]
Leave your name if you have anything!
