### ISSUE TITLE
Rainbow indent guides not works in Rider 2019.2.1

### ISSUE THREAD

**Issue by sevelee** [izhangzhihao/intellij-rainbow-brackets#285]
![image](https://user-images.githubusercontent.com/8036235/66829551-2fe98500-ef86-11e9-9bbc-371c7687358f.png)

* Plugin version: 5.26
JetBrains Rider 2019.2.2
Build #RD-192.6584.65, built on August 29, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by izhangzhihao** [comment]
Yes, indent guides does not intend to work with Rider at all.
