### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by quisse** [izhangzhihao/intellij-rainbow-brackets#29]
## Expected Behavior
* Everything running smooth

## Current Behavior
* CPU rising to 100% when editing files with +2700 lines (like .less, .js,...)

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change

## Code snippet for reproduce (for bugs)
Provide code snippet

## Your Environment

* Plugin version: 3.1.1
* IDEA version: 2017.3.4
* Operating System and version: macOS 10.13.3

**Comment by izhangzhihao** [comment]
My env:
plugin version 5.0-RC1
IDEA: 2018.1-EAP
OS:  macOS 10.13.2

When I editing [this file](https://gist.github.com/rwaldron/8720084) I got CPU usage between 75% ~ 85%, even I disable the plugin and re-load IDE  still got high CPU usage between 70% ~ 80%

**Comment by izhangzhihao** [comment]
Have you tested the CPU usage when you disable the plugin?

**Comment by quisse** [comment]
Sometimes it runs smooth and sometimes it doesn't. Probably depending on how many files open & perhaps what gulp is doing etc. Looks like this will be hard to get to the cause... But i'll keep an eye on it & maybe other users also experience this.

**Comment by izhangzhihao** [comment]
Great, thanks for your feedback. I'm going to close this issue now, please feel free to re-open it or raise a new one when you have any issues. Thanks again.
