### ISSUE TITLE
Angular template support

### ISSUE THREAD

**Issue by ghost** [izhangzhihao/intellij-rainbow-brackets#3]
Does not Work in HTML files (angular 2+ template)

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/31571743-221bede6-b05e-11e7-8e1e-ece85a469a0a.png)
Initial support for HTML/XML is just added.

**Comment by izhangzhihao** [comment]
New version 2.3 is just been released and wait for approval of jetbrains for this release.

**Comment by izhangzhihao** [comment]
But you still could download the zip file in [here](https://github.com/izhangzhihao/intellij-rainbow-brackets/releases/download/2.3/intellij-rainbow-brackets-2.3.zip) and choose install from disk in intelliJ. Thanks.

**Comment by GeorgeJashin** [comment]
its nice, but what about "[(ngModel)]"

**Comment by GeorgeJashin** [comment]
will be good if you add colors to actual nested brackets not html tags.
(()), [[]], {{}}, [()] like this ones.

**Comment by izhangzhihao** [comment]
Maybe someone could check [this](https://github.com/JetBrains/intellij-plugins/tree/master/AngularJS) and create a highlighter for Angular 2+ HTML template.

**Comment by izhangzhihao** [comment]
If you have free time to add a specific implement for Angular template, please take a look [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#implement-for-some-language-you-would-like)

**Comment by izhangzhihao** [comment]
It seems impossible, because elements such as `[(model)]` is a whole `XmlToken:XML_DATA_CHARACTERS`. 

And I think all the brackets in angular html are (()), [[]], {{}}, [()], but (({{}})) seems not possible, that means this plugin can't play a role.

So... I'm going to close this issue. Feel free to re-open it or raise a new one if you have any issue.
