### ISSUE TITLE
Red color is reserved for errors

### ISSUE THREAD

**Issue by orfeonomia** [izhangzhihao/intellij-rainbow-brackets#30]
This is not a duplicate of https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/18
I don't suggest that colors should be configurable.

I think the red color (and colors very similiar to red like dark pink, dark magenta etc.) should be excluded from all color palettes since red is reserved for errors and red bracket is actually perceived as error

* Plugin version: 5.0-RC1

**Comment by izhangzhihao** [comment]
You are correct.

**Comment by izhangzhihao** [comment]
The red & purple color has been removed, and I add more "material design" color from [material.io](https://material.io/guidelines/style/color.html#). If you have any suggestions please feel free raise a new issue, thanks!

**Comment by izhangzhihao** [comment]
A new version has been released and waiting for approve from JetBrains.

**Comment by orfeonomia** [comment]
I use "rainbow brackets" daily so I'm glad to see you make this change so quickly. Thank you.

**Comment by PaulWoitaschek** [comment]
Thanks! I found this issue because this orange looks like errors to my eye too.

![image](https://user-images.githubusercontent.com/743462/39505260-63ea7754-4dd1-11e8-8c8b-fd4440b1e5c2.png)

**Comment by izhangzhihao** [comment]
@PaulWoitaschek You can change your config file to customize your own colors, see more [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#config-brackets-colors).
