### ISSUE TITLE
Enablement of round brackets enables all but angle brackets

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#31]
## STR
1. Disable all brackets but round
![settings](https://user-images.githubusercontent.com/6392013/36679501-08af47e4-1b1c-11e8-9c7b-e406e0d1532b.png)
2. Look at some code with different types of brackets
![code](https://user-images.githubusercontent.com/6392013/36679587-3cfa30ea-1b1c-11e8-8de9-4a08bc309b43.png)

## Expected Behavior
Only round brackets should be colored

## Current Behavior
All but angle brackets are colored

* Plugin version: 5.0.0-RC2
* IDEA version: WebStorm 2017.3.4
* Operating System and version: Windows 10

**Comment by Alexsey** [comment]
BTW after enabling of other brackets, colors get changed:
![settings](https://user-images.githubusercontent.com/6392013/36683908-892f3a22-1b27-11e8-85b1-98b3c896b6d5.png)
become
![code](https://user-images.githubusercontent.com/6392013/36683917-8dea4de0-1b27-11e8-9a0a-505681ca073e.png)

**Comment by izhangzhihao** [comment]
Related to [this line](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/b4e6860d530e58666ef07f5c14c3c43cd97adaae/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/RainbowHighlighter.kt#L71), for example: if we disable rainbow for square brackets, we should not give them `defaultRoundBracketsColors`

**Comment by izhangzhihao** [comment]
<img width="186" alt="screen shot 2018-02-27 at 9 51 07 am" src="https://user-images.githubusercontent.com/12044174/36706201-c9b0e3bc-1ba3-11e8-932d-bd516f919ea6.png">

**Comment by izhangzhihao** [comment]
Please try this snapshot build 
[intellij-rainbow-brackets.jar.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1760965/intellij-rainbow-brackets.jar.zip)

**Comment by izhangzhihao** [comment]
See [this PR](https://github.com/izhangzhihao/intellij-rainbow-brackets/pull/33)
