### ISSUE TITLE
Configure single colour range for all bracket types; cycle colour on all types

### ISSUE THREAD

**Issue by JumbleJumble** [izhangzhihao/intellij-rainbow-brackets#316]
I've a few points here that are all related:

First, I would like to be able to configure one series of colours, which is used for all bracket types. I would like to be able to choose how many different colours are used. Other similar extension do this by letting you configure 10 colours and then setting a numerical config value specifiying how many of those colours are used.

Second I would like to be able to configure it so that the coloured nesting level changes each time _any_ open or close is enountered. Currently if I type in the following:

`{<([])>}`

All the text will be the same colour. I would prefer it to be using the rainbow colours so that each level of bracket causes a colour change.

**Comment by mindyourlifeguide** [comment]
> Second I would like to be able to configure it so that the coloured nesting level changes each time _any_ open or close is enountered. Currently if I type in the following:
> 
> `{<([])>}`
> 
> All the text will be the same colour. I would prefer it to be using the rainbow colours so that each level of bracket causes a colour change.

I also thought about this and wanted to independently implement it by shifting the initial color for different quotes, but quickly realized that this method would not help.
I would also like similar functionality in future releases.

Thank you for your work!

**Comment by izhangzhihao** [comment]
As I see, the first is duplicated with #187, and the second just been implement in #247. Please have a check, any other thoughts are welcome!

**Comment by izhangzhihao** [comment]
And by the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin and my work.

**Comment by izhangzhihao** [comment]
And #187 just implemented!
