### ISSUE TITLE
if elsif else

### ISSUE THREAD

**Issue by smikkelsen** [izhangzhihao/intellij-rainbow-brackets#34]
Your issue may already be reported!
Please search on the [issue track](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) before creating one.

## Expected Behavior
* When using if elsif else end blocks in ruby, the else should be styled the same color

## Current Behavior
* "elsif" & "else" is colored the original IDE color, not matching the colored "if" and "end"

## Code snippet for reproduce (for bugs)
def foo
  if 1 == 1
    puts 'true'
  elsif 1 != 1
    puts 'false'
  else
    puts 'false'
  end
end

## Your Environment

* Plugin version: 5.0 RC3
* IDEA version: 2017.3.3
* Operating System and version: Mac High Sierra

**Comment by izhangzhihao** [comment]
Related to #16

**Comment by izhangzhihao** [comment]
Assume that we will support `if`,`elsif`,`else` for ruby, then we need to add specific implementation for other languages, for example:
`if`,`else`,`match`,`case` for scala;
`if`,`else`,`switch`... for java;
`if`,`else`,`when`,`case`... for kotlin;
`if`,`elif`,`else` for python;
...
And much more, so ... that will be a huge work to do.

**Comment by izhangzhihao** [comment]
I'm going to close it because this new features should belong to a new plugin (not exist for now, maybe you could create one. Maybe something like [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) will also helpful), this plugin only rainbow-ify brackets.

**Comment by izhangzhihao** [comment]
Feel free to re-open it or raise a new one if you have any issue.

**Comment by faoiseamh** [comment]
Would really like to see Ruby's `do`...`end` blocks supported as they are conceptually the same as brackets used to define blocks/ closures. I get the work involved in supporting all the permutations of conditionals but is there a similar issue with Ruby's main block operators? I admittedly haven't thought about it for very long but it seems like a fairly straightforward regex

**Comment by izhangzhihao** [comment]
> Would really like to see Ruby's `do`...`end` blocks supported as they are conceptually the same as brackets used to define blocks/ closures. I get the work involved in supporting all the permutations of conditionals but is there a similar issue with Ruby's main block operators? I admittedly haven't thought about it for very long but it seems like a fairly straightforward regex

Well, now it's not hard actually, We did something like that in Python, Please try 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/12044174/176121619-2a191024-a18b-4fda-9742-bb8d8611ca07.png">
PR welcome!
