### ISSUE TITLE
Same color if/else/for/while/switch statement's parentheses and its first curly brackets

### ISSUE THREAD

**Issue by RickWong** [izhangzhihao/intellij-rainbow-brackets#36]
**You should `Star` this repo before you create a issue, thanks for your support 😁**
Done!

## Expected Behavior
* The first curly brackets should have the same color as the parentheses:
![image](https://user-images.githubusercontent.com/40102/37519047-0958f730-2918-11e8-83f5-38acdc839c72.png)
(screenshot from VS Code)

## Current Behavior
* The first curly brackets have a different color from the parentheses:
![image](https://user-images.githubusercontent.com/40102/37518976-cf4dbfa8-2917-11e8-8057-b1c66fecd94c.png)
(screenshot from WebStorm)

## Possible Solution
The plugin could keep count of the block-level and use the same color for each level. In the example the yellow block-level started with `(` and was closed with `)` so the next set of braces are at the same block-level, thus can reuse the yellow color. 

Or perhaps it's easier to just hardcode this rule for these type of statements.

## Code snippet for reproduce (for bugs)
```js
if (foo === "bar") {
  // curly braces get the same color as the parentheses
}
```

## Your Environment

* Plugin version: 5.0-RC3
* IDEA version: WebStorm 2018.1 EAP, WS-181.4096.25, built on March 8, 2018
* Operating System and version: macOS 10.13.x

**Comment by RickWong** [comment]
Just looked at the source, it's nice. However different braces `{` `(` `[` have separate predefined color swatches it seems. If this is simplified to one the shared swatch, then this issue would be resolved immediately?

**Comment by izhangzhihao** [comment]
Yep, different brackets have different colors (predefined). So, the problem should be "How to customize brackets colors?" . I mean if users could customize colors, then  this issue would be resolved.

**Comment by RickWong** [comment]
Yes, that in a way is definitely true. I would say though, that one color swatch is probably sufficient unless I'm mistaken?

**Comment by Alexsey** [comment]
To achieve this you will need to also handle a situations like
```js
function foo () { // "{}" are blue
  // "()" can not be blue because "{}" above are blue
  // and you shouldn't have "{}" directly inside of "{}" with the same color
  if (goo) {
     ...
  }
}
```

**Comment by RickWong** [comment]
Yes it would behave like this: 

```js
function foo () { // all orange
  if (goo) { // all blue
     ...
  } // blue
} // orange
```

**Comment by Alexsey** [comment]
I mean that with this change to determine what should be the color of the bracket just knowledge about the color of the closest bracket of the same type would not be enough - it would require also to take the color of different brackets in to account as well. Now consider that brackets of the same type should have the same color
```js
function foo () { // blue
  if (bar) return // blue
  if (baz) { // this one should be orange. And this should also change the color of the first "if"
    ...
  }
}

**Comment by izhangzhihao** [comment]
I'm going to close this issue, feel free to re-open it or raise a new one if you have any issue.
