### ISSUE TITLE
Rainbow indent seems not working in PyCharm

### ISSUE THREAD

**Issue by zhengyu-yang** [izhangzhihao/intellij-rainbow-brackets#361]
## Your programming language(s)
python

## Current Behavior
Rainbow ident doesn't have any effect on python in PyCharm

## Your Environment

* Plugin version:
5.27

* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
PyCharm 2019.2.5 (Professional Edition)
Build #PY-192.7142.56, built on November 19, 2019
Licensed to namaenashi
Subscription is active until February 4, 2020
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true
Non-Bundled Plugins: IdeaVIM, com.jetbrains.intellij.datalore, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, BashSupport, izhangzhihao.rainbow.brackets
```

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by zhengyu-yang** [comment]
![image](https://user-images.githubusercontent.com/25852061/69931521-76366d00-147c-11ea-9a1e-51525544bce6.png)

**Comment by izhangzhihao** [comment]
Maybe rainbow ident does not design for python, am I right? @YiiGuxing

**Comment by YiiGuxing** [comment]
Python code blocks without brackets, so the indent guide is not colored.
