### ISSUE TITLE
Not compatible with IntelliJ Idea 2019.3 update

### ISSUE THREAD

**Issue by Cukac** [izhangzhihao/intellij-rainbow-brackets#365]
Plugin stopped working for me after 2019.3 update (tested it only with cursive in clojure and clijurescript)

**Comment by izhangzhihao** [comment]
Please provide your environment information.

**Comment by Cukac** [comment]
=== About ===
Build version: IntelliJ IDEA 2019.3 Build #IC-193.5233.102 November 28, 2019
Java version: 11.0.4+10-b520.11x86_64
Operating System: Mac OS X (10.15.1, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 8
Used memory: 310Mb 
Free memory: 44Mb 
Total memory: 355Mb 
Maximum available memory: 1981Mb

=== Displays ===
Displays: 
Display 0: 2880x1800; scale: 2.00
Display 1: 2560x1440; scale: 1.00

=== Plugins ===
Custom plugins: [ANSI Highlighter (1.2.4), Material Theme UI (4.9.2.1), Cursive (1.9.0-2019.3), Catdea (1.1.2), Ideolog (193.0.16.0), JS GraphQL (2.2.0), One Dark theme (3.3.1), Rainbow Brackets (5.27), IDE Features Trainer (193.5233.115)]
Disabled plugins:[Bytecode Viewer (193.5233.102), XPathView + XSLT (193.5233.102), Plugin DevKit (193.5233.102), XSLT Debugger (193.5233.102), Java Stream Debugger (193.5233.102), Eclipse Interoperability (193.5233.102), Task Management (193.5233.102), Terminal (193.5233.102), YAML (193.5233.102)]

Is this enough?

**Comment by izhangzhihao** [comment]
And your setting page in preference => Rainbow Brackets

**Comment by Cukac** [comment]
![Screenshot 2019-12-03 at 13 14 34](https://user-images.githubusercontent.com/48802540/70050333-fa006e80-15ce-11ea-8ec5-5a40cdb7fa09.png)

**Comment by leonle9527** [comment]
Does't work with IntelliJ Idea 2019.3 update.

**Comment by Z-WolF** [comment]
In PhpStorm, the colors in `Settings`->`Editor`->`Color Scheme`->`Rainbow Brackets` are all `808080`, as if those were the default colors. Changing them works, and it is reflected in the editor, but restoring to defaults or reinstalling the plugin changes back the values to `808080`.

![Captura de pantalla de 2019-12-07 22-12-37](https://user-images.githubusercontent.com/931200/70382745-87312380-193f-11ea-8e26-a1a3d1426ce3.png)

**Comment by izhangzhihao** [comment]
@Z-WolF what is your environment information?

**Comment by Z-WolF** [comment]
```
=== About ===
Build version: PhpStorm 2019.3 Build #PS-193.5233.101 November 27, 2019
Java version: 11.0.4+10-b520.11amd64
Operating System: Linux (4.19.0-6-amd64, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 4
Used memory: 194Mb 
Free memory: 117Mb 
Total memory: 311Mb 
Maximum available memory: 953Mb

=== Displays ===
Displays: 
Display 0: 1366x768; scale: 1,00
Display 1: 1920x1080; scale: 1,00

=== Plugins ===
Custom plugins: [Material Theme UI (4.11.0), Ideolog (193.0.16.0), PHP Annotations (6.2.2), Symfony Support (0.19.186), Rainbow Brackets (5.27), .ignore (3.2.3.193), ReStructuredText Support (193.5233.116), .env files support (2019.3), Nyan Progress Bar (1.14)]
Disabled plugins:[]
```
And settings

![Captura de pantalla de 2019-12-08 01-48-23](https://user-images.githubusercontent.com/931200/70384420-da659f00-195c-11ea-9021-6f724465a9e2.png)

**Comment by izhangzhihao** [comment]
Then where the "Arc Dark" color schema come from?

**Comment by Z-WolF** [comment]
One of "Material Theme UI" schemas.

**Comment by izhangzhihao** [comment]
ok, @Cukac Can you show me your settings in `Settings->Editor->Color Scheme->Rainbow Brackets` ?

**Comment by izhangzhihao** [comment]
And because `cursive` and `PhpStorm` are all paid products, please consider donating to this project. @Cukac @Z-WolF

**Comment by Cukac** [comment]
I had to revert to version 2019.2.4
Version 2019.3 completely broke all of my projects in Clojure and Clojurescript.
I will donate as soon as possible. Appreciate your hard work :)

**Comment by tanrich** [comment]
I also encountered this problem。webstorm 2019.3

**Comment by luoyedaren** [comment]
me too,  and can not uninstall .......
想卸载都卸载不了，插件列表上点击它都卡死 直接  有毒啊。。。
my idea
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Licensed to hai cheng
Subscription is active until July 16, 2020
For educational use only.
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.0-6-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 1958M
Cores: 4
Registry: 
Non-Bundled Plugins: JRebelPlugin, Lombook Plugin, MavenRunHelper, String Manipulation, cn.wuzhizhan.plugin.mybatis, com.ccnode.codegenerator.MyBatisCodeHelperPro, izhangzhihao.rainbow.brackets, org.intellij.gitee

**Comment by sualex** [comment]
Works well on 2019.3 when the Material Theme has completely been uninstalled. Seems like rainbow can't override theme color settings since they have a higher priority?
![Screenshot (2)](https://user-images.githubusercontent.com/19490632/70652990-a93ee480-1c64-11ea-9738-5cce719711d6.png)

**Comment by sualex** [comment]
Material theme just drops rainbow color scheme. Reset them up manually :
![Screenshot (2)](https://user-images.githubusercontent.com/19490632/70654936-5c5d0d00-1c68-11ea-9b13-84a43a1e5c93.png)

**Comment by izhangzhihao** [comment]
Fixed in the latest version of material theme UI plugin.

**Comment by marcojulioarg** [comment]
Not working in PyCharm 2019.3.2
Same issue

**Comment by KrisNie** [comment]
> me too, and can not uninstall .......
> 想卸载都卸载不了，插件列表上点击它都卡死 直接 有毒啊。。。
> my idea
> IntelliJ IDEA 2019.3 (Ultimate Edition)
> Build #IU-193.5233.102, built on November 28, 2019
> Licensed to hai cheng
> Subscription is active until July 16, 2020
> For educational use only.
> Runtime version: 11.0.4+10-b520.11 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.19.0-6-amd64
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1958M
> Cores: 4
> Registry:
> Non-Bundled Plugins: JRebelPlugin, Lombook Plugin, MavenRunHelper, String Manipulation, cn.wuzhizhan.plugin.mybatis, com.ccnode.codegenerator.MyBatisCodeHelperPro, izhangzhihao.rainbow.brackets, org.intellij.gitee

先disabled material theme at first, 然后 uninstall
