### ISSUE TITLE
Some bracket colors conflict with Intellij's changes view

### ISSUE THREAD

**Issue by matejdro** [izhangzhihao/intellij-rainbow-brackets#366]
## Expected Behavior
My code should be visible in all circumstances

## Current Behavior
In IntelliJ's changes view (for example when viewing changes before commiting code), changed code is highlighted blue. When rainbox brackets also colors brackets blue, it makes some brackets very hard to see:

![image](https://user-images.githubusercontent.com/507922/70047170-d4bc3200-15c7-11ea-96f9-95119099d252.png)

## Possible Solution
Maybe add exception to exclude blue-ish colors when in changes view (or at worst completely disable rainbow brackets in changes view - single-color but visible brackets are still better than colored, but invisible brackets).

## Your Environment

* Plugin version: 5.27

```
Android Studio 3.6 Beta 4
Build #AI-192.6817.14.36.5994180, built on November 7, 2019
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
```

**Comment by izhangzhihao** [comment]
Please try: https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors

**Comment by matejdro** [comment]
This customizes the colors globally, right? This ticket is only for changes window.

**Comment by izhangzhihao** [comment]
Yep, it's globally. There is no extra plan to change the color of changes window
