### ISSUE TITLE
Color customization notification does not go to the proper location

### ISSUE THREAD

**Issue by chrisdeely** [izhangzhihao/intellij-rainbow-brackets#367]
## Expected Behavior
* the link within the pop up should direct the user to settings menu for editing colors

## Current Behavior
* upon clicking the link, the user is directed to the plugin's main configuration page, not the color scheme editing page

## Possible Solution
- `com.github.izhangzhihao.rainbow.brackets.activity. CustomRainbowActivity` uses an `href=#` which seems to direct to the plugin's primary config page - if possible it should be changed to the proper link.
- also, the copy should be corrected to: `Want to customize your own color scheme of Rainbow Brackets?`

## Code snippet for reproduce (for bugs)
No code needed - just click the [pop up which appears after installation](https://www.dropbox.com/s/rnb6sd8xl7q19wy/Screenshot%202019-12-04%2013.44.01.png?dl=0)
![Screenshot 2019-12-04 13 44 01](https://user-images.githubusercontent.com/230378/70172166-20d9a600-169e-11ea-940c-ce6281aca94a.png)

## Your Environment

* Plugin version: 5.27
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Licensed to Chris Deely
Subscription is active until February 24, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1088M
Cores: 8
Registry: 
Non-Bundled Plugins: com.alayouni.ansiHighlight, izhangzhihao.rainbow.brackets
```

**Comment by izhangzhihao** [comment]
Could you please help me verify this is been fixed by install the snapshot build version? 
[intellij-rainbow-brackets-5.27.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/3938701/intellij-rainbow-brackets-5.27.zip)

**Comment by chrisdeely** [comment]
I was the latest version 5.27. I installed the zip file provided, edited my `rainbow_brackets.xml` to set `customNotifyShowed=true` so the notification would reappear.

Clicking the notification link still goes to the main plugin settings page, not the color customization page.

**Comment by chrisdeely** [comment]
I was able to setup a development environment for the project and I confirmed  the 5.27 build handles the notification properly in the default IntelliJ version of 2017.1, but when upgrading to 2019.3 it breaks.

 I have been unable to get plugin debugging to work but I'm willing to help out if someone can assist me with the environment setup.

**Comment by izhangzhihao** [comment]
Tested with latest 2020.1 EAP :

```
IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.3803.71, built on January 24, 2020
IntelliJ IDEA EAP User
Expiration date: February 23, 2020
Runtime version: 11.0.5+9-b674.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, bigger.font.in.project.view=true, search.everywhere.settings=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.alayouni.ansiHighlight, com.daylerees.rainglow, GenerateSerialVersionUID, GrepConsole, JUnit4-Parallel-Runner, Lombook Plugin, com.alibaba.p3c.smartfox, com.intellij.bigdecimal-folding, com.viartemev.requestmapper, com.jetbrains.CyanTheme, com.markskelton.one-dark-theme, com.intellij.kubernetes, org.nik.presentation-assistant, some.awesome, org.intellij.scala, Pythonid, me.aristotll.python.typing.adder, tanvd.grazi, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets
```

It works as expected:

![image](https://user-images.githubusercontent.com/12044174/73159988-c8190d80-4122-11ea-9607-8e5c8d03cfa2.png)
