### ISSUE TITLE
Highlight text between brackets when Ctrl pressed

### ISSUE THREAD

**Issue by ctrl-brk** [izhangzhihao/intellij-rainbow-brackets#37]
## Expected Behavior
* If you're suggesting a change/improvement, tell us how it should work
Make the content within current brackets highlighted when some special key (Ctrl?) is pressed.

## Possible Solution
Check out Viasfora Visual Studio extension as an example:
https://www.youtube.com/watch?v=PlF1COGVwmw

**Comment by amitav13** [comment]
Is there a way to disable this? I'm finding it very distracting

**Comment by izhangzhihao** [comment]
You could config this in your settings. https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/60#issuecomment-389009735

**Comment by fraserredmond** [comment]
I really like this... but Ctrl gets pressed a lot for all sorts of unrelated commands, so I think I'll turn it off.

I'd prefer it was changed to use Ctrl+Shift. Much fewer false-positives that way, and just as easy to press.

**Comment by izhangzhihao** [comment]
@fraserredmond In next [release](https://github.com/izhangzhihao/intellij-rainbow-brackets/releases/tag/5.8) you could config the key map.

**Comment by fraserredmond** [comment]
Thanks!

**Comment by frnusmartobjects** [comment]
Please allow the keymapping to be configured. In my case I have almost all my keybindings associated with Ctrl or Alt and would like for example to use instead Ctrl+Alt+Shift+Button3 to "Flat out all text other than brackets" and Alt+Shift+Button3 to "Highlight Current Scope"
