### ISSUE TITLE
All brackets are yellow in Haskell (with IntelliJ-Haskell)

### ISSUE THREAD

**Issue by dima74** [izhangzhihao/intellij-rainbow-brackets#374]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming language(s)
Haskell

## Expected Behavior
Nested brackets have different colors

## Current Behavior
All brackets have yellow color:

![image](https://user-images.githubusercontent.com/6505554/70864613-caede380-1f64-11ea-90d5-1d06b8f41c25.png)

## Code snippet for reproduce (for bugs)
Install [Intellij-Haskell](https://github.com/rikvdkleij/intellij-haskell) plugin, then create haskell project, then create any haskell file with content:

```x = (1 + (2 + (3 + (4 + 5))))```

## Your Environment

* Plugin version: 5.27
* IDE & Operating System version:

```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.2-zen1-1-zen
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4
Registry: 
Non-Bundled Plugins: BashSupport, PsiViewer, String Manipulation, com.mnw.tabmover, intellij.haskell, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, kotlintest-plugin-intellij, org.jetbrains.idea.grammar, org.toml.lang, tanvd.grazi, org.rust.lang
```

**Comment by izhangzhihao** [comment]
It seems that you are using IntelliJ-Haskell, not HackForce.

**Comment by izhangzhihao** [comment]
And it works great with HaskForce:
![image](https://user-images.githubusercontent.com/12044174/70879861-db07d080-2001-11ea-81c9-0d6f52ecb1d5.png)

```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: 
Non-Bundled Plugins: PsiViewer, com.haskforce, izhangzhihao.rainbow.brackets, org.intellij.scala, zjhmale.haskell-conceal
```

**Comment by dima74** [comment]
Indeed, I am using IntelliJ-Haskell. Sorry for incorrect information.

**Comment by izhangzhihao** [comment]
Related to https://github.com/rikvdkleij/intellij-haskell/issues/490

**Comment by izhangzhihao** [comment]
Please help me verify this plugin now works with both intelliJ-Haskell and HaskForce by install this snapshot:
[intellij-rainbow-brackets-5.30.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/4115958/intellij-rainbow-brackets-5.30.zip)

**Comment by izhangzhihao** [comment]
Please consider donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this feature.

**Comment by dima74** [comment]
Yes, with this snapshot brackets are colored correctly. Thank you!

**Comment by izhangzhihao** [comment]
Great then
