### ISSUE TITLE
Highlighted rainbow indent guide lines 

### ISSUE THREAD

**Issue by mindyourlifeguide** [izhangzhihao/intellij-rainbow-brackets#380]
Hello!

Is it possible that when working inside the tag, the Rainbow indent guide lines are highlighted, and not the line on the left?
It would be much more convenient to work with the code.

Here is the highlight to the left of the code.
![image](https://user-images.githubusercontent.com/35348648/71101745-e9035000-21bf-11ea-9029-d9eb7c58442e.png)

That's how I would like
![image](https://user-images.githubusercontent.com/35348648/71101923-341d6300-21c0-11ea-9570-31e0313a9800.png)

## Environment

* Plugin version: 5.28
* WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.15-1-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 2000M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: ImportCost, Key Promoter X, com.chrisrm.idea.MaterialThemeUI, com.intellij.react.css.modules, com.jinsihou.react.snippets, com.mallowigi.imageicon, com.markskelton.one-dark-theme, com.softwareco.intellij.plugin, com.suming.react.PropTypes, com.tobszarny.activetabhighlighter.plugin.id, com.wakatime.intellij.plugin, com.wix.eslint, com.xcodersteam.idea.plugins.mkupscss, io.github.qeesung.component.HighlightBracketPair, izhangzhihao.rainbow.brackets, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.file-preview, org.intellij.plugins.postcss, quokka.js, socrates.tabshifter, tanvd.grazi, zielu.gittoolbox

**Comment by mindyourlifeguide** [comment]
You can underline the line at the beginning of the block, as is done in VS Code

**Comment by mindyourlifeguide** [comment]
Here is an example:
https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag

**Comment by izhangzhihao** [comment]
Thanks for the great example, I will give a try when I have free time. If you find this plugin helpful, please do consider donating at [opencollective](https://opencollective.com/intellij-rainbow-brackets).

**Comment by TheBestPessimist** [comment]
Possibly related: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/164#issuecomment-546830088

**Comment by TheLordDrake** [comment]
This is a feature I have in VSC via a plugin (Bracket Pair colorizer 2), it's something I really miss in my Jetbrains IDEs. Highlighting the line at the beginning of the block as suggested by @mindyourlifeguide may work for some folks but it really isn't a replacement for this functionality.

**Comment by byyxx128** [comment]
Happy to see someone already reported this. And another good example:
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

Now let me show some GIFs to explain more clearly.

[Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
) will show **highlighted indent line plus a horizontal line** to help users identify the current insertion block:
![Bracket_Pair_Colorizer](https://user-images.githubusercontent.com/20079289/77649252-81ba2080-6fa4-11ea-90d4-e7c5120dee19.gif)

However, [Rainbow Brackets](https://plugins.jetbrains.com/plugin/10080) will highlight the indent line **only if** I put my cursor in front of the vertical line:
![Rainbow_Brackets](https://user-images.githubusercontent.com/20079289/77649269-8979c500-6fa4-11ea-9e55-60ff49dd031b.gif)

Which one is better? I believe it's easy to say.

Please try to improve.

**Comment by izhangzhihao** [comment]
So which one is better?

在 2020年3月26日，下午9:03，byyxx128 <notifications@github.com> 写道：

﻿

Happy to see someone already reported this. And another good example:
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

Now let me show some GIFs to explain more clearly.

Bracket Pair Colorizer<https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2> will show highlighted indent line plus a horizontal line to help users identify the current insertion block:
[Bracket_Pair_Colorizer]<https://user-images.githubusercontent.com/20079289/77649252-81ba2080-6fa4-11ea-90d4-e7c5120dee19.gif>

However, Rainbow Brackets<https://plugins.jetbrains.com/plugin/10080> will highlight the indent line only if I put my cursor in front of the vertical line:
[Rainbow_Brackets]<https://user-images.githubusercontent.com/20079289/77649269-8979c500-6fa4-11ea-9e55-60ff49dd031b.gif>

Which one is better? I believe it's easy to say.

Please try to improve.

**Comment by byyxx128** [comment]
Why was my comment minimized...

**Comment by byyxx128** [comment]
Happy to see someone already reported this. And another good example:
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

Now let me show some GIFs to explain more clearly.

[Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
) will show **highlighted indent line plus a horizontal line** to help users identify the current insertion block:
![Bracket_Pair_Colorizer](https://user-images.githubusercontent.com/20079289/77649252-81ba2080-6fa4-11ea-90d4-e7c5120dee19.gif)

However, [Rainbow Brackets](https://plugins.jetbrains.com/plugin/10080) will highlight the indent line **only if** I put my cursor in front of the vertical line:
![Rainbow_Brackets](https://user-images.githubusercontent.com/20079289/77649269-8979c500-6fa4-11ea-9e55-60ff49dd031b.gif)

Which one is better? I believe it's easy to say.

Please try to improve.

**Comment by TheBestPessimist** [comment]
@byyxx128 i have mixed feelings about the horizontal line. On one hand it looks interesting and it might bring some good visual effects, on the other hand it will load even more the editor, plus i _feel_ the vertical bar that we have now does everything i want, as long as my code is indented properly.

**Comment by byyxx128** [comment]
For horizontal line definitely it will load more as the vertical indent line is built-in. It's not a very big problem without the horizontal line. However, in order to have better visual effects, why not add a horizontal line?🤔

**Comment by byyxx128** [comment]
For horizontal line definitely it will load more as the vertical indent line is built-in. It's not a very big problem without the horizontal line. However, in order to have better visual effects, why not add a horizontal line?🤔 (Thus, this can be an optional feature and disabled by default, but I believe many people need it.)

**Comment by izhangzhihao** [comment]
Please vote for @byyxx128 's comment if you like it. By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.

**Comment by mindyourlifeguide** [comment]
When I reported the desired functionality above, I meant exactly what @byyxx128 suggested.
The horizontal line really makes code navigation easier.

**Comment by RashiqAzhan** [comment]
I would really appreciate this feature. It's so helpful for debugging purposes and for focusing intently on the section of the code.

I would also suggest adding a highlight option for the entire code block that would really compliment this feature. Whenever you place a cursor on any line in the IDE, that particular line turns darker or lighter than the surrounding depending on the theme. I was hoping this could be done for the entire block of code that fits within the braces for easier focusing.
![image](https://user-images.githubusercontent.com/7370540/140808861-79770d77-f5cf-4896-bd4d-2f7973eee673.png)
The yellow arrow shows the line that is highlighted because of the cursor placement. The line shown by the purple arrow should also be highlighted in a different color as it is between the braces and therefore in the same block of code. This feature could be extended to functions, classes, and much more.

**Comment by makiwata** [comment]
Very good idea, my idea I posted had the same goal: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2428

So it seems some kind of highlighting would be good for a lot of people, good to see this :-)

**Comment by lpoirothattermann** [comment]
Hi,

Would be very nice if someone with skills does this feature !
Many people would be happy about this feature like said @makiwata . (Me included obviously)

UPDATE: Seems that work need to be done at https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/b0bf49968b75e6186c55321d81455d4526e01c69/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/indents/RainbowIndentGuideRenderer.kt#L67 to change this behavior.

**Comment by izhangzhihao** [comment]
> Hi,
> 
> Would be very nice if someone with skills does this feature ! Many people would be happy about this feature like said @makiwata . (Me included obviously)
> 
> UPDATE: Seems that work need to be done at
> 
> https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/b0bf49968b75e6186c55321d81455d4526e01c69/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/indents/RainbowIndentGuideRenderer.kt#L67
> 
> to change this behavior.

PR welcome!

**Comment by izhangzhihao** [comment]
Please take a look at these two options, please use 👍 for your choice:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/12044174/198984655-aedcec69-58c3-465f-b06a-279fd35068bd.png">

**Comment by izhangzhihao** [comment]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/12044174/198995710-a7956ae3-b008-41f0-a391-caf5a39cd8dd.png">

**Comment by TheBestPessimist** [comment]
@izhangzhihao i want to make sure i understood the options:
- picture 1: ALL the indent guides are highlighted from top until the current one where the cursor is
- picture 2: ONLY the innermost (current) indent guide is highlighted

In that case, i  👍 picture 2

---

Another clarification needed: in both cases, the innermost (current) indent guide is highlighted but not in a very bright color, correct?

**Comment by lpoirothattermann** [comment]
For the option one:

Maybe it would be better that the indent guide as the same (or higher thinkness) than the parents ?

**Comment by izhangzhihao** [comment]
> @izhangzhihao i want to make sure i understood the options:
> 
> * picture 1: ALL the indent guides are highlighted from top until the current one where the cursor is
> * picture 2: ONLY the innermost (current) indent guide is highlighted
> 
> In that case, i 👍 picture 2
> 
> Another clarification needed: in both cases, the innermost (current) indent guide is highlighted but not in a very bright color, correct?

Yes, and the last one is, true the color of mine might not so bright, but this does not effect to the functionality(since you guys must have your own color pattern already😄)

**Comment by TheBestPessimist** [comment]
> since you guys must have your own color pattern already

i use your default :)


Lastly, none of your samples implement the optional "horizontal line" mentioned [in this comment above](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/380#issuecomment-604459927). 
I still have mixed feelings about it, though i would be interested in trying that as well. It might be a very good addition or a very bad one (bad in the sense of noise on the screen), i'm not sure until i test it. 

Do you wish to implement that option, or is it too much?


Later edit: That horizontal option seems to work better with my preference for picture 2 as well. Not sure how it would work when all indent guides are highlighted. `¯\_(ツ)_/¯`

**Comment by izhangzhihao** [comment]
> the optional "horizontal line" mentioned [in this comment above](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/380#issuecomment-604459927). 

It does possible to implement that, but I need some time to figure out how to. So I guess I will implement this feature request step by step.

**Comment by izhangzhihao** [comment]
I made an option:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/12044174/199013321-331a5597-5a8b-45c4-91c8-382e0ad7bbf6.png">

please try the build snapshot here

NOTE: this will be a paid feature, `Only selected indent guide` is free but the other two options require a license. Feel free to start a trial for 30 days before you purchase.

BTW, if you already contribute to this project by code or financially, please contact me and you will get a free license.

**Comment by izhangzhihao** [comment]
The new version 2022.3.2 is already in the marketplace, please download and enjoy it.
