### ISSUE TITLE
Conflict to Matched brace color setting

### ISSUE THREAD

**Issue by daddyofsky** [izhangzhihao/intellij-rainbow-brackets#385]
## Current Behavior
1. Change Matched brace color setting at Editor > Color Scheme > General > Code > Matched brace
2. Matched brace color setting is affected.
3. Restart IDE
4. Matched brace color setting is changed to default color setting.

## Expected Behavior
Matched brace color setting should be persisted after IDE restart.
It occurs only if Rainbow Brackets plugin is installed.

Please see https://youtrack.jetbrains.com/issue/IDEA-209939

## Your Environment
* Plugin version:
5.28

* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

PhpStorm 2019.3.1
Build #PS-193.5662.63, built on December 19, 2019
Licensed to JaeHan Seo
You have a perpetual fallback license for this version
Subscription is active until November 29, 2020
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, search.everywhere.settings=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=205
Non-Bundled Plugins: String Manipulation, com.ken.savebackup, com.paperetto.dash, com.ptby.dynamicreturntypeplugin, de.espend.idea.php.toolbox, izhangzhihao.rainbow.brackets

**Comment by izhangzhihao** [comment]
Please set 	`<option name="overrideMatchedBraceAttributes" value="false"/>` in https://github.com/izhangzhihao/intellij-rainbow-brackets#config-file-path

**Comment by daddyofsky** [comment]
Thanks. 谢谢。
