### ISSUE TITLE
support dim amount for indent guides

### ISSUE THREAD

**Issue by markfarber** [izhangzhihao/intellij-rainbow-brackets#386]
- [x] I already support this project.
- [x] This issue/feature request is not reported before.

## Your programming language(s)
Java, Kotlin

## Expected Behavior
ability to set dim amount for indent guides

## Current Behavior
indent guides are very bright, and there is no possibility to dim them down, this is very distracting

![image](https://user-images.githubusercontent.com/21201413/72358854-e5e37d00-36f5-11ea-9423-db7094ff8a26.png)

## Your Environment
* Plugin version: 5.29
* IDE & Operating System version: 
```Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by izhangzhihao** [comment]
As a workaround for now, you can turn "show rainbow indent guidelines" off. I'm currently on vacation, I will add this feature as soon as possible.
