### ISSUE TITLE
Bracket lines displaced

### ISSUE THREAD

**Issue by ak2766** [izhangzhihao/intellij-rainbow-brackets#387]
## Your programming language(s)
Dart

## Expected Behavior
Bracket lines should not be intermingled with the code.

## Current Behavior
Bracket lines are intermittently cutting right through code - see screenshot below:
![Selection_00133](https://user-images.githubusercontent.com/6629646/72673327-d5981d00-3abc-11ea-8c5d-c0af29f83cf5.png)

## Possible Solution
I have found that closing and reopening the file with the problem fixes the issues.

## Your Environment
* Plugin version: `v5.29`
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-74-generic
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

**Comment by izhangzhihao** [comment]
Can you please provide some sample code?

**Comment by ak2766** [comment]
Hi @izhangzhihao.  Still trying to figure out how to make it repeatable - but it it mostly happens when I'm wrapping widgets with other widgets manually so that I end up with brackets that aren't closed properly.  After I wrangle them brackets into submission, I **_at times_** end up with these displaced bracket lines.

**Comment by izhangzhihao** [comment]
Any update?
