### ISSUE TITLE
Disable update notification

### ISSUE THREAD

**Issue by ruudk** [izhangzhihao/intellij-rainbow-brackets#388]
How do I turn off the notification that pops up every time this plugin gets an update? Why can't I disable this? I feel that it's a way to get more sponsors?

See https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/279

**Comment by izhangzhihao** [comment]
Just fellow this comment: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/279#issuecomment-542695618

**Comment by ruudk** [comment]
@izhangzhihao See this comment: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/279#issuecomment-567888437
