### ISSUE TITLE
JS字符串中HTML代码的问题

### ISSUE THREAD

**Issue by YiiGuxing** [izhangzhihao/intellij-rainbow-brackets#39]
![img](https://user-images.githubusercontent.com/10737066/37753053-039508b2-2dd6-11e8-8c0a-6a693cee6eb6.png)
像上图的代码应该是要被着色才对。事实上插件也已经向IDE提交了着色信息了的，但IDE并没有着色，原因不明，猜测应该是被覆盖了。
如果指定字符串内容的语言为`XML`便能着色了：
![img2](https://user-images.githubusercontent.com/10737066/37753057-06b2b9cc-2dd6-11e8-8db4-a1bc79dbc161.png)
或者取消`HTML Code`的默认颜色也能着色：
![img3](https://user-images.githubusercontent.com/10737066/37753551-763734b0-2dd8-11e8-9391-e8eca040e4e8.png)

关于这个问题，可以向JetBrains寻求帮助。

**Comment by izhangzhihao** [comment]
你试试把 html 最外面的引号去掉

**Comment by YiiGuxing** [comment]
这个是JS代码，不是JSX的代码。

**Comment by izhangzhihao** [comment]
你用的是 #38 里面的 snapshot 吗

**Comment by YiiGuxing** [comment]
也就是JS字符串中HTML代码理论上应该是可以着色的。

**Comment by YiiGuxing** [comment]
不是

**Comment by YiiGuxing** [comment]
我在尝试实现 #20 的时候也遇到这样的问题，着色信息已经提交，但是后来又被覆盖了。。。

**Comment by izhangzhihao** [comment]
你试一下 #38 里面那个 snapshot 吧，我不熟悉 js 的环境，直接在本地加了一个测试，待会儿提交一下。测试结果是没问题的。

**Comment by YiiGuxing** [comment]
一样的，问题的性质不同，修复 #38 的代码不能修复这个问题。测试代码的通过也证明了插件已经向IDE提交了着色信息了的，但IDE并没有着色。表现为：首先插件已经成功着色，但后来又被默认的颜色覆盖了，只要取消了默认的颜色，就不会被覆盖。

这个问题和`kotlin`着色标签应该是一样的。我尝试跟踪过，而且跟得很深，都跟到`kotlin`内部的高亮着色器里了，也找到`kotlin`着色标签的地方，但还是没能解决。所以需要你去向JetBrains寻求下帮助。

**Comment by izhangzhihao** [comment]
你测试过 snapshot 的版本着色还是被覆盖了是吧？那我就去提一个问题。

**Comment by YiiGuxing** [comment]
是的

**Comment by izhangzhihao** [comment]
See [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000117450-My-HighlightVisitor-been-covered-by-intellij-built-in-functionality)

**Comment by YiiGuxing** [comment]
与 #38 不是同一个问题，#38 已经解决了的

**Comment by izhangzhihao** [comment]
没听懂，你在 react 环境下使用 #38 的 snapshot 测试JSX是被正常染色的嘛？

**Comment by YiiGuxing** [comment]
JSX是JSX语法，这里是字符串，js的字符串，和JSX语法无关。

**Comment by izhangzhihao** [comment]
了解了

**Comment by izhangzhihao** [comment]
都没人理我，我看还是把这个写到 README 里得了，想用这个功能就改一下默认配置。或者说，我们可以通过我们的插件去修改 intellij 自己的配置吗，这样用户就不用手动改配置了。

**Comment by YiiGuxing** [comment]
嗯，应该可以，有时间试一试。
