### ISSUE TITLE
Cycle color on all bracket types

### ISSUE THREAD

**Issue by JumbleJumble** [izhangzhihao/intellij-rainbow-brackets#391]
I already raised this as part of issue #316, however it seems that issue was misunderstood and has been closed without being implemented.

The relevant text is as follows:

>  I would like to be able to configure it so that the coloured nesting level changes each time any open or close is enountered. Currently if I type in the following:
> 
> {<([])>}
> 
> All the text will be the same colour. I would prefer it to be using the rainbow colours so that each level of bracket causes a colour change.

To try and avoid misunderstanding, let me explain this again. Let's say I have my colours for all bracket types set to "red, yellow, green, blue, purple". With the latest version I would just do that once, and check the option to use round-bracket colouring for all types. If I am in a new file and I type in the following:

`{<([])>}`

Then every character will be red.

If this feature is implemented then opening _any_ kind of bracket will shift the colour to the next in the range. So when I type into that new file:

`{<([])>}`

the colours of the characters should be: red, yellow, green, blue, blue, green, yellow, red.

This makes different bracket types stand out against each other much better.

Thanks!

**Comment by izhangzhihao** [comment]
I think you may just need to set different colors for different brackets.

**Comment by JumbleJumble** [comment]
Should I just take this as "this will not be implemented"? There is currently no way to achieve this.

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors

**Comment by JumbleJumble** [comment]
Hi, yes, there's still a misunderstanding here.

Let's say I have the option switched on for all bracket types to use the colour range - say red, yellow, green blue, purple.

At present the sequences would look like this:

( - red
[ - red
{ - red
} - red
] - red
) - red.

Or

( - red
( - yellow
( - green
[ - red
] - red
) - green
) - yellow
) - red

I know I could change this by setting colours for each bracket type.

However, with the feature I am talking about, the colours would cycle through the range any time a bracket of _any kind_ is opened, so you might get:

( - red
( - yellow
[ - green
( - blue
[ - purple
] - purple
) - blue
] - green
) - yellow
) - red

or 

[ - red
{ - yellow
[ - green
( - blue
[ - purple
] - purple
) - blue
] - green
} - yellow
] - red

This simply is not possible with the current config options.

**Comment by izhangzhihao** [comment]
Yep, what if your brackets don’t share any colors?

在 2020年1月30日，下午11:00，JumbleJumble <notifications@github.com> 写道：

﻿

Hi, yes, there's still a misunderstanding here.

Let's say I have the option switched on for all bracket types to use the colour range - say red, yellow, green blue, purple.

At present the sequences would look like this:

( - red
[ - red
{ - red
} - red
] - red
) - red.

Or

( - red
( - yellow
( - green
[ - red
] - red
) - green
) - yellow
) - red

I know I could change this by setting colours for each bracket type.

However, with the feature I am talking about, the colours would cycle through the range any time a bracket of any kind is opened, so you might get:

( - red
( - yellow
[ - green
( - blue
[ - purple
] - purple
) - blue
] - green
) - yellow
) - red

or

[ - red
{ - yellow
[ - green
( - blue
) - blue
] - green
} - yellow
] - red

This simply is not possible with the current config options.

**Comment by izhangzhihao** [comment]
I mean ([{ have does not have same color in any time.

在 2020年1月30日，下午11:00，JumbleJumble <notifications@github.com> 写道：

﻿

Hi, yes, there's still a misunderstanding here.

Let's say I have the option switched on for all bracket types to use the colour range - say red, yellow, green blue, purple.

At present the sequences would look like this:

( - red
[ - red
{ - red
} - red
] - red
) - red.

Or

( - red
( - yellow
( - green
[ - red
] - red
) - green
) - yellow
) - red

I know I could change this by setting colours for each bracket type.

However, with the feature I am talking about, the colours would cycle through the range any time a bracket of any kind is opened, so you might get:

( - red
( - yellow
[ - green
( - blue
[ - purple
] - purple
) - blue
] - green
) - yellow
) - red

or

[ - red
{ - yellow
[ - green
( - blue
) - blue
] - green
} - yellow
] - red

This simply is not possible with the current config options.

**Comment by izhangzhihao** [comment]
Or maybe I’m still not understanding this correctly, I will review it again tomorrow.

在 2020年1月30日，下午11:00，JumbleJumble <notifications@github.com> 写道：

﻿

Hi, yes, there's still a misunderstanding here.

Let's say I have the option switched on for all bracket types to use the colour range - say red, yellow, green blue, purple.

At present the sequences would look like this:

( - red
[ - red
{ - red
} - red
] - red
) - red.

Or

( - red
( - yellow
( - green
[ - red
] - red
) - green
) - yellow
) - red

I know I could change this by setting colours for each bracket type.

However, with the feature I am talking about, the colours would cycle through the range any time a bracket of any kind is opened, so you might get:

( - red
( - yellow
[ - green
( - blue
[ - purple
] - purple
) - blue
] - green
) - yellow
) - red

or

[ - red
{ - yellow
[ - green
( - blue
) - blue
] - green
} - yellow
] - red

This simply is not possible with the current config options.

**Comment by JumbleJumble** [comment]
You're right that this can only work if you are using the same colour set for all types of brackets. This option would only be available if you have enabled that option.

I have tried to illustrate here.

Option off (how it is now):

![image](https://user-images.githubusercontent.com/10434326/73463805-c72bea00-4375-11ea-8b98-7629bd017e72.png)

With new feature:

![image](https://user-images.githubusercontent.com/10434326/73463659-892ec600-4375-11ea-9147-e9a6f4d6eeeb.png)

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/73609205-57805e00-4606-11ea-815d-d6aa07bc35cb.png)

**Comment by JumbleJumble** [comment]
Awesome! Once I test this out I’ll definitely support the project! Thanks so much!

**Comment by izhangzhihao** [comment]
Please try the snapshot build here: https://github.com/izhangzhihao/intellij-rainbow-brackets#install

**Comment by izhangzhihao** [comment]
Oh, C# support is another story...

**Comment by izhangzhihao** [comment]
Please try the last build snapshot.

**Comment by JumbleJumble** [comment]
> Oh, C# support is another story...

Oh. C# is all I use it for!!

**Comment by izhangzhihao** [comment]
The latest snapshot already have C# support

在 2020年2月2日，下午10:43，JumbleJumble <notifications@github.com> 写道：

﻿

Oh, C# support is another story...

Oh. C# is all I use it for!!

**Comment by JumbleJumble** [comment]
Awesome, will try it tomorrow!

**Comment by JumbleJumble** [comment]
Just installed it and it seems to work great! Thanks!

**Comment by JumbleJumble** [comment]
Hmm, having some problems. ~~First one seems simple. it seems that square brackets [] don't use the same colour cycle as the other kinds of brackets.~~
-EDIT-: I realised the line I was looking at had a `<` sign in it, which is triggering the colour to cycle. That's the problem, because it's being used as a less-than symbol, not an angle bracket. The same problem exists with `>` greater-than symbols.

Second is I tried to configure 6 colours and it seems to only be using 5.

**Comment by izhangzhihao** [comment]
Please try edit the file or restart your IDE

在 2020年2月3日，下午7:30，JumbleJumble <notifications@github.com> 写道：

﻿

Hmm, having some problems. First one seems simple. it seems that square brackets [] don't use the same colour cycle as the other kinds of brackets.

Second is I tried to configure 6 colours and it seems to only be using 5.

**Comment by JumbleJumble** [comment]
Hi - the problem with the colour count went away by restarting the IDE, thanks! The problem with greater and less-than sign remains.

**Comment by izhangzhihao** [comment]
Screenshots?

在 2020年2月3日，下午7:55，JumbleJumble <notifications@github.com> 写道：

﻿

Hi - the problem with the colour count went away by restarting the IDE, thanks! The problem with greater and less-than sign remains.

**Comment by JumbleJumble** [comment]
Notice here on the top line the `<` sign is blue, which would be the next colour in the sequence. Then the `[]` are pink but the `{}` are blue again; they should be the same colour.

![image](https://user-images.githubusercontent.com/10434326/73652023-b634ee80-467d-11ea-987a-040e0094f4d0.png)

If I change the `<` to a `==`, the colours change to how they should be:

![image](https://user-images.githubusercontent.com/10434326/73652185-322f3680-467e-11ea-909f-3ef25414c3b5.png)

**Comment by izhangzhihao** [comment]
The two screenshots are same.

**Comment by JumbleJumble** [comment]
Edited and fixed.

**Comment by izhangzhihao** [comment]
The C# implementation is using the old annotator. The behavior of `<` is might relate to a known bug or the disadvantage of the old annotator.

**Comment by JumbleJumble** [comment]
OK, cool. It doesn't matter too much,

**Comment by izhangzhihao** [comment]
By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.

**Comment by JumbleJumble** [comment]
Done! Thanks for looking at this!
