### ISSUE TITLE
Highlight vertical line of active block

### ISSUE THREAD

**Issue by schrek1** [izhangzhihao/intellij-rainbow-brackets#392]
Is there option for highlight verical line which join braces in active block?

There is only when I place caret to start of method
![image](https://user-images.githubusercontent.com/17483576/73452475-47e4e900-436a-11ea-8fea-5ac35f8657d3.png)

But inside it isn't highlited
![image](https://user-images.githubusercontent.com/17483576/73452579-71057980-436a-11ea-9566-840e782d24c1.png)

**Comment by izhangzhihao** [comment]
I don't think I really understand your idea.

**Comment by schrek1** [comment]
Sorry it is duplicate of #380
