### ISSUE TITLE
Colorization of quotes is difficult to read, but can't be overridden

### ISSUE THREAD

**Issue by andrewryan1906** [izhangzhihao/intellij-rainbow-brackets#393]
## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ x ] This issue/feature request is not reported before.

## Your programming language(s)
Node/Javascript, WebSotem 2019.3

## Expected Behavior
I need to be able to change the color of matching quotes.

## Current Behavior
After I install your plugin, the colorization of bracket is light blue and really difficult to see:

![image](https://user-images.githubusercontent.com/37671394/73771771-f4e5aa00-474c-11ea-897e-9caeb0c1e318.png)

This is pretty easy to change in WebStorm here:

![image](https://user-images.githubusercontent.com/37671394/73771798-06c74d00-474d-11ea-8601-164df1909cb1.png)

But, when I change it, your plugin overwrites it whenever I restart the IDE. I've confirmed this by disabling your plugin and observing that the change persists.

How can I change this color and keep your plugin from overwriting my configuration change?

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/270
