### ISSUE TITLE
(Request) Rainbow Brackets on Switch() statements 

### ISSUE THREAD

**Issue by bryannevega** [izhangzhihao/intellij-rainbow-brackets#402]
Hello,

So far so good!

The only thing (maybe I'm missing the proper usage?) is to apply code block coloring on switch() and it's "case"s.

Thanks

**Comment by izhangzhihao** [comment]
Did you mean in java lang?

**Comment by bryannevega** [comment]
> 
> 
> Did you mean in java lang?

Yes, please!

**Comment by izhangzhihao** [comment]
It's a good idea. And, emmmm, there are many `switch`s, like `match` in scala, `when` in kotlin, `switch` in java, etc. I will be thinking about it...

**Comment by bryannevega** [comment]
> 
> 
> It's a good idea. And, emmmm, there are many `switch`s, like `match` in scala, `when` in kotlin, `switch` in java, etc. I will be thinking about it...

Awesome!

I imagine that people mostly use case/match for short statements but when the block of code is big enough, it's definitely a helpful thing! I was test driving the tool when I came across this yesterday.

Good luck!
