### ISSUE TITLE
Modified single quotes's color unnecessarily（jQuery）

### ISSUE THREAD

**Issue by wangziling** [izhangzhihao/intellij-rainbow-brackets#41]
## Current Behavior
The last single quote's color had been changed by this plugin in every pairs single quotes.
开了插件后，每对单引号中的最后一单引号颜色被修改了。好像就jQuery选择器会这样。

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change

## Code snippet for reproduce (for bugs)

- Enabled this plugin (开启这个插件)

![image](https://user-images.githubusercontent.com/24818903/37753969-74a4ae00-2dda-11e8-890d-e06d1248b749.png)
![image](https://user-images.githubusercontent.com/24818903/37754244-a96fafda-2ddb-11e8-8796-d14f15f19165.png)
![image](https://user-images.githubusercontent.com/24818903/37754256-bc5404f2-2ddb-11e8-92d7-fdae40ebaa7a.png)

- Disabled or uninstalled this plugin (禁用或者卸载这个插件)

![image](https://user-images.githubusercontent.com/24818903/37754059-ec3057b2-2dda-11e8-830e-c482b322e1eb.png)
![image](https://user-images.githubusercontent.com/24818903/37754295-f6958c8a-2ddb-11e8-9bdf-f5212b822146.png)
![image](https://user-images.githubusercontent.com/24818903/37754306-0164e99e-2ddc-11e8-827f-ec47da9c8653.png)

## Your Environment

* Plugin version: 5.0-RC3
* IDEA version: I used PHPstorm under ver.2017.3.6
* Operating System and version: win10 ver.1709  x64

**Comment by izhangzhihao** [comment]
It seems like `$` and `'` are pairs...

**Comment by wangziling** [comment]
好像是的...我还是打中文吧，英语太难了。。。

**Comment by wangziling** [comment]
但是好像要比$的颜色要深那么点。

**Comment by izhangzhihao** [comment]
是的...

**Comment by izhangzhihao** [comment]
你用的 PHP 是吧，我不熟悉 PHP，你能告诉我`$('')`是什么语法吗？

**Comment by wangziling** [comment]
jQuery的语法。JQuery是 javascript的一个库

**Comment by wangziling** [comment]
这个是在 js 文件里面。

**Comment by izhangzhihao** [comment]
提供一下那几段代码吧，蟹蟹

**Comment by wangziling** [comment]
```js
var  
    $searchQuestionsBtn = $('[data-name="searchQuestionsBtn"]'),
    oSubjects = $('#subjects'),
    $searchList = $('.search-list');
```

**Comment by wangziling** [comment]
![image](https://user-images.githubusercontent.com/24818903/37754962-86b67c5a-2dde-11e8-8cbc-fd71d4e391a3.png)
现在是在webstorm里面，没有引用JQuery的时候，也就是$是未定义的。这个也是在js文件下。

**Comment by wangziling** [comment]
![image](https://user-images.githubusercontent.com/24818903/37755051-d7cfd6a4-2dde-11e8-8e73-4bf1a8b1b03b.png)

还真的好像是 与 $ 成对了。

**Comment by izhangzhihao** [comment]
我的环境没有复现：

<img width="219" alt="screen shot 2018-03-22 at 3 10 18 pm" src="https://user-images.githubusercontent.com/12044174/37756096-2adce432-2de3-11e8-95ce-793637808868.png">

**Comment by wangziling** [comment]
emmm....其他人的界面也是这样，webstorm
![image](https://user-images.githubusercontent.com/24818903/37756248-bd77118c-2de3-11e8-92b5-4562afa1e73c.png)

**Comment by izhangzhihao** [comment]
emmmmm.... 除了这个插件之外你还装了什么第三方插件？

**Comment by wangziling** [comment]
他应该没有装什么的多余的。  我就多装了个 material ui

**Comment by wangziling** [comment]
我们都是win，看你的截图，感觉你是mac

**Comment by izhangzhihao** [comment]
我的环境是：
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.400, built on March 19, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

**Comment by wangziling** [comment]
PhpStorm 2017.3.6
Build #PS-173.4674.46, built on March 16, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by YiiGuxing** [comment]
使用JQuery，JQuery在IDE中有对应的JQuery Language。

我靠！这是被隐藏属性爆击了啊！！

 `$("#e")` 这代码包含了以下挂号对：
```
 {   CSS_LBRACE
 }   CSS_RBRACE
 (   JS:LPAR
 )   JS:RPAR
```
也就是说包含了隐藏属性：`{`和`}`，插件无法识别这些隐藏属性，所以着色出问题了。。。

**Comment by izhangzhihao** [comment]
这个环境复现成功:
IntelliJ IDEA 2017.2.7
Build #IU-172.4574.19, built on March 2, 2018
JRE: 1.8.0_144-b01 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Mac OS X 10.13.3

**Comment by wangziling** [comment]
:smile: 好像有点意思-.-

**Comment by izhangzhihao** [comment]
一脸懵逼/(ㄒoㄒ)/~~

**Comment by YiiGuxing** [comment]
先不管吧，不是什么大问题。。。

**Comment by wangziling** [comment]
😄

**Comment by kamronbatman** [comment]
Same issue:
Webstorm: 2018.2
Rainbow Bracket: 5.9.1
Mac OSX: 10.13.6

I hope there is a fix!

**Comment by izhangzhihao** [comment]
Close for nobody still using jQuery, it's 2020 now...

**Comment by liux-pro** [comment]
Even 2020，I‘m the one who still use “colorful” jQuery. o(╥﹏╥)o
![image](https://user-images.githubusercontent.com/20764978/94507914-64138f80-0243-11eb-97eb-4cd7214ebb5d.png)

**Comment by izhangzhihao** [comment]
Sad story.

**Comment by izhangzhihao** [comment]
The fix:

![image](https://user-images.githubusercontent.com/12044174/106728984-fc81ac80-6647-11eb-94a1-8fb3e1376ac0.png)

Open "Do not rainbowify brackets without content"
