### ISSUE TITLE
Rainbow indent guides does not respect IDE's own "Indent Guides" setting

### ISSUE THREAD

**Issue by TapGhoul** [izhangzhihao/intellij-rainbow-brackets#417]
## Your programming language(s)
Typescript JSX (TSX)

## Expected Behavior
Rainbow Brackets should respect the IDE's own "Indent Guides" setting
In Zen/no distraction mode, Rainbow Brackets should disable indent guides like how the IDE does when the plugin is not enabled (as zen mode toggles that setting when enabled/disabled).

## Current Behavior
Rainbow Brackets ignores the IDE's own indent guides setting, using its own indent guides regardless of what the IDE's own setting is.

## Possible Solution
Have Rainbow Brackets respect the IDE's own "indent guides" setting, and change Rainbow Brackets own settings to be "Rainbow-ify indent guides" (or some variation of) rather than "Show rainbow indent guides" - i.e. have it "colourize" instead of replacing.

## Your Environment

* Plugin version: 6.2
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
WebStorm 2020.1
Build #WS-201.6668.106, built on April 7, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.31-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: org.intellij.plugins.postcss, com.markskelton.one-dark-theme, AWSCloudFormation, aws.toolkit, izhangzhihao.rainbow.brackets, riot.js
Current Desktop: KDE
```

**Comment by izhangzhihao** [comment]
I guess what you are expecting is "stop rainbow anything(brackets/indents)" when entering "Zen mode".

**Comment by TapGhoul** [comment]
Personally I actually still want everything else. Just indent guides I want to obey what the editor's own setting is.
-------- Original Message --------

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/79750463-94c1d580-8343-11ea-8187-595dab12c6ae.png)

**Comment by izhangzhihao** [comment]
This feature will happen in the next release. If you want to have a try, please download the snapshot build from [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#install-snapshot-build). By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.
