### ISSUE TITLE
Provide pay link for Alipay donation

### ISSUE THREAD

**Issue by upsuper** [izhangzhihao/intellij-rainbow-brackets#418]
Hi! I'm a long-time user of this plugin, and like it very much, so I'm considering donating.

Generally I prefer donating through Alipay, but I don't like to go through their mobile app, so it would be great if you can provide a pay link which can be used via web directly.

Thanks for your work!

**Comment by izhangzhihao** [comment]
I didn't find a way that users can just click and pay. Did you know how to do this?
If you could read Chinese, please use [this link](https://shenghuo.alipay.com/send/payment/fill.htm) to transfer money to my Alipay account(izhangzhihao@hotmail.com). Or you can try the English version of Alipay(https://global.alipay.com/)

**Comment by izhangzhihao** [comment]
Donation received! Thanks, that’s means a lot. Hope you enjoy your colorful code🎉

**Comment by upsuper** [comment]
It would still be great if you can put a Alipay donation link in README. Not everyone wants to go through the mobile app :)

**Comment by izhangzhihao** [comment]
Yes, their mobile App is just terrible.
