### ISSUE TITLE
PHP act different when having only PHP compared to PHP with HTML

### ISSUE THREAD

**Issue by KGroenendijk** [izhangzhihao/intellij-rainbow-brackets#423]
## Your programming language(s)
* PHP with HTML

## Expected Behavior
Should act the same as a file with only PHP in there, like this:
![image](https://user-images.githubusercontent.com/42764875/80947316-317a7d80-8df0-11ea-8997-303818df2266.png)

## Current Behavior
Right now the colors in a regular PHP file really differ with a file like one with HTML in there, like this:
![image](https://user-images.githubusercontent.com/42764875/80947716-05abc780-8df1-11ea-80e3-56d2f4193954.png)

## Possible Solution
I'm having the issue since the 2020 update and I think there might be added something which I like to disable. Is there any way to do so via the XML plugin file. Keep in mind that I would really like to keep the colored brackets and all, just don't want the syntax color to change

## Code snippet for reproduce (for bugs)
When you are making a PHP file and put some HTML in there as well, you will notice my issue

## Your Environment
```
PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Licensed to Kevin Groenendijk
Subscription is active until October 9, 2020
For educational use only.
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1971M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: zielu.gittoolbox, com.almightyalpaca.intellij.plugins.discord, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin
```

**Comment by izhangzhihao** [comment]
I do not quite get your idea, maybe write it down by steps?

**Comment by KGroenendijk** [comment]
* Since the update of 2020.1.1 I see a change of syntax color with PHP files when having HTML implemented into the file.
* When messing around with it more I noticed that it acted different compared to a file with only PHP in there, but when I try to echo something the color of the syntax `echo` changes to green like the current behavior. This time without the change of color in the PHP tags at the top and bottom of the file.
* I was thinking, did you change anything that might be related to syntax color and tag color in PHP and is there a way of disabling it?

**Comment by izhangzhihao** [comment]
Oh, you are talking about the specific tag `php`, right?

**Comment by KGroenendijk** [comment]
Yes and stuff like `echo`

**Comment by izhangzhihao** [comment]
Ok, I'm sure I didn't make any changes in this plugin about PHP recently. But I found this happens when I upgrade the dep to `2020.1` from `2017.2`. So there is something changed in the PHP plugin. But I could have a try of the `php` tag. By the way, I'm still didn't get what happened to `echo`. just because it's become green?

**Comment by KGroenendijk** [comment]
It acts different compared to previous versions and it just looks odd when having a complete purple function with an `echo` in there which is green. What I mean is that not only the PHP tags have changed, but other stuff as well like `echo`

**Comment by izhangzhihao** [comment]
Please provide some sample code.

**Comment by KGroenendijk** [comment]
PHP with HTML:
```php
<?php
$template = $GLOBALS['file'];
?>
<section class="normal-section nbi-investors" id="section<?php echo $section['position']; ?>">
	<div class="grid-container <?php echo $fw ?> container-fluid">
    </div>
</section>
```
Regular PHP file:
```php
<?php

function format_price($price) {
	return number_format($price,2,',','.');
    echo 'test';
}
```

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/80956314-8d1a2a80-8e33-11ea-88b5-fa0cf5bbcf96.png)
![image](https://user-images.githubusercontent.com/12044174/80956626-29443180-8e34-11ea-82fc-76cebff85fa0.png)
![image](https://user-images.githubusercontent.com/12044174/80956645-306b3f80-8e34-11ea-9f77-a05d77d8094c.png)

**Comment by KGroenendijk** [comment]
I'm also getting the second example after the update and I would like to turn off everything that is different compared to the first example, is there a way to do so? Do you have a before and after of the third example?

**Comment by izhangzhihao** [comment]
That's because I'm using the `random color generator`. that's where the green comes from in my case.

**Comment by izhangzhihao** [comment]
Please try this build snapshot: 
[intellij-rainbow-brackets-6.3.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/4574089/intellij-rainbow-brackets-6.3.zip)

**Comment by KGroenendijk** [comment]
No change

**Comment by izhangzhihao** [comment]
Have you restart your IDE?

**Comment by KGroenendijk** [comment]
Yes, even tried earlier versions and restart but those are not compatible

**Comment by izhangzhihao** [comment]
Ah, you just want NOT rainbow `php` tag, right?

**Comment by izhangzhihao** [comment]
To be clear, the green color in your screenshot is nothing to do with this plugin.

**Comment by KGroenendijk** [comment]
YES, I don't want the rainbow php tag. NO, this is within the plugin because when I turn of the plugin the color goes back to the original color which is purple (same as php tag)

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/81056285-de422100-8efc-11ea-8801-79cf385c3d49.png)
![image](https://user-images.githubusercontent.com/12044174/81056299-e601c580-8efc-11ea-9320-86b180a23de1.png)

**Comment by izhangzhihao** [comment]
Please try this snapshot build: 
[intellij-rainbow-brackets-6.3.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/4580146/intellij-rainbow-brackets-6.3.zip)

**Comment by KGroenendijk** [comment]
You recommended this earlier and this didn't work, tried earlier versions like mentioned before and those didn't work as well. It seems like you have disabled something in the settings and I can't quite recognise what it is, could you tell me so I can recreate your environment

**Comment by KGroenendijk** [comment]
@izhangzhihao Found anything to get the result I want?

**Comment by izhangzhihao** [comment]
my env
```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to IntelliJ Rainbow Brackets / Zhang Zhihao
Subscription is active until February 19, 2021
For non-commercial open source development only.
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 8
Non-Bundled Plugins: org.jetbrains.plugins.ruby, Dart, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, org.intellij.scala, com.jetbrains.php
```

Did you tried to disable the Material Theme UI plugin?
