### ISSUE TITLE
Not colorizing angle brackets for Typescript generics

### ISSUE THREAD

**Issue by edalex-ian** [izhangzhihao/intellij-rainbow-brackets#427]
## Your programming language(s)

Typescript

## Expected Behaviour

That angle brackets for Typescript generics should be treated just as they are for generics in Java.

## Current Behaviour

Typescript angle brackets are left uncoloured:

![2020-05-14-110059_416x63_scrot](https://user-images.githubusercontent.com/43919233/81880964-3ac6cf80-95d2-11ea-9e8c-6024cb97cb1c.png)

## Possible Solution

I've confirmed it works fine in another language (Java), and other elements are being coloured by the plug-in in Typescript.

## Code snippet for reproduce (for bugs)

```typescript
let example: Array<Map<string,string>>;
```

## Your Environment

* Plugin version: 6.4
* IDE & Operating System version:

```
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to <redacted>
Subscription is active <redacted>
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.0-1-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Non-Bundled Plugins: IdeaVIM, com.4lex4.intellij.solarized, com.dubreuia, com.cursiveclojure.cursive, org.intellij.scala, izhangzhihao.rainbow.brackets, intellij.prettierJS
Current Desktop: Undefined
```

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/81918459-0ae6ee80-9609-11ea-8075-1d42471375a3.png)

This feature will happen in the next release. If you want to have a try, please download the snapshot build from [here](https://izhangzhihao.github.io/rainbow-brackets-document/#install-snapshot-build). By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.
