### ISSUE TITLE
Fatal Error when starting Intellij IDE after ver 6.5 update

### ISSUE THREAD

**Issue by nrmancuso** [izhangzhihao/intellij-rainbow-brackets#434]
## Your programming language(s)
Java, C, C++, MASM

## Current Behavior
IDE Fatal Error upon opening Intellij after latest update (6.5),  Rainbow Brackets will not start.

## Possible Solution
Restarting Intellij, reinstalling Intellij, disabling and removing other plugins doesn't help

## Code snippet for reproduce (for bugs)
Gist of output here: https://gist.github.com/nmancus1/0d7afc4322fa413eead986009ae2e137

## Your Environment
```
IntelliJ IDEA 2020.1.1 (Community Edition)
Build #IC-201.7223.91, built on May 7, 2020
Runtime version: 1.8.0_242-b08 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.4.39-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 6433M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: izhangzhihao.rainbow.brackets, com.thvardhan.gradianto, monokai-pro
Current Desktop: XFCE
```

**Comment by izhangzhihao** [comment]
Right, you are using java8, which is not supported anymore, please upgrade to java 11.
