### ISSUE TITLE
Duplicated indent guides in 2020.2 EAP

### ISSUE THREAD

**Issue by dima74** [izhangzhihao/intellij-rainbow-brackets#436]
## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming language(s)
Reproducible on any language

## Expected Behavior
Indent guides are not duplicated

## Current Behavior
In 2020.2 EAP indent guides are duplicated:
![image](https://user-images.githubusercontent.com/6505554/83513161-cd300400-a4ea-11ea-84df-3bd2ac89d389.png)

This is because standard indent guides have shifted a bit to the left, so I guess rainbow indent guides should be shifted as well.

## Code snippet for reproduce (for bugs)
Reproducible literally on any file, e.g. https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.1/src/main/resources/META-INF/plugin.xml

## Your Environment

- [x] I'm using java11, NOT java8.
* Plugin version: 6.5
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.4357.23, built on May 27, 2020
IntelliJ IDEA EAP User
Expiration date: June 26, 2020
Runtime version: 11.0.7+10-b912.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.6.15-arch1-1
GC: ParNew, ConcurrentMarkSweep
Registry: actionSystem.fixLostTyping=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, IndentRainbow, PsiViewer, intellij.haskell, org.jetbrains.idea.grammar, com.mnw.tabmover, com.wakatime.intellij.plugin, com.ppolivka.plugin.gitcleaner, org.toml.lang, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, org.rust.lang
Current Desktop: KDE
```

**Comment by izhangzhihao** [comment]
Right, that's the diff: https://github.com/JetBrains/intellij-community/commit/e3a677591f25ae1fdccecb1ac7f6e9dd8b641920#diff-82202b6d313676209d3b400d22b92726

**Comment by izhangzhihao** [comment]
Please try this snapshot build:
[intellij-rainbow-brackets-6.5.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/4717105/intellij-rainbow-brackets-6.5.zip)
