### ISSUE TITLE
连续的引号遇到html字符串时渲染颜色出错

### ISSUE THREAD

**Issue by wangziling** [izhangzhihao/intellij-rainbow-brackets#44]
## Current Behavior
好像当连续的引号遇到html字符串的时候，渲染颜色出错。
![image](https://user-images.githubusercontent.com/24818903/38032904-4c630ae4-32d1-11e8-92c7-cd3b1862fa6b.png)

## Code snippet for reproduce (for bugs)
Please provide code snippet
```js
var a = ''+''+''+""+""+'<li></li>';
a = ''+''+''+""+"()"+'<li></li>';
a = ''+''+'('+""+""+'<li></li>';
a = ''+"<li></li>";
```
## Your Environment

* Plugin version: 5.0-RC4
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
```
PhpStorm 2017.3.6
Build #PS-173.4674.46, built on March 16, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by izhangzhihao** [comment]
<img width="227" alt="screen shot 2018-04-26 at 12 34 12 am" src="https://user-images.githubusercontent.com/12044174/39259662-968060bc-48e9-11e8-95e5-cf7ebf7b82c0.png">

似乎只是在将空字符串与 html 代码 contact 的时候才会出现这种情况，见上图。
我认为这种情况的原因可能跟 html 插件有关，它可能将空字符串和 html 代码连起来当做一段 html，所以才会出现这种奇怪的现象。不过真正写代码的时候应该不会使用空字符串去连接 html 代码吧😁

**Comment by wangziling** [comment]
嗯。:smile:
