### ISSUE TITLE
Plugin Error: Plugin "Rainbow Brackets" is incompatible (until build 193.SNAPSHOT < PY-201.7846.77).

### ISSUE THREAD

**Issue by rive-n** [izhangzhihao/intellij-rainbow-brackets#448]
## Expected Behavior
> Plugin "Rainbow Brackets" is incompatible

## Current Behavior
* New version of PyCharn destroyed plugin

## Possible Solution
* Update plugin

**Comment by izhangzhihao** [comment]
Why not just update the plugin(check for update)

**Comment by rive-n** [comment]
> Why not just update the plugin(check for update)

tryed. pyCharm crashed

**Comment by izhangzhihao** [comment]
Any screenshots?

**Comment by rive-n** [comment]
> Any screenshots?

![image](https://user-images.githubusercontent.com/45512613/85720915-8bfdcf00-b6f9-11ea-8259-9f06d38921d2.png)

**Comment by izhangzhihao** [comment]
wow, you can install two versions at the same time? why not just uninstall the older one?

**Comment by rive-n** [comment]
> wow, you can install two versions at the same time? why not just uninstall the older one?

They are working in the same time. so i dont really know why :D 
like if i disable 1 - 2nd disabled too (it's appeared after update btw)

**Comment by izhangzhihao** [comment]
That's should be a bug of the IDE, but you can try to uninstall the two versions both, and after restart the IDE, install the newest version again.

**Comment by rive-n** [comment]
> That's should be a bug of the IDE, but you can try to uninstall the two versions both, and after restart the IDE, install the newest version again.


After a complete reinstall for some reason, it worked. However, after downloading the latest version of PyCharm IDE crashed.

So I don’t know if you should pay attention to this.
After deleting one version, both were deleted (For some reason unknown to me)

**Comment by izhangzhihao** [comment]
Right, please post your about info like this:

```
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets
```

I can make a bug report for the IDE

**Comment by izhangzhihao** [comment]
Or maybe you can do this since I didn't have much info than you.

**Comment by rive-n** [comment]
> Or maybe you can do this since I didn't have much info than you.


Yes, perhaps you're right. I will try to register a bug soon. Thank you for your prompt reply
