### ISSUE TITLE
Same level square brackets has different color

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#45]
## Your programming language
JavaScript

## Expected Behavior
Same level square brackets on line 2 must have the same color

## Current Behavior
Same level square brackets on line 2 have different color

## Code snippet for reproduce (for bugs)
```js
const a = [[0]]
const a[0][0]
```
![sketch](https://user-images.githubusercontent.com/6392013/38376670-c90fae5e-3901-11e8-9b64-35d40f9fbb98.png)

## Your Environment

* Plugin version: 5.0
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon): 
```
WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
Licensed to Oleksii Bobyr
Subscription is active until November 2, 2018
JRE: 1.8.0_152-release-991-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by Alexsey** [comment]
On the other hand - I can understand why it might be by design. Is it so?

**Comment by izhangzhihao** [comment]
It's not by design but by IDE build-in features.
PS: Same feature for python as well.
