### ISSUE TITLE
Kotlin: Unstable coloring of variable as function-like call

### ISSUE THREAD

**Issue by fee1-dead** [izhangzhihao/intellij-rainbow-brackets#453]
# Please check

- [x] I already support this project.
- [x] This issue/feature request is not reported before.

## Your programming language
Kotlin

## Expected Behavior
* The color of variable as function-like call should be the defined by color scheme

## Current Behavior
* Half of its color is color-scheme defined variable color, another half is function-like call.

## Code snippet for reproduce 
```kotlin
operator fun Int.invoke(){}
val foo = 0; var foo1 = 0; const val foo2 = 0
val bar = 1; var bar1 = 1; const val bar2 = 1
val baz = 2; var baz1 = 2; const val baz2 = 2
fun test(){
	foo(); foo1(); foo2()
	bar(); bar1(); bar2()
	baz(); baz1(); baz2()
}
```

## Your Environment

- [x] I'm using java11, NOT java8.
* Plugin version: 6.7

```
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2000M
Cores: 4
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Key Promoter X, CheckStyle-IDEA, com.almightyalpaca.intellij.plugins.discord, Lombook Plugin, com.demonwav.minecraft-dev, com.jetbrains.ChooseRuntime, com.wakatime.intellij.plugin, Dart, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, io.ktor.intellij.plugin, JRebelPlugin, MetricsReloaded, JProfiler, izhangzhihao.rainbow.brackets
```

**Comment by fee1-dead** [comment]
This is the color-scheme.
[Atom One Dark.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/4851473/Atom.One.Dark.zip)

**Comment by izhangzhihao** [comment]
Any screenshots? it seems works fine for me
![image](https://user-images.githubusercontent.com/12044174/86121877-644ba400-bb09-11ea-8bc4-0a5b90b67bfc.png)

**Comment by fee1-dead** [comment]
try using the color scheme I attached.
I already did some pre-testing and found out that disabling the plugin fixes it and appears normal again.

screenshot: 
![screenshot.png](https://user-images.githubusercontent.com/43851243/86122443-6d894080-bb0a-11ea-9785-bdc3ddf7c6e2.png)

**Comment by izhangzhihao** [comment]
And by the way, if it works fine without the Atom One Dark theme, I think you should report this as a bug for the Atom One Dark theme

**Comment by izhangzhihao** [comment]
Yep, colorify the function/variable name is not any part of this plugin.

**Comment by fee1-dead** [comment]
It works fine when using the theme but with the plugin disabled.
I think you might be using a color-scheme that does not define the "variable as function-like call" color.

**Comment by fee1-dead** [comment]
this is a screenshot of the theme working fine without the plugin:
![Screenshot from 2020-06-30 11-41-381593506553469](https://user-images.githubusercontent.com/43851243/86122744-e5576b00-bb0a-11ea-8ec3-b11d1a70af2c.png)

**Comment by izhangzhihao** [comment]
Emmmm, so what is your config, I didn't find any "variable as function-like call" from my preference.

**Comment by fee1-dead** [comment]
Under kotlin in the color-scheme section:
Under "properties and variables":
variable as function-like call

**Comment by izhangzhihao** [comment]
What is your config in detail?
![image](https://user-images.githubusercontent.com/12044174/86123252-b7265b00-bb0b-11ea-82aa-6daf5bbcd119.png)

**Comment by fee1-dead** [comment]
Try changing the foreground color, and see if the snippet i posted produces the problem

**Comment by izhangzhihao** [comment]
Ah, I see.

**Comment by izhangzhihao** [comment]
I checked again, but have no idea what's going wrong, but I still believe that should blame the Kotlin plugin itself, not Rainbow Brackets. So I'm going to close this issue, if you can help or find a way to fix this, please comment, I will re-open it.
