### ISSUE TITLE
cool idea, super slow on my code base

### ISSUE THREAD

**Issue by streamnsight** [izhangzhihao/intellij-rainbow-brackets#46]
## Your programming language
Python, JS

## Your Environment

* Plugin version: 5.0
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

PyCharm 2017.3.3 (Professional Edition)
Build #PY-173.4301.16, built on January 11, 2018
Licensed to --------------------------------
Subscription is active until April 19, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

Pycharm just takes seconds, sometimes dozens of seconds, to update.
I use eslint for auto-linting, maybe it conflicts with this plugin.

**Comment by izhangzhihao** [comment]
If  you have suspicion of the 'eslint', did you tried to disable lint? Or disable rainbow brackets?

**Comment by izhangzhihao** [comment]
I'm going to close this issue, feel free to re-open it or raise a new one if you have any issue.
