### ISSUE TITLE
Flashes of indexation every few seconds even while idle

### ISSUE THREAD

**Issue by Alphare** [izhangzhihao/intellij-rainbow-brackets#47]
## Your programming language
Python/JSX

## Expected Behavior
Indexation at plugin install time, then dynamic coloring when typing, and no "white flashes".

## Current Behavior
Every few seconds, most of the syntactic coloration disappears then comes back, even while idle. This is very distracting and kind of a deal breaker.
Performance itself is fine.

## Your Environment

* Plugin version: 5.0
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
PyCharm 2018.1 (Professional Edition)
Build #PY-181.4203.547, built on March 26, 2018
Licensed to XXXXXX / Raphaël Gomès
Subscription is active until June 23, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-53-generic
```

**Comment by izhangzhihao** [comment]
Can you provide a gif screenshot?

**Comment by Alphare** [comment]
@izhangzhihao I can't seem to reproduce the issue after disabling/re-enabling the plugin... I'll get back to you should it happen again

**Comment by izhangzhihao** [comment]
Good to know. If this issue happened again re-open this issue please.
