### ISSUE TITLE
Support for files with .shader .cginc .hlsl extensions

### ISSUE THREAD

**Issue by viruseg** [izhangzhihao/intellij-rainbow-brackets#478]
Please add support for files with .shader .cginc .hlsl extensions for Rider. The latest version of Rider 2020.2 provides full support for shaders, but the Rainbow Brackets plugin does not work with these files. Thank you.

**Comment by izhangzhihao** [comment]
For .hlsl file, the UE4 Rider even don't have C++ front parser support, so this should be done only after this feature request: #424 (according to https://github.com/JetBrains/resharper-unity/issues/216#issuecomment-618079910)

For .shader .cginc files, there seems still don't have a front parser. you can check https://github.com/JetBrains/resharper-unity/pull/78/files

So basically the Rider has really different ecosystems compare with other IntelliJ-based IDEs. For specific file support like([F# support](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/186) or [cshtml support](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/191) or [C++ support for UE 4 Rider](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/424)) they all need some font parser implemented in the Rider part in first place. For now, the Rider only has backend parser support. So if you really need this, please submit a feature request for the Rider IDE in here: https://youtrack.jetbrains.com/issues/RIDER


By the way, please considers donating to this project on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) if you love this plugin.

**Comment by izhangzhihao** [comment]
.shader file already supported, with [GLSL plugin](https://plugins.jetbrains.com/plugin/6993-glsl-support)
![image](https://user-images.githubusercontent.com/12044174/108810540-50980500-75e6-11eb-9345-fadc1d43b67b.png)

**Comment by izhangzhihao** [comment]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/12044174/211548621-0b039a0b-89ce-4574-bb12-0694ba919171.png">

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/12044174/211548705-036be735-ec3f-483b-8e5c-be790bc5b9f3.png">


Support for .cginc and .hlsl files will be in the next release. because of some limitations of JetBrains, I could not support all brackets in .cginc file.

**Comment by izhangzhihao** [comment]
Please try this build snapshot:
[intellij-rainbow-brackets-2023.1.0-ij.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/10382879/intellij-rainbow-brackets-2023.1.0-ij.zip)
