### ISSUE TITLE
rainbow-brackets does not support bash shell properly

### ISSUE THREAD

**Issue by binbjz** [izhangzhihao/intellij-rainbow-brackets#481]
## programming language(s)
bash shell
## Expected Behavior
* Bash shell can display syntax highlighting correctly. Example: For keyword "if, then, fi, for, do, done", they should be the same color scheme.

## Current Behavior
* broken highlighting.
* I've tried enabling rainbow parentheses with BashSupport Pro or Shell Script, and neither of them displays syntax highlighting correctly.

## Possible Solution
rainbow-Brackets plugin is not compatible with the bash shell.

## Your Environment
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,3
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB

Pycharm、Idea、Clion are the same version with 2020.2.1, Rainbow-brackets version 6.10

## rainbow-brackets with pycharm, idea, clion (broken highlighting)
<img width="520" alt="issue" src="https://user-images.githubusercontent.com/8213913/92073171-b1881280-ede5-11ea-8982-57108c78f67d.png">

## Bash Support or Shell Script will work well after I disabled "rainbow Brackets" plugin.
<img width="444" alt="Screen Shot 2020-09-05 at 14 38 12" src="https://user-images.githubusercontent.com/8213913/92299521-85a39300-ef85-11ea-89ae-2b9de57d1093.png">

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/92117028-38111400-ee27-11ea-9c18-6dcbcdca3536.png)

**Comment by izhangzhihao** [comment]
Since "BashSupport Pro" is a close source & paid plugin, I could not support BashSupport Pro.
Since BashSupport has been retired, so BashSupport won't get supported.

Please try this snapshot build:

[intellij-rainbow-brackets-6.10.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5168954/intellij-rainbow-brackets-6.10.zip)

**Comment by izhangzhihao** [comment]
So, finally, BashSupport Pro and Shell Script will get proper support in the next release. please don't forget to upgrade BashSupport Pro and IntelliJ Rainbow Brackets.
