### ISSUE TITLE
JSON color difference indistinguishable 

### ISSUE THREAD

**Issue by izznogooood** [izhangzhihao/intellij-rainbow-brackets#486]
![Screenshot from 2020-09-16 21-48-10](https://user-images.githubusercontent.com/23040578/93386031-63542400-f867-11ea-807b-b7e40a76e82f.png)

**Comment by izhangzhihao** [comment]
It seems that `[` and `{` has the same level. To fix that, you can try [color generator](https://github.com/izhangzhihao/intellij-rainbow-brackets#use-color-generator) or [define your own color for different brackets](https://github.com/izhangzhihao/intellij-rainbow-brackets#customize-colors).

**Comment by izznogooood** [comment]
Yes, and it seems like they are slightly different if you look very close ;).
Thank you for the tip. New colors works fine.
