### ISSUE TITLE
Wrong scope highlighting in `.lock`

### ISSUE THREAD

**Issue by maxwase** [izhangzhihao/intellij-rainbow-brackets#490]
## Your programming language(s)

Rust

## Expected Behavior
[[package]] - 2 scopes 2 colors (and correct scopes)

## Current Behavior
The plugin incorrectly recognizes scopes in `.lock` files (see pictures down below)
![image](https://user-images.githubusercontent.com/23321756/94163843-0113a880-fe91-11ea-96cd-b8c32b15433f.png)

## Code snippet for reproduce (for bugs)

You can see this by creating a new rust project, add new dependency in `Cargo.toml` file and compile your project. `Cargo.lock` file will automatically generate.

```
[[package]]
name = "tokio"
version = "0.2.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5d34ca54d84bf2b5b4d7d31e901a8464f7b60ac145a284fba25ceb801f2ddccd"
dependencies = [
 "bytes",
 "pin-project-lite",
]
```
## P.S.

Of course it is not critical and no one will use this, i've discovered this accidentally, but it is a bug, so I should report it :)
 
## Your Environment

* Plugin version: 6.11
```
CLion 2020.2.3
Build #CL-202.7319.72, built on September 17, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.7.15-100.fc31.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.allow.merge.buttons=false, search.everywhere.settings=true, debugger.watches.in.variables=false, cidr.max.intellisense.file.length=600000
Non-Bundled Plugins: name.kropp.intellij.makefile, org.jetbrains.plugins.localization, org.toml.lang, tanvd.grazi, izhangzhihao.rainbow.brackets, org.rust.lang, rs.pest
Current Desktop: KDE
```

**Comment by izhangzhihao** [comment]
If would not be a bug if the `[[` and `]]` must appear at the same time, like some template language:

code is taken from https://docs.djangoproject.com/en/3.1/ref/templates/language/

```
<h1>{{ section.title }}</h1>
```

the `{{` and `}}` must appear at the same time , and they are one pair. 

So, I think this's what I expected.

**Comment by maxwase** [comment]
Okay, sounds reasonable, I didn't get it firstly
