### ISSUE TITLE
C# in Rider - only squiggly brackets are rainbowified

### ISSUE THREAD

**Issue by machekku** [izhangzhihao/intellij-rainbow-brackets#497]
## Your programming language(s)

C#

## Expected Behavior

I installed RainbowBrackets in Rider. I expected to see all brackets colored. Only squiggly brackets and indent lines are colored. 

## Current Behavior

Round brackets, etc, are all in default color, not rainbow.

## Code snippet for reproduce (for bugs)

```
using System;

namespace Test1
{
    public class Test
    {
        public void MyTest()
        {
            Console.WriteLine(new Test());
        }
    }
}

```
![rainbow](https://user-images.githubusercontent.com/16875/95731221-8532a200-0c7f-11eb-8cd4-0d254a54b860.PNG)
## Your Environment
Plugin version: 6.11

```
JetBrains Rider 2020.2.4
Build #RD-202.7660.16, built on September 30, 2020
Licensed to ........
You have a perpetual fallback license for this version
Subscription is active until September 14, 2021
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: com.microsoft.vso.idea, izhangzhihao.rainbow.brackets
```

**Comment by izhangzhihao** [comment]
For C#, the psi structure of the code 

```C#
Console.WriteLine(new Test());
```

is 

```
        CSharpDummyNode(112,142)
              PsiElement(IDENTIFIER)('Console')(112,119)
              PsiElement(DOT)('.')(119,120)
              PsiElement(IDENTIFIER)('WriteLine')(120,129)
              PsiElement(LPARENTH)('(')(129,130)
              PsiElement(NEW_KEYWORD)('new')(130,133)
              PsiWhiteSpace(' ')(133,134)
              PsiElement(IDENTIFIER)('Test')(134,138)
              PsiElement(LPARENTH)('(')(138,139)
              PsiElement(RPARENTH)(')')(139,140)
              PsiElement(RPARENTH)(')')(140,141)
              PsiElement(SEMICOLON)(';')(141,142)
```

**Comment by izhangzhihao** [comment]
For javascript, the psi structure of the code

```javascript
console.log(new PannerNode())
```

is 

```
JSFile:Dummy.js(0,30)
  JSExpressionStatement(0,29)
    JSCallExpression(0,29)
      JSReferenceExpression(0,11)
        JSReferenceExpression(0,7)
          PsiElement(JS:IDENTIFIER)('console')(0,7)
        PsiElement(JS:DOT)('.')(7,8)
        PsiElement(JS:IDENTIFIER)('log')(8,11)
      JSArgumentList(11,29)
        PsiElement(JS:LPAR)('(')(11,12)
        JSNewExpression(12,28)
          PsiElement(JS:NEW_KEYWORD)('new')(12,15)
          PsiWhiteSpace(' ')(15,16)
          JSReferenceExpression(16,26)
            PsiElement(JS:IDENTIFIER)('PannerNode')(16,26)
          JSArgumentList(26,28)
            PsiElement(JS:LPAR)('(')(26,27)
            PsiElement(JS:RPAR)(')')(27,28)
        PsiElement(JS:RPAR)(')')(28,29)
  PsiWhiteSpace('\n')(29,30)
```

**Comment by izhangzhihao** [comment]
The reason of why it does not works well for C#, is because clearly, the PSI structure of **js** implementation has a nested structure, but for C#, the structure just been flattened.

**Comment by izhangzhihao** [comment]
And, all levels of round brackets are not been recognized correctly. So I made [this change](https://github.com/izhangzhihao/intellij-rainbow-brackets/blob/2020.2/src/main/kotlin/com/github/izhangzhihao/rainbow/brackets/visitor/DefaultRainbowVisitor.kt#L37-L39), it will use the first level color, if the brackets are not been recognized correctly.

**Comment by izhangzhihao** [comment]
If someone has free time to implement the specific logic for C# lang would be great.

**Comment by rf-0** [comment]
This is still happening (c#). Using v6.15

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/108627523-03564f00-7491-11eb-95ac-5f103fcb51e2.png)

**Comment by izhangzhihao** [comment]
Try this build snapshot, please [SUPPORT US](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) if you like this plugin.

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/108704089-7a015400-7546-11eb-8dba-e98051819917.png)

Please use the latest snapshot:

[intellij-rainbow-brackets-6.15.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/6021677/intellij-rainbow-brackets-6.15.zip)

**Comment by MeisterDerMagie** [comment]
I just bought Rainbow Brackets and this issue still seems to occur. Has the fix been published yet?

**Comment by izhangzhihao** [comment]
> I just bought Rainbow Brackets and this issue still seems to occur. Has the fix been published yet?

@MeisterDerMagie what is your IDE version and plugin version?

**Comment by MeisterDerMagie** [comment]
I use JetBrains Rider 2023.1.2 and Rainbow Brackets 2023.3.2. Only squiggly brackets are differently colored. All others have the first level color.

**Comment by intellij-rainbow-brackets** [comment]
hi there have an IDE issue, please upgrade  to  Rider  2023.2. Your issue should be fixed.
________________________________

**Comment by MeisterDerMagie** [comment]
That did indeed solve the issue. Thank you for the quick answer!
