### ISSUE TITLE
Angle brackets in React

### ISSUE THREAD

**Issue by stlr00** [izhangzhihao/intellij-rainbow-brackets#508]
I try to turn off angle brackets, but it is still working, why?
I use React JS.

![image](https://user-images.githubusercontent.com/61075639/96287549-ca8e0100-0fea-11eb-9cd0-47d9c8d19f84.png)
![image](https://user-images.githubusercontent.com/61075639/96287562-d083e200-0fea-11eb-909b-7ddf5c7851f8.png)
![image](https://user-images.githubusercontent.com/61075639/96287585-d974b380-0fea-11eb-89c0-92dd0e280094.png)

WebStorm 2020.2.3
Build #WS-202.7660.23, built on September 30, 2020
Licensed to Alexandr Vesyolkin
Subscription is active until July 9, 2021
For educational use only.
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: project.tree.structure.show.url=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi, com.intellij.database, izhangzhihao.rainbow.brackets

**Comment by izhangzhihao** [comment]
https://github.com/izhangzhihao/intellij-rainbow-brackets#html-code-in-js

**Comment by izhangzhihao** [comment]
It's JSX, not angle brackets, though it looks the same as angle brackets.

**Comment by stlr00** [comment]
So if i turn off "Apply colors of round for all brackets" everything will work fine

**Comment by izhangzhihao** [comment]
Oh, right.
