### ISSUE TITLE
Preview image become unreadable

### ISSUE THREAD

**Issue by Alexsey** [izhangzhihao/intellij-rainbow-brackets#51]
## Expected Behavior
Preview image should be representative

## Current Behavior
Preview image is a mess (see screens)

## Code snippet for reproduce (for bugs)
![preview update](https://user-images.githubusercontent.com/6392013/39573485-11877b04-4edc-11e8-82bc-a30a525ae96c.png)
![preview plugin](https://user-images.githubusercontent.com/6392013/39573488-12f3deba-4edc-11e8-9b3a-30536925fef1.png)

## Your Environment

* Plugin version: 5.2
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
WebStorm 2018.1.2
Build #WS-181.4668.60, built on April 23, 2018
Licensed to Oleksii Bobyr
Subscription is active until November 2, 2018
JRE: 1.8.0_152-release-991-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by izhangzhihao** [comment]
Related to #49

**Comment by izhangzhihao** [comment]
Maybe I should remove the screenshots from preview image...

**Comment by Alexsey** [comment]
Maybe you can just crop a smaller piece of a screen? So it should not scale and fit the window at the same time
