### ISSUE TITLE
Add option to remove the color for XML/HTML from entire tag (back to just the brackets)

### ISSUE THREAD

**Issue by dragonmerc** [izhangzhihao/intellij-rainbow-brackets#516]
I recently updated to the newest version of this plugin and one thing I didn't like was that in HTML, the entire tag is now colored. While I can see some people liking this, I am not a fan. I have specific colors for tags and it helps me keep things easy to find. Now that that entire tag is colored, my code doesn't look right to me anymore. I have had to turn off angle brackets in the options to remove this and now I don't have colors for those brackets anywhere.

## Possible Solution
Add option to remove the color for XML/HTML from entire tag (back to just the brackets).

## Your Environment

* Plugin version: 6.12
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Licensed to ....
Subscription is active until July 4, 2021
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: String Manipulation, com.khmelyuk.multirun, net.ashald.envfile, org.jetbrains.plugins.vagrant, intellij.prettierJS, org.jetbrains.plugins.vue, tv.twelvetone.intellij.plugins.intellivue, org.jetbrains.kotlin, com.jetbrains.php, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, training

**Comment by cyb3rko** [comment]
Definitely feel your point.

**Comment by keeganwitt** [comment]
A simple checkbox would be enough for my use case. But I started thinking, maybe some users would want on for HTML, but not for XML for performance reasons. Maybe it'd be better to configure by file type. This could possibly exist today as a use case (e.g. giant JSON files).

**Comment by HonLuk** [comment]
Oh my god, this is a disaster.I've turned off the Angle brackets option for now.Thank you for the way to protect my eyes @dragonmerc

**Comment by webistomin** [comment]
Is there a way to downgrade plugin?😁

**Comment by izhangzhihao** [comment]
yes, if you want to use the previous version, please download from https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/97187

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/97293482-ae5e4f80-1887-11eb-825d-e42b5c636ea4.png)

A new option added, which is disabled by default.

**Comment by izhangzhihao** [comment]
A new release already made, which will be available within two days.

**Comment by webistomin** [comment]
Thanks 🥇

**Comment by izhangzhihao** [comment]
The new release already available.
