### ISSUE TITLE
Flat out all text other than brackets on key press.

### ISSUE THREAD

**Issue by VladOstrovski** [izhangzhihao/intellij-rainbow-brackets#52]
When you have a lot of colors in the editor, the brackets are still hard to match. A good solution should be to gray out all the text other than the brackets on a key press (or when you have mismatched parentheses which is primary when it's needed).

**Comment by izhangzhihao** [comment]
Seems related to #37

**Comment by VladOstrovski** [comment]
Well, if you're in a broken parentheses state, the "current" scope is not very helpful..

**Comment by izhangzhihao** [comment]
You are Correct. It's a cool idea, I will give a try, but note that even the IDE can't make the mismatched parentheses much intuitively.

**Comment by VladOstrovski** [comment]
Right. That's we do it with our eyes :)

**Comment by VladOstrovski** [comment]
I've implemented this, but i'm having trouble with layering. Maybe I could create a pull request and see if you guys can help out? Let me know.

**Comment by izhangzhihao** [comment]
Good to know, let's do it.:smile:

**Comment by izhangzhihao** [comment]
Close because #63 already available.
