### ISSUE TITLE
The closing brackets or keywords are not highlighted 

### ISSUE THREAD

**Issue by shunwen** [izhangzhihao/intellij-rainbow-brackets#53]
## Your programming language
Ruby

## Expected Behavior
* The closing brackets or keywords should be highlighted correctly

## Current Behavior
* The closing brackets or keywords are not highlighted 
<img width="192" alt="signup_modal rb core 2018-05-07 13-59-17" src="https://user-images.githubusercontent.com/485385/39686994-d9f37a50-51fe-11e8-9757-731c41037e96.png">

## Your Environment

* Plugin version: 5.2
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
RubyMine 2018.1.1
Build #RM-181.4445.97, built on April 11, 2018
Licensed to Shunwen Hsiao
Subscription is active until February 4, 2019
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
```

**Comment by jdreesen** [comment]
This is broken (at least for curly brackets) in PHP, too.

![grafik](https://user-images.githubusercontent.com/424602/39705353-739394f6-520e-11e8-9088-9e937ecf56f7.png)


## Your programming language
PHP

## Your Environment

* Plugin version: 5.2
* IDE & Operating System version:

```
PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-39-generic
```

**Comment by izhangzhihao** [comment]
@jdreesen Did you mean older version works fine?

**Comment by izhangzhihao** [comment]
It will be great if I will have your code gists.

**Comment by izhangzhihao** [comment]
Seems break by 9cecce78c36bace1bf72bab1824ef873cbce9aef

**Comment by izhangzhihao** [comment]
@shunwen It works before version 5.1, I'm sorry that I break that.

**Comment by izhangzhihao** [comment]
Related to #48

**Comment by izhangzhihao** [comment]
Related to #55

**Comment by shunwen** [comment]
@izhangzhihao No problem at all, thank you for this amazing plugin. If you need ruby snippet I copied the example from RubyMine to this gist: https://gist.github.com/shunwen/be6ae7019a71593c070fa57ab703992b

**Comment by izhangzhihao** [comment]
All fixed

**Comment by izhangzhihao** [comment]
New version 5.4 just published, you will receive this update serval days later. Or use this [intellij-rainbow-brackets-5.4.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1980442/intellij-rainbow-brackets-5.4.zip)

**Comment by shunwen** [comment]
Hi @izhangzhihao , thanks for the quick fix. The `end` keyword is highlighted correctly in Ruby now, but the brackets `)]` are still not highlighted.

**Comment by izhangzhihao** [comment]
@shunwen did you mean "[()]" not working? Does it works in previous version?

**Comment by shunwen** [comment]
@izhangzhihao I think everything works fine in version 5.1, and every closing brackets/keywords are broken in version 5.2. In version 5.4, sometimes it works sometimes it doesn't.

<img width="463" alt="scratch_51 rb 2018-05-08 08-28-55" src="https://user-images.githubusercontent.com/485385/39731438-2e28fcd0-529a-11e8-8083-9c856d072d38.png">

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-5.4.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1982063/intellij-rainbow-brackets-5.4.zip)

try this build snapshot version. This issue should been fixed.
