### ISSUE TITLE
customize colour

### ISSUE THREAD

**Issue by yingbo** [izhangzhihao/intellij-rainbow-brackets#57]
Great if the colour of each level can be customized.

**Comment by izhangzhihao** [comment]
See [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#config-brackets-colors), you could customize you own rainbow color.

**Comment by izhangzhihao** [comment]
PS: A config example [here](https://gist.github.com/Avinash-Bhat/c4d0575dad56046d930b1af3197d8d5d)

**Comment by yingbo** [comment]
Thanks!

**Comment by izhangzhihao** [comment]
Have fun!
