### ISSUE TITLE
Curly Braces Color Issue with Laravel Blade

### ISSUE THREAD

**Issue by webworthydesign** [izhangzhihao/intellij-rainbow-brackets#58]
## Your programming language
PHP Laravel Blade

## Current Behavior
![rainbow-brackets-laravel-blade](https://user-images.githubusercontent.com/1003195/39976297-05af8560-5701-11e8-9994-5e65033c42da.PNG)
Color of curly braces is not matching correctly. Seems to consider the $ as the first curly brace.

## Expected Behavior
The $ should not change colors. First inner curly brace should.

## Code snippet for reproduce (for bugs)
`<small>Written on {{$post->created_at}}</small>`

## Your Environment
* Plugin version:
5.5

* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
Licensed to Dave Williams
Subscription is active until March 9, 2019
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by izhangzhihao** [comment]
<img width="356" alt="screen shot 2018-05-14 at 12 02 16 pm" src="https://user-images.githubusercontent.com/12044174/39977760-b0353904-576e-11e8-9269-3f62e945fd0e.png">
If there is nothing in the braces, it works fine.

**Comment by izhangzhihao** [comment]
<img width="298" alt="screen shot 2018-05-14 at 12 03 56 pm" src="https://user-images.githubusercontent.com/12044174/39977808-e946a76e-576e-11e8-89bb-c1b5fab39bd2.png">

And if you put a backspace after your variable, it works fine.

**Comment by izhangzhihao** [comment]
I think our colors been covered by PHP plugin built-in functionality, so this should be a bug of PHP plugin.

**Comment by webworthydesign** [comment]
Ok, so the fault is with the PHP plugin?... and Rainbow Brackets is working as intended?

**Comment by izhangzhihao** [comment]
Yep, I think so.

**Comment by webworthydesign** [comment]
Hmmm... so is there any way I can fix this? Or at least disable it when in a blade file?

**Comment by izhangzhihao** [comment]
I think it's similar to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000117450-My-HighlightVisitor-been-covered-by-intellij-built-in-functionality

**Comment by izhangzhihao** [comment]
If anyone can find which "Color Scheme" setting lead to this behavior, I can create a workaround to cover the built-in settings.

**Comment by izhangzhihao** [comment]
Another simple workaround is add blackspace before brackets, just like https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/58#issuecomment-388691080

**Comment by webworthydesign** [comment]
Hmmm... I'm currently using the "One Dark" theme, which can be found here...
https://github.com/yurtaev/idea-one-dark-theme

But I tried switching to the default Darcula theme and I'm still having the issue. Also still happens even with nothing in the braces or a space at the end like shown above...

ONE DARK
![still-broke-one-dark](https://user-images.githubusercontent.com/1003195/40078209-fcdbbae2-5851-11e8-949a-263d55978e9c.png)

DARCULA
![still-broke-darcula](https://user-images.githubusercontent.com/1003195/40078217-00d7ed32-5852-11e8-957a-83a07ed67f31.png)

**Comment by izhangzhihao** [comment]
By the way, is there any other plugins you are using now? like "Laravel plugin" or something else related.

**Comment by webworthydesign** [comment]
Yep, I did some testing and it does seem like it is indeed the "Laravel Plugin", which also requires the "Blade Support" plugin (which it automatically downloads with it), that is causing the problem! Maybe you can implement some sort of work-around? Would be great!

Thanks for all your help and concern... it is very appreciated!

**Comment by izhangzhihao** [comment]
Maybe you can submit a issue [here](https://youtrack.jetbrains.com/issues/WI).

As I see, this situation is similar to [this](intellij-support.jetbrains.com/hc/en-us/community/posts/360000117450-My-HighlightVisitor-been-covered-by-intellij-built-in-functionality), if that is true and someone can find which "Color Scheme" setting lead to this behavior, I can create a workaround to cover the built-in settings.

PS: I don't know any syntax of PHP or Laravel.
