### ISSUE TITLE
Support C# language

### ISSUE THREAD

**Issue by nvlad** [izhangzhihao/intellij-rainbow-brackets#6]
![image](https://user-images.githubusercontent.com/2493052/31709729-84fda972-b3fb-11e7-86d0-1d3995990512.png)

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-2.3.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/1394249/intellij-rainbow-brackets-2.3.zip)

Please try this snapshot build and give me feedback, thanks

**Comment by nvlad** [comment]
Not work. Tested on latest Rider EAP build.

**Comment by izhangzhihao** [comment]
Thanks for your feedback, I will check it later.
________________________________

**Comment by izhangzhihao** [comment]
Related to https://youtrack.jetbrains.com/issue/IJSDK-324

**Comment by izhangzhihao** [comment]
Related to https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000670130-I-want-create-a-plugin-which-will-support-C-language

**Comment by izhangzhihao** [comment]
As [Alexander-Kirsanov](https://intellij-support.jetbrains.com/hc/en-us/profiles/1283077561-Alexander-Kirsanov) said : "The good thing however is that in 2017.3 will provide light-weight parser for C# files which should be enough for needs of Rainbow Brackets plugin."

So that I think this plugin will work in latest EAP version of Rider. But I don't have any .Net environment . 

@nvlad Have you tried this plugin in lasted EAP version of Rider, or any update on that?

**Comment by SugoiDev** [comment]
Confirmed: not working with Rider 2017.3 EAP (updated today).

**Comment by izhangzhihao** [comment]
I can't do anything on that , the only way is waiting for Rider team add a tiny layer  which will support annotators like what Alexandre Kirsanov said before...

**Comment by izhangzhihao** [comment]
@EReeves @SugoiDev thanks for your feedback!

**Comment by izhangzhihao** [comment]
Rider 2017.3 already been released! Ping @EReeves @SugoiDev , any update on that?

**Comment by SugoiDev** [comment]
@izhangzhihao Still not working on latest Rider. Did they add the abstraction for annotators?

**Comment by izhangzhihao** [comment]
The response from Rider team is [this task has been postponed to future releases. Current estimates are 2018.1-2018.2](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000670130/comments/115000648424)

**Comment by yunlux** [comment]
still faild in Rider 2018.1 nightly

**Comment by izhangzhihao** [comment]
Thanks for your feedback! Maybe the functionality will work until 2018.2 releases.

**Comment by yongyili** [comment]
Rainbow Brackets 5.0 still failed in Rider 2018.3.1 :(

**Comment by izhangzhihao** [comment]
@yongyili Rider **2018.3.1** ? Are you serious?

**Comment by yongyili** [comment]
Sorry, Rider 2017.3.1…… -____-

**Comment by kamilbudziewski** [comment]
Any news on that? It doesn't work in Rider 2018.1.

**Comment by izhangzhihao** [comment]
There is nothing I could do but waiting for Rider team.

**Comment by izhangzhihao** [comment]
You could add new comments in [this thread](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000670130-I-want-create-a-plugin-which-will-support-C-Sharp-language), or vote for this thread.

**Comment by kirill-d-lappo** [comment]
@wudzik, the author can't do anything for now.
The problem is that extensions in Rider has no access to code model in .cs files. 
I tried to write an extension, which analyzes some attributes of methods in class for my own needs, but it is impossible, Rider's SDK allows only to get . cs file content as simple text, you can't visit code parts and get or change their values or/and properties.

**Comment by SugoiDev** [comment]
Confirming it still doesn't work on 2018.2 EAP/Nightly.
I'm leaving the plugin enabled, so I'll post back here as soon as I see it working.

**Comment by izhangzhihao** [comment]
Update: [RIDER-16744 Provide light-weight dummy C# parser on frontend](https://youtrack.jetbrains.com/issue/RIDER-16744). It seems [will be available starting from the first 2018.3 EAPs](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000670130/comments/360000059320).

**Comment by SugoiDev** [comment]
Update: [Starting from 2018.3 EAP2 Rider will expose simple version of parser on IJ-side. So it'll be possible to support C# in rainbow brackets plugin.](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000670130/comments/360000161480)

**Comment by izhangzhihao** [comment]
Is there anyone tried this nightly build version? It should work with intellij-rainbow-brackets.

![image](https://user-images.githubusercontent.com/12044174/46949160-0a941380-d0b3-11e8-8316-3f95d9d5c26a.png)

**Comment by nvlad** [comment]
Not work. PsiViewer show C# code structure.
![image](https://user-images.githubusercontent.com/2493052/46951681-5fbf2d80-d091-11e8-8e5f-981a47a902e8.png)

**Comment by izhangzhihao** [comment]
Just seen that the EAP3 released [2018.3 EAP 3 build 183.3647.257 Released: October 18, 2018](https://www.jetbrains.com/rider/eap/), did anyone tried that? This issue reported by @nvlad on Oct 18, 2017, a full year...

**Comment by sweethuman** [comment]
I have tried it in the latest EAP3 release, they're still not working. @izhangzhihao

**Comment by sweethuman** [comment]
![ex](https://user-images.githubusercontent.com/22968511/47526328-257f3880-d8a8-11e8-882e-52b5a8a5be28.png)
This is EAP4, as you can see they are still not working... @izhangzhihao

**Comment by sweethuman** [comment]
In EAP5 they still aren't working, it's so annoying

**Comment by izhangzhihao** [comment]
Update: [RIDER-16744](https://youtrack.jetbrains.com/issue/RIDER-16744) is reopend, so keep waitting...

**Comment by izhangzhihao** [comment]
It seems we should implement a new C# annotator, is there anyone could verify this snapshot works or not?
[intellij-rainbow-brackets-5.11.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/2599959/intellij-rainbow-brackets-5.11.zip)

**Comment by SugoiDev** [comment]
Give me a few minutes.

**Comment by SugoiDev** [comment]
Confirmed working with your snapshot in both the latest nightly and EAP 5.

Thanks for the great work!

**Comment by XsnTrcK** [comment]
Braces look good `{}` but `()` are not working properly.

![rainbowbracketsoddity](https://user-images.githubusercontent.com/42541979/48780542-c8f11c80-ec9f-11e8-9557-7f1e62a863ff.PNG)
![pythonexample](https://user-images.githubusercontent.com/42541979/48780548-cb537680-ec9f-11e8-885b-bf07145a722e.PNG)

**Comment by izhangzhihao** [comment]
Please try the latest snapshot: 
[intellij-rainbow-brackets-5.11.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/2600270/intellij-rainbow-brackets-5.11.zip)

**Comment by izhangzhihao** [comment]
A new release is pending JetBrains approval.

**Comment by shahzad-0** [comment]
Hi, I am using v5.12 with 2018.3 EAP.
There seems to be a mismatch of colors for the following:
![image](https://user-images.githubusercontent.com/19955449/49096953-a0e75780-f263-11e8-87ab-0764b1ac5b0e.png)

**Comment by squalsoft** [comment]
Not worked with Rider 2020.2.
<img width="642" alt="Снимок экрана 2020-10-13 в 08 33 01" src="https://user-images.githubusercontent.com/1629660/95819510-d8aff900-0d2e-11eb-8e92-a7c0af73a93c.png">
Only colors outer brackets.

**Comment by izhangzhihao** [comment]
@squalsoft are you using the `Do NOT rainbowify the first level` in config page?
