### ISSUE TITLE
Enable option to specify scope highlighting and text flattening effect duration

### ISSUE THREAD

**Issue by frnusmartobjects** [izhangzhihao/intellij-rainbow-brackets#65]
## Expected Behavior
* If you're suggesting a change/improvement, tell us how it should work
There's an option in the settings menu (Other Settings/Rainbow Brackets) that allows the user to determine for how long does the highlighting/flattening effect stay in place after being activated. I would expect to be the options: "Do not remove effect until clicking", "Remove after releasing Ctrl/Alt key" and "Remove effect after X milliseconds" to be available.

## Current Behavior
* If suggesting a change/improvement, explain the difference from current behavior
Currently the highlighting/flattening effect disappears after release the Ctrl or Alt key, respectively.

**Comment by bamapookie** [comment]
Edit: Maybe I should read the request before blindly adding what was already there. :)

**Comment by TheBestPessimist** [comment]
I would like to +1 this request as i often find myself wanting to go to the margins of the highlighted block of code, but they are outside of my screen, and i cannot scroll while keeping `alt` pressed, so i have to stop pressing alt then scroll, then press `alt+right click` again.

**Comment by hsegnitz** [comment]
+1 from me, I was actually wondering if an option to have this permanently enabled (maybe less opaque) would make sense. In DataGrip the current scope of the query you're writing is highlighted like this and I would find it quite helpful, especially working with really bad formatted legacy code where reformatting would mean losing most history in git blame.

**Comment by TheBestPessimist** [comment]
> where reformatting would mean losing most history in git blame.

@hsegnitz i would totally reformat if that were the case.  although git blame is useful, it's way more useful to have _the damn code_ readable. intellij has a very good history and diffing support, so not much is lost when you look at a file/folder history.

**Comment by izhangzhihao** [comment]
What about the plugin will remove effects only after the key `ESC` pressed?

**Comment by izhangzhihao** [comment]
There are [some options](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/codeInsight/highlighting/HighlightManager.java#L29-L42) we could choose: 

```java
  /**
   * Specifies that a highlighter added with {@link #addOccurrenceHighlight} should be removed when the user presses Esc.
   */
  public static final int HIDE_BY_ESCAPE = 0x01;

  /**
   * Specifies that a highlighter added with {@link #addOccurrenceHighlight} should be removed when the user presses any key.
   */
  public static final int HIDE_BY_ANY_KEY = 0x02;

  /**
   * Specifies that a highlighter added with {@link #addOccurrenceHighlight} should be removed when the editor text is changed.
   */
  public static final int HIDE_BY_TEXT_CHANGE = 0x04;
```

**Comment by izhangzhihao** [comment]
![q](https://user-images.githubusercontent.com/12044174/61626958-316e1e80-acb1-11e9-89ae-72f77a31f184.gif)

**Comment by izhangzhihao** [comment]
Please try this SNAPSHOT build: 
[intellij-rainbow-brackets-5.20.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/3417057/intellij-rainbow-brackets-5.20.zip)

**Comment by TheBestPessimist** [comment]
After using it a little (alt+right click, only with esc dismissal) it's not bad at all 😄 !

I would like to test it also with "any key" dismissal (as long as scrolling works). Is there a way to have both options selectable by the user, or is this going towards "bad ux via too many options"?

**Comment by izhangzhihao** [comment]
We don't have the option at this moment, but yes if we do add the option things can be complex, I'm considering to add the option or not.

**Comment by TheBestPessimist** [comment]
There's no pressure for adding "any-key"! The esc option (and scrolling in a demo i just presented) is sufficient and _works so damn well_ :) (i made some of my eclipse-using colleagues a bit jelly ^^).

**Comment by izhangzhihao** [comment]
Thanks for sharing with your colleagues! What about using `ESC` to remove effects by default, but add an option to choose `press any key to remove the highlighting effects`?

**Comment by TheBestPessimist** [comment]
If that's possible then yeah, that would add all the control one would like.
Btw, does `press any key to remove the highlighting effects` also include mouse clicks? (eg. click mouse buttons to dismiss highlighting)

**Comment by izhangzhihao** [comment]
No, mouse clicks will not dismiss anything.

**Comment by izhangzhihao** [comment]
If you love this feature, please consider [supporting us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us)!

**Comment by izhangzhihao** [comment]
A new release will be there within two days.
