### ISSUE TITLE
PHP in PhpStorm (blade.php) - miscolor after first round brackets

### ISSUE THREAD

**Issue by nbs-jodi** [izhangzhihao/intellij-rainbow-brackets#688]
## Programming language
 - PHP

## Expected Behavior
* file: `*.blade.php`, need different color with/without space after first round bracket

## Current Behavior
* file: `*.blade.php`, varable / logic when no space after first round brackets has same color
![image](https://user-images.githubusercontent.com/61995004/102581664-98586700-4133-11eb-94d1-4d0acf3bfe41.png)

## Environment

* Plugin version: 6.12.1
* IDE & Operating System version:
  * PhpStorm 2020.3
  * Build #PS-203.5981.175, built on December 2, 2020
  * Runtime version: 11.0.9+11-b1145.21 amd64
  * VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  * Windows 10 10.0

**Comment by izhangzhihao** [comment]
That's should be a bug of the PhpStorm itself, I'm sure this issue is because of the parsing logic of the PhpStorm parser.
