### ISSUE TITLE
Enable/disable rainbow brackets by languages

### ISSUE THREAD

**Issue by mallowigi** [izhangzhihao/intellij-rainbow-brackets#7]
It would be great to be able to disable the highlighting per feature or globally.

For instance, remove the highlighting in HTML only

**Comment by izhangzhihao** [comment]
Check out [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000726210-It-is-possible-to-dynamically-add-or-remove-annotator-section-in-extensions-)

**Comment by mallowigi** [comment]
I think it’s not the right way to do it; instead, in your annotator, before applying the color, you check if the setting is on or off.

You should create a setting page and a global settings service where you put all your settings, for instance one for the brackets, one for the braces etc. Then with this settings service you can control what to colorify.

I’m on mobile right now but try to check for examples in my plugin on how to implement settings

**Comment by izhangzhihao** [comment]
I'm trying to add an `ApplicationComponent` which will register annotators when init component. But when I can't read settings in `initComponent`.

As [Plugin components lifecycle](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_components.html#plugin-components-lifecycle) said: the initComponent method is invoked before the loadState method.

I'm trying to read config in `ApplicationComponent` with another way but not done yet.

**Comment by manusobles** [comment]
It would be great to **enable/disable** feature **per language or file type**.

For example, I could enable it for JSON, XML or Java and disable it for Kotlin.

I find rainbow brackets really handy when dealing with files containing a lot of nested brackets but for some other files I do not really need it and I think a toggle setting for it would be handy.

Since the issue name is not very descriptive, you could maybe rename it please?

**Comment by izhangzhihao** [comment]
It seems not really possible to list all languages, but a blacklist may be helpful.

**Comment by manusobles** [comment]
> It seems not really possible to list all languages, but a blacklist may be helpful.

Yeah, maybe a list and then say if we want to interpret it as a whitelist or a blacklist?

Thanks!

**Comment by izhangzhihao** [comment]
See more info [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#disable-rainbow-brackets-for-specific-languages).

**Comment by tleeanderson** [comment]
> See more info [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#disable-rainbow-brackets-for-specific-languages).

I tried this today and it does not work. I verified that Intellij is reading in the changes. Did something change recently? Should I be following instructions elsewhere?

EDIT:: nvm on this

**Comment by izhangzhihao** [comment]
> > See more info [here](https://github.com/izhangzhihao/intellij-rainbow-brackets#disable-rainbow-brackets-for-specific-languages).
> 
> I tried this today and it does not work. I verified that Intellij is reading in the changes. Did something change recently? Should I be following instructions elsewhere?
> 
> EDIT:: nvm on this

which languages are you using? There are no changes recently.
