### ISSUE TITLE
Please bring back CTRL only as the keyboard shortcut - configurable!

### ISSUE THREAD

**Issue by dharrigan** [izhangzhihao/intellij-rainbow-brackets#75]
Hello,

Whilst I understand that since 5.8, the default mapping is now CTRL+Mouse Button 3 (and ALT+Mouse Button 3), I actually quite liked having the highlight bound to either CTRL. I find it quite disruptive now to lift my hand off they keyboard, to reach over to the mouse to click on the right mouse button whilst holding down CTRL (or ALT). It didn't bother me that the hightly would briefly flash if I was executing another keyboard shortcut, but I certaintly found it very useful to simply hold down CTRL whilst in a code block to see the scope of the brackets - all without having to lift my (other) hand off the keyboard.

You could say, why not remap CTRL+Mouse Button 3 to an exclusively keyboard-only shortcut - I could, but that's just another thing to remember :-) 

Could we have a toggle on the perferences for Rainbow Plugin to allow CTRL (or ALT) only on keypress. If this option is selected (off by default - to keep with the new setup), then rainbow brackets highlighting would revert to the pre-5.8 behaviour.

Actually, let me further show another *bigger* problem with using the mouse.

When the mouse button is depressed, the cursor  jumps to wherever the mouse cursor is located - obviously if I'm in a block of text that I want highlighted, I have to be *very* careful to ensure that my mouse is hovering over the line of text that my text cursor is currently resting upon, otherwise if I CTRL+right click to show the highlight scope, the text cursor jumps to the new location. I then have to remember to move my text cursor to where it was before - this is not great - it's very distruptive whilst in the flow of writing code. The previous behaviour of just pressing CTRL whilst in the code block meant that the text cursor would stay where it is and I could continue onwards without having to reposition the text cursor.

:-)

Thank you.

**Comment by YiiGuxing** [comment]
Not recommended.

**Comment by dharrigan** [comment]
See the amended comment for a *bigger* problem with using the mouse...

**Comment by izhangzhihao** [comment]
Origin idea: #37 
Change key map request: #61 

It is hard to balance users preference, but you still could re-map your shortcut.

**Comment by dharrigan** [comment]
Hi,

Yes, the problem with having software being used by the general public is that everyone has an opinion on how it should be used :-) It's hard to reach consensus when everyone has a say.

I guess leave my suggestion for now. I'm sorry to see that the binding is keyboard and mouse by default as it does cause problems with the text cursor jumping around, but again, you're right - I can remap to a keyboard mapping. I just have to find one that has a good mnemonic...
