### ISSUE TITLE
Feature request: Disable on big files

### ISSUE THREAD

**Issue by ggalmazor** [izhangzhihao/intellij-rainbow-brackets#784]
## Please check

- [x] I already support this project.
- [x] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming language(s)

Ruby, Go, Erlang, JavaScript, Java

## Expected Behavior

Overall IDE performance is negatively affected by this plugin when dealing with big files (hundreds of lines). 

I would like to configure a threshold of lines so that, when the file I'm editing has more lines than those set on the threshold, then this plugin is automatically disabled for that file.

That way, I can set a threshold that works for my specific environment (memory settings, type of files I open, number of open files, etc).

## Current Behavior

The plugin works for every open file, regardless of their size.

## Possible Solution

I'm not sure about the specific implementation of this feature, but I think it would require a new configuration option to enable this feature, and another new configuration field to set the threshold.

## Code snippet for reproduce (for bugs)

N/A

## Your Environment

* Plugin version: 6.13
* macOS BigSur 11.1

```
RubyMine 2020.3
Build #RM-203.5981.152, built on November 30, 2020
Licensed to Guillermo Gutierrez Almazor
Subscription is active until February 20, 2021
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 8125M
Cores: 8
Registry: ide.balloon.shadow.size=0, jest.test.tree.use.jasmine.reporter=false
Non-Bundled Plugins: com.4lex4.intellij.solarized, com.github.mturlo.intellij.theme.spacegray, com.samdark.intellij-visual-studio-code-dark-plus, com.thvardhan.gradianto, NodeJS, org.jetbrains.plugins.vue, com.dmarcotte.handlebars, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv
```

**Comment by izhangzhihao** [comment]
![image](https://user-images.githubusercontent.com/12044174/106354486-1e6bee00-632d-11eb-8d72-dc301acff035.png)
![image](https://user-images.githubusercontent.com/12044174/106354502-36dc0880-632d-11eb-9571-d8309e0fc9f5.png)

Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) if you like this plugin.

**Comment by Xtrem532** [comment]
Would it be possible to specify the Line-cutoff instead of a Hardcoded 1000 Limit?

**Comment by izhangzhihao** [comment]
> Would it be possible to specify the Line-cutoff instead of a Hardcoded 1000 Limit?

So, what might be your suggestion exactly

**Comment by macdja38** [comment]
> > Would it be possible to specify the Line-cutoff instead of a Hardcoded 1000 Limit?
> 
> So, what might be your suggestion exactly

Different devices will likely have different acceptable thresholds. My old laptop I might set a very small threshold on while on my Desktop at home tens of thousands of lines might be fine.

**Comment by mpsijm** [comment]
I would also like to see the threshold for the maximum number of lines be configurable. I'm currently working on a code base that has many files of a couple of thousand lines that I would like to see rainbowified, but also some generated files that are close to a million lines which definitely should not be rainbowified.

**Comment by izhangzhihao** [comment]
> I would also like to see the threshold for the maximum number of lines be configurable. I'm currently working on a code base that has many files of a couple of thousand lines that I would like to see rainbowified, but also some generated files that are close to a million lines which definitely should not be rainbowified.

Please raise a new issue so someone could pick it up later, and PR welcome!(this should be easy)
