### ISSUE TITLE
OPTION to not rainbowify if within a string or template string. (Enhancement)

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [izhangzhihao/intellij-rainbow-brackets#830]
This is Javascript:

![image](https://user-images.githubusercontent.com/42372270/104906734-b7703180-5949-11eb-93a1-30c8736c54e1.png)

Note: Javascript's template strings i.e. grave symbol allows use of variables within strings via ${variable}.

Since these are squiggly brackets, they get rainbowified by default.

While it's working correctly, I wish an option for the brackets to **not** be rainbowified if within javascript's template strings. I have other IDE/theming coloring which makes spotting these variables easier.

**Comment by izhangzhihao** [comment]
Maybe add a new option to disable rainbowify all template brackets.

**Comment by izhangzhihao** [comment]
I guess that will make you happy, please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) if you like this plugin.

![image](https://user-images.githubusercontent.com/12044174/106353271-4a36a600-6324-11eb-8335-31901e8c4ed1.png)

**Comment by j-a-s-o-n-g** [comment]
Thanks I can't wait until this is added to the stable release!

PS: Typo in that line, needs to be "Do NOT rainbowify" instead of "Do NOT rainboify".

**Comment by izhangzhihao** [comment]
Right, will fix it~
