### ISSUE TITLE
Pycharm stuck at analyzing...

### ISSUE THREAD

**Issue by trolhamonas** [izhangzhihao/intellij-rainbow-brackets#930]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://izhangzhihao.github.io/rainbow-brackets-document/) before creating one.

## Please check

- [ ] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [ X] This issue/feature request is not reported before.

## Your programming language(s)
Python (Pycharm)

## Expected Behavior
* If you're describing a bug, tell us what should happen
When opening Pycharm be able to finish the analyzing.
* If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
When opening Pycharm the interpreter stays stuck at Analyzing... the code in every project, disabling the Rainbow Brackets and restarting solves the issue and the interpreter is able to analyse the code 
* If suggesting a change/improvement, explain the difference from current behavior

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change.
Or what have you tried to resolve this issue.
Disabling the plugin and it worked fine

## Code snippet for reproduce (for bugs)
Please provide code snippet for reproduce bugs.
Any code in Pycharm

## Your Environment

* Plugin version: 
6.14
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
PyCharm 2020.3.3 (Professional Edition)
Build #PY-203.7148.72, built on January 27, 2021
Licensed to Edi Carocho
Subscription is active until October 6, 2021.
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, net.seesharpsoft.intellij.plugins.file-preview, com.ppolivka.gitlabprojects, com.almightyalpaca.intellij.plugins.discord, mobi.hsz.idea.gitignore, com.jetbrains.codeWithMe, izhangzhihao.rainbow.brackets, com.jetbrains.intellij.datalore, ru.meanmail.plugin.requirements
```

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-6.14.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5907797/intellij-rainbow-brackets-6.14.zip)

Can you help me verify this snapshot version works?

**Comment by trolhamonas** [comment]
Installed that snapshot and worked perfectly normal, thanks for the help!
