### ISSUE TITLE
Updating in Webstorm from 6.13 -> 6.14 plugin no longer functions, always throws the same exception

### ISSUE THREAD

**Issue by ScottAwesome** [izhangzhihao/intellij-rainbow-brackets#932]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

Your issue may already be reported!
Please search on the [issues](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues) and the [document](https://izhangzhihao.github.io/rainbow-brackets-document/) before creating one.

## Please check

- [x] I already support this project.
- [ ] If you are submitting a feature request, please do consider donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay.
- [x] This issue/feature request is not reported before.

## Your programming language(s)
TypeScript, HTML, JavaScript, CSS, Less, Python

## Expected Behavior
Bug:

I am experiencing the same behavior as outlined in this (now closed) issue: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/426

I was working along okay within WebStorm, no issue, and after updating to 6.14 I am unable to use this plugin, every time I open a source file it crashes. I downloaded a snapshot build of 6.13, and the same issue is occurring. If I downgrade all the way down to 6.7, I no longer have an issue and the plugin works as expected. ~Interestingly enough, my PyCharm instance is still on 6.13, and it works okay, it appears the issue may be related to updating from 6.13 to 6.14~

Actually, PyCharm was not working either, and I did a fresh wipe and install of both PyCharm and WebStorm, redownloaded the plugin, and the issue is still occurring.

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, explain the difference from current behavior

## Possible Solution
Only fix I could find is downgrading to 6.7, downgrading to 6.13 did not work (I could not find a build for 6.12)

## Code snippet for reproduce (for bugs)
Any supported language is failing to highlight properly.

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):
* NOTE: If you are going to report a bug but WITHOUT your env information, your issue might be closed directly.

```
WebStorm 2020.3.2
Build #WS-203.7148.54, built on January 25, 2021
Licensed to
Subscription is active until April 30, 2021.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: ide.tree.collapse.recursively=false, vcs.annotations.preload=true, eslint.additional.file.extensions=svelte
Non-Bundled Plugins: GrepConsole, Shifter, String Manipulation, cc.duduhuo.git-conflict, cc.moky.intellij.plugin.svga-support, com.godwin.json.parser, com.intellij.lang.liquid, com.jetbrains.colorful.toolwindow.icons, com.jetbrains.plugins.ini4idea, org.intellij.plugins.postcss, com.karateca.jstoolbox, com.mallowigi, com.rmondjone.jsontotypescript, commit-template-idea-plugin, idea.plugin.protoeditor, com.yoheimuta.intellij.plugin.protolint, main.kotlin.com.jimschubert.intellij.swaggercodegen, net.seesharpsoft.intellij.plugins.csv, net.seesharpsoft.intellij.plugins.file-preview, gr.jchrist.gitextender, zielu.gittoolbox, mobi.hsz.idea.gitignore, com.crunch42.openapi, org.toml.lang, lv.midiana.misc.idea-plugins.deep-js-completion, mdx.js, lermitage.intellij.extra.icons, com.intellij.database, com.intellij.lang.jsgraphql, com.intellij.swagger, io.plugin.tsnode, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, PlantUML integration
```

**Comment by ofek** [comment]
Same here! cc @izhangzhihao

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-6.14.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5907797/intellij-rainbow-brackets-6.14.zip)

Can you help me verify this snapshot version works?

**Comment by ScottAwesome** [comment]
> [intellij-rainbow-brackets-6.14.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5907797/intellij-rainbow-brackets-6.14.zip)
> 
> Can you help me verify this snapshot version works?

@izhangzhihao Works perfectly for me in Webstorm, on a large codebase too.

Thanks for the quick response! seriously fast. I appreciate it.

**Comment by chrgxdev** [comment]
Just reporting that this also generates the issues in #934 in phpStorm (Linux).

**Comment by izhangzhihao** [comment]
@cgxwebs Did you restart your ide after installing the snapshot?

**Comment by chrgxdev** [comment]
> @cgxwebs Did you restart your ide after installing the snapshot?

Sorry, I was referring to the marketplace update. The snapshot link above worked though. Thank you.
