### ISSUE TITLE
Does not work in Goland 2020.3.2

### ISSUE THREAD

**Issue by borjapazr** [izhangzhihao/intellij-rainbow-brackets#933]
When I activate Rainbow Brackets in Goland, the editor theme is not applied and is not displayed correctly. Is it compatible with Go?

**Rainbow Brackets DISABLED**
![image](https://user-images.githubusercontent.com/9295713/106533229-07c2c400-64f2-11eb-9761-ac0ba76f8b9d.png)

**Rainbow Brackets ENABLED**
![image](https://user-images.githubusercontent.com/9295713/106533295-2759ec80-64f2-11eb-957b-a216ec329c48.png)

```
Rainbow Brackets version: 6.14
GoLand 2020.3.2
Build #GO-203.7148.71, built on January 26, 2021
```

**Comment by izhangzhihao** [comment]
Can you provide your code as example?

**Comment by izhangzhihao** [comment]
[intellij-rainbow-brackets-6.14.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5907797/intellij-rainbow-brackets-6.14.zip)

Can you help me verify this snapshot version works?

**Comment by borjapazr** [comment]
> [intellij-rainbow-brackets-6.14.zip](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/5907797/intellij-rainbow-brackets-6.14.zip)
> 
> Can you help me verify this snapshot version works?

Yes, this version works correctly. 🥳

To clarify. The version published in the Marketplace works on Windows but not on Linux.

Thank you!
