### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by ghost** [izhangzhihao/intellij-rainbow-brackets#990]
I'd like to use this plugin as it looks very useful, but in order to get it approved I need information on how it handles privacy.
Does it collect any personal information?
If so, what kind of data is collected and when is it collected?
Would also be great if you could add this to the documentation.

Thank you very much!

**Comment by izhangzhihao** [comment]
None of data is collected.

**Comment by izhangzhihao** [comment]
Unless your are submitting a bug report, you could refer to #973
